- cli/azd/cmd/deploy.go
Add missing trailing newline to resource group URL
> Add missing trailing newline to resource group URL

- .github/workflows/templates-ci.yml
- .vscode/cspell-templates.txt
- templates/tests/test-templates.sh
fix https://github.com/Azure/azure-dev/issues/73
> Fix cspell from test-templates

- cli/azd/pkg/tools/npm.go
> fix node error message typo

- templates/todo/projects/csharp-cosmos-sql/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/nodejs-mongo/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
- templates/todo/projects/python-mongo/README.md
This change adopts feedback from the content team.
> Update "Environment name" description in READMEs

- cli/azd/CHANGELOG.md
- cli/azd/cmd/init.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/util.go
- cli/azd/pkg/templates/template_manager.go
fix https://github.com/Azure/azure-dev/issues/62
> fix to use template name and repository path from resources #62

- ext/vscode/.vscodeignore
Fixes https://github.com/Azure/azure-dev/issues/51
> Remove unnecessary PS files from VS Code extension package

- ext/vscode/src/extension.ts
- ext/vscode/src/telemetry/activeSurveys.ts
- ext/vscode/src/telemetry/surveyScheduler.ts
- ext/vscode/src/test/suite/unit/surveys.test.ts
Fixes https://github.com/Azure/azure-dev/issues/157
> Shorten flight ID for survey

- eng/pipelines/release-cli.yml
- eng/pipelines/release-vscode.yml
Example publishing run uploading to test container and using the new `azure-dev` environment. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1726228&view=results
> Set release environment to azure-dev

- cli/azd/pkg/tools/bicep.go
- eng/pipelines/release-cli.yml
I'm doing a bicep refactor that takes advantage of some of the new bicep features like single line array declarations.  I'd also like to update to all the latest versions of the RPs, which come with v0.8.9.
Fixes #188
> Update bicep min version to v0.8.9

- cli/azd/test/functional/cli_test.go
The current test tries to access the webapp immediately after it is deployed, which can result in a 404 or the default page for app service, not the actual app code.
This fix will retry for static text 'Hello, `azd`. until it finds it or until retries have been exhausted.
> Add retry to webapp test

- .vscode/settings.json
- cli/azd/pkg/azureutil/resource_group.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/service.go
- cli/azd/test/functional/cli_test.go
Adds retry support in multiple functions that perform graph queries to combat against newly created resources not being immediately available for querying.
Resolves #436
> Adds retry support for graph queries

- cli/azd/pkg/tools/azcli.go
> az version and extensions should force json output

- templates/todo/projects/csharp-cosmos-sql/.vscode/launch.json
- templates/todo/projects/nodejs-mongo-aca/.vscode/launch.json
- templates/todo/projects/nodejs-mongo-swa-func/.vscode/launch.json
- templates/todo/projects/nodejs-mongo/.vscode/launch.json
- templates/todo/projects/python-mongo-aca/.vscode/launch.json
- templates/todo/projects/python-mongo-swa-func/.vscode/launch.json
- templates/todo/projects/python-mongo/.vscode/launch.json
Fixes https://github.com/Azure/azure-dev/issues/488
> Update frontend debugger type (VSCode)

- cli/azd/CHANGELOG.md
- cli/azd/ci-test.ps1
- cli/azd/pkg/azureutil/resource_group.go
- cli/azd/test/functional/cli_test.go
- eng/pipelines/template-tests.yml
fix https://github.com/Azure/azure-dev/issues/477
fix: https://github.com/Azure/azure-dev/issues/481
> Remove toUpper from query when looking for resource group name

- ext/vscode/src/telemetry/surveyOne.ts
- ext/vscode/src/telemetry/surveyScheduler.ts
Fixes https://github.com/Azure/azure-dev/issues/475
> Add number of active days per user to survey telemetry

- ext/vscode/src/commands/cmdUtil.ts
Fixes https://github.com/Azure/azure-dev/issues/476
> Use `azd template list` to populate template list

- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/init.ts
- ext/vscode/src/commands/up.ts
Fixes https://github.com/Azure/azure-dev/issues/148
> Show README file after successful init/up

- cli/azd/test/samples/funcapp/infra/main.bicep
- cli/azd/test/samples/resourcegroups/infra/main.bicep
- cli/azd/test/samples/storage/infra/main.bicep
- cli/azd/test/samples/webapp/infra/main.bicep
- templates/todo/common/infra/aca/main.bicep
- templates/todo/projects/csharp-cosmos-sql/infra/main.bicep
- templates/todo/projects/csharp-mongo/infra/main.bicep
- templates/todo/projects/csharp-sql/infra/main.bicep
- templates/todo/projects/nodejs-mongo-swa-func/infra/main.bicep
- templates/todo/projects/nodejs-mongo/infra/main.bicep
- templates/todo/projects/python-mongo-swa-func/infra/main.bicep
- templates/todo/projects/python-mongo/infra/main.bicep
Bicep has a function called resourceGroup.  Our current templates resource is named resourceGroup.  Renaming it to rg to prevent future collisions.
> Change resourceGroup to rg

- .vscode/cspell-templates.txt
- templates/todo/common/tests/todo.spec.ts
Fixes issue https://github.com/Azure/azure-dev/issues/246
Change files: templates/todo/common/tests/todo.spec.ts
Add setTimeOut is used to wait for the page data to full load.
@rajeshkamal5050 for notification.
> Fix Playwright test fail in todo-nodejs-mongo

- ext/vscode/.eslintrc.json
- ext/vscode/package.nls.json
- ext/vscode/src/commands/getDotEnvFilePath.ts
Fixes https://github.com/Azure/azure-dev/issues/397
> Improve error message when no environments are found

- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
PR adds repo.yaml rules to copy the python dev container.
> copy python dev container

- .github/workflows/cli-ci.yml
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/setup-go.yml
- go.mod
> Upgrade go to 1.19

- schemas/v1.0/azure.yaml.json
Updates the `azure.yaml` JSON schema for the new infra provider configuration options.
> Adds top level 'infra' configuration section to the azure.yaml schema

- cli/azd/resources/templates.json
Position on the list (last entry) was vetted by @savannahostrowski
> Add CSharp Azure SQL to well-known templates list

- eng/pipelines/template-tests.yml
- eng/pipelines/templates/steps/install-azd-live-sh.yml
- eng/pipelines/templates/steps/repoman-generate.yml
- eng/pipelines/templates/steps/set-git-credentials.yml
* Installs daily version -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1841394&view=logs&j=28b17376-e9c9-57b2-322e-c3a087d09a4f&t=e6589f90-3afe-57a5-98a6-8799b60470ee&l=14
* Runs expected tests from `daily` build by default -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1841394&view=logs&j=255759e9-95fd-5b22-cada-8803e798a082&t=e39b3856-d7f9-53f8-aecf-19f4626fff0c
> Template tests: Consistent azd install

- templates/common/.azdo/pipelines/README.md
- templates/common/.azdo/pipelines/azure-dev.yml
- templates/common/.github/workflows/azure-dev.yml
Update the templates CI to set he ARM env Vars for terraform.
Addreses #627
> Update templates pipeline to use ARM env values

- .vscode/cspell.global.yaml
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/python-mongo/README.md
this PR updates the readme.md for template todo-python-mongo to based on the IAC tool
fixes #629
> update readme content based on the iac Version

- cli/azd/pkg/commands/pipeline/github_provider.go
The json is not the expected from `az` result as it is parsed to be as GitHub expects
> Correct values for ARM env vars

- cli/azd/pkg/commands/pipeline/github_provider.go
- templates/common/.github/workflows/bicep/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
- templates/todo/projects/csharp-cosmos-sql/repo.yaml
- templates/todo/projects/csharp-mongo/repo.yaml
- templates/todo/projects/csharp-sql/repo.yaml
- templates/todo/projects/nodejs-mongo-aca/repo.yaml
- templates/todo/projects/nodejs-mongo-swa-func/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-aca/repo.yaml
- templates/todo/projects/python-mongo-swa-func/repo.yaml
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
**Pipeline config will throw a warning if the remote state configuration is invalid.**
**GitHub secrets set by azd when using Terraform IaC provider**
> Adds new github action for terraform

- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/cosmos.tf
- templates/todo/projects/python-mongo/.repo/terraform/infra/cosmos.tf
This PR update the cosmoc db resource to ignore capabilities changes . 
Fixes #645
> update cosmos module to ignore capabilities changes

- .vscode/cspell.global.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/nodejs-mongo/README.md
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/python-mongo/README.md
Update nodejs-mongo and python-mongo asset rules to include more details in readme based on IAC tool
> update readme contents

- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
update nodejs repo.yaml to load the correct github workflow
> add gh action to nodejs repo.yaml

- cli/azd/main.go
> Write version check warning message to stderr

- eng/pipelines/release-cli.yml
patch https://github.com/Azure/azure-dev/issues/763 to have a green build and unblock other PRs
> Fix CI Pipeline - do not fail if folder is there

- templates/common/infra/bicep/core/host/appservice-dotnet.bicep
- templates/common/infra/bicep/core/host/appservice-node.bicep
- templates/common/infra/bicep/core/host/appservice-python.bicep
- templates/common/infra/bicep/core/host/appservice.bicep
- templates/common/infra/bicep/core/host/functions-node.bicep
- templates/common/infra/bicep/core/host/functions-python.bicep
- templates/common/infra/bicep/core/host/functions.bicep
- templates/todo/common/infra/bicep/app/api-appservice-dotnet.bicep
- templates/todo/common/infra/bicep/app/api-appservice-node.bicep
- templates/todo/common/infra/bicep/app/api-appservice-python.bicep
- templates/todo/common/infra/bicep/app/api-functions-node.bicep
- templates/todo/common/infra/bicep/app/api-functions-python.bicep
- templates/todo/common/infra/bicep/app/web-appservice.bicep
> Make appInsights optional for app service

- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/azdo/project.go
- cli/azd/pkg/azdo/repository.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/tools/git/git.go
- remove git config credentials
- Fix https://github.com/Azure/azure-dev/issues/759
> Updates to Azdo implementation

- cli/azd/pkg/tools/git/git.go
fix https://github.com/Azure/azure-dev/issues/778
issue seen on git version 2.25.1 (ubuntu 20)
> can't rename a branch that has no commits as the branch does not exists

- cli/azd/pkg/azdo/pipeline.go
fix https://github.com/Azure/azure-dev/issues/781
> refresh variables on every run

- .github/fabricbot.json
fix https://github.com/Azure/azure-dev/issues/322
> Use auto assign for team's PRs

- templates/todo/projects/csharp-cosmos-sql/README.md
- templates/todo/projects/csharp-sql/README.md
- templates/todo/projects/java-mongo-aca/README.md
- templates/todo/projects/java-mongo/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/nodejs-mongo/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
- templates/todo/projects/python-mongo/README.md
> Fixes #285 and #599

- cli/azd/cmd/monitor.go
- cli/azd/pkg/tools/azcli/account.go
- cli/azd/pkg/tools/azcli/azcli.go
Removes `az` CLI commands that are no longer in use by `azd`
> Deprecates unused Az CLI commands

- cli/installer/README.md
Fixes https://github.com/Azure/azure-dev/issues/909
> Fix discovered occurrences of unprintable characters

- cli/azd/internal/telemetry/fields/fields.go
- cli/azd/internal/telemetry/resource/exec_environment.go
Add telemetry for when user is using Codespaces. 
Updated the concept of "CI" to include "hosted" which should better match Codespaces and JetBrains Space.
> Codespaces telemetry

- ext/vscode/package.json
- ext/vscode/src/commands/init.ts
Add `bugs` URL to `package.json` so the "Report an issue" link will use the correct URL.
Resolves #927
> Add bugs property to package.json

- templates/todo/web/react-fluent/package-lock.json
- templates/todo/web/react-fluent/package.json
Using override for minimatch version
> manual update for dependencies after security alert

- cli/azd/pkg/azsdk/zip_deploy_client.go
- cli/azd/pkg/graphsdk/application_request_builders.go
- cli/azd/pkg/graphsdk/me_request_builder.go
- cli/azd/pkg/graphsdk/service_principal_request_builders.go
- cli/azd/pkg/httputil/util.go
Resolves issue #997 with bad error handling in executing MS graph requests.
> Azd CLI: Graph panic fix

- cli/azd/resources/templates.json
This pr resolves https://github.com/Azure/azure-dev/issues/1017
> Adding csharp-sql-swa-func to templates list

- cli/azd/main.go
- cli/azd/pkg/azsdk/zip_deploy_client.go
- Add additional ~12s retry delay by adding an additional retry attempt for zipdeploy
Helps with #1032
> Increase retry for zipdeploy

- cli/azd/cmd/util.go
- cli/azd/cmd/util_test.go
- cli/azd/pkg/config/manager.go
- cli/azd/test/mocks/mock_context.go
> use nil for non default

- templates/common/infra/bicep/core/host/container-app.bicep
- templates/common/infra/bicep/core/host/container-registry.bicep
- templates/common/infra/bicep/core/monitor/applicationinsights.bicep
- templates/common/infra/bicep/core/monitor/monitoring.bicep
1. Allow containerName param on container app
2. Export instrumentationKey
3. Change CR sku to Basic
> Bicep core updates

- templates/common/.devcontainer/Dockerfile/base/Dockerfile
- templates/common/.devcontainer/Dockerfile/func/Dockerfile
- templates/common/.devcontainer/devcontainer.json/csharp/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/terraform/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/terraform/devcontainer.json
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/python-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/repo.yaml
Fixes #1075 and adds node/terraform devc
> Fix up devcontainers

- .devcontainer/Dockerfile
- templates/common/.devcontainer/Dockerfile/base/Dockerfile
> Fix for docker files installing xdg-utils

- cli/azd/CHANGELOG.md
Give a bit more detail about the change by creating a new section that explains the change and also documents a little bit about how to adopt these changes into existing pipelines.
> Discuss auth-related changes in CHANGELOG.md

- cli/azd/internal/global_command_options.go
Remove deprecated flag that was missed in #1143
> Remove deprecated flag

- .github/workflows/lint-bicep.yml
- eng/scripts/Test-BicepLint.ps1
- templates/todo/projects/csharp-sql/.repo/bicep/infra/main.bicep
Example failure: https://github.com/Azure/azure-dev/actions/runs/3640866818/jobs/6146103787
Error highlighting in PR:
> Fix Bicep linting in PR

- .vscode/cspell.global.yaml
- templates/todo/api/csharp-cosmos-sql/Program.cs
- templates/todo/api/csharp-sql-func/Program.cs
- templates/todo/api/csharp-sql/Program.cs
- templates/todo/api/csharp/Program.cs
- templates/todo/common/auth/csharp/AzureDeveloperCliCredential.cs
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/repo.yaml
> Adds Azd CLI credential for C#

- cli/Dockerfile
- templates/common/.devcontainer/Dockerfile/base/Dockerfile
- templates/common/.devcontainer/Dockerfile/func/Dockerfile
Fixes https://github.com/Azure/azure-dev/issues/952
> Use amd64 in dockerfiles that install azd

- cli/azd/.vscode/cspell.yaml
- cli/azd/pkg/exec/command_runner.go
- cli/azd/pkg/exec/util_test.go
> Redacting sensitive data when logging commands

- ext/vscode/package-lock.json
- ext/vscode/package.json
Same as https://github.com/microsoft/vscode-docker/pull/3792
> Update to use `@vscode/vsce` instead of `vsce`

- templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
fix: https://github.com/Azure/azure-dev/issues/1057
> Fix cors param in task for python func template

- cli/azd/cmd/auth_token.go
- cli/azd/cmd/auth_token_test.go
- cli/azd/pkg/contracts/auth_token.go
- cli/azd/pkg/contracts/auth_token_test.go
> Use RFC3339 without Nanoseconds for expiresOn

- cli/installer/install-azd.ps1
- cli/installer/test-win-install.ps1
- eng/pipelines/release-cli.yml
Changes: 
* Add support in install-azd.ps1 for installing MSI directly (including specifying install location) 
* Updated testing (uninstall support not required as that should be done in the "Add or Remove programs" dialog)
> Install script uses MSI on Windows

- cli/azd/cmd/login.go
> Fixing flag listing in help message

- cli/azd/cmd/middleware/debug.go
- cli/azd/pkg/config/manager.go
Adding err to the message to provide some insight on what's happening in https://github.com/Azure/azure-dev/issues/1365
> Add err to message for help with debugging login issue

- eng/pipelines/release-cli.yml
Fixes build issues
Docker install task succeeds on Mac: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2125410&view=logs&j=3eb4d8a5-5d97-562b-c71d-6ac568d84486&t=eee25bf3-cd7c-5962-1098-c35045f0e6f7
> Pin DockerInstaller task

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli.yml
- eng/scripts/Update-HomebrewFormula.ps1
- eng/templates/brew.template
Completes: https://github.com/Azure/azure-dev/issues/1383
Successful pipeline run isolating just those publishing steps: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2126120&view=logs&j=493e9ff3-1332-590a-730c-4fca05f30c58&t=347bd482-f14a-5066-41a0-f4c562c123fc
Compare test branch with `main`: https://github.com/Azure/homebrew-azd/compare/main...test-devops-publish
> Homebrew publishing

- cli/azd/CHANGELOG.md
> Update CHANGELOG for #1406

- cli/azd/pkg/lazy/lazy.go
- cli/azd/pkg/lazy/lazy_test.go
Adds a new `Lazy[T]` data structure for lazy evaluation of values
> Adds lazy lib

- .github/workflows/cli-ci.yml
- .github/workflows/lint-bicep.yml
- .github/workflows/templates-ci.yml
- .github/workflows/vscode-ci.yml
- .vscode/cspell.global.yaml
- templates/common/.github/workflows/bicep/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
fix: https://github.com/Azure/azure-dev/issues/1425
> Update git flows to use checkout v3

- .devcontainer/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/terraform/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/terraform/devcontainer.json
Along with #1549, this fixes #1518.
> Fix remaining devcontainer files

- ext/vscode/src/commands/cmdUtil.ts
> Sort "Use other template" choice to top

- templates/todo/api/python/todo/models.py
Just a little follow-up from https://github.com/Azure/azure-dev/pull/1574/files that I noticed.
> Remove unused import

- templates/common/infra/bicep/core/gateway/apim.bicep
- templates/common/infra/bicep/core/host/appservice.bicep
These are two security updates to the /core modules based on the Microsoft Security recommendations. (See https://github.com/Azure/azure-dev/issues/1640)
These both seem like options that won't negatively affect the apps.
> Security updates to APIM and AppService

- cli/Dockerfile
Adds kubectl CLI to be installed in the AZD CI image
> Installs kubectl to the Azd image used in CI

- .vscode/cspell.global.yaml
- README.md
- cli/installer/README.md
Documentation updates to address some of the concerns raised in https://github.com/Azure/azure-dev/issues/1673
> Update documentation to feature new install methods more prominently

- ext/vscode/CHANGELOG.md
- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/src/utils/azureDevCli.ts
> Refine conditions for displaying the install azd prompt

- ext/vscode/CHANGELOG.md
- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/src/commands/loginCli.ts
- ext/vscode/src/telemetry/telemetryId.ts
- ext/vscode/src/utils/azureDevCli.ts
> Fix issue with login command where `PATH` isn't being modified

- cli/azd/resources/templates.json
Just something I noticed while Victor and I were having a discussion.
> Fix typo in templates.json

- cli/installer/install-azd.ps1
Fixes https://github.com/Azure/azure-dev/issues/1489
cc @jongio
> azd-install.ps1 - Handle msiexec.exe 1603 exit code

- ext/vscode/package.json
Also `azure` and `azd` as keywords
> Add Azure category to VSCode extension

- cli/azd/pkg/project/framework_service_maven_test.go
These unit tests were failing on my local machine because I do not have Maven installed globally. It seems like we could get these tests to work if we just orchestrated the test folder such that the Maven wrapper was present in the `api/src/` folder (as we have in our templates).
This change updates the tests such that we now lay down an `mvnw` "script" (it's actually a zero byte file, but good enough to convice `os.LookPath` that the wrapper is there and ready to be used) and then updates the test to expect that we invoke `mvnw` instead of `mvn`.
The diff here looks a little noiser than it is, because I made each scenario (Restore, Build, and Package) a subtest of `Test_MavenProject` so I could share the setup logic that creates the `mvnw` wrapper. The only change to the logic of the …
> Make `Test_MavenProject` tests work when `mvn` is missing

- cli/azd/.vscode/launch.json
- cli/azd/CONTRIBUTING.md
Just wondering - would it be helpful for the team to check this in?
> Add Attach to Process configuration for use with `AZD_DEBUG`

- schemas/v1.0/azure.yaml.json
Adds missing `package` command hooks to azd schema
> Adds `package` command hooks to azd schema

- .github/workflows/cli-ci.yml
- .github/workflows/cspell-misc.yml
- .github/workflows/templates-ci.yml
- .github/workflows/vscode-ci.yml
- eng/pipelines/release-vscode.yml
- eng/pipelines/template-tests.yml
Upgrades to use Node 18 (LTS) in pipelines
> Upgrade to use node 18 (LTS) in pipelines

- cli/azd/cmd/package.go
- cli/azd/cmd/root.go
- cli/azd/cmd/testdata/TestUsage-azd-package.snap
- cli/azd/cmd/testdata/TestUsage-azd.snap
Adds `package` command to `azd help` with BETA designation
> Adds `package` command to azd help with beta designation

- templates/todo/projects/csharp-cosmos-sql/.vscode/tasks.json
- templates/todo/projects/csharp-sql-swa-func/.vscode/tasks.json
- templates/todo/projects/csharp-sql/.vscode/tasks.json
- templates/todo/projects/java-mongo-aca/.vscode/tasks.json
- templates/todo/projects/java-mongo/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aca/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aks/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo/.vscode/tasks.json
- templates/todo/projects/python-mongo-aca/.vscode/tasks.json
- templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/python-mongo/.vscode/tasks.json
'--service' has been deprecated. Pass the service as-is.
Fixes: https://github.com/Azure/azure-dev-pr/issues/1497
> Remove '--service' usage in templates

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/service_models.go
- cli/azd/pkg/project/service_models_test.go
Fixes issue with our JSON marshal implementation causing stack overflow when using our custom result types.
> Fixes json marshall panic when specifying JSON output

- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
> Fixes panic for postpackage hook errors

- templates/common/infra/bicep/core/ai/ai.bicep
- templates/common/infra/bicep/core/ai/cognitiveservices.bicep
- templates/common/infra/bicep/core/host/appserviceplan.bicep
- templates/common/infra/bicep/core/search/search-services.bicep
- templates/common/infra/bicep/core/security/role.bicep
- templates/common/infra/bicep/core/storage/storage-account.bicep
We have a few templates that use ai and search.  Adding the core changes to main so others can benefit.
> Add ai/search to bicep core

- cli/azd/docs/feature-stages.md
Forgot https:// so this link is broken
> Link update

- cli/Dockerfile
> adding python3-venv to universal img

- templates/todo/projects/nodejs-mongo-aks/README.md
Resolves #1871 
Updates AKS todo readme to include details about required roles for provisioning this template.
> Updates Todo AKS template to add details about required roles

- templates/common/infra/bicep/core/host/aks-agent-pool.bicep
- templates/common/infra/bicep/core/host/aks-managed-cluster.bicep
Resolves #1814 
Updates Bicep API versions for AKS
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters
The latest version at time of this PR is `2023-02-01`
> Updates AKS Bicep API versions

- cli/azd/docs/manual-pipeline-config.md
A document for folks who can't use azd to run `azd pipeline config` bur want to still use the pipelines from the todo samples or want to re-use an existing SP or service connection.
This document should provide some help for now until azd has a better story for covering these scenarios.
> manual steps for setting up a pipeline

- cli/azd/main.go
Fixes https://github.com/Azure/azure-dev/issues/1793
After discussing with @heaths, we should try for a more e2e upgrade approach (like `az upgrade`) or link to docs. Guessing at which command line to run could result in bad user experiences in edge cases. https://github.com/Azure/azure-dev/issues/1793#issuecomment-1511859890
> Recommend upgrade link

- templates/common/infra/bicep/core/database/postgresql/flexibleserver.bicep
- templates/common/infra/bicep/core/networking/cdn-profile.bicep
I ran `bicep format` on all the files in core. Lo and behold, only the files I contributed had formatting issues. So here's a PR with my files reformatted.
For reference, I used this script:
```
#!/bin/bash
command="az bicep format -f"
find . -type f -name "*.bicep" | while read file
do
$command "$file"
done
```
However, it doesn't quite work as it doesn't insert a final new line. There's a --insert-final-newline option that would theoretically fix that, but it's broken right now, so I filed issue on the CLI. 
Also of interest, here's a Github workflow that runs Bicep format and auto commits changes:
https://github.com/pamelafox/django-quiz-app/pull/15/files#diff-8af3e80c405f1ab691b04ee13deecae46a34d6e87cc81b9a5f21490bc17e2609R29
> Format my Bicep files

- cli/azd/pkg/project/service_manager.go
Got this long line committed as part of an earlier PR where I committed a suggestion directly within the PR and then use `check-enforcer override` as checks were run before and the change was only wording... but ended up breaking the linter :)
> Fix main branch with linter issue

- cli/azd/.vscode/cspell.yaml
- cli/azd/docs/docgen.go
This ensures that @alexwolftmsft is reviewing and merging changes to the ref docs
> Update author in ref docs front matter

- cli/installer/install-azd.ps1
> Quote file location

- cli/azd/internal/telemetry/telemetry.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/service_manager.go
> Capitalize Docker in strings

- templates/starter/bicep/README.md
- templates/starter/terraform/README.md
The next step sections cover the journey to getting the application up to Azure.
> Add next step sections to starter readme

- templates/todo/api/js/src/app.ts
fix: https://github.com/Azure/azure-dev/issues/2139
eslint fixes for node app
> fix eslint for node app

- cli/azd/cmd/pipeline.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
fix: https://github.com/Azure/azure-dev/issues/2153
> use provider name for output

- templates/common/infra/bicep/core/host/container-app-upsert.bicep
- templates/common/infra/bicep/core/host/container-app.bicep
- templates/common/infra/bicep/core/host/container-apps-environment.bicep
- templates/common/infra/bicep/core/host/container-apps.bicep
- templates/todo/projects/java-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo-aca/.repo/bicep/infra/main.bicep
Replaces #1958 to adjust for merge conflicts.
> Adds dapr & additional container configuration properties to ACA modules

- cli/azd/cmd/init.go
> Use `aks.ms` link for 3rd party code notice

- cli/azd/cmd/middleware/hooks.go
- cli/azd/cmd/up.go
- cli/azd/pkg/commands/pipeline/pipeline_test.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_test.go
- cli/azd/test/functional/initialize_test.go
Fixes #2025 
Fixes the following:
- Invalid host specified in azure.yaml file
- Empty azure.yaml file
> Fixes invalid hosts in azure.yaml file

- cli/azd/cmd/config.go
- cli/azd/cmd/testdata/TestUsage-azd-config-list-alpha.snap
> Adds additional help examples for how to turn alpha features on/off

- cli/azd/.vscode/cspell.yaml
- cli/azd/docs/docgen.go
@alexwolfmsft -- I think your name is correct now.
> Docs author, fix naming: alexwolftmsft -> alexwolfmsft

- templates/todo/projects/java-postgresql/README.md
> Add alpha note for todo-java-postgresql-terraform

- cli/azd/.vscode/settings.json
We shouldn't be forcing any VS code color schemes on anyone 😊
> Removes custom color scheme

- cli/azd/pkg/azsdk/zip_deploy_client_test.go
- cli/azd/pkg/exec/util_test.go
- cli/azd/test/mocks/mockgraphsdk/mocks.go
Avoid lengthy sleep retries. Lower cancellation delay.
Fixes #2255
> Avoid slow-running unit tests

- cli/azd/internal/tracing/resource/exec_environment.go
- cli/azd/internal/useragent.go
- cli/azd/internal/useragent_test.go
- cli/azd/main.go
- cli/azd/pkg/account/subscriptions.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/container_registry.go
- cli/azd/pkg/tools/azcli/managed_clusters.go
- cli/azd/pkg/tools/azcli/spring_app.go
- cli/azd/pkg/tools/azcli/user_profile.go
Refactor changes include:
1. Remove template in user agent since we no longer use this and have a better way of tracking template usage.
2. Rename `MakeUserAgentString("")` to `UserAgent()` for better readability.
3. Simplify implementation
> Refactor user agent for simplicity

- cli/azd/cmd/deploy.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/show.go
- cli/azd/cmd/util.go
- cli/azd/pkg/azdo/project.go
- cli/azd/pkg/azdo/repository.go
- cli/azd/pkg/azdo/utils.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/util.go
- cli/azd/pkg/project/framework_service_dotnet.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/tools/ensure.go
- cli/azd/test/functional/deploy_test.go
Based on feedback from our copy editors.
> Remove the use of "please" from our UX

- cli/azd/CHANGELOG.md
- cli/azd/pkg/infra/azure_resource_types.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/keyvault.go
- cli/azd/pkg/tools/azcli/managed_hsm.go
> Support purging of Managed HSMs

- cli/azd/CHANGELOG.md
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
> Make sure spinner is stopped appropriately

- schemas/v1.0/azure.yaml.json
> Updates azure.yaml schema to match implementation for hook configuration

- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
The package we are using for storing values in a `.env` file has some surprising behavior where numeric like values are stored as unquoted strings with any leading zero dropped (since the value is round tripped via `strconv.Atoi` and then `fmt.Sprintf` with a `%d` format directive.
This leads to issues where if you have a bicep file that does something like:
```bicep
output NUMBER_WITH_LEADING_ZERO string = '01'
```
The value stored in the `.env` file will be just `1` instead of `01`.
This change addresses this issue by detecting the case and ensuring that we store the raw value in the .env file (after wrapping it with quotes).
Fixes #2307
> Store numeric values with leading zeros in `.env` correctly

- cli/azd/cmd/auth_login.go
- cli/azd/pkg/auth/manager.go
> Handle azd auth scenarios in CloudShell

- templates/todo/api/python/requirements.txt
Update python templates to use latest identity GA client
> Update python templates with non-beta identity library

- templates/todo/api/csharp-cosmos-sql/Todo.Api.csproj
- templates/todo/api/csharp-sql-func/Todo.Api.csproj
- templates/todo/api/csharp-sql/Todo.Api.csproj
- templates/todo/api/csharp/Todo.Api.csproj
fix: https://github.com/Azure/azure-dev/issues/2440
> Update identity for C# templates

- ext/vscode/.vscode/settings.json
- ext/vscode/src/language/AzureYamlDiagnosticProvider.ts
- ext/vscode/src/language/AzureYamlProjectRenameProvider.ts
- ext/vscode/src/language/azureYamlUtils.ts
- ext/vscode/src/language/languageFeatures.ts
> Add document rename handler

- ext/vscode/src/commands/cmdUtil.ts
> Fix issue where init command doesn't work immediately after install

- SUPPORT.md
fix: https://github.com/Azure/azure-dev-pr/issues/1554
> Adding CSS notes to support.md

- cli/azd/resources/alpha_features.yaml
For: https://github.com/Azure/azure-dev/issues/2499
> promote ASA to beta feature

- cli/azd/cmd/init.go
- cli/azd/cmd/testdata/TestUsage-azd-init.snap
fix: https://github.com/Azure/azure-dev/issues/2053
> improve help for azd init with a branch

- cli/azd/pkg/tools/git/git.go
fix: https://github.com/Azure/azure-dev/issues/2582
> skip codespaces auth patch for git clone

- cli/azd/pkg/infra/azure_resource_manager.go
Updating the current approach to recursively pull all `deploymentOperations` from a root deployment.
Instead of return error and stop the traversal for a problematic deployment node, it is just ignored (error is only logged)
This will allow azd to get as much information from a deployment as possible for the `ProgressReporter` instead of giving nothing.
fix: https://github.com/Azure/azure-dev/issues/2622
> do not stop traversing deployments graph for a problematic deployment

- cli/azd/docs/feature-stages.md
> Update repo docs: feature stages: ASA to Beta and Cloudshell

- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/github/github_test.go
fix: https://github.com/Azure/azure-dev/issues/2181
Quick fix for a regex
> fix reg exp for repo in use (github)

- cli/azd/cmd/auth_login.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
fix: https://github.com/Azure/azure-dev/issues/2697
> use openWithDefaultBrowser for azd auth with device code

- templates/todo/api/java-postgresql/pom.xml
- templates/todo/api/java/pom.xml
Fix #2693 
@rajeshkamal5050 , @weikanglim for notification.
> Update prettier-maven-plugin version to 0.18

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
> Fix typo in soft delete warning message

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
> use location filter to init env

- cli/azd/cmd/auth_login.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/tools/git/git.go
- cli/azd/pkg/tools/github/github.go
fix: https://github.com/Azure/azure-dev/issues/2451
> Use git-credential-helper only on codespaces

- ext/vscode/src/commands/env.ts
Missed something in https://github.com/Azure/azure-dev/pull/2789.
> VSCode extension: Add a change I missed for environment listing

- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/java/terraform/devcontainer.json
- templates/todo/web/react-fluent/Dockerfile
continuation of: https://github.com/Azure/azure-dev/pull/2753
> Update missing node16 references to node18

- cli/azd/pkg/infra/azure_resource_types.go
fix: https://github.com/Azure/azure-dev/issues/2809
> adding private endpoint mapping

- schemas/v1.0/azure.yaml.json
Adds new top level `state` element into `azure.yaml` schema.
> Remote environment schema updates

- cli/azd/pkg/environment/data_store.go
- cli/azd/pkg/environment/manager.go
Improves the error message presented to the user when the azd remote state configuration is invalid.
> Improves error message when remote state configuration is invalid

- cli/azd/pkg/devcentersdk/devcenter_request_builders.go
- cli/azd/pkg/devcentersdk/developer_client.go
Fixes a race condition on the devcenter client cache map.
> Fixes race condition on writes to the devcenter client cache

- cli/azd/CHANGELOG.md
- cli/azd/cmd/init.go
- cli/azd/pkg/alpha/alpha_features.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/resources/alpha_features.yaml
- cli/azd/test/functional/init_test.go
- cli/azd/test/functional/telemetry_test.go
Promote alpha features easyInit and buildpacks to beta
Fixes #2861
> Promote easyInit and buildpacks to beta

- cli/azd/resources/apphost/templates/resources.bicept
- update blob contributor id for role assignment
> Update blob-contributor role id

- cli/azd/internal/tracing/fields/fields.go
- cli/azd/pkg/project/project_manager.go
Add usage telemetry for service targets resolved from hosts.
> Add service targets

- schemas/v1.0/azure.yaml.json
Promotes the devcenter & platform schema updates to v1.0
> [!IMPORTANT]  
> Do not merge till day of 1.5.0 release
Resolves #2911
> Promotes platform/devcenter schema updates to v1.0

- cli/azd/pkg/pipeline/pipeline_manager.go
fix: https://github.com/Azure/azure-dev/issues/2973
> check for nil before continue

- templates/common/infra/bicep/core/search/search-services.bicep
Cognitive Search just became AI Search.
> Update search-services.bicep with latest branding

- templates/common/infra/bicep/core/database/sqlserver/sqlserver.bicep
fix: https://github.com/Azure/azure-dev/issues/3022
> avoid warning for drop user

- cli/azd/CHANGELOG.md
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/docker/docker_test.go
fixes https://github.com/Azure/azure-dev/issues/3050
> adding target for docker build

- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- adding rg as variable for pipeline config
- azdo
> Setting RG env var for CI when it is set on env

- schemas/v1.0/azure.yaml.json
Updating azure.yaml schema to support docker build target
> [Merge for 1.5.1] Update azure.yaml.json so support docker build target

- schemas/v1.0/azure.yaml.json
Fixing small extra coma on last schema-update
> Fix schema typo

- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/remote_state_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_ProvisionState.yaml
- cli/azd/test/functional/testdata/recordings/Test_CLI_ProvisionStateWithDown.yaml
- cli/azd/test/functional/testdata/recordings/Test_CLI_Up_ResourceGroupScope.yaml
- cli/azd/test/functional/up_test.go
- cli/azd/test/recording/recording.go
Enable more tests for recording. This should speed up PR builds by ~10 minutes.
> Enable more tests for recording

- cli/azd/pkg/infra/azure_resource_types.go
> Display mysql flexible server during provison

- ext/vscode/package-lock.json
> `npm update @vscode/test-electron` and `npm audit fix`

- templates/common/infra/bicep/core/host/aks-agent-pool.bicep
- templates/common/infra/bicep/core/host/aks-managed-cluster.bicep
- templates/common/infra/bicep/core/host/aks.bicep
- templates/common/infra/bicep/core/security/aks-managed-cluster-access.bicep
- Updates bicep files to target the latest preview version
- Exposes additional properties onto the `aks` module to allow more configuration flexibility that is passed through to the underlying cluster creation.
> Updates AKS core modules for Azure RBAC support

- cli/azd/pkg/input/console.go
When the output is not a terminal, we can't erase the spinner, and so the spinner package just prints the next step of the spinner each time the message changes. For us that leads to output like:
````
| =     | Doing some long running thing
| =     | Doing some other running thing
`````
This doesn't look great.
Arrange things such that when we are not connected to a terminal, we just don't have a spinner animation. We still print the message, there is just no artwork to go with it.
> Don't show the spinner when output is not a terminal

- .github/workflows/devcontainer-feature-release.yml
- ext/devcontainer/src/azd-persistence/README.md
- ext/devcontainer/src/azd-persistence/devcontainer-feature.json
- ext/devcontainer/src/azd-persistence/install.sh
fix: https://github.com/Azure/azure-dev/issues/2921
Adding a new devcontainer feature to persist the .azd folder across devcontainers.
> azd-persistence feature

- cli/azd/ci-build.ps1
- cli/azd/pkg/input/console.go
> Remove quotes to appease ldflags parsing

- cli/azd/internal/scaffold/funcs.go
- cli/azd/internal/scaffold/funcs_test.go
- cli/azd/pkg/apphost/eval.go
- cli/azd/pkg/apphost/eval_test.go
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/resources/apphost/templates/resources.bicept
- scale to min 1
- handle special case for dbs with containerApp as parent resource
fixes: https://github.com/Azure/azure-dev/issues/3134
> For Aspire project using many dbs with a container.v0 as parent, create just one ContainerApp for all dbs

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
fix: https://github.com/Azure/azure-dev/issues/3302
> handle sql dbs with dev service in container

- templates/common/infra/bicep/core/search/search-services.bicep
We needed this change for latest search feature:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1159/files
> Update search-services.bicep with principalId

- cli/azd/pkg/infra/azure_resource_manager.go
This PR renames Form Recognizer to Document Intelligence, per their new name.
> Update azure_resource_manager.go name to Document Intelligence

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
Resolves #3391 
Updates condition for short circuit return during docker build
> Fixes docker build/package for Aspire projects

- cli/azd/internal/vsrpc/environment_service.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/pkg/environment/manager.go
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
> vsrpc: Expose .env path

- cli/azd/internal/vsrpc/environment_service_create.go
- cli/azd/internal/vsrpc/environment_service_load.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
Expose values stored in `.env` for `vs-server`.
Closes #3356
> vs: Expose setting/getting environment values 

- cli/azd/pkg/project/service_target_dotnet_containerapp.go
fix: https://github.com/Azure/azure-dev/issues/3436
> use Release for container push - service target dotnet containerapp

- cli/azd/pkg/apphost/service_ingress_configurer.go
fix: https://github.com/Azure/azure-dev/issues/3441
> hide containerApp for exposes services for prev4

- cli/azd/resources/scaffold/base/abbreviations.json
- templates/common/infra/bicep/abbreviations.json
- templates/common/infra/bicep/core/config/configstore.bicep
- templates/common/infra/bicep/core/security/configstore-access.bicep
Add Azure App Configuration store support
> Add Azure App Configuration store support

- cli/azd/pkg/devcentersdk/developer_client.go
> Fixes concurrent map race condition in devcenter client

- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
Avoid panic in constructing service components. Also did a quick scan of the codebase but did not find anything substantial.
Fixes #3463
> Avoid panic in constructing service components

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
fix: https://github.com/Azure/azure-dev/issues/3510
> update rules for setting secret env vars for projects

- schemas/v1.0/azure.yaml.json
Tracks https://github.com/Azure/azure-dev/pull/3452
> Add schema updates for sovereign cloud support

- cli/azd/resources/apphost/templates/next-steps.mdt
I noticed this typo in the next-steps.md and thought I should just submit the fix.
> Fix typo in next-steps.md

- cli/azd/test/functional/aspire_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_VsServer/LiveDeployRefresh.dotnet.yaml
- cli/azd/test/functional/testdata/recordings/Test_CLI_VsServer/LiveDeployRefresh.yaml
- cli/azd/test/functional/testdata/samples/aspire-full/Directory.Build.props
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.Web/manifests/containerApp.tmpl.yaml
- cli/azd/test/functional/testdata/snaps/aspire-full/aspire.hosting.azure.bicep.storage.bicep
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/main.bicep
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/resources.bicep
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/storage/aspire.hosting.azure.bicep.storage.bicep
- cli/azd/test/functional/testdata/snaps/aspire-full/manifest.json
> Update aspire functional tests to use preview4

- templates/common/infra/bicep/core/host/container-registry.bicep
- templates/common/infra/bicep/core/monitor/applicationinsights.bicep
- templates/common/infra/bicep/core/monitor/monitoring.bicep
- templates/common/infra/bicep/core/security/keyvault.bicep
- templates/common/infra/bicep/core/storage/storage-account.bicep
**Changes in `infra/core`**:
1. Upgrade `'Microsoft.ContainerRegistry/registries@2023-01-01-preview'` to `'Microsoft.ContainerRegistry/registries@2023-11-01-preview'`.
2. Add some default configurations in the `container-registry.bicep` file
3. Output some resourceId.
4. Upgrade `'Microsoft.Storage/storageAccounts@2022-05-01'` to `'Microsoft.Storage/storageAccounts@2023-01-01'`.
5. Add the creation of `fileServices`, `queueServices` and `tableServices` in the `storage-account.bicep` file
@jongio for notification.
> Update infra/core to adapt to more azdevify templates.

- eng/pipelines/templates/stages/1es-redirect.yml
Removes eslint warnings unrelated to our build.
> Update eslint config

- ext/vscode/package-lock.json
- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/init.ts
- ext/vscode/src/utils/azureDevCli.ts
> Allow init `--from-code`

- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-frontend.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
- cli/azd/pkg/apphost/testdata/TestAspireEscaping-api.snap
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
fix: https://github.com/Azure/azure-dev/issues/3649
> write default port to manifest for docker

- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/azure.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/azure.yaml
- templates/todo/projects/java-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/java-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/java-postgresql/.repo/terraform/azure.yaml
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/azure.yaml
- templates/todo/projects/python-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo/.repo/terraform/azure.yaml
Fix pwsh hooks error under windows, fixes [issue#3643](https://github.com/Azure/azure-dev/issues/3643).
@rajeshkamal5050 for notification.
> Fix pwsh hooks

- cli/azd/internal/vsrpc/environment_service_create.go
Add a progress message to improve the UX slightly.
> vs-server: Add progress message when analyzing Aspire app while creating environment

- cli/azd/cmd/env.go
- cli/azd/cmd/init.go
- cli/azd/internal/vsrpc/environment_service.go
- cli/azd/internal/vsrpc/environment_service_create.go
- cli/azd/pkg/environment/azdcontext/azdcontext.go
- cli/azd/pkg/environment/manager.go
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/initialize_test.go
fix: https://github.com/Azure/azure-dev/issues/2755
> Add .gitignore to .azure folder to make sure it is not committed

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/jobs/cross-build-cli.yml
- eng/pipelines/templates/stages/build-and-test.yml
> Fix cross-build configuration

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/apphost/testdata/TestAspireArgsGeneration.snap
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-frontend.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-api.snap
- cli/azd/pkg/apphost/testdata/TestAspireEscaping-api.snap
- cli/azd/pkg/apphost/testdata/aspire-args.json
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.ApiService/manifests/containerApp.tmpl.yaml
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.Web/manifests/containerApp.tmpl.yaml
> Support `args` on `project.v0` and `dockerfile.v0` resources

- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_DevCenter_Init_Up_Down.yaml
Updates the dev center functional tests configuration to a new instance.
- Test leverages recording when run in CI or when playback is enabled
> Updates devcenter functional test configuration

- cli/azd/pkg/project/ai_helper.go
getting:
but it is false possitive
> fix false positive credential leak

- templates/common/infra/bicep/core/ai/cognitiveservices.bicep
- templates/common/infra/bicep/core/ai/hub-dependencies.bicep
- templates/common/infra/bicep/core/ai/hub.bicep
- templates/common/infra/bicep/core/ai/project.bicep
- templates/common/infra/bicep/core/host/ai-environment.bicep
Adds the AI bicep modules used for the AI starter templates.
> Adds AI bicep modules used for AI starter templates

- cli/azd/cmd/actions/action.go
- cli/azd/cmd/cobra_builder.go
- cli/azd/cmd/container.go
- cli/azd/cmd/init.go
- cli/azd/cmd/middleware/middleware.go
- cli/azd/cmd/middleware/middleware_test.go
- cli/azd/cmd/middleware/telemetry.go
- cli/azd/cmd/middleware/ux.go
- cli/azd/cmd/root.go
- cli/azd/internal/cmd/provision.go
- cli/azd/internal/errors.go
- cli/azd/main.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/input/console_test.go
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/tools/azcli/ad.go
- cli/azd/pkg/tools/dotnet/dotnet.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/restore_test.go
- Refactors the display of action results and error messages.
- Moves action resolution from cobra builder to middleware runner
- Allows us to catch all errors consistently
- Easier to use `AZD_DEBUG` flag with `DebugMiddleware` to handle all classes of errors.
**Failure case with error, suggestion & Trace ID**
**Success**
> Azd Result & Error Display Refactor

- cli/azd/cmd/show.go
- cli/azd/pkg/contracts/show.go
- cli/azd/pkg/project/service_target_ai_endpoint.go
> Fixes panic during `azd show` for AI endpoint

- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/init.ts
> Split "from source" into separate question

- cli/azd/pkg/infra/azure_resource_types.go
Add a friendly string to be output when a Video Indexer resource is being created.
> Update Azure resource types to include Video Indexer

- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-my-sql-abstract.snap
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-mysqlabstract.snap
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-noVolume.snap
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
fix: https://github.com/Azure/azure-dev/issues/3873
> Fix mounting volumes add unit test for volumes and the expected yaml file

- cli/azd/pkg/config/config.go
- cli/azd/pkg/config/file_config_manager.go
- cli/azd/pkg/config/file_config_manager_test.go
fix: https://github.com/Azure/azure-dev/issues/3896
> update ResolvedRaw() to remove reference to the vault

- cli/azd/resources/apphost/templates/next-steps.mdt
- cli/azd/resources/scaffold/templates/next-steps.mdt
Refine docs in next steps based on feedback.
- Include docs for database environment variables only if configured
- Update instructions for `azd pipeline config`
- Update docs for Java default port
- Improve container app troubleshooting info
> easyInit: Refine docs in next steps

- cli/azd/pkg/azsdk/zip_deploy_client.go
- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_appservice_test.go
- cli/azd/pkg/tools/azcli/azcli_functions_test.go
- cli/azd/pkg/tools/azcli/azcli_staticwebapp_test.go
- cli/azd/pkg/tools/azcli/function_app.go
- cli/azd/pkg/tools/azcli/static_webapp.go
- cli/azd/pkg/tools/azcli/webapp.go
- go.mod
- go.sum
> Revert "add deployment status tracking for linux web apps"

- templates/todo/projects/java-postgresql/.repo/terraform/infra/main.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/main.tf
Updates remaining terraform AppService templates to B3 SKU
> Updates remaining terraform AppService templates to B3 SKU

- templates/common/infra/bicep/abbreviations.json
Used in this PR- 
https://github.com/Azure-Samples/azure-search-openai-demo/pull/113
> Update abbreviations.json with cog services speech

- cli/azd/ci-build.ps1
- cli/azd/main.go
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/jobs/cross-build-cli.yml
- eng/pipelines/templates/stages/build-and-test.yml
- eng/pipelines/templates/stages/publish.yml
- eng/pipelines/templates/stages/sign.yml
- eng/pipelines/templates/steps/publish-cli.yml
- eng/pipelines/templates/variables/image.yml
This PR brings azd to `Alpha` stage in this issue: https://github.com/Azure/azure-dev/issues/3968
`auth login`, `up`, and `down` commands were manually tested and work on a Windows ARM64 test machine.
> Alpha Windows ARM64

- templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep
See https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Cosmos.MinTLS/
> Force TLS1.2 in cosmos accounts

- cli/azd/pkg/project/framework_service_docker.go
Upgrade the oryx builder version
> Upgrade oryx

- cli/azd/ci-test.ps1
Looking at a functional test time increased.  Need to update from 90m to 120m
> more time for functional tests

- cli/azd/pkg/tools/azcli/function_app.go
Avoid making assumptions about the resource group of the service plan, parse the resource ID returned directly to locate the plan.
Fixes #4072
> Fix error in retrieving cross-rg service plan

- templates/todo/api/csharp-cosmos-sql/Todo.Api.csproj
- templates/todo/api/csharp-sql-func/Todo.Api.csproj
- templates/todo/api/csharp-sql/Todo.Api.csproj
fix: https://github.com/Azure/azure-dev/issues/4089
> update dotnet projects

- templates/todo/projects/csharp-cosmos-sql/.vscode/tasks.json
- templates/todo/projects/csharp-sql-swa-func/.vscode/tasks.json
- templates/todo/projects/csharp-sql/.vscode/tasks.json
- templates/todo/projects/java-mongo-aca/.vscode/tasks.json
- templates/todo/projects/java-mongo/.vscode/tasks.json
- templates/todo/projects/java-postgresql/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aca/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aks/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo/.vscode/tasks.json
- templates/todo/projects/python-mongo-aca/.vscode/tasks.json
- templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/python-mongo/.vscode/tasks.json
fix: https://github.com/Azure/azure-dev/issues/4107
> start web with `cross-env` for todo-templates. Makes command task to work in pwsh and bash both

- cli/azd/pkg/project/framework_service_docker.go
This change fails the service build when an explicit Dockerfile path is specified using `docker.path`, and the Dockerfile isn't found.
When no Dockerfile is specified, or `docker.path` is set to empty, `azd` will continue to use Oryx build.
Fixes #4086, #3551
> containerapp: Fail when explicit Dockerfile path not found

- .github/workflows/cli-ci.yml
- .github/workflows/cspell-misc.yml
- .github/workflows/templates-ci.yml
- .github/workflows/vscode-ci.yml
Issue reported to cspell: https://github.com/streetsidesoftware/cspell/issues/6025
> Pin cspell 8.12.1 b/c 8.13.0 has a bug

- .github/workflows/cli-ci.yml
- .github/workflows/cspell-misc.yml
- .github/workflows/templates-ci.yml
- .github/workflows/vscode-ci.yml
Removing the pin version after cspell fix: https://github.com/streetsidesoftware/cspell/issues/6025
> Revert "Pin cspell 8.12.1 b/c 8.13.0 has a bug" - new fixed version released for cspell

- .devcontainer/full/devcontainer.json
- .devcontainer/light/devcontainer.json
Provide a quick and smaller devcontainer for the project. Util for just looking at PRs and doing quick changes where we don't need support for all languages
> Add a light devcontainer which is good for reviewing PRs without loading a full environment with all languages support

- eng/pipelines/templates/stages/publish.yml
- eng/pipelines/templates/stages/verify-installers.yml
- eng/pipelines/templates/stages/vscode-publish-integration.yml
- eng/pipelines/templates/steps/install-azd-live-sh.yml
- eng/pipelines/templates/steps/publish-cli-container.yml
- eng/pipelines/templates/steps/publish-cli.yml
- eng/pipelines/templates/steps/publish-shield.yml
- eng/pipelines/templates/steps/publish-vscode.yml
- eng/pipelines/templates/steps/template-test-run-job.yml
- eng/pipelines/templates/variables/globals.yml
Also remove configuration from KV and put it directly in the yml files.
> Update storage publishing to use MI

- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
> Adds support for environment variable substitution for source container image

- cli/azd/docs/feature-stages.md
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/resources/alpha_features.yaml
- cli/azd/test/functional/deployment_stacks_test.go
- cli/azd/test/functional/telemetry_test.go
- cli/azd/test/functional/up_test.go
Promotes resource group scoped deployments to beta
> Promotes resource group scoped deployments to beta

- cli/azd/test/recording/proxy_test.go
Fixing the handling for record_mode = LIVE to unblock CI for now.
> recording: fix nil panic

- cli/azd/pkg/azapi/stack_deployments.go
fix: https://github.com/Azure/azure-dev/issues/4425
> report inner error description

- .github/workflows/vscode-ci.yml
> Update upload-artifact action to v4

- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/resources.go
> project: add resources schema

- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/resources.bicept
Add backend infra generation for OpenAI models.
> compose: generate openai in the backend

- cli/azd/internal/repository/infra_confirm.go
Refactoring port prompting. These changes are being teased out to reshare implementation across composability-enabled and regular pathways.
> chore: refactor port prompt

- cli/azd/pkg/input/asker.go
Update formatting for select, multiselect and input.
Changes:
- Select/multiselect - Blue instead of cyan for highlighted entry
- Multiselect - Green tick mark for selected entries
- Input - Grey text for default value
Images:
> asker: update formatting for select, multiselect and input.

- eng/pipelines/templates/steps/install-terraform.yml
Contributes to: https://github.com/Azure/azure-dev/issues/4668
> update terraform task installer

- cli/azd/pkg/tools/bicep/bicep.go
Updating bicep cli to support [bicep extensions](https://learn.microsoft.com/azure/azure-resource-manager/bicep/bicep-extension)
> udep bicep

- eng/pipelines/templates/stages/build-and-test.yml
- eng/pipelines/templates/stages/verify-installers.yml
- eng/pipelines/templates/variables/image.yml
Fixes #4693
@JeffreyCA this should unblock you... and everyone else
> Update mac images

- .github/CODEOWNERS
Cutting down my notifications after leaving the team and ensuring you all keep me honest and don't let me approve anymore PRs ;-).
Was a ton of fun working with you all!  Hopefully I won't be a stranger.
> chore: Remove @ellismg from `CODEOWNERS`

- cli/azd/pkg/tools/bicep/bicep.go
Following bicep release: https://github.com/Azure/bicep/releases/tag/v0.33.13
> update bicep version 33 13

- cli/azd/.vscode/cspell.yaml
- cli/azd/cmd/show.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/pkg/common/detailed_error.go
- cli/azd/pkg/ux/canvas.go
- cli/azd/pkg/ux/confirm.go
- cli/azd/pkg/ux/internal/cursor.go
- cli/azd/pkg/ux/internal/input.go
- cli/azd/pkg/ux/printer.go
- cli/azd/pkg/ux/prompt.go
- cli/azd/pkg/ux/select.go
- cli/azd/pkg/ux/spinner.go
- cli/azd/pkg/ux/task_list.go
- cli/azd/pkg/ux/ux.go
- cli/azd/pkg/ux/visual.go
- go.mod
- go.sum
Adds v2 UX components used within extension framework experiences.  
Components are built upon a canvas rendering strategy that support inline re-rendering of components as needed.
Prompts a user for a single piece of data.  Includes formatting and validation and automatic user feedback.
Prompts a user to confirm (yes/no) some operation
Prompt a user to select a value from a list. Includes filtering and paging of long data.
Lightweight spinner component
Shows a series of tasks that are in progress with automatic reporting of status.  Support multiple async operations
> Extensions Framework: Adds v2 UX Components

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/stages/build-and-test.yml
- eng/pipelines/templates/stages/verify-installers.yml
- eng/pipelines/templates/variables/image.yml
Fixes https://github.com/Azure/azure-sdk-tools/issues/9723 for [known usages in Azure org](https://github.com/search?q=org%3AAzure+azsdk-pool-mms-ubuntu-2004-arm&type=code).
> Migrate usage of azsdk-pool-mms-ubuntu-2004-arm to azsdk-pool-arm64

- schemas/v1.0/azure.yaml.json
To me merged after merging: https://github.com/Azure/azure-dev/pull/4517
> update schema hooks secrets

- cli/azd/.vscode/cspell.yaml
- cli/azd/docs/extension-framework.md
- cli/azd/grpc/proto/deployment.proto
- cli/azd/grpc/proto/environment.proto
- cli/azd/grpc/proto/prompt.proto
- cli/azd/grpc/proto/user_config.proto
Adds developer markdown docs for internal extension development.
> Extensions: Developer Docs

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/internal/scaffold/scaffold.go
- cli/azd/internal/scaffold/scaffold_test.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
Address https://github.com/Azure/azure-dev/issues/4671, this PR will add the resource support of MySQL database.
> Add schema support for mysql

- cli/azd/cmd/infra.go
- cli/azd/cmd/root.go
- cli/azd/pkg/extensions/manager.go
- Only run extensions middleware in the same commands that support hooks
- Fix issues where extensions where capabilities were not being set during installation
> Extensions: Minor fixes for extensions middleware

- cli/azd/cmd/root.go
- cli/azd/cmd/util.go
- cli/azd/internal/cmd/show/show.go
- cli/azd/internal/cmd/util.go
Refactoring only, moving show command to separate package to better deliver upcoming changes for showing resources.
Contributes to #4727
> chore: move show to separate pkg

- cli/azd/pkg/password/generator.go
fix: https://github.com/Azure/azure-dev/issues/4848
> reduce symbols for generator

- cli/azd/docs/extension-framework.md
- cli/azd/grpc/proto/event.proto
Updates docs to include details about lifecycle events.
> Extension Framework: Updates developer docs for extension framework

- .github/CODEOWNERS
Update CODEOWNERS to use the same configuration as other SDK repos and eliminate @danieljurek from the critical path to updating the CODEOWNERS file.
> Add code owners for CODEOWNERS file

- cli/azd/pkg/extensions/manager.go
- cli/azd/pkg/extensions/manager_test.go
> Extensions: Adds execute permissions to extension binary artifact during installation

- ext/azuredevops/README.md
Updating docs for Azure DevOps task after customer's feedback: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.azd&ssr=false#review-details
> update docs for azdo task

- ext/azuredevops/README.md
- ext/azuredevops/setupAzd/package-lock.json
- ext/azuredevops/setupAzd/package.json
- ext/azuredevops/setupAzd/task.json
- ext/azuredevops/vss-extension.json
Had to release 1.0.1 just to correct the Readme that is displayed in the Marketplace.
> AzureDevOps - Install Azd extension - 1.0.1 release

- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/tools/avmres/main.go
fix: https://github.com/Azure/azure-dev/issues/4922
When defining the usageName, users can either set an string with just one sku and capacity or they can define an array.
> Adding support for array of usageName when checking for quota

- cli/azd/cmd/init.go
> Prompt Deploy after Init

- .vscode/cspell.global.yaml
- cli/azd/test/recording/recording.go
- cli/installer/install-azd.ps1
- cli/installer/install-azd.sh
- cli/installer/test-installer-containers.ps1
- cli/installer/test-pwsh-xplat-install.ps1
- cli/installer/test-win-install.ps1
Workaround for https://github.com/Azure/azure-dev/issues/4992
Updates hostname to use storage account.
> [mitigation] Use storage host directly

- cli/azd/internal/grpcserver/prompt_service.go
- cli/azd/pkg/prompt/prompt_models.go
- cli/azd/pkg/prompt/prompt_service.go
- cli/azd/pkg/ux/confirm.go
- cli/azd/pkg/ux/multi_select.go
- cli/azd/pkg/ux/printer.go
- cli/azd/pkg/ux/select.go
- cli/azd/pkg/ux/spinner.go
Addresses some edge cases for UX controls used in prompting:
- Detecting console within within sub shell
- Color adjustments to use `azd` standards
- Spinner refactoring
> Ext Framework: Prompt / UX fixes

- ext/vscode/CHANGELOG.md
- ext/vscode/package-lock.json
- ext/vscode/package.json
Releasing new version with npm packages updates and the change to support azd init with up flag
> VSCode ext - release - 0.9.0

- cli/azd/pkg/tools/swa/swa.go
- ext/azuredevops/setupAzd/package-lock.json
- ext/azuredevops/setupAzd/package.json
- templates/todo/api/python/requirements.txt
Addresses:
CVE-2024-35255 - updated `azure-identity` python package in `templates/todo/api/python/requirements.txt`
CVE-2022-25881 - removed unused dependency from `setupAzd`
CVE-2022-33987 - removed unused dependency from `setupAzd`
- Flaky test: https://github.com/Azure/static-web-apps-cli/issues/916
> Update and remove unused dependencies

- eng/pipelines/repoman.yml
fix: https://github.com/Azure/azure-dev/issues/5062
missing changes after: https://github.com/Azure/azure-dev/pull/4984/files
> add missing pipeline variables

- eng/pipelines/repoman.yml
Using variables failed with:
##[error]Pipeline does not have permissions to use the referenced pool(s) . For authorization details, refer to https://aka.ms/yamlauthz.
Started: Just now
Duration: <1s
Trying w/o variables, to unblock pipeline
> try with no variable

- cli/azd/cmd/extensions.go
- cli/azd/pkg/extensions/manager.go
- cli/azd/pkg/extensions/manager_test.go
- cli/azd/pkg/ux/task_list.go
Fixes issues with local extension sources that reference local file artifact paths.
Resolves #5038
> Fixes support for local file extension sources

- cli/azd/cmd/middleware/extensions.go
> Extensions: Fixes hang issues on azd up

- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/watch.go
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/azd_client.py
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/commands/listen_command.py
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/event_manager.py
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/main.py
- Adds additional file/folder exclusions on watch list for python apps
- Fixes event_manager.py implementation
- Adds missing `authorization` handling in event streams
- Updates `stdout` to use unbuffered printing for faster user feedback
> Developer Extension - Python updates

- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/build.ps1
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/build.sh
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/commands/version_command.py
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/main.py
- Adds version command to python template
- Fixes #5136
> Developer Extension: Adds version command to python template

- .gitattributes
- cli/azd/.vscode/cspell.yaml
- cli/azd/docs/extension-framework.md
- cli/azd/extensions/microsoft.azd.extensions/changelog.md
- cli/azd/extensions/microsoft.azd.extensions/extension.yaml
- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/init.go
- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/watch.go
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/build.ps1
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/build.sh
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/commands/listen.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/commands/prompt.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/eventManager.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/grpcUtils.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/index.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/logger.js
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/package.json
- Adds some additional documentation
- Fixes event manager implementation
- Replaces console.log logging with winston implementation
- Updates ignore files for JS (for watch command)
- Fixes line endings for shell scripts
> Developer Extension: Fixes for JS support

- cli/azd/internal/repository/detect_confirm_apphost.go
Removing ACA fom the description as Aspire is no longer ACA only.
> Update Aspire detection description

- .github/CODEOWNERS
Add @rajeshkamal5050 as owner for `/cli/` path
> Update CODEOWNERS under `/cli/` path

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/pipeline/pipeline.go
Fix the logic while resolving if parameters are using value from env var mapping or not
> make provider return when env var is used

- cli/azd/pkg/environment/manager.go
fix: https://github.com/Azure/azure-dev/issues/5169
> Adding unique to the input message for azd environment

- cli/azd/internal/vsrpc/server.go
Fix background telemetry upload handling in vs-server
fix: https://github.com/Azure/azure-dev/issues/5251
> Fix VS-Server telemetry system when OFF

- cli/azd/test/functional/testdata/vs-server/tests/AzdVsServerTests.csproj
Contributes to: https://github.com/Azure/azure-dev/issues/4956
> Update dependencies for CVE-2024-48924

- .github/CODEOWNERS
Sticking myself in CODEOWNERS so I can review PRs.  :smile:
> tg-msft joining azd

- .github/copilot-instructions.md
Update the GitHub Copilot documentation to include a comprehensive architecture overview and refined coding standards, emphasizing dependency injection, middleware integration, and testing patterns.
> Enhance GitHub Copilot instructions with detailed architecture overview and coding standards

- cli/azd/test/functional/env_refresh_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_EnvRefresh_NoBicep.yaml
Fixing a test issue introduced as part of https://github.com/Azure/azure-dev/pull/4832
> update test broken test case and recording

- cli/azd/pkg/azdo/pipeline.go
fix: https://github.com/Azure/azure-dev/issues/5438
> Fix: Skip auth config for AzureDevOps returning nil pointer error

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/variables/image.yml
Fixes #5541
Example pipeline run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5154422&view=logs&j=90dd592b-3d52-543c-a8c6-c88386b77a8c&t=0ab8055a-c162-59f1-3cdc-560d5532707f
> Update macos image value

- ext/azuredevops/CONTRIBUTING.md
- ext/azuredevops/setupAzd/package-lock.json
- ext/azuredevops/setupAzd/package.json
- ext/azuredevops/setupAzd/task.json
- ext/azuredevops/vss-extension.json
Releasing 1.1.0 with dependency updates
fix: https://github.com/Azure/azure-dev/issues/5526
> release install azd for azure devops 1.1.0

- cli/azd/resources/scaffold/base/abbreviations.json
Followed recommendations here: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations
> Add abbreviation for aiFoundryAccounts

- cli/azd/internal/appdetect/testdata/java-multimodules/application/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/library/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/module2/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/module2/submodule1/pom.xml
- cli/azd/test/functional/testdata/samples/springapp/pom.xml
Actions for https://spring.io/security/cve-2025-41248
fix: https://github.com/Azure/azure-dev/issues/5801
> Bump version to mitigate CVE-2025-41249

- cli/azd/extensions/azure.coding-agent/extension.yaml
- eng/pipelines/release-ext-azure-coding-agent.yml
Updated the description of the extension based on @vhvb1989's feedback.
> Adding in CI for the `coding-agent` extension

- cli/azd/extensions/registry.json
Publish 0.3.0 version of demo extension
> Publish 0.3.0 of demo extension
