- templates/tests/test-templates.sh
Updates the template testing scripts with the following options:
- Adds support to specify azure location/region to use (defaults to eastus2)
- Adds configurable Playwright retries (defaults to 3)
- Adds parallelism for azd up/down
- Adds output to specify `TEST_ONLY` run
- Adds option to specify whether local & remote cleanup should be performed
> Updates template testing script with additional options

- cli/azd/CHANGELOG.md
- cli/azd/main.go
- cli/azd/test/functional/cli_test.go
We have logic very early in the startup process of `azd` to do an
initial parse of the command line arguments to see if `--debug` has
been passed (so we can set up our debugging channels to output to the
correct location).
That logic uses `pflag` to parse the command line with a very limited
set of flags (just `--debug`) with it configured to ignore all other
flags. However, pflag treats `--help` as special and when the flag is
not defined returns `ErrHelp` from `Parse` to denote that help was
requested.
Our logic would write any failure from `Parse` to the debug log, which
meant that we would end up printing something like this to stderr at
the start of the command when `--help` was passed:
```
Usage of :
--debug
```
This change adds a `help` parameter so that we don't hit this behavior …
> Fix debug message when --help is passed to CLI

- .github/workflows/vscode-ci.yml
Related to: https://github.com/Azure/azure-dev/pull/74
and to: https://github.com/Azure/azure-dev/pull/72
Where cspell is moved from running all checks only when updating the cli folder to run it depending on the folder
> Run cspell for vscode extension only when updating the extension code

- .github/workflows/cli-ci.yml
- cli/azd/CHANGELOG.md
- cli/azd/cmd/pipeline.go
- cli/azd/pkg/tools/gh.go
- cli/azd/pkg/tools/git.go
fix https://github.com/Azure/azure-dev/issues/71
Check if GitHub actions are disabled *Only* when user requested to push changes AND this is NOT a just-created repo
A repo that is just created would return zero GitHub Actions and might be confused by azd
as a repo where Actions are disabled. Sadly, there's not GitHub API to fetch exact information
to distinguish between disabled-after-fork v/s repo-disabled-actions v/s similar scenarios).
check if workflow file is already tracked by git.
If the file is not tracked, it means this is a new file (never pushed to mainstream)
A git untracked file should not be considered as GitHub workflow until it is pushed.
> fix `disabled actions` detector

- cli/azd/pkg/rzip/rzip.go
- cli/azd/test/functional/cli_test.go
Updating implementation details to use walkDir() instead of walk()
fix https://github.com/Azure/azure-dev/issues/22
> Update walk() to walkDir() API

- cli/azd/cmd/login.go
- cli/azd/cmd/util.go
- cli/azd/pkg/tools/azcli.go
- Fix internal #1392 : Location prompt now first attempts `az login`
- Fix #10: Update error message to include `run azd login`
- Fix #48: Detect when refresh token is expired and run automatic login
> Improve login detection

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/environment/azd_context.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/tools/azcli.go
- cli/azd/pkg/tools/docker.go
- cli/azd/pkg/tools/docker_test.go
- schemas/v1.0/azure.yaml.json
Adds support for custom docker options.
**Example**
```yaml
name: todo-nodejs-mongo-aca
metadata:
template: todo-nodejs-mongo-aca@0.0.1-beta
services:
api:
project: src/api
language: js
docker:
path: ./Dockerfile
context: ../
web:
project: src/web
language: js
```
Resolves Azure/azure-dev-pr#1298
> Adds support for custom docker options

- cli/azd/pkg/tools/dotnet.go
Add stderr, stdout output to error logged when `dotnet` command fails.
Before:
After:
> Add more detailed log for failed `dotnet` commands

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/.vscode/cspell.yaml
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/init.go
- cli/azd/cmd/login.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/root.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/up.go
- cli/azd/cmd/util.go
- cli/azd/cmd/version.go
- cli/azd/docs/.gitignore
- cli/azd/docs/docgen.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/output/parameter.go
- eng/pipelines/release-cli.yml
Our current story for generating docs suitable for ingestion in
docs.microsoft.com is "generate a single markdown file with all the
commands and use anchors to cross reference". Since that's not
something the Cobra markdown formatters support out of the box, PC has
manually been merging these files together and doing some small
tweaks.
This PR attempts to automate that logic.
My first attempt at these changes had us to continue to use the Cobra
logic directly (by importing the package it was in) and then try to
clean up small things with some post processing. However, once I
realized that we would need to re-order the default output of the list
commands from SEE ALSO I decided to just take the existing code and
bring it in here and make small tweaks.
At some point, we will move to a …
> Generate combined markdown docs file per build

- templates/todo/api/csharp-cosmos-sql/Program.cs
- templates/todo/api/csharp-sql/Program.cs
- templates/todo/api/csharp/Program.cs
- templates/todo/api/js/src/config/observability.ts
- templates/todo/web/react-fluent/src/services/telemetryService.ts
Fixes #105
With this change if Application Insights setup throws (e.g. when running apps locally), we log the error but let an application work.
> Continue on AppInsights setup errors to simplify local development

- ext/vscode/package.nls.json
- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/deploy.ts
- ext/vscode/src/commands/env.ts
- ext/vscode/src/commands/infra.ts
- ext/vscode/src/commands/init.ts
- ext/vscode/src/commands/monitor.ts
- ext/vscode/src/commands/pipeline.ts
- ext/vscode/src/commands/provision.ts
- ext/vscode/src/commands/restore.ts
- ext/vscode/src/commands/up.ts
- ext/vscode/src/extension.ts
- ext/vscode/src/test/suite/unit/lazy.test.ts
- ext/vscode/src/test/suite/unitTests.ts
- ext/vscode/src/test/testUtil/async.ts
- ext/vscode/src/utils/azureDevCli.ts
- ext/vscode/src/utils/lazy.ts
This change will detect that `azd` CLI is not installed and if that is the case, offer to open the web page with installation instructions.
It will also track the `azd` CLI version in VS Code telemetry.
> Add azd CLI installation and version check

- cli/azd/CHANGELOG.md
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/init.go
- cli/azd/main.go
- cli/azd/pkg/environment/azd_context.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/osutil/permissions.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/test/functional/cli_test.go
- schemas/v1.0/azure.yaml.json
This fix ensure that the full infra module path is created when generating bicep module parameters file.
This fix allows the use of paths in the service `moduleName` property.  We should also consider renaming this prop to `modulePath` or similar.
**Example**
```yaml
name: todo-nodejs-mongo-aca
metadata:
template: todo-nodejs-mongo-aca@0.0.1-beta
services:
api:
project: src/api
language: js
module: ./api/api
web:
project: src/web
language: js
module: ./web/web
```
Fixes Azure/azure-dev-pr#1377
> Support for nested Bicep infra modules with container app target

- ext/vscode/src/extension.ts
(by mistake it was left enabled only for the product team members)
> Enable experimentation for all users

- cli/azd/.vscode/settings.json
- cli/azd/cmd/env.go
- cli/azd/cmd/init.go
- cli/azd/cmd/util.go
- cli/azd/pkg/environment/environment.go
This change supports AZD integration with Visual Studio
> Add location and subscription parameters to env new commad

- generators/repo/src/commands/generate.ts
- generators/repo/tsconfig.json
Updates the relative path rewriting within referenced files
This change also updates the TypeScript lib to `es2021` to take advantage of some new methods available on `string` such as `replaceAll`
> Repoman - Updates relative path rewriting algo

- cli/azd/cmd/deploy.go
The error variable was shadowed by mistake, causing deployment errors to be ignored
> Fix deployment error handling

- cli/azd/CONTRIBUTING.md
(no need to have hard-coded working directory)
> Update debug configuration

- cli/azd/cmd/deploy.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/up.go
Formatting fixes:
- Print a newline between `provision` and `deploy` in `azd up`
- Print with styling for endpoint links in `deploy`
Before:
After:
> Fix formatting issues

- eng/pipelines/repoman.yml
Today, whenever a change to templates or generators is made in `main` the updates are propagated to samples repos immediately. This eliminates the CI trigger and requires a manual run to update the template repos. 
When working on template changes in a PR, the change report generated by the pipeline will include changes accumulating in `main` which have not yet been pushed to the sample repos.
> Repoman: Disable CI trigger 

- cli/azd/pkg/project/framework_service_docker_test.go
Add synchronization to remove non-determistic assertions.
Fixes #204
Verified that the test still passes with introduced delay (it was failing before)
```golang
go func() {
for value := range progress {
time.Sleep(10 * time.Seconds) // Add delay to verify determistic program
status = value
progressMessages = append(progressMessages, value)
}
done <- struct{}{}
}()
```
> Fix flaky test `TestDefaultDockerOptions`

- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_config_test.go
Adds the ability the register event handlers for project/service lifecycle events and raise events to call all registered handlers
This event driven design will allow for framework services and service targets to create more robust integrations based on lifecycle events versus having tightly coupled code changes spread throughout the codebase.
> Adds support for project/service lifecycle events

- cli/azd/CHANGELOG.md
- cli/installer/install-azd.ps1
- cli/installer/test-pwsh-win-install.ps1
- cli/installer/uninstall-azd.ps1
What this change does: 
* Stops using `[Environment]::SetEnvironmentVariable` when setting `PATH` as it changes the registry entry type and sets the type directly using registry APIs. Also of note, the install script preserves the registry key type as it is read from the system and do not attempt to mutate the type. 
* Sends a message to other windows using a "noop" invocation `[Environment]::SetEnvironmentVariable` which deletes a nonexistent variable. The result is a safe invocation of code which sends a `WM_SETTINGCHANGE` message (thus allow users to start using `azd` without having to restart or log out). The nonexistant variable is `AZD_INSTALLER_NOOP`
Also explored a couple of alternatives: 
* `Set-ItemProperty` -- Does not send `WM_SETTINGCHANGE` message
* PInvoke …
> Installer: PATH registry type

- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_config_test.go
> Adds support to pass custom event args when raising project/service events

- eng/pipelines/template-tests.yml
Some of our templates require resources that are not supported in
eastus, just eastus2. The script itself defaults to eastus2, so the
pipeline should as well.
> Use `eastus2` not `eastus` as default location

- cli/azd/cmd/deploy.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/init.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/util.go
- cli/azd/cmd/util_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/input/console.go
- cli/azd/test/mocks/mock_console.go
Merges the old asker Fn implementation with the new `input.Console` interface to support easier testing and usage with standard return values rather than forcing function parameters with pointers.
> Consolidate and refactor to single asker/console

- eng/pipelines/release-cli.yml
I happened to notice the Mac jobs of Verify_Installers were actually running on `ubuntu-latest`.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1787785&view=logs&j=ff4b8089-48d5-53de-a8b8-1b4437579a6d
The wrong variable was being set in the `pool` section, which doesn't matter for 1ES pools, but it was causing the default image to be used for the DevOps pool.
You may also want to add a step to verify the correct OS is being used, like https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Verify-AgentOS.ps1.
> Fix Verify_Installers vmImage for Mac

- eng/pipelines/template-tests.yml
The environment name for each template test must be unique.
This PR updates the name used for the extra template-name (which validates using upper case letters for the env name)
to be unique.
> Fix template-test CI pipeline with unique name for upper case env name test

- cli/azd/test/samples/funcapp/infra/resources.bicep
- templates/todo/common/infra/aca/api.bicep
- templates/todo/common/infra/aca/resources.bicep
- templates/todo/projects/csharp-cosmos-sql/infra/resources.bicep
- templates/todo/projects/csharp-mongo/infra/resources.bicep
- templates/todo/projects/csharp-sql/infra/resources.bicep
- templates/todo/projects/nodejs-mongo-swa-func/infra/resources.bicep
- templates/todo/projects/nodejs-mongo/infra/resources.bicep
- templates/todo/projects/python-mongo-swa-func/infra/resources.bicep
- templates/todo/projects/python-mongo/infra/resources.bicep
Fixes #503
We discovered that serverfarms now requires "properties: {}" to be valid.  We have also filed an issue with bicep here, but have added that now to unblock. 
Bicep issue: https://github.com/Azure/bicep/issues/8118
We are also updating all RPs to latest versions.
> Add asp properties and update rp versions

- cli/azd/test/functional/cli_test.go
Using `t.parallel()` on azd test which are doing init+provision
> Update functional tests to run in parallel

- templates/todo/common/tests/todo.spec.ts
The file had some characters that looked like colons but were not the
colons that JavaScript was looking for.
> Fix syntax issue in playwrite tests

- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/init.go
- cli/azd/cmd/login.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/up.go
- cli/azd/cmd/version.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/commands/builder_test.go
Introduce a `BuildOptions` struct for optional build parameters so that we can easily customize build options in the future, such as in upcoming PR #483 
Refactor `Long` and `Aliases` to use it.
> Refactor command build options

- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/pkg/azure/resource_ids.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/azure_resource_manager_test.go
- cli/azd/pkg/infra/provisioning/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display_test.go
- cli/azd/pkg/infra/provisioning/test_provider.go
- cli/azd/pkg/infra/scope.go
- cli/azd/pkg/infra/scope_test.go
- cli/azd/pkg/project/service_target_containerapp.go
Since container app deployments today use a resource group scoped Bicep deployment the output required some updates to correctly display the effected resources.
> Fixes provisioning output for container app deployments

- cli/azd/main.go
- cli/azd/pkg/container/dependencies.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/test/functional/cli_test.go
Moves the `bicep` and `test` infra providers into their respective packages.
Also introduces a **registration** concept for providers to register themselves with azd and to avoid circular dependencies.
> Moves infra modules into seperate packages

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/main.go
- cli/azd/pkg/azureutil/principal.go
- cli/azd/pkg/cmdsubst/cmdsubst.go
- cli/azd/pkg/cmdsubst/cmdsubst_test.go
- cli/azd/pkg/cmdsubst/secretOrRandomPassword.go
- cli/azd/pkg/environment/azdcontext/azdcontext.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/password/generator.go
- cli/azd/pkg/password/generator_test.go
- cli/azd/pkg/password/shuffle.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/tools/azcli/azcli.go
- templates/todo/api/csharp-sql/Program.cs
- templates/todo/api/csharp-sql/Todo.Api.csproj
- templates/todo/projects/csharp-sql/.vscode/launch.json
- templates/todo/projects/csharp-sql/.vscode/tasks.json
- templates/todo/projects/csharp-sql/infra/db.bicep
- templates/todo/projects/csharp-sql/infra/main.bicep
- templates/todo/projects/csharp-sql/infra/main.parameters.json
- templates/todo/projects/csharp-sql/infra/resources.bicep
A bigger change than just the template because we need to add password-generation capability to AZD (for Bicep). Note that if we decide to have an equivalent Terraform template, no extra work will be necessary because Terraform already has password generation built-in.
The changes to deployment provider (renaming `Preview()` to `Prepare()` method and having `Deploy()` take a `PreparedDeployment` is something @ellismg @HadwaAbdelhalem and @wbreza discussed offline.
I will need some help with making this template subject to automated tests and flipping the corresponding repo to public--TIA!
Fixes https://github.com/Azure/azure-dev/issues/450
> Fix C# + SQL Azure template

- generators/repo/src/commands/generate.ts
- generators/repo/src/common/util.ts
This PR addresses part of #524 , specifically adding ./ to local paths. This is needed to support Terraform local modules PR #532. A separate PR will be provided to add the ReWrite Rules section.
This PR introduces:
- A utility method in repoman utils to add a base path that is platform specific "./" or ".\\".
- Changes to the repoman path rewrite normalization to add a base prefix.
Tests were conducted to verify the CI workflow for repoman generate and a test azd deployment was conducted against a test repo with the relative base path included "./"
[Repo generation CI (on fork)](https://dev.azure.com/csedevops/Azure-dev/_build/results?buildId=15093&view=logs&s=2f4b62b5-8d35-5570-0513-04a0c5199809
)
Resources Deployed via modified template:
Running Application:
> Repoman - Adding relative base path ./ to path rewrites.

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
Fix invalid JSON tag.
Verification program:
```go
package main
import (
"encoding/json"
"fmt"
)
type Before struct {
InternalSchema string `json:"$schema`
}
type After struct {
InternalSchema string `json:"$schema"`
}
func print(prefix string, v any) {
bytes, err := json.Marshal(v)
if err != nil {
panic(err)
}
fmt.Println(prefix + " " + string(bytes))
}
func main() {
print("Before:", Before{InternalSchema: "foo"})
print("After:", After{InternalSchema: "foo"})
}
```
Output:
```bash
Before: {"InternalSchema":"foo"}
After: {"$schema":"foo"}
```
```
> Fix JSON tag of bicepTemplate `$schema`

- generators/repo/src/commands/generate.ts
- generators/repo/src/models/index.ts
- templates/todo/projects/csharp-cosmos-sql/repo.yaml
- templates/todo/projects/csharp-mongo/repo.yaml
- templates/todo/projects/csharp-sql/repo.yaml
- templates/todo/projects/nodejs-mongo-aca/repo.yaml
- templates/todo/projects/nodejs-mongo-swa-func/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-aca/repo.yaml
- templates/todo/projects/python-mongo-swa-func/repo.yaml
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
This PR addresses #524 and provides an update to the repoman.yaml file structure to introduce a new property for Rewrite rules. The rules property replaces the previously used patterns list. 
Changes:
- Introduce new rewrite.rules section.
- Add Rewrite rules section to all repo.yaml files for all existing templates.
```yaml
rewrite:
rules:
- from: ../../../../common/infra/bicep
to: ./
patterns:
- "**/*.bicep"
```
Similar to AssertRules, Rewrite rules supports the following options per rule:
- from: the path string to replace. 
- to: the replacement string.
- patterns: A list of glob patterns to apply the replacement to.
- ignore: pattern of files to ignore in the glob search.
Testing:
- Generated all templates locally and verified that azure.yaml and IAC paths were rewritten correctly.
- …
> Repoman - Adding support for Rewrite Rules in repo yaml.

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/monitor.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/provisioning/bicep_provider.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/project_test.go
- cli/azd/pkg/project/service.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/test/mocks/executil/mock_executil.go
- cli/azd/test/mocks/httputil/mock_http_client.go
- cli/azd/test/mocks/mock_context.go
- Switch to `az resource list` or `az group list` to fix resource query delays. 
- Remove "ERROR: " prefix from DeploymentNotFound error detection.
- Remove "ERROR: " prefix from ConfigNotFound error detection.
Fixes:
- #540
- #559 
- #539
> Switch to azure resource list

- cli/installer/install-azd.sh
- eng/pipelines/release-cli.yml
Fixes #430
Install-over scenario failing: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1818525&view=logs&s=62dbc4f1-f27c-5ddb-f6ac-c39a8a0ad4eb&j=3af97778-1b65-5cdf-4769-7545b9560ece
Install-over scenario succeeding after changing from `cp` to `mv`: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1824321&view=logs&j=3af97778-1b65-5cdf-4769-7545b9560ece&t=ff826ce0-844a-565c-9402-6d06ff212f8e
> Validate Mac install-over scenario

- cli/azd/cmd/deploy.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/spin/spin.go
- cli/azd/pkg/spin/spin_test.go
With the introduction of provisioning manager it is now possible that there could be multiple instances of spinner created within different components.  This PR introduces the spinner into the context where it can be leveraged by downstream components.  
Without reusing the spinner component we see flashing display as the 2 spinner instances attempt to overwrite each other.
Ex) Spinner is used in the `deploy` command that calls into the provisioning manager.
> Reuse spinner instance when available

- cli/azd/pkg/project/service_target_containerapp.go
Resolves initial container app deploy error during template tests.  The deployment plan that includes the input parameters was created before the container image is evaluated.
After the first failure the image name env var has been set allowing subsequent deployment to succeed.
> Fixes order of operations on container app deploy

- cli/azd/CHANGELOG.md
- cli/azd/cmd/monitor.go
fix https://github.com/Azure/azure-dev/issues/522
> Update default view for azd monitor to dashboard

- cli/azd/pkg/tools/ensure.go
- cli/azd/pkg/tools/ensure_test.go
- cli/azd/pkg/tools/tool_test.go
With multiple components requiring various external tools at different levels we are getting to a point where the tools install check is slowing down the executing of our commands.
This fix effectively introduces a cache and ensures that tool checks are only ever checked a single time.
> Improves performance of dependent tool checking

- cli/azd/test/functional/cli_test.go
From `1 / 4096 = 0.02%` chance to `1 / 16777216 = 5.96e-6%` chance
Fixes #613
> Decrease likelihood for name collisions on CI tests

- cli/azd/internal/telemetry/telemetry.go
Use new dev instrumentation key since the resource was deleted.
> Use new dev instrumentation key

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/telemetry/fields/fields.go
- cli/azd/internal/telemetry/resource/exec_environment.go
- cli/azd/internal/telemetry/resource/machine_id.go
- cli/azd/internal/telemetry/resource/resource.go
- cli/azd/internal/telemetry/telemetry.go
- cli/azd/internal/telemetry/telemetry_context.go
- cli/azd/internal/telemetry/tracer.go
- cli/azd/internal/useragent.go
- cli/azd/internal/useragent_test.go
Check `AZURE_DEV_USER_AGENT` for the presence of VSCode's user agent. Set the execution environment based on this.
Also, moving app-level resource initialization into a smaller package `resource`.
Fixes #600
> Identify VSCode in telemetry

- templates/todo/projects/python-mongo/.repo/terraform/.devcontainer/Dockerfile
- templates/todo/projects/python-mongo/.repo/terraform/.devcontainer/devcontainer.json
- templates/todo/projects/python-mongo/.repo/terraform/azure.yaml
- templates/todo/projects/python-mongo/.repo/terraform/infra/provider.tf
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
In terraform projects we need to ensure that both the Terraform CLI and the Terraform vs code extensions are installed by default in the dev container.
> Install terraform cli and vs code plugin in dev container

- cli/azd/pkg/exec/command_runner.go
- cli/azd/pkg/exec/util.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/samples/resourcegroupterraform/infra/provider.tf
- cli/azd/test/samples/resourcegroupterraformremote/infra/provider.tf
- eng/pipelines/templates/steps/install-terraform.yml
The `Interactive` flag was never being correctly set for posix environments which is used during command execution.  This now sets the correct value based on the `exec.RunArgs`.
Posix interactive usage:
https://github.com/Azure/azure-dev/blob/main/cli/azd/pkg/exec/cmdtree_posix.go#L28
> Fixes interactive exec support for posix environments

- .github/workflows/cli-ci.yml
- cli/azd/pkg/osutil/osversion/osversion_linux.go
> Fix uncaught lint error in osversion_linux.go

- cli/azd/resources/templates.json
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/apps.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/cosmos.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/keyvault.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/loganalytics.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/main.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/main.tfvars.json
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/output.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/provider.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/variables.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/nodejs-mongo/README.md
This PR adds template-nodejs-mongo terraform iac code by  
-  Create new Azure-Samples repo
-  Build out required terraform infra components
Addresses #231
> Add nodejs terraform template

- cli/azd/cmd/monitor.go
This fix addresses the issue where the `azd monitor` commands fail for terraform deployed apps.
This change modifies the discovery to query resource groups by environment instead of by ARM deployment since Terraform deployments do not utilize ARM.
> Fixes azd monitor for terraform

- cli/azd/cmd/deploy.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/init.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/util.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/project_test.go
- cli/azd/pkg/project/service_config_test.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_test.go
- cli/azd/test/functional/cli_test.go
Today the `Environment` object just holds a go map of values which represent the environment. Different parts of the system had different opinions as to if a pointer to an environment or the entire object should be passed around.  We intend to chage the internal shape of this object, so to prepare, I've done a pass over the codebase to do the following:
- Environments are now only created by code in the environment package, and all the "constructors" return `*Environment`.
- `Ephemeral` and `EphemeralWithValues` have been introduced to the environment package for testing purposes. They can be used to replace explicit construction of environments.
- Methods that return an environment along with an error now return `nil`, instead of the zero value for `Environment` (which is itself invalid …
> Embrace `*Environment` over `Environment`

- cli/azd/cmd/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_test.go
fix: https://github.com/Azure/azure-dev/issues/238
- auto detection for ci and scm providers based on project directory folders
> pipeline provider detection

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/docker/docker_test.go
- cli/azd/test/functional/cli_test.go
- eng/pipelines/release-cli.yml
Docker EE has been replaced with Docker CE / Moby for the windows images used by both GitHub Actions and the ones we use for our internal AzDo runs.
With this change, docker --version started to report a version number like:
```
Docker version master-dockerproject-2022-03-26, build dd7397342a
```
Our logic to parse the version number could not handle this scheme. It has now been rewritten to support this, as well as the older scheme which is still used by the Mac and Linux images (as well as for folks who have installed Docker Desktop on Windows)
> Support more `docker --version` schemes

- templates/common/.gitattributes
According to the issue I reported in #694 I changed the sample template for the `.gitattributes` file in accordance to the proposed troubleshooting described in the Visual Studio Code documentation ([link](https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files)).
I successfully tested the changed setup with Windows 11 and WSL2 and it fixes the issue.
> Change gitattributes for Windows file endings

- templates/todo/web/react-fluent/src/components/todoItemListPane.tsx
- templates/todo/web/react-fluent/src/components/todoListMenu.tsx
- templates/todo/web/react-fluent/src/pages/homePage.tsx
This PR addresses the issue where the UI allows you to attempt to create new items before the default list has loaded.  
This adds a `ready` state that will disable the UI input controls until the required service calls have completed successfully.
> Block Web UI until service is ready

- templates/todo/projects/csharp-sql/.repo/bicep/infra/resources.bicep
Fix #697
As part of bicep refactor, `KeyVault` was migrated from a resource to a bicep module. `keyVault.Name` now refers to the module name, whereas `keyVault.outputs.keyVaultName` is the actual KeyVault name created.
> Fix cosmos SQL template tests failing due to KeyVault secret failure

- cli/azd/cmd/deploy.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/up.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/test/functional/cli_test.go
Fixes #689
As part of Terraform refactor, we had switched the display logic to directly use ARM: `resourceManager.FindResourceGroupForEnvironment`. This misses out on the override abilities that the user can provide through `AZURE_RESOURCE_GROUP` or specifying a `resourceGroup` in `azure.yaml` that helps in resolving multiple resource group cases (which `azd` doesn't currently fully support).
- Refactor resource group resolution logic to a central place as `project.GetResourceGroup`. `projectConfig.ResourceGroupName` now always refers to the design-time YAML key defined, `project.ResourceGroupName` refers to the runtime resolved resource group name.
- Move display output of created resources from `deploy` to `provision`. The logic being in `deploy` has always been weird as most code …
> Fix error in `deploy` with multiple resource groups

- cli/azd/pkg/azdo/azdo.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
Modify AzDo provider to use main as default and to also fetch the current branch and use that if there is a different default branch set by the tool.
This is to go along with #764 , but it does not depend on that PR.
> Modify Azdo provider default branch to be use the current git branch.

- cli/azd/pkg/commands/pipeline/azdo_provider.go
Looks like `main` got into a corrupt state some how.
This PR fixes build issue in `main` branch.  Missing git package reference.
> Fixes missing git reference

- eng/pipelines/release-cli.yml
A [recent PR](https://github.com/Azure/azure-dev/pull/674) added a `docs/` folder into the root of the repo. 
Because that PR did not change anything that would necessitate a build of the CLI, the CLI CI did not trigger. 
Azure DevOps' default working directory is the root of the repo. 
It's not uncommon for work done in Azure DevOps (like product builds, artifact generation, etc.) to work from the root of the repo and mutate the file structure... However, the `docs` folder does leave itself open to collisions in a way that other folders might not. 
To fix: Do the work in the `docs` folder outside of the source directory. 
Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1881382&view=logs&s=2b1cf740-7e83-5b38-9f56-89c750cf5d77&j=dab3e848-2257-5774-eb9b-38eb96 …
> Use out of source docs folder for generating docs artifacts

- templates/common/.azdo/pipelines/azure-dev.yml
This pr introduces a change to the azdo pipeline used in all templates. To support the azdo pipeline provider, this modifies the pipeline to use pipeline variables instead of system environment variables.
> Modify azdo pipeline to use pipeline variables for inputs.

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/project/framework_service_maven.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/tools/javac/javac.go
- cli/azd/pkg/tools/javac/javac_test.go
- cli/azd/pkg/tools/maven/maven.go
- cli/azd/pkg/tools/maven/maven_test.go
- cli/azd/test/ostest/ostest.go
- schemas/v1.0/azure.yaml.json
Fixes #416
Changes:
- Adds `language` = `java` to `azure.yaml` schema specification. `maven` is supported by default -- no additional configuration required. `gradle` support in the future will be added by autodetection.
- Adds `javac` and `maven` as required tooling for `maven` framework service. Java 17 and above is supported.
> Add Java with maven support

- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
this PR fixes assets rules to copy the bicep dev container only.
> Update asset rules to copy the bicep python devcontainer only

- cli/azd/test/functional/cli_test.go
Switch to `CLI_VERSION`:
1. Avoids newline endings
2. Avoids introducing another dependency to `version.txt`. `CLI_VERSION` is set by the CI runner which also sets the other environment variable we're already dependent on.
> Fix version tests on Windows

- cli/azd/internal/telemetry/appinsights-exporter/endpoint_config.go
- cli/azd/internal/telemetry/appinsights-exporter/endpoint_config_test.go
- cli/azd/internal/telemetry/telemetry.go
- cli/azd/internal/telemetry/telemetry_context.go
- cli/azd/internal/telemetry/telemetry_test.go
- cli/azd/internal/version.go
- Remove feature guard
- Remove `ObjectId` from telemetry collection
- Classify `daily` (master merged) builds as prod
- Use connection strings over instrumentation keys. Unfortunately, the appinsights SDK does not implement connection string parsing, and we had to implement our own. See [schema](https://learn.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net#schema) here
Fixes #190
> Enable telemetry for prod

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display_test.go
Fixes #490
The console interactive output is unchanged. Just that we'll print "Provisioning Azure resource..." while waiting for the deployment to be started. Once the deployment has been started (by querying ARM APIs), we'll print the deployment link once.
There still exists possibility of the user receiving a 404 if the ARM API reports deployment is running, but the Portal API which might end up hitting a different backend does not see the same.
> Print Azure deployment link only when deployment has started

- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/test/functional/cli_test.go
fix https://github.com/Azure/azure-dev/issues/755
Adding 3 retry strategy for pushing code as part of azd pipeline config
This will workaround the issue about rotating credentials for git and the interaction with a git credential manager (caching credentials)
If this ever happens, or if the user manually made a mistake the first time while logging in to AzureDevOps, there would be another 2 times to re-enter the credentials (similar to running `sudo` in linux, where you have a few times to enter your password correctly)
> use 3 retries for pushing code

- cli/azd/pkg/azdo/project.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
fix https://github.com/Azure/azure-dev/issues/708
> Update Devops to DevOps

- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/test/functional/cli_test.go
We can write this this map concurrently in tests when multiple tests create a test context, which in turns registers the Bicep and Terraform providers and these registrations happene concurrently.
Fixes: #829
> Protect providers map from concurrent writes

- cli/azd/cmd/contracts/doc.go
- cli/azd/cmd/contracts/login.go
- cli/azd/cmd/contracts/show.go
- cli/azd/cmd/login.go
- cli/azd/cmd/show.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- Extend the set of STS codes we map to `ErrRefreshTokenExpired` based on new codes seen in the wild.
- If the user is not logged in, have `azd login --check-status` say so, and return success, instead of behaving as if the command had failed with some internal error. This also means when using `--output=json` we print an object that shows this unauthenticated state, which is helpful to folks consuming us (see #738).
- Move the types that model the JSON output of `azd login` into the contracts package.
- Improve documentation for some contracts.
Fixes #738
> Improve `azd login` behavior when logged out

- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/pkg/tools/internal/azure_deployment_error.go
- cli/azd/pkg/tools/internal/samples/arm_sample_error_01.txt
- cli/azd/pkg/tools/internal/samples/arm_sample_error_02.txt
- cli/azd/pkg/tools/internal/samples/arm_sample_error_03.txt
- cli/azd/pkg/tools/internal/samples/arm_sample_error_04.txt
Fixes #786 
Add logic to parse remainder of `az cli`'s stderr output as inner errors.
Example output text:
```
Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'weilim-todo-java-mongo' is not valid according to the validation procedure. The tracking id is '96acda23-5fa4-4439-a9c3-6aad0cd7733d'. See inner errors for details.
Inner Error:
PreflightValidationCheckFailed: Preflight validation failed. Please refer to the details for the specific errors.
Inner Error:
AccountNameInvalid: invalid-123 is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
```
Once we switch to ARM APIs, parsing the `az cli` output will no longer be necessary so this is really a temporary fix.
> Parse inner deployment errors

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- cli/azd/cmd/init.go
- cli/azd/cmd/login.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/test/functional/cli_test.go
First time writing Go. Please have a look and let me know where I can write more correctly. 
Since this is related to Codespaces, I added some codespaces configs for the azure-dev repo. 
A couple of things I noticed: 
* `CodespacesEnvVarName` and `RemoteContainersEnvVarName` are defined in `init.go` but only referenced in `login.go`... should those definitions be moved into `login.go` ... If so, what's the correct scope? The function in which they're used or further up?
* Was `newTimeoutTestContext` the way to go here? Do we want to look at timeout vs. deadline so as not to let tests run over on a long timeout?
> az login uses device token in codespaces

- cli/azd/cmd/root.go
- cli/azd/main.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/test/functional/cli_test.go
We had a few places which were using `context.Background()` instead of flowing a context value around.  I did an audit of all calls to `context.Background()` in non test files and cleaned up everything except for a single call at the start of `main()`.
> Flow context around in more places

- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/tools/ensure.go
- cli/azd/pkg/tools/ensure_test.go
- cli/azd/pkg/tools/tool_test.go
Instead of using a package level variable and having an internal method for testing to reset the cache, store the cache on the Context object and pull it when we need it.
> Store installed check cache in Context

- cli/azd/test/mocks/console/mock_console.go
Without this, a handler for a "Confirm" action may be used for a "Prompt" or "Select" action if the predicates match, which is not what would be expected.
> Consider command when matching expression in MockConsole

- cli/azd/pkg/tools/azcli/deployments.go
I saw a panic in one of our end to end test runs recently:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x43fd3a6]
goroutine 57 [running]:
github.com/azure/azure-dev/cli/azd/pkg/tools/azcli.(*azCli).GetSubscriptionDeployment(0xc00016bf00, {0x477ccd8, 0xc000025680}, {0xc00002ecc0, 0x24}, {0xc00002c390, 0xf})
/Users/runner/work/1/s/cli/azd/pkg/tools/azcli/deployments.go:36 +0x3e6
github.com/azure/azure-dev/cli/azd/pkg/infra.(*SubscriptionScope).GetDeployment(0xc0001e7e68?, {0x477ccd8?, 0xc000025680?})
/Users/runner/work/1/s/cli/azd/pkg/infra/scope.go:116 +0x42
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning.(*ProvisioningProgressDisplay).ReportProgress(0xc0001e7f90, {0x477ccd8, …
```
> Fix `errors.As` usage

- cli/azd/internal/telemetry/fields/fields.go
- cli/azd/internal/telemetry/resource/exec_environment.go
Use case-insensitive match of `true` to detect Azure DevOps correctly. Also, adding BitBucket Pipelines and Bamboo specific CI detection.
> Fix azure devops CI detection in telemetry

- cli/azd/.vscode/settings.json
- Pass `--fast` to `golangci-lint` as described in https://golangci-lint.run/usage/integrations/. I had been hitting freezes from time to time so hopefully this helps.
- Add a line at 125 cols, now that wrap there.
> Adjust `settings.json` for `cil/azd`

- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/input/console.go
In #879 we incorrectly refactored things such that we would lose writing via the colorable writer when calling `Message` and friends. This change separates things such that we can have to same behavior as we had as before.
> Undo the merging of `writer` and `handles.Stdout`

- cli/azd/pkg/input/console.go
I had intended this to be part of #891 but forgot to commit before pushing the PR. Originally, when SetWriter(nil) was called, we would use `GetDefaultWriter()` (which has since been removed) to re-fetch the same value that was passed in to `writer` when the object was created.
So store the originial writer for now and restore to it. We could otherwise run into issues when NO_COLOR was set where we'd not restore the stream that striped the ANSI color codes.
> SetWriter should restore to original writer

- cli/azd/cmd/sets.go
- cli/azd/cmd/wire_gen.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/identity/credentials.go
- cli/azd/pkg/tools/azcli/account.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/pkg/tools/azcli/container_app.go
- cli/azd/pkg/tools/azcli/container_registry.go
- cli/azd/pkg/tools/azcli/deployments.go
- cli/azd/pkg/tools/azcli/keyvault.go
- cli/azd/pkg/tools/azcli/resources.go
- cli/azd/pkg/tools/azcli/static_webapp.go
- cli/azd/pkg/tools/azcli/webapp.go
- cli/azd/test/functional/cli_test.go
As part of this change, I adjusted `identity.GetCredentials` to panic if one was not found in the context.
> Require a `azcore.TokenCredential` when constructing an `AzCli`

- cli/azd/cmd/sets.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/input/console.go
`azd` used to produce output when --no-prompt is specified. However, this behavior was changed in a console refactor. 
Here's the current description of `--no-prompt`:
```
--no-prompt            Accepts the default value instead of prompting, or it fails if there is no default.
```
This is currently causing pipelines generated by `azd pipeline config` to have no output for `azd provision`. In `azd deploy`, some output escapes as we don't consistently use `console.Message`.
> Do not disable output when `noPrompt` is specified

- .github/workflows/event.yml
Adding check enforcer v2 action to repository. See https://github.com/Azure/azure-sdk-tools/pull/3287 for details.
The naming of the file is a little generic because for the other sdk repos we had in mind to make "one handler to rule them all." In this repo there are more actions defined, so I can change the yaml filename if people like.
> Add github actions check enforcer

- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/init.ts
- ext/vscode/src/commands/up.ts
- ext/vscode/src/tasks/dotEnvTaskProvider.ts
- ext/vscode/src/utils/fileUtils.ts
- ext/vscode/webpack.config.js
Removes the VS Code extension's dependency on `fs-extra` which is more or less supplanted by `fs/promises` in the runtime itself, or with equivalents in VS Code's virtualized file system API.
Resolves #675
> Remove VS Code extension dependency on `fs-extra`

- ext/vscode/src/utils/azureDevCli.ts
Updates the link offered when `azd` is not installed to point to a more specific installation document.
Resolves #803
> Update install doc link

- ext/vscode/package.json
Add the `azd provision` command to the "create resources" menu of the Azure Resources view.
Resolves #924
> Add provision command to the Azure Resources "create resources" menu.

- cli/azd/pkg/commands/pipeline/github_provider.go
Quick fix for a broken UI prompt.
User reported error:
```
? What would you like to do now?  [Use arrows to move, type to filter]
> I have manually enabled GitHub Actions. Continue with pushing my changes.
Exit without pushing my changes. I don't need to run GitHub actions right now.
Error: check git push prevent: prompting to enable github actions: default value of select must be an int or string
```
I could reproduce this locally in a unit test.
> stringify default value in github prompt

- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/func/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/terraform/devcontainer.json
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/repo.yaml
Picking up where @danieljurek left off. Cherry-picked changes from: #902
- Bump memory requirements to 8GB for devcontainers
- Fix python func template not installing `azurefunctions` extension
> Fix codespaces setup issues

- eng/CHECKENFORCER
Temporary fix for legacy check enforcer given that the new license/cla check now posts a check_run instead of a status.
> [check enforcer] Bump minimum check runs to 2

- .vscode/cspell.global.yaml
- cli/azd/cmd/config.go
- cli/azd/cmd/init.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/root.go
- cli/azd/cmd/sets.go
- cli/azd/cmd/util.go
- cli/azd/cmd/wire.go
- cli/azd/cmd/wire_gen.go
- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/account/models.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/config/config.go
- cli/azd/pkg/config/config_test.go
- cli/azd/pkg/config/manager.go
- cli/azd/pkg/config/manager_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/tools/azcli/account.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/mocks/config/mock_config.go
- cli/azd/test/mocks/mock_context.go
- eng/pipelines/release-cli.yml
Adds new `azd config` command category with the following commands.
- `azd config list` => List all configurations
- `azd config get` => Gets the values stored at the specified path
- `azd config set` => Sets a value stored at the specified path
- `azd config unset` => Removes/unsets the value at the specified path
- `azd config reset` => Clears out any configuration values that were previously set
Updates the `config` package to support above commands.
**First run experience**
Updates  `azd init` to store default values for subscription & location when not previously set.
> Adds new config command category

- templates/common/.devcontainer/devcontainer.json/csharp/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/func/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/terraform/devcontainer.json
Addresses https://github.com/Azure/azure-dev/issues/946
This PR updates the devcontainer.json files for Python samples to use the new deprecated features syntax. I tested by using the same features in my fork of the todo-mongo-python app, and confirmed no warnings about deprecation in the logs.
I retained the version numbers used in the previous JSON files, but let me know if you think we should un-pin and use latest instead. I don't know the thinking there. (One concern with pinning is that people will copy these templates and never-ever update their versions. But of course using latest subjects the repos to regression issues).
I can update the features for other languages once this PR is approved. I just want to make sure this one looks good first.
> Updating features in devcontainers to not use deprecated syntax

- .devcontainer/devcontainer.json
As I started work on https://github.com/Azure/azure-dev/issues/946, I noticed the devcontainer.json for this repository also uses the deprecated syntax. 
I updated the syntax and kept the same version numbers, but I notice its using an older version of azure-cli (2.38) than latest (2.41), and I wonder if the pinning is intentional.
> Update featured syntax

- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/pkg/tools/azcli/deployments.go
With the introduction of leveraging the Go SDK for ARM deployments we have regressed to no longer parsing the ARM error messages.  This re-introduces the `AzureDeploymentError` error parsing instead of getting a wall of JSON.
> Azd CLI: Parse ARM deployment errors from Go SDK response

- eng/pipelines/template-tests.yml
- eng/pipelines/templates/steps/az-login.yml
- templates/tests/delete-test-templates.sh
- templates/tests/test-templates.sh
Change `azd init` in `test-templates.sh` to explicitly accept a subscription ID.
> Fix subscription used in template tests

- cli/azd/cmd/templates.go
- cli/azd/cmd/templates_test.go
- cli/azd/pkg/templates/template_manager.go
- cli/azd/resources/templates.json
- eng/pipelines/template-tests.yml
- eng/pipelines/templates/steps/install-ms-openjdk.yml
Add java templates to `azd` templates list.
Display templates sorted by name. This groups languages together and provides better consistency:
Fixes #1016
> Add java templates

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/main.go
- Add logging for Azure requests in `--debug` mode. This allows us to debug HTTP requests if needed. It is less noisy than `az` and has proper redaction for all logged outputs.
Example output:
```
2022/10/31 13:37:24 main.go:47: Retry: 
=====> Try=1 PUT https://management.azure.com/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/providers/Microsoft.Resources/deployments/weilim-log-test-1?api-version=2021-04-01
2022/10/31 13:37:26 main.go:47: Authentication: *azidentity.AzureCLICredential.GetToken() acquired a token for scope https://management.core.windows.net//.default
2022/10/31 13:37:26 main.go:47: Request: ==> OUTGOING REQUEST (Try=1)
PUT https://management.azure.com/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/providers/Microsoft.Resources/deployments/weilim-log-test-1?api-ve …
```
> Add azure-sdk logs in debug mode

- cli/azd/pkg/azdo/pipeline.go
- templates/common/.azdo/pipelines/bicep/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/azure-dev.yml
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/python-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
This PR addresses #658 by:
- Updates azdo provider to set the needed terraform remote state variables as part of azd pipeline config --provider azdo cmd.
- Introduces an additional azdo pipeline for terraform, and update the existing azdo pipeline to remove the terraform related variables.
- Updates all templates todo/repoman.yaml files to use the right azdo pipeline based on the infra selection.
Co-authored-by: Hattan Shobokshi <hattan.shobokshi@microsoft.com>
> introduce terraform azdo workflow

- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/tools/azcli/account.go
- cli/azd/pkg/tools/azcli/azcli.go
If azure subscription id is not set in either azd config, env var, or flag then calling `azd init --no-prompt` should fail.
> Explicitly require subscription id when `azd` config is not set

- cli/azd/pkg/tools/azcli/keyvault.go
Fix incorrect error handling causing panic in the keyvault client.
I did not find other places where we were doing it wrong (grep `azcore.ResponseError`)
Fixes #1050
> Fix incorrect error handling

- cli/azd/cmd/config.go
- cli/azd/main.go
> Updates inline help docs for `azd config` commands

- cli/azd/CHANGELOG.md
- cli/azd/cmd/sets.go
- cli/azd/main.go
- cli/azd/pkg/commands/builder.go
Historically, the Windows console has used out of band signaling for control color information, unlike *nix where control characters are added to the text to control what color it is printed in and other formatting information.
For a long time, Windows could not cope with the *nix strategy, leading to things like `colorable.NewColorableStdout()` and friends which tried to provide streams which would interpret ANSI escape sequences and call the corresponding Win32 methods to change colors as it rendered the text.
This process was very fragile and would lead to cases where we'd end up not using `colorable.NewColorableStdout()` and then when run on windows in the legacy console host we'd see these escape codes get printed.
Windows now supports processing these escape sequences. Enable that …
> Simplify color processing on Windows

- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/tools/github/github.go
Problem: When `GITHUB_TOKEN` variable is set in codespaces, GitHub CLI will always attempt to use `GITHUB_TOKEN`, which fails to set repository-level secrets. This is due to tokens generated in codespaces not having the ability to manage repository secrets (this is a technical limitation of codespaces).
As a holistic fix that is not specific to codespaces, we simply detect if GitHub CLI is using an environment variable token source (`GITHUB_TOKEN` or `GH_TOKEN`), and if we fail setting secrets due to authorization errors, we simply configure GitHub CLI to ignore the environment variables (by hiding these environment variables when invoking the command) and proceed with logging in.
This type of authorization failure detection + forcing auth mode can be extended to other types of API calls …
> Fix `azd pipeline config` in codespaces

- templates/common/infra/bicep/core/host/appservice.bicep
- templates/common/infra/bicep/core/host/container-app.bicep
In Bicep version 0.12.1 release today (11/3/2022) our app service and container app templates are throwing an error:
This resolves the issue by setting managed identity type to `None` instead of a null value.
Bicep 0.12.1 Release Notes
https://github.com/Azure/bicep/releases/tag/v0.12.1
Confirmed this is NOT a breaking change and will NOT require users to upgrade to latest bicep version.
> Templates: Update managed identity value due to change in Bicep 0.12.1

- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/dotnet/dotnet.go
- cli/azd/pkg/tools/git/git.go
- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/javac/javac.go
- cli/azd/pkg/tools/javac/javac_test.go
- cli/azd/pkg/tools/npm/npm.go
- cli/azd/pkg/tools/python/python.go
- cli/azd/pkg/tools/tool.go
- cli/azd/pkg/tools/tool_test.go
- For major release of Java, the version reported by `javac` is a major only version. Example output: `javac 19`. This change fixes our CLI version extraction logic to be more flexible in parsing, allowing: `major`, `major.minor` only formats as well.
- On extremely old versions of Java, (Java 8 and below) `javac --version` is not recognized. This change fixes the error output to be the version check validation failure.
Fixes #1077
> Fix java version check for major-only release

- cli/azd/CHANGELOG.md
- cli/azd/cmd/env.go
- cli/azd/cmd/wire_gen.go
- cli/azd/pkg/contracts/env_list.go
- cli/azd/pkg/environment/azdcontext/azdcontext.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/env_test.go
- Address #502 as a breaking change: `azd env new` now reads from arg instead of the `-e` flag (which means the environment to execute the command under, i.e: ` azd env new <environment>` instead of ` azd env new -e <environment>`
- Add functional end-to-end tests for `azd env *` commands
> Fix `env new` to use positional argument

- .vscode/cspell.global.yaml
- cli/azd/cmd/pipeline.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/azdo_provider_test.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/github_provider_test.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/graphsdk/application_request_builders.go
- cli/azd/pkg/graphsdk/application_request_builders_test.go
- cli/azd/pkg/graphsdk/entity_list_request_builder_test.go
- cli/azd/pkg/graphsdk/fic_models.go
- cli/azd/pkg/graphsdk/fic_request_builders.go
- cli/azd/pkg/graphsdk/fic_request_builders_test.go
- cli/azd/pkg/graphsdk/graph_client.go
- cli/azd/pkg/graphsdk/graph_client_test.go
- cli/azd/pkg/graphsdk/service_principal_models.go
- cli/azd/pkg/graphsdk/service_principal_request_builders.go
- cli/azd/pkg/graphsdk/service_principal_request_builders_test.go
- cli/azd/pkg/tools/azcli/ad_test.go
- cli/azd/test/mocks/graphsdk/mocks.go
- templates/common/.github/workflows/bicep/azure-dev.yml
Addresses #408 
When auth type is **Federated** in a valid configuration, `azd` will create a federated identity credential on the new/updated service principal for the following subjects:
- repo:**${REPO}**:ref:refs/heads/main
- repo:**${REPO}**:pull_request
- https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows
**Auth Default**: Federated
**Supported Auth**: Federated, ClientCredentials
Github secret configuration is different between Federated and ClientCredentials.  The github workflow has been setup to test which secrets have been defined and then use the correct version of the `az login` command.
**Auth Default**: ClientCredentials
**Supported Auth**: ClientCredentials
Display **_error_** if `--auth-type` is explicitly set to …
> Adds FederatedIdentityCredentials (FICS) request builders to Graph Client

- cli/azd/cmd/actions/action.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/root.go
- cli/azd/cmd/sets.go
- cli/azd/cmd/wire.go
- cli/azd/cmd/wire_gen.go
- cli/azd/pkg/commands/builder.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/output/formatter.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/test/mocks/console/mock_console.go
- cli/azd/test/mocks/mock_context.go
With the introduction of spinner in #965, we want to avoid creating multiple instances of console since the spinner state is now on console.
To fix this, first notice that `console` shouldn't be constructed within the `action` itself, as we also want to format and print additional output in `root.go` when we're formatting the output result.
Thus, the right change is to move `console` to be constructed outside of the `action`. We then pass this to be registered in `ctx` for existing code that depends on `ctx`. This will again be removed when we start removing all `ctx` dependencies.
What we gained:
- No more `formatter` and `writer` in `ctx`
- Single `console` instance. No duplication of logic.
- The `actionBuilder` is more inline with long-term thinking -- action doesn't depend on …
> Avoid multiple instances of `console`

- cli/Dockerfile
- cli/azd/pkg/tools/bicep/bicep.go
Adds an additional check to see if the `AZURE_CONFIG_DIR` env var has been set.  We have found that Azdo pipelines set this variable for the installation path that is used for the default location for the Bicep exe.
This PR also moves away from an `az bicep install` approach to prefer a bicep standalone installation.
Resolves #1094
> Bicep path not found fix - Check for AZURE_CONFIG_DIR

- cli/azd/cmd/actions/action.go
- cli/azd/cmd/actions/middleware.go
- cli/azd/cmd/middleware/debug.go
- cli/azd/cmd/middleware/telemetry.go
- cli/azd/cmd/root.go
As we explore the path of extensibility introducing the concept of middleware within our commands will enable a more loose coupling of components and be a start to our extensibility journey.
For example - In order to add extensible script support for running custom scripts before/after commands within our pipeline we could simply introduce this as middleware component where we can pull registered scripts from azure.yml and execute them at the correct stage of any command in azd.
In this PR
> Extensibility Spike: Add support for middleware

- templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
I got an error about directory not found when I tried to run "Start Functions" from Github Codespaces on the Python Mongo function sample. I changed the "cwd" to use "${workspaceFolder}" and that seemed to work well. I'm not an expert in VS Code JSON config yet, so do let me know if there's some good reason not to reference `workspaceFolder` here.
> Update cwd in tasks.json to be workspace-based

- cli/azd/cmd/env.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/telemetry.go
- cli/azd/pkg/config/manager.go
- cli/azd/test/functional/env_test.go
As fallout of #1022 we ended up requiring authentication for some commands that did not need it. This change ads annotations to these commands such that they do not require authentication.
We should be able to remove these annotations and have everything be correct by construction when we stop putting a credential and azcli on the context but instead just inject these into the commands that need them (and only the commands that need them).
Fixes #1135
> Mark more commands as not requiring login

- .devcontainer/Dockerfile
- cli/Dockerfile
- templates/common/.devcontainer/Dockerfile/base/Dockerfile
- templates/common/.devcontainer/Dockerfile/func/Dockerfile
`azd login` uses this to launch a browser when running on Linux. Ensure it is installed in our containers.
> Add `xdg-open` to our Dev Containers

- cli/azd/cmd/pipeline.go
- cli/azd/cmd/wire_gen.go
This command requries that you are logged into Azure to work, but in
I removed the incorrect annotation, and I also added a `azcli.AzCli` parameter to the type that represents the action itself and used wire to ensure it is injected. This is work we'd do any way as part of remvoing `commands.RequireNoLoginAnnotation` (see #1145) so might as well lock it is now.
Fixes #1147
> Mark `pipeline config` as requiring login

- cli/azd/cmd/sets.go
- cli/azd/cmd/wire_gen.go
- cli/azd/test/azdcli/cli.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/version_test.go
It is intended that the final JSON output of `azd` to be written to `stdout` instead of `stderr`. This change restores that behavior (unintended behavioral change caused by #1108), and updates existing tests to explicitly verify `stdout` output instead of `stdout` or `stderr`.
> Write final JSON output from `azd` to `stdout`

- ext/vscode/package.json
Since `VisualStudioCodeCredential` / `DefaultAzureCredential` are no longer able to use the tokens created by the Azure Account extension, IMO we should just remove the extension dependency. Relates also to the bigger auth questions in #1157 / #1101 / etc.
As an aside, the long term plan for the Azure Account extension is deprecation in favor of VSCode's authentication provider API.
> Remove Azure Account extension dependency

- eng/scripts/Set-TemplateTestMatrixVariable.ps1
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
The `todo-csharp-cosmos-sql` template had two issues that prevented it from being used locally:
1. It did not set `AZURE_COSMOS_ENDPOINT` as an output of the infrastructure - but this value was used by the application to at runtime to connect to the cosmos database. When run in App Service we correctly defined the environment variaible, but since we didn't export it from the infrastructure, it was not added to the `.env` file and hence not avaiaible for the app to use when running locally.
2. It did not grant RBAC access to the local user, so once (1) was fixed, the local user could not access the database.
This change fixes both of these issues.
Fixes #1101
> Fix issues so `todo-csharp-cosmos-sql` can be run locally

- cli/installer/test-installer-containers.ps1
- cli/installer/test-pwsh-xplat-install.ps1
- cli/installer/test/telemetry/alpine.pwsh.telemetry.json
- cli/installer/test/telemetry/alpine.sh.telemetry.csv
- cli/installer/test/telemetry/centos.sh.telemetry.csv
- cli/installer/test/telemetry/debian.pwsh.telemetry.json
- cli/installer/test/telemetry/debian.sh.telemetry.csv
- cli/installer/test/telemetry/fedora.sh.telemetry.csv
- cli/installer/test/telemetry/ubuntu.pwsh.telemetry.json
- cli/installer/test/telemetry/ubuntu.sh.telemetry.csv
- eng/pipelines/release-cli.yml
Container validation works locally in Docker running in WSL, fails silently in DevOps pipelines. The installer scripts _do_ work correctly but the pipeline tests don't currently prove that.
> Installer container validation fixes

- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_appservice_test.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/pkg/project/service_target_functionapp.go
- cli/azd/pkg/project/service_target_functionapp_test.go
- cli/azd/pkg/project/service_target_staticwebapp.go
- cli/azd/pkg/project/service_target_staticwebapp_test.go
CI informs me there are cases where Azure will return the all lower-case form, as I'm seeing errors like this in the template tests:
```
ERROR: creating project: creating service web: creating service target: failed validation for host 'appservice': resource 'app-web-xxmeesgcaossw' with type 'microsoft.web/sites' does not match expected resource type 'Microsoft.Web/sites'
```
Ignore case differences in these comparisons.
Fixes #1203
> Use case insensitive match for resource types

- cli/azd/cmd/deploy.go
We did not set the `commandRunner` state in the object constructor, leading to a nil ref later when trying to use it.
> Fix nil ref in deploy

- cli/azd/cmd/util.go
- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/commands/pipeline/azdo_provider_test.go
- cli/azd/pkg/environment/azdcontext/azdcontext.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/scope.go
- cli/azd/pkg/infra/scope_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/deployments.go
- cli/azd/test/functional/cli_test.go
Our logic to prompt the user for missing infrastructure values was
broken because we did not tell the spinner we wanted to interact with
the user, so the spinner would prevent the prompt UI from being shown.
The logic we had for trying to save these values was totally broken
and in practice would end up generating files that the ARM control
plane would reject.
We now save these values in the newly added `Config` object on the
environment, using `infra.prameters.<parameterName>` as the key name.
As part of this work, we no longer materialize the full
`.parameters.json` file to disk, we no longer need to do this now that
we are using the SDK directly.
Fixes https://github.com/Azure/azure-dev/issues/1176
Fixes https://github.com/Azure/azure-dev/issues/1191
> Fix prompting for missing infrastructure values

- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
In #1202 we added a `config.json` file in the environment, which we use to persist configured values for required infrastructure parameters which are not set in `.parameters.json` files.
As part of that logic, we made it so that the constructor of the environment would validate that a `config.json` file was present in the environment and if not, fail (similar to the check it already did for the .env file).
This worked for new environments, since `.Save()` will always write an empty `config.json` file. But for existing environments, the read of the config.json would fail, with ErrNotExists, which would be wrapped up and returned to the caller. The caller would use the ErrNotExists to mean "the environment doesn't exist" and so it would prompt the user to see if they wanted to create it. …
> Fix regression on loading existing environments

- templates/todo/common/infra/bicep/app/api-appservice-java.bicep
There seems to be a recent change in App Service that prevents `applicationinsights-runtime-attach` from loading correctly. The root cause is that the plugin attempts to write to tempDir as a workaround when  `jdk.attach.allowAttachSelf` is `false` which times out after awhile.
With `jdk.attach.allowAttachSelf` specified to `true`, the app service works as normal.
Confirmed with the Application Insights team that this is a safe workaround. Still root causing how this has started happening.
Addresses #1214
> Enable `jdk.attach.allowAttachSelf`

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/az-login.yml
- eng/pipelines/templates/steps/template-test-run-job.yml
- Always run `az login` for post-cleanup
- Avoid silent errors if `az group show` fails unexpectedly.
> Fix template test not cleaning up when test fails

- templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/AzureDeveloperCliCredential.java
- templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/ConfigurationSources.java
- templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/MongoDBConfiguration.java
- templates/todo/api/java/src/main/resources/application.properties
Updates Java template to:
- Disable auto-configuration from Key Vault to pull secrets as application properties during spring boot initialization.
- Disable auto-configuration for mongodb url
- Adds a customizer `@bean` for setting the mongodb url
- Creates Key Vault secrets client manually using the Azure Developer CLI Token Credential
> adding Azure Developer CLI credential for Java

- templates/common/infra/bicep/core/security/keyvault-secret.bicep
This PR add an additional template to the `core` folder for `.bicep`. The template allows the creation of an Azure Key Vault secret as a further building block in the `security` folder
CC @jongio
> Enhance core templates with Key Vault secret

- eng/pipelines/template-tests.yml
We want our scheduled test runs to run against template repository `staging` by default using azd `daily`. This was changed inadvertently when refactoring the template tests.
> Switch default branch to `staging` for template tests

- templates/todo/projects/csharp-sql-swa-func/.vscode/settings.json
The Azure Functions VS Code extension will offer to add Functions-specific tasks to tasks.json when the workspace is open in VS Code. The problem is, if the user agrees, the Azure Functions extension will overwrite the "API Functions Run" task that is necessary for local application run/debugging, rendering the local app run impossible.
See https://github.com/microsoft/vscode-azurefunctions/issues/3469 for more details about the issue.
> Suppress offer to modify tasks.json

- cli/azd/cmd/login.go
- cli/azd/cmd/testdata/TestUsage-azd-login.snap
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
This PR adds a new parameter `redirect-port` for `azd login` which can be used to define the port to use after doing an interactive web browser authentication.
The default behavior (when this new arg is not set, or is set to 0) is to let `azd` to automatically select an available port.
But, in some cases, customers might want to define the port to be used for convenience. For example:
- When using codespaces, customers can create a `port redirect` before calling `azd login`.
- When using remote-ssh connection, similarly, customers don't need to wait for the url redirect from `azd login` to discover the port that azd is using.
- When using a `dev-tunnel`, each new `port redirect` requires approving the connections thru the tunnel (the first time it is used). This approval ends up as an …
> Support redirect port for azd login

- cli/azd/pkg/password/generator_test.go
There are only 10 lowercase letters in the generated password
> Fix test pass condition

- cli/azd/.vscode/cspell.yaml
- cli/azd/pkg/commands/pipeline/azdo_provider_test.go
- cli/azd/pkg/graphsdk/application_request_builders_test.go
- cli/azd/pkg/graphsdk/entity_list_request_builder_test.go
- cli/azd/pkg/graphsdk/fic_request_builders_test.go
- cli/azd/pkg/graphsdk/graph_client_test.go
- cli/azd/pkg/graphsdk/me_request_builder_test.go
- cli/azd/pkg/graphsdk/service_principal_request_builders_test.go
- cli/azd/pkg/graphsdk/util_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/tools/azcli/ad_test.go
- cli/azd/pkg/tools/bicep/bicep_test.go
- cli/azd/pkg/tools/javac/javac_test.go
- cli/azd/test/mocks/mock_context.go
- cli/azd/test/mocks/mockarmresources/mockarmresources.go
- cli/azd/test/mocks/mockconfig/mock_config.go
- cli/azd/test/mocks/mockexec/mock_runner.go
- cli/azd/test/mocks/mockgraphsdk/mocks.go
- cli/azd/test/mocks/mockhttp/mock_http_client.go
- cli/azd/test/mocks/mockinput/mock_console.go
All mock packages now follow the naming: `mock<package name>`. This avoids package name clobbering and creates a pattern that is generalizable for all.
> Standardize naming for mock packages

- templates/todo/api/common/openapi.yaml
The `TodoListArray` and the `TodoItemArray` are missing, `type: array`, which causes client code generation to fail.
> Add `array` types to lists

- templates/todo/projects/csharp-sql-swa-func/.vscode/settings.json
An improvement over https://github.com/Azure/azure-dev/pull/1254 where we tell Azure Functions extension what the project's language and Functions runtime are, instead of just suppressing their (unnecessary) offer to re-configure project tasks.
> Improve Azure Functions config

- .github/workflows/event.yml
**Requires https://github.com/Azure/azure-sdk-actions/pull/7 to merge first (currently reverted), which adds support for workflow_run action types and enforcing multiple check suites**
This updates the check enforcer github action to run on completion of other github actions, namely template-ci, cli-ci and vscode-ci (by default, events from github actions do not trigger other github actions to prevent loops).
With this update, we will be able to de-commission check enforcer v1. Once it goes in, we will need to update the branch protection settings to require `https://aka.ms/azsdk/checkenforcer` and remove the `check-enforcer` github app from this repository.
I think these changes are pretty well tested, but regardless should be monitored for a while after they go in.
> Enable check enforcer for mixed github actions + azure pipelines CI

- cli/azd/cmd/actions/action.go
- cli/azd/cmd/root.go
- cli/azd/test/functional/version_test.go
If a command returned a nil ActionResult (as most commands do), we would still try to create a MessageUxItem for it and render that. This would end up with an empty message being printed to the console and then another newline. When using JSON output this was very obvious (when running at the terminal, it's a little easy to not notice the extra blank line that is at the end of the command).
> Don't print an extra newline after (most) commands

- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/prompt_test.go
From the user's point of view, these behave the same ways as their insecure counterparts. During a deployment, ARM will not retain information about secure parameters.
When prompting for un-configured parameters, we do not offer to save the value of a secure parameter in the environment.
Fixes #1289
> Support `secureObject` and `secureString` ARM parameter types

- cli/azd/pkg/project/service_target_containerapp.go
Addressing #1290 by replacing the `-` with `_` when generating the env var names for the container image used by container apps.
> Normalising the container image env var

- cli/azd/cmd/auth_token.go
- cli/azd/cmd/auth_token_test.go
- cli/azd/cmd/login.go
- cli/azd/cmd/sets.go
- cli/azd/cmd/wire_gen.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
- go.mod
This allows fetching a token from a different tenant than the user's default tenant.
> Support `--tenant-id` parameter on `azd auth token`

- templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/AzureDeveloperCliCredential.java
There was a missing command to wait for the process to terminate before checking the return code.
fix: https://github.com/Azure/azure-dev/issues/1303
> Fix AzureDeveloperCredential for Java

- cli/azd/cmd/deploy.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/infra/provisioning/provisioning.go
- cli/azd/pkg/project/service.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_test.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/expected-output-types/typed-values.env
- cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/output.tf
- cli/azd/test/functional/testdata/samples/storage/infra/main.bicep
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
Allow users to specify their own endpoints for a given service, in cases where they've configured their own front-end load balancers, reverse proxies or DNS host names outside of the service target (and prefer that to be used instead).
With this change, manually tested that the CSharp cosmos template with APIM enabled prints the APIM endpoint:
```
(✓) Done: Deploying service api
- Endpoint: https://apim-tktoainmj6iyu.azure-api.net/todo
```
And also works correctly when APIM is not enabled.
Fixes #1192
> Allow configuration of service endpoint using `SERVICE_<service>_ENDPOINTS`

- cli/azd/cmd/cobra_builder.go
- cli/azd/pkg/ioc/container.go
- cli/azd/pkg/ioc/container_test.go
Fixes #1322 
Will verify if an error received during action instantiation is rooted from a developer container registration error vs an an actual error returned by a resolving dependency.
> Checks for container registration errors vs actual errors

- cli/azd/cmd/middleware/middleware.go
- cli/azd/cmd/middleware/middleware_test.go
In the case where we had reached the end of the middleware chain, we used an outdated context. If the middleware chain changed the context object (as the telemetry middleware does, when it creates a new span) we'd lose these updates. In the case of telemetry, it means that any child spans we created would not be correctly parented.
> Pass the correct context from middleware to the action

- cli/azd/cmd/middleware/debug.go
Add pid to debug attach printout. Since attaching debugger to the process requires the PID, having it displayed saves an extra step and avoids confusion when multiple instances of `azd` is running.
> Add pid to debug attach printout

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/expected-output-types/typed-values.env
- cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/output.tf
- cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/variables.tf
- cli/azd/test/functional/testdata/samples/storage/infra/main.bicep
- cli/azd/test/functional/testdata/samples/storage/infra/main.parameters.json
For Bicep parameters, allow for stringly-typed conversions for `bool` and `number`, i.e.: `"true"` to `true` and `"123"` to `123`. This allows us to write JSON that is both valid and suitable for `envsubt` substitutions, i.e. `"useApim": "${USE_APIM:false}"`. Terraform does this by-default.
For Terraform, provide support for converting `list`, `set` and `map` complex-type outputs. Also, handle `null` values.
Pre-req for #1323
> Improve bicep and terraform input/output type-handling

- templates/todo/web/react-fluent/package-lock.json
Bumps loader-utils package version by updating all `package-lock.json` versions based on our `package.json` semver tags.
Fixes the following Dependabot alerts
- https://github.com/Azure/azure-dev/security/dependabot/8
- https://github.com/Azure/azure-dev/security/dependabot/9
Run the following in your shell:
```bash
rm package-lock.json && rm -rf node_modules/ && npm install
```
> Bump loader-utils & Todo Web App package-lock.json

- cli/azd/pkg/tools/azcli/container_app.go
`Ingress.Fqdn` properties may not be defined for container apps that only run in the background.
Fixes #1231
> Add `nil` check for container app endpoints fetch

- cli/azd/.vscode/cspell.yaml
- cli/azd/cmd/config.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/init.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/pipeline_test.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/root.go
- cli/azd/cmd/show.go
- cli/azd/cmd/testdata/TestUsage-azd-env.snap
- cli/azd/cmd/testdata/TestUsage-azd-infra.snap
- cli/azd/cmd/testdata/TestUsage-azd-login.snap
- cli/azd/cmd/testdata/TestUsage-azd-monitor.snap
- cli/azd/cmd/testdata/TestUsage-azd.snap
- cli/azd/cmd/up.go
- cli/azd/docs/docgen.go
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli.yml
Also fixes https://github.com/Azure/azure-dev/issues/1380 
Changes of note in both CLI and ref docs markdown: 
* "application" -> "app" in just about all mentions (except "Application Insights" which is a product name)
Documentation changes to match copy edits from the docs team up to this point and trivial changes are put back into the CLI help (like "application" -> "app").
Discussions here: 
* https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4037
* https://github.com/MicrosoftDocs/azure-dev-docs/pull/993/files
<details><summary>CLI help generated by commands with the most changes:</summary>
`azd --help` 
```
Azure Developer CLI is a command-line interface for developers who build Azure solutions.
To begin working with Azure Developer CLI, run the `azd up` command by supplying a …
```
> Reference doc copy updates

- templates/common/infra/bicep/core/database/sqlserver/sqlserver.bicep
Not a big deal, but my pre-commit hook keeps fixing it when I use core in my projects, so I figure might as well fix it in azure-dev.
> Remove trailing whitespace in sqlserver.bicep

- eng/pipelines/release-cli.yml
Fixes https://github.com/Azure/azure-dev/issues/1379
Since splitting up signing into separate jobs the signed PowerShell artifacts download sources and locations need to be updated. 
Test run showing success in a test storage account: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2115773&view=logs&j=550e6a3f-0691-5d18-3071-14c14b608781&t=550e6a3f-0691-5d18-3071-14c14b608781
@rajeshkamal5050 -- This fixes the issue we saw on installer release on Wednesday.
> Install script sign artifacts

- cli/azd/CHANGELOG.md
- cli/azd/cmd/deploy.go
- cli/azd/cmd/infra_create.go
- cli/azd/test/functional/cli_test.go
In #1296 we changed our logic such that we would inject `AzdContext` as a depenecy of our actions, and expect our IoC container to wire things up.
This had the side effect of breaking `azd up --template` to initilize (and then provison and deploy) a new project.
The break comes from the fact that the IoC container will call `NewAzdContext` as part of building the `deploy` and `infraCreate` actions, which need to be created because they are dependencies of the `up` composite action.  However, `NewAzdContext` should not be called before the project has actually been created (which will happen when the `up` composite action calls the `init` action), because it looks for an existing project and if it doesn't find one it fails.
To work around this issue - I've made the infra create and deploy …
> Fix `azd up --template` so it can initialize a new project

- templates/common/infra/bicep/core/host/appservice.bicep
My apps all have ftpsState: 'disabled', so I need the ability to override ftpsState if I want my apps to use the core modules. This PR adds ftpsState as a param. It defaults to 'FtpsOnly' since that's what the TODO apps currently use and also appears to be the default for Portal-created web apps.
> Add ftpsState as a param to App Service module

- cli/installer/windows/azd.wxs
> Overwrite unversioned azd.exe on install

- cli/azd/pkg/infra/azure_resource_types.go
Currently, azd doesn't display when it creates a PostgreSQL flexible server, but it should, since it displays SQL server creations.
I based this PR off https://github.com/Azure/azure-dev/pull/1320/files
> Display PostgreSQL server created in resource

- cli/azd/CHANGELOG.md
This would fail change log entry validation for release but that validation doesn't apply to already released packages.
> Move **DEPRECATED** to a place where it won't be removed in changelog automation

- cli/azd/main.go
- cli/azd/pkg/config/manager.go
This switches `user.Current().HomeDir` to `os.UserHomeDir`, avoids loading entire user profile when only the home directory is needed, and improves `azd` (including `--help` only) performance by ~100ms to seconds on certain Windows machines.
`user.Current` fetches the entire user profile (this is loaded once and then cached). On *Nix, it simply reads pwd through a single syscall. However, on Windows, it requires talking to the domain controller for a domain-joined account. This is on magnitude of ~100ms to seconds slow which is noticeable, and also impacts the `--help` experience (since we currently have logic that runs in `main` irrespective of flags).
This changes the underlying implementation to use %HOMEPROFILE% or $HOME env variables instead of looking the system user. This should …
> Avoid loading entire user profile for `homeDir`

- cli/azd/cmd/down.go
- cli/azd/cmd/middleware/hooks.go
- cli/azd/cmd/middleware/hooks_test.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/up.go
- cli/azd/pkg/ext/hooks_runner.go
- cli/azd/pkg/ext/models.go
Fixes #1481 the following azd hook issues
> Azd Hook bug fixes

- .github/workflows/cli-ci.yml
Updating golangci-version to fix these warnings:
> update golangci-lint to version 3 with golang 1.20

- cli/azd/cmd/container.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/env.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/middleware/hooks.go
- cli/azd/cmd/middleware/hooks_test.go
- cli/azd/cmd/restore.go
- cli/azd/pkg/ext/event_dispatcher.go
- cli/azd/pkg/ext/models.go
- cli/azd/pkg/project/project_config.go
Fixes service event hooks to fire correctly in the case of nested actions where azd env / project are lazily loaded.
> Fixes service event hooks firing correctly in azd up

- cli/azd/cmd/login.go
- cli/azd/cmd/middleware/debug.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/auth/credential_providers.go
- cli/azd/pkg/auth/manager.go
Fixes issue when user runs `azd login --tenant-id <X>`, but has MFA policy preventing access to home tenant. `azd login` currently reports an error.
> Fix incorrect login failure

- templates/common/infra/bicep/core/host/appservice.bicep
- templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode.tf
- templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode_variables.tf
- templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython.tf
- templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython_variables.tf
This PR contains the changes necessary for a user to configure the health check endpoint when suing the Azure App Service.
The PR adds the corresponding parameter to both IaC variants i.e., Bicep and Terraform. The parameter is defaulted to an empty string. 
The change is a *non*-breaking change as the new parameters are optional and the default value causes the same behavior as the current templates do.
Real-life setups can have a dedicated health endpoint that should be used in the app service.
n/a
> Azure App Service - Enhancement to specify health check endpoint

- ext/vscode/package-lock.json
- ext/vscode/package.json
Fixes #1509. VSCode has gotten pretty pushy about removing these--showing warnings even when `package.json` isn't open--so I'm just going to deal with it now. VSCode 1.74.0 has been out for about two months now and by the time we release this version of the extension, it'll have been closer to three months.
> Clean up VSCode extension activation events

- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/pkg/tools/azcli/resources.go
Function Apps and App Service apps use the same Azure resource types, so our display logic needs to query information about the provisioned resource to understand if a provisioned resource is an app service or a function app.
Our existing logic to do this was broken when we moved away from using `az` to get information about a resource, since we were not passing an API version on our query. This caused our REST call to fail, and we just ignored the error (under the assumption it was a transient issue and we were okay displaying slightly wrong output for progress in this case).
This change addresses the issue by forcing callers (who in theory understand what API version is valid for the resource they want to fetch information about) to provide an API verison and updates the one call site …
> Correctly show function app resources in provision log

- cli/azd/pkg/infra/azure_resource_types.go
I'm making some templates with CDNs in front, and I realized it doesn't display when the CDN is created. Making a CDN involves both a CDN Profile and a CDN endpoint, but endpoints require a profile, so probably okay to just show the profile created? I'm not sure how to reason about what resources should be displayed other than my surprise at not seeing something listed.
The labeling is tricky - the Portal calls it "Front Door and CDN profiles", but the "and" feels a bit ambiguous, so I went for a slash here. Let me know your preference.
> Add CDN to resource types

- ext/vscode/.vscode/extensions.json
- ext/vscode/.vscode/tasks.json
Webpack watch takes about the same amount of time on the first build, but drastically less on subsequent builds, speeding up inner loop.
> Use webpack watch as default build task for extension

- cli/azd/CHANGELOG.md
[version.txt](https://github.com/Azure/azure-dev/blob/main/cli/version.txt) is already up-to-date.
> Update changelog entry for `0.6.0-beta.2`

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/telemetry/events/events.go
- cli/azd/internal/telemetry/fields/fields.go
- cli/azd/internal/telemetry/tracer.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/account/subscriptions_manager_test.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/test/mocks/mock_credentials.go
- cli/azd/test/mocks/mockarmresources/subscriptions.go
- cli/azd/test/mocks/mockhttp/mock_http_client.go
Improve performance of multi-tenant subscription listing by fanning out subscription listing across tenants. Listing subscriptions for a given tenant can incur 200ms - seconds worth of delay. If a user has 5 tenants, this can be noticeably slow. Fanning out subscription listing per tenant alleviates this problem.
Tests, specifically `TestSubscriptionsManager_ListSubscriptions_LotsOfTenants` verifies the behavior when listing across 100 tenants. This test does not cover the full extent of application due to specific mocked dependencies. The dependencies that are not verified are: `multiTenantCredentialProvider`, `azdCredential`. I inspected these two types and verified that they are safe for parallel use.
Additionally, with this change, I've added usage telemetry for tracking multitenancy …
> Improve performance of multi-tenant subscription listing

- cli/azd/cmd/util.go
- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/test/mocks/mockaccount/mock_manager.go
Currently, the concept of a `default.location` and `default.subscription` is tied to the UI selection. For the UI selection, it's not important to validate the default configuration's validity, and it is preferred that the UI simply chooses no default, or a hardcoded default, if the default configuration isn't valid.
This change removes the extra validation we're performing to validate account defaults. The API and implementation for validated defaults is still available in case we want better guarantees for other use-cases.
> Remove service calls for location and subscription defaults in UI prompt

- cli/azd/CHANGELOG.md
- cli/azd/pkg/tools/bicep/bicep.go
- cli/installer/test/telemetry/alpine.pwsh.telemetry.json
- cli/installer/test/telemetry/alpine.sh.telemetry.csv
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli.yml
Add support for building (but not signing or releasing) ARM64 binaries: 
* Linux ARM64 -- Basic cross-compile, CGO not required, validation of `azd version` on ARM64 Linux machine
* macOS ARM64 -- Cross-compile with CGO enabled (cannot compile without it because of `osutil/osversion` constraints)
> Add support for cross compile

- templates/common/.devcontainer/devcontainer.json/csharp/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/devcontainer.json
The "extensions" key is supposed to be nested inside "customizations"/"vscode". See reference here:
https://containers.dev/supporting#visual-studio-code
VS Code also tells you as soon as you start editing any devcontainer.json with "features" at outer level.
I assume it was originally "extensions" at outer level, so current syntax might still work, but this change will make VS Code happy.
> Fix devcontainer syntax

- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/tools/azcli/subscriptions.go
User experienced crash while running `azd login`, due to a tenant `DisplayName` being `nil`.
This adds minimal runtime safety guards against `armsubscriptions.TenantIDDescription` fields being `nill`. #1577 will examine how we handle `nil` data contracts from `azure-sdk-for-go` holistically (incremental steps).
Fixes #1573
> Handle arm tenant optional fields

- .github/workflows/cli-ci.yml
`golangci-lint` v1.51.2 introduces a new lint rule to catch error formatting errors when dealing with multiple errors. This lint rule is only applicable on go 1.20, and ends up creating false positives on go 1.19.
> Pin `golangci-lint` version to undo breakage

- cli/azd/internal/telemetry/resource/machine_id.go
To standardize on a process for determining a machine id, we only want to use adapters which have an active IP address. This aligns with the process that VS Code uses, whereas previously the first non-loopback device was used.
> Only use adapters which have an active IP address for creating a machine id

- templates/todo/projects/nodejs-mongo-aca/.vscode/launch.json
- templates/todo/projects/nodejs-mongo-swa-func/.vscode/launch.json
- templates/todo/projects/nodejs-mongo/.vscode/launch.json
VS Code pops up an error on "pwa-node" instructing dev to use "node" instead. Looks like "pwa-node" has been deprecated. (Some discussion of history at https://github.com/microsoft/vscode/issues/151910 )
In my quick test, changing to "node" seemed to work.
> Rename pwa-node launch type to node

- cli/azd/CHANGELOG.md
- cli/azd/cmd/init.go
`azd init` not depends on `git` all the time, as it creates a local git project even for `empty template`
> Update dependency `git` for init

- .github/workflows/cli-ci.yml
- cli/azd/CONTRIBUTING.md
- cli/azd/ci-build.ps1
- cli/azd/main.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/ioc/container.go
- eng/pipelines/templates/steps/setup-go.yml
- go.mod
Address following lint issues:
- Use of '%v' formatting for multiple errors -- `go` 1.20 supports formatting multiple errors in an error formatting directive. 
- Remove `rand.Seed` in `main.go` to provide a random seed value since this is no longer required. From release notes:
> The [math/rand](https://tip.golang.org/pkg/math/rand/) package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level [Seed](https://tip.golang.org/pkg/math/rand/#Seed) function has been deprecated. Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using rand.New(rand.NewSource(seed)).
Pin `golangci-lint` version to avoid future unexpected breakage. We should …
> Upgrade go to 1.20, pin golangci-lint

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/test/functional/testdata/samples/storage/infra/main.bicep
This fixes a `panic` that is now happening with the pinned `azd` `bicep` version. With bicep >=0.14.46, secure string types are emitted with lowercase names.
Without this change, `azd` panics with the message:
```
panic: unexpected bicep type: 'securestring'
goroutine 46 [running]:
github.com/azure/azure-dev/cli/azd/pkg/infra/provisioning/bicep.(*BicepProvider).mapBicepTypeToInterfaceType(0xfa39e0?, {0xc000138a80?, 0xc000138aa0?})
D:/repos/azure-dev/cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go:747 +0x1f9
```
> Support lower-cased bicep types

- cli/azd/cmd/login.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/auth/manager.go
Log when access token retrieval fails. The error currently looks like:
```golang
"http call(%s)(%s) error: reply status code was %d:\n%s", req.URL.String(), req.Method, reply.StatusCode, sd
```
`sd` is the body of the AAD response, which is safe for logging.
Add additional safety-nets to prevent users from getting into stale subscriptions due to cross-account logins.
Fixes #1609
> Add small login error-handling improvements

- cli/azd/internal/telemetry/resource/machine_id.go
Discovered a scenario on Windows where IP addresses are not always zero-length, even if the adapter is not active/assigned. Checking that adapters are both up and have an assigned IP
> Adding check to ensure the selected adapter is "up"

- eng/pipelines/templates/steps/publish-cli-winget.yml
@ItzLevvie [pointed out](https://github.com/microsoft/winget-pkgs/pull/99040#issuecomment-1462526639) that our automation was not setting the winget package version properly. Thanks, @ItzLevvie! 
This PR fixes that issue. 
There was some back and forth over how we will structure version numbers when releasing to WinGet and Choco and it was ultimately decided that we'd follow the MSI versioning scheme. I updated the PR with that strategy but missed that variable. This corrects it so future release will have the correct variables in place.
> Use MSI_VERSION instead of WinGetVersion in WinGet publishing script

- cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/provider.tf
- cli/azd/test/functional/testdata/samples/resourcegroupterraformremote/infra/provider.tf
- templates/common/infra/terraform/core/database/cosmos/cosmos.tf
- templates/common/infra/terraform/core/gateway/apim-api/apim-api.tf
- templates/common/infra/terraform/core/gateway/apim/apim.tf
- templates/common/infra/terraform/core/host/appservice/appservicenode/appservicenode.tf
- templates/common/infra/terraform/core/host/appservice/appservicepython/appservicepython.tf
- templates/common/infra/terraform/core/host/appserviceplan/appserviceplan.tf
- templates/common/infra/terraform/core/monitor/applicationinsights/applicationinsights.tf
- templates/common/infra/terraform/core/monitor/loganalytics/loganalytics.tf
- templates/common/infra/terraform/core/security/keyvault/keyvault.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/provider.tf
- templates/todo/projects/python-mongo/.repo/terraform/infra/provider.tf
As described in issue #1716 the Terraform provider version in the templates is not supporting Node.js version 18-lts. 
This PR updates the `azurerm` provider to the latest available minor version and this way fixes issue #1716 .
In addition this PR updates the version of the `azurecaf` provider. This is more a "cosmetic" update as due to the version restriction in the Terraform files this version was fetched anyways.
> Feat: Update terraform provider versions

- cli/azd/cmd/monitor.go
- cli/azd/cmd/show.go
- cli/azd/cmd/util.go
- cli/azd/pkg/azure/resource_ids.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/azure_resource_manager_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/project/project_test.go
- cli/azd/pkg/project/resource_manager.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_functionapp.go
- cli/azd/pkg/project/service_target_staticwebapp.go
- cli/azd/test/functional/cli_test.go
To prepare for this value be initialized later (and hence the caller needs to think about "will this value have a value?", I was looking at all the places we call `GetSubscriptionId` today.  For some of them, we already have a resource ID around and we could just pick the value from there.  In other cases, I tried to push the use "up" by making `subscriptionId` a parameter of a function (instead of taking the `env` as a parameter and just calling `GetSubscriptionId` on it).
> Call Environment.GetSubscriptionId in fewer places

- cli/azd/cmd/container.go
- cli/azd/cmd/util_test.go
- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/account/models.go
- cli/azd/pkg/account/subscriptions.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/account/subscriptions_manager_test.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/pkg/infra/provisioning/bicep/prompt_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/tools/azcli/account.go
- cli/azd/test/mocks/mockaccount/mock_manager.go
As part of some future work, I need to be able to take a dependency on the `auth` and `account` packages from `azcli`. That can't be done today because some code in the `account` package depended on the `azcli` package and so what I wanted to do would lead to an import cycle.
Looking at the code, it seemed like the best thing to do as move the SubscriptionsService out of the `azcli` package and into `account`. This change does the refactoring of doing that.
I tried to this as non destructively as possible to the existing implementation, but did need to move away from some of the model types in the `azcli` package (which I think long term we should just remove) in favor of the types exposed by the armsubscriptions SDK.
> Move `SubscriptionsService` into `account` Package

- cli/installer/install-azd.sh
- eng/templates/brew.template
Fixes https://github.com/Azure/azure-dev/issues/1548
Includes install caveats in `brew install` scenaio: 
Brew documents recommend using caveats to describe Rosetta requirements. There's a bit more functionality in [Casks](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/dsl/caveats.rb#L140-L143)
than Formulas but given we're just outputting text to the console it doesn't warrant a switch from Formula to Cask at this time for our scenario. 
There's no obvious prior art in Brew formulae or casks that attempts to detect or install Rosetta 2.
> [install-azd.sh] Add check for Rosetta on install

- cli/azd/internal/repository/initializer.go
- cli/azd/internal/repository/initializer_test.go
Offer the option to keep local files when initializing from template.
This is useful for azdevifying scenarios.
Fixes #1656
> Allow local files to be kept when running `init`

- templates/common/infra/bicep/core/host/container-app.bicep
- templates/common/infra/bicep/core/host/container-apps.bicep
- templates/common/infra/bicep/core/security/keyvault-access.bicep
The template analyzer pointed out this issue with container-app.bicep, that it sets the names to empty strings that are later used to define existing resources. You can't define an existing resource with an empty string, so that's not a valid default value for it. These values always need to be set, as far as I can see.
> Don't default necessary values to empty strings

- cli/azd/CONTRIBUTING.md
- cli/azd/test/azdcli/cli.go
- cli/azd/test/functional/cli_test.go
Add logic to automatically invoke `go build` for local e2e tests. This is inspired by the Rust implementation of `assert_cmd::Command::cargo_bin`, where the CLI is automatically built if needed ([docs](https://rust-cli.github.io/book/tutorial/testing.html#testing-cli-applications-by-running-them)).
> Remove need to run `go build` for running e2e tests

- cli/azd/pkg/osutil/rename_unix.go
- cli/azd/pkg/osutil/rename_windows.go
- cli/azd/pkg/osutil/rename_windows_test.go
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/github/github_test.go
I noticed recently we've been seen intermittent failures in CI on Windows in our integration tests that look like this:
```
creating provisioning manager: error creating infra provider: error creating provider for type 'bicep' : downloading bicep: rename C:\\Users\\cloudtest\\.azd\\bin\\bicep.exe.tmp4175873399 C:\\Users\\cloudtest\\.azd\\bin\\bicep.exe: Access is denied.
```
I suspect what is happening here is that in CI when we run our integration tests, we have multiple copies of `azd` running concurrently (one per integration test) that are all racing to download bicep (since there is no cached copy of the machine). Each process downloads bicep to a temporary file and then attempts to use os.Rename to move the intermediate file into the final location.
In cases where either the source …
> Retry `Rename` when it fails, on Windows.

- cli/azd/cmd/deploy.go
- cli/azd/cmd/env.go
This fixes an issue where azd cannot find maven `mvn` external tools.  This ensures that the project is initialized before performing any tool checks.  The project init ensures the project path is set correctly within the maven project.
> Fix maven tool dependencies

- templates/todo/projects/csharp-cosmos-sql/README.md
- templates/todo/projects/csharp-sql-swa-func/README.md
- templates/todo/projects/csharp-sql/README.md
- templates/todo/projects/java-mongo-aca/README.md
- templates/todo/projects/java-mongo/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-aks/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/nodejs-mongo/.repo/bicep/README.md
- templates/todo/projects/nodejs-mongo/.repo/terraform/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
- templates/todo/projects/python-mongo/.repo/bicep/README.md
- templates/todo/projects/python-mongo/.repo/terraform/README.md
Our samples in the sample browser aren't rendering certain images. [Example](https://learn.microsoft.com/en-us/samples/azure-samples/todo-nodejs-mongo-terraform/todo-nodejs-mongo-terraform/)
This change removes the image elements in favor of markdown image reference which doesn't allow custom sizing. The UX experience is pretty similar and has been reviewed by @savannahostrowski.
This change also adds frontmatter for the new `aks` template
Example for `nodejs-mongo-swa-func`: [Before](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/main), [After](https://github.com/Azure-Samples/todo-python-mongo-aca/tree/pr/1780)
> Fix image rendering in samples browser

- cli/azd/pkg/project/framework_service_npm.go
- cli/azd/pkg/project/framework_service_python.go
A last change in previous PR broke the condition to exclude `node_modules` during zip deploy.
Enhancing the code here
> fix excluding node_modules

- cli/azd/cmd/deploy.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/init.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/root.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/testdata/TestUsage-azd-config-get.snap
- cli/azd/cmd/testdata/TestUsage-azd-config-list.snap
- cli/azd/cmd/testdata/TestUsage-azd-deploy.snap
- cli/azd/cmd/testdata/TestUsage-azd-down.snap
- cli/azd/cmd/testdata/TestUsage-azd-env-get-values.snap
- cli/azd/cmd/testdata/TestUsage-azd-env-list.snap
- cli/azd/cmd/testdata/TestUsage-azd-env-refresh.snap
- cli/azd/cmd/testdata/TestUsage-azd-infra-create.snap
- cli/azd/cmd/testdata/TestUsage-azd-infra-delete.snap
- cli/azd/cmd/testdata/TestUsage-azd-login.snap
- cli/azd/cmd/testdata/TestUsage-azd-provision.snap
- cli/azd/cmd/testdata/TestUsage-azd-restore.snap
- cli/azd/cmd/testdata/TestUsage-azd-template-list.snap
- cli/azd/cmd/testdata/TestUsage-azd-template-show.snap
- cli/azd/cmd/testdata/TestUsage-azd-template.snap
- cli/azd/cmd/testdata/TestUsage-azd-up.snap
- cli/azd/cmd/testdata/TestUsage-azd-version.snap
- cli/azd/cmd/testdata/TestUsage-azd.snap
- cli/azd/cmd/up.go
- cli/azd/cmd/usage_test.go
- cli/azd/pkg/output/parameter.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/telemetry_test.go
Hide specific flags that are being deprecated or hidden for preview. Issue warning messages for deprecated usage.
Changes:
- Remove `azd init` from `azd up` (flags and execution)
- `azd deploy` and `azd restore` now accepts a positional arg. `azd deploy <web>` instead of `azd deploy --service <web>`.
- Hide `--no-progress` flag from `azd provision` and `azd up`
- Hide `--output` flag from all commands
Fixes: https://github.com/Azure/azure-dev-pr/issues/1495
> Restructuring specific command flags

- cli/azd/pkg/project/framework_service_docker.go
Fixes issue where container based apps that use the docker framework service are not initializing the source framework which was causing build paths to not be set for Maven java projects.
> Ensures that docker init calls source framework init

- cli/azd/internal/telemetry/appinsights-exporter/span_to_envelope.go
- cli/azd/internal/telemetry/appinsights-exporter/span_to_envelope_test.go
Fix serialization for slice-attributes in our telemetry emission pipeline. Recent prerelease changes have only started emitting slice attributes, thus not a concern for existing data.
In our telemetry pipeline, we currently serialize a slice attribute as `{"Type":"STRINGSLICE","Value":["cwd","force","purge"]}`. This is because `attribute.Value` from otel implements a custom `json.Marshaler` that attaches the type information. The type makes it harder to work with since we don't need strong-typing here to consume telemetry.
This fix changes the serialization to `["cwd","force","purge"]`.
> Fix serialization for slice attributes in telemetry

- cli/azd/cmd/auth_login.go
- cli/azd/cmd/auth_logout.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/contracts/login.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/initialize_test.go
- eng/pipelines/templates/steps/template-test-run-job.yml
- templates/common/.github/workflows/bicep/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
Remove `azd login` references. Emit warning message when `azd login` and `azd logout` is used. 
There are no `azd logout` references.
> Remove `azd login` references

- cli/azd/pkg/project/resource_manager.go
Updates error messages to use more generic naming.
Resolves #1521, #1439,
> Updates error messages to use more generic naming for infra templates

- cli/installer/windows/test-win-msi.ps1
- eng/pipelines/release-cli.yml
Prevents race conditions which could lock up azd.exe and prevent a clean uninstall.
> Disable telemetry during MSI test

- cli/azd/cmd/auth_login.go
- cli/azd/cmd/auth_logout.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/infra_delete.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/up.go
Update messaging for deprecated commands/flags based on UX feedback.
Fixes: https://github.com/Azure/azure-dev-pr/issues/1496, https://github.com/Azure/azure-dev-pr/issues/1495
> Update messaging for deprecated commands/flags

- cli/installer/windows/azd.wxs
- cli/installer/windows/ui.wxs
Also has uninstall text that it might not have worked for all users and what to do.
> Attempt MSI clean-up of ~/.azd/bin

- cli/azd/pkg/input/console.go
- cli/azd/pkg/output/ux/created_resource.go
fix: https://github.com/Azure/azure-dev/issues/1689
Removing the json-logs for state changes from the spinner.  
Also updating the json messages for Resource-Create without the special char `(✓)` (which is not parsed correctly from Visual Studio)
> do not log spinner changes for json output

- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/azure.yaml
Move `postpackage` to `predeploy` hooks for `staticwebapp` ToDo templates
This allows the `env-config.js` to be correctly generated when observing the environment state from `azd`. This is the current intended integration for `staticwebapp` to observe environment state that also works when invoked through `azd up`.
> Move `postpackage` to `predeploy` hooks for `staticwebapp`

- cli/azd/cmd/deploy.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/testdata/TestUsage-azd-deploy.snap
- cli/azd/cmd/up.go
- cli/azd/pkg/project/container_helper.go
Adds `--from-package` param to `azd deploy` to support deploying a service from an existing package.
> Deploy from existing package

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/service_config_test.go
Fixes #1874 
Docker enforces all lowercase on docker image repositories.  By default we generate the repo name from the combination of project/service name.
This fix ensures that generated names are all lowercased before invoking docker CLI commands.
> Ensure default generated docker repo/tags are all lowercase

- cli/installer/fpm/install-notice.sh
- cli/installer/fpm/uninstall.sh
- cli/installer/uninstall-azd.sh
- eng/scripts/New-LinuxPackages.ps1
- eng/templates/brew.template
This change follows the changes we made to MSI. On Linux: 
* Remove files from ~/.azd/bin for the current user
* Output warnings to the console that there may be other ~/.azd/bin folders for other users on the machine with files in them and that they should be updated. 
On MacOS: 
* Add caveat during install to warn the user about removing files from ~/.azd/bin. 
* Note: brew does not support custom uninstall actions (like cleaning up files in ~/.azd/bin)
> Uninstall removes extra files

- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/framework_service_dotnet.go
- cli/azd/pkg/project/framework_service_dotnet_test.go
- cli/azd/pkg/project/framework_service_maven.go
- cli/azd/pkg/project/framework_service_npm.go
- cli/azd/pkg/project/framework_service_npm_test.go
- cli/azd/pkg/project/framework_service_python.go
- cli/azd/pkg/project/framework_service_python_test.go
- templates/common/.devcontainer/devcontainer.json/aks/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/csharp/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/java/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/terraform/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/terraform/devcontainer.json
- templates/todo/common/infra/bicep/app/api-appservice-node.bicep
- templates/todo/common/infra/bicep/app/web-appservice.bicep
- templates/todo/web/react-fluent/Dockerfile
- templates/todo/web/react-fluent/package.json
Resolves #1867
> Note: Template tests will fail for all file based templates until new `daily` build is available.
> Assert package outputs and more verbose error messages

- cli/azd/cmd/deploy.go
- cli/azd/cmd/package.go
- cli/azd/cmd/up.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/deploy_test.go
Hide package output from `deploy`.  Do not show `(BETA)` in packaging title for `azd up` use case.
Add tests to verify invalid flag behaviors, since some behaviors were not tested and incorrect.
With this change, the output is now:
Fixes #1904, #1905
> Update `deploy` and `up` UX

- cli/azd/docs/feature-stages.md
We need to have this in the repo so that docs can refer out to it for our feature stages for 0.8.0
> Add doc to outline features + current stages (alpha, beta, stable)

- cli/azd/pkg/project/service_target_staticwebapp.go
Fixes #1944 
Adds missing `return` statements after setting error on task.
> Fixes static web app panic during deploy

- schemas/v1.0/azure.yaml.json
Resolves #1552 
Updates the azure.yaml JSON for hooks so `run` is only required if `windows` or `posix` has not been specified.
> azure.yaml schema update: Hooks `run` only required if `windows` or `posix` is not specified

- cli/azd/ci-build.ps1
Resolves Azure/azure-dev-pr#1547
The following are addressed by default by the go compilier:
- Stack protection (stack canaries/cookies) (Enabled by default in Go 1.15 & 1.17)
- Address Space Layout Randomization (ASLR)
- Data Execution Prevention (DEP), the Non-Executable (NX) bit, or W^X functionality
```bash
go build -buildmode=exe -tags=cfi,cfg,osusergo,netgo -trimpath -gcflags="-trimpath" -asmflags="-trimpath" -ldflags="-s -w -linkmode=auto -extldflags=-Wl,--high-entropy-va" -o azd.exe .
```
| Flag | Description | 
| --- | --- | 
| `-buildmode=exe` | Set the build mode to build an executable binary file | 
| `-tags=cfi,cfg,osusergo,netgo` | Enable Control Flow Integrity (CFI), Control Flow Guard (CFG), optimize for OS user accounts and network I/O performance |
| `-trimpath` | …
> Updates go build flags

- cli/azd/pkg/project/framework_service_maven.go
- cli/azd/pkg/project/framework_service_maven_test.go
- schemas/v1.0/azure.yaml.json
Relax packaging validation to also examine `*.war` and `*.ear` files in addition to `*.jar` files. Provide ability to specify a specific archive file if multiple archives are present.
Functionality-wise, these archive file formats are transparent to `azd`. For `zipdeploy` deployments, they are strictly zip files that simply needs to be uploaded to the target endpoint. This has been tested end-to-end working by reliable-web-app-pattern-java team.
Fixes #1943
> Support other java archive files

- cli/azd/cmd/auth_login.go
- cli/azd/cmd/testdata/TestUsage-azd-auth-login.snap
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
Fix implementation of GitHub federated auth token provider to allow for fetching of tokens when tokens expire.
Validated the failing behavior before this change, and success behavior after this change, using a GitHub action that slept for 15 minutes, calling `azd auth token` in-between, and runs full `azd provision` and `azd deploy` after 15 minutes.
Fixes #1901
> Update federated auth to allow token re-fetch

- ext/vscode/package.json
- ext/vscode/package.nls.json
- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/services/AzureDevApplicationProvider.ts
- ext/vscode/src/services/AzureDevEnvListProvider.ts
- ext/vscode/src/services/AzureDevShowProvider.ts
Fixes #1688
Also fixes an issue found by @weikanglim where, when this repository was opened, a huge number of `azd` processes were started up to get information about the "apps" (the `azure.yaml` files) in the workspace--from the templates.
> Use `--no-prompt` as appropriate and cap the maximum number of `azure.yaml` files to autodiscover

- cli/azd/pkg/commands/pipeline/github_provider.go
Minor fixes for `Github` pipeline provider
- Resolves #1482 - Create unique federated credential name
> Fixes Federated credentials conflict in Github Pipelines

- cli/azd/pkg/infra/azure_resource_manager.go
Rolls back one unintentional change when showing `deleted` resources from PR #1967
> Only show 'create' resource operations during provision

- cli/azd/.vscode/settings.json
VS Code recently made a change such that when you launch code from a subfolder it does not automatically load the git repository in the parent folder. This was done to prevent user confusion in some cases, and is discussed in more detail in the VS Code source control FAQ:
https://code.visualstudio.com/docs/sourcecontrol/faq#_why-isnt-vs-code-discovering-git-repositories-in-parent-folders-of-workspaces-or-open-files
Due to how our repository is structured, many folks working on `azd` launch code from within `cli/azd` (the root of the tree for the CLI) and this new setting means that you get a toast out of the box asking you if you want to load the repository or not. If you ignore this toast, the source control manager doesn't work (since VS Code doesn't assoicate the folder with the git …
> Force discovery of git repository in parent folder

- cli/azd/cmd/version.go
- cli/azd/internal/telemetry/resource/resource.go
- cli/azd/internal/useragent.go
- cli/azd/internal/useragent_test.go
- cli/azd/internal/version.go
- cli/azd/internal/version_test.go
- cli/azd/main.go
- cli/azd/pkg/contracts/version.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/test/functional/version_test.go
- schemas/v1.0/azure.yaml.json
This allows a project to specify a range of supported versions of
`azd`, by introducing a new `requiredVersions` object to
`azure.yaml`. Today, the only supported key is `azd`, which allows the
project author to specify a set of supported versions.
When parsing a project file, if this member is set, we ensure that the
current version is within the allowed range.
Dev versions of the CLI ignore this check.
Fixes #1504
> Add `requiredVersions` to `azure.yaml`

- cli/azd/pkg/config/manager.go
- cli/azd/pkg/config/manager_test.go
- cli/azd/pkg/osutil/permissions.go
Fixes #1691 
I spotted this behavior on a mac after an upgrade in the course of doing other work. The fix for now is to ensure that the directory has the "x" bit set for the user so that it's accessible to the user. At this point I'm not entirely sure why an outside process is resetting this bit during OS upgrades. It would seem that the upgrade is determining that this directory should not be accessible. 
There is a [`repairHomePermissions` tool on macOS](https://eclecticlight.co/2020/03/28/apple-has-changed-resetting-permissions-again/) which can be run in recovery mode. Running that tool does not change these file permissions. We'd need to test an OS upgrade directly in detail to learn more.
> Ensure directory has user "execute" permissions so it is accessible

- cli/installer/install-azd.ps1
- cli/installer/install-azd.sh
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/install-azd-live-sh.yml
- eng/pipelines/templates/steps/template-test-run-job.yml
For Windows installer scripts, perform `Get-AuthenticodeSignature <msi artifact>` and ensure that the `Status` returned is `Valid`. This verifies that the signed binary originates from a trusted cert chain.
For macOS installer scripts, perform `codesign -v <azd binary>`.
Current output of our code sign designated requirements: `codesign -dv -r- /usr/local/bin/azd`:
```
designated => identifier "azd-darwin-amd64" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9
```
which verifies for an anchor trusted cert chain. 
Fixes https://github.com/Azure/azure-dev-pr/issues/1548
> Add signature verification to artifacts downloaded

- templates/todo/web/react-fluent/package.json
This change ensures swa-apps can be deployed from CI pipelines.
This is a temporally patch until swa-cli is fixed. See: https://github.com/Azure/static-web-apps-cli/issues/688
> Fix todo swa templates to work on CI builds

- cli/azd/docs/proxy-configuration.md
Adds docs for using `azd` behind a proxy.
Resolves #1600
> Configure `azd` for use behind an an HTTP/HTTPS proxy

- cli/azd/ci-build.ps1
With `netgo` build constraint added (which removes `cgo`-based DNS resolution), users are seeing that `azd auth login` now fails on Windows with VPN enabled due to `localhost` DNS resolution failing. Removing this build constraint allows `azd auth login` to work even under VPN conditions. Verified the behavior locally
Fixes #1994
> Remove netgo build constraint

- cli/azd/pkg/environment/azdcontext/azdcontext.go
- cli/azd/pkg/environment/azdcontext/azdcontext_test.go
Fixes two issues with environment list implementation:
1. `azd env list` reports error instead of returning `[]` when no `.azure` directory exists: #2011
2. `azd env list` returns `null` instead of `[]` with `azd env list --output json` is ran on a project with no environment directories'
Add test coverage for modified code.
Fixes #2011
> Fix idiosyncrasies in `azd env list`

- cli/azd/cmd/deploy.go
- cli/azd/pkg/alpha/alpha_feature_manager.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
This changes set a central point to validate when a service-host is an alpha feature and if it is ON/OFF
The validation is done while resolving the service-host implementation to be used, making next commands to fail if the alpha feature is off:
- up
- provision
- deploy
- package
- restore
When adding a new `host` as alpha feature or changing an existing host to alpha, the only need to do is to add the name of the host in the list of `alpha_features.yaml`
> support adding new host as alpha feature

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/container.go
- cli/azd/cmd/deploy.go
- cli/azd/pkg/auth/cloudshell_credential.go
- cli/azd/pkg/azsdk/azsdk.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/containerapps/container_app_test.go
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/muted_console.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_config_test.go
- cli/azd/pkg/project/service_models.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/container_app.go
- cli/azd/pkg/tools/azcli/container_app_test.go
- cli/azd/test/functional/testdata/samples/containerapp/infra/main.bicep
- cli/azd/test/functional/up_test.go
- cli/azd/test/mocks/mock_context.go
- cli/azd/test/mocks/mock_credentials.go
- cli/azd/test/mocks/mockazsdk/container_apps.go
- schemas/v1.0/azure.yaml.json
This update brings the implementation of container apps inline with our other service targets.  Previously ACA apps performed an additional `provision` operation to perform container image modifications during deployment.
This additional internal `provision` step introduced additional complexity and also made it difficult to support other infra providers.
This update performs the following:
- Leverages the Azure SDK for Go
- Modeled after [az cli command](https://github.com/Azure/azure-cli-extensions/blob/64fcab983940b3a7b259bf2ff9dd2f5cbd16c85a/src/containerapp/azext_containerapp/custom.py#L1644)
**Single Revision Mode**
- New revision is published automatically when container app is updated
Multiple Revision Mode
- New revision ingress traffic weights sets 100% of traffic to new …
> Container App Service Target refactor

- cli/azd/pkg/auth/cache_windows.go
When storing the MSAL cache on Windows we use CryptProtectData to ensure that the data is encrypted at rest. Previously, we stored just the raw data as returned by CryptProtectData. This would make it difficult in the future for us to change our encryption strategy because we would be unable to determine from the opquae encrypted data how it was encrypted (and hence what we needed to do to decrypt it).
This change updates our strategy to encrypt the data as before, but then store it as part of a JSON object which contains a string denoting how the data was encrypted.
To support transparent upgrades, care is taken to fall back to the older strategy in the case where we can't succesfully unmarshall the stored data as a JSON object (this allows new versions of `azd` to read the cache written …
> Store encrypted MSAL cache with algorithm type

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/main.go
- cli/azd/pkg/commands/pipeline/github_provider_test.go
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/dotnet/dotnet.go
- cli/azd/pkg/tools/git/git.go
- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/github/github_test.go
- cli/azd/pkg/tools/javac/javac.go
- cli/azd/pkg/tools/kubectl/kubectl.go
- cli/azd/pkg/tools/kubectl/kubectl_test.go
- cli/azd/pkg/tools/maven/maven.go
- cli/azd/pkg/tools/maven/maven_test.go
- cli/azd/pkg/tools/python/python.go
- cli/azd/pkg/tools/swa/swa.go
- cli/azd/pkg/tools/terraform/terraform.go
This change ensures that we log both the version of `azd` itself and all the external tools that we end up using the debug log.  This is useful for diagnostics purposes.
Fixes #1936
> Write azd and tool versions to debug log

- schemas/v1.0/azure.yaml.json
We currently have an issue where are schema for `azure.yaml` references our main branch the removal of this property is causing our issues confusion.
Bring back the property and mark as deprecated for now till we have a better yaml schema versioning strategy.
> Brings back 'module' property and mark as deprecated

- cli/azd/cmd/up.go
Make `up` perform a early login check before prompting for subscriptions.
Usually, this is not required as our dependency constraints will always guarantee that the login check is performed first. However, `up` is special since it is an orchestrating command that creates other commands and has a special prompt for subscriptions.
Related: #2054
Fixes #2037
> Add early login check to `up`

- templates/todo/api/java/README.md
- templates/todo/api/java/src/main/java/com/microsoft/azure/simpletodo/configuration/WebConfiguration.java
- templates/todo/api/js/src/app.ts
- templates/todo/api/python/todo/app.py
- templates/todo/common/infra/bicep/app/api-container-app.bicep
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
- templates/todo/projects/java-mongo-aca/.vscode/launch.json
- templates/todo/projects/java-mongo-aca/.vscode/tasks.json
- templates/todo/projects/java-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/java-mongo/.vscode/launch.json
- templates/todo/projects/java-mongo/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/main.tf
- templates/todo/projects/python-mongo-aca/.vscode/launch.json
- templates/todo/projects/python-mongo-aca/.vscode/tasks.json
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo-swa-func/.vscode/launch.json
- templates/todo/projects/python-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo/.repo/terraform/infra/main.tf
- templates/todo/projects/python-mongo/.vscode/launch.json
- templates/todo/projects/python-mongo/.vscode/tasks.json
- templates/todo/web/react-fluent/README.md
fix: https://github.com/Azure/azure-dev/issues/1057
This PR re-designs the CORS strategy for the `api` service.
There are 2 layers where CORS (allowed-orings) can be configured:
- Infra:   The Azure Service takes care of validating the incoming http request and lets only allowed-origins to get to the api server.
- runtime Server.  Once the request passes the infra layer, it is received by the server running on the Azure Service and it can also check allowed-origins.
Not every Azure service supports the CORS configuration on `infra` layer. For example, Azure Container Apps does not support the CORS configuration on infra layer.
- Use CORS on infra layer if supported (web-apps) and do not add CORS on `runtime server`
- Use CORS on `runtime server` when it is not supported on `infra layer`, …
> fix cors stategy for Java/NodeJs/Python

- cli/azd/CHANGELOG.md
- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/project.go
- schemas/v1.0/azure.yaml.json
We will no longer default `language` to `dotnet` when unset. Instead, the user receives an error in `azure.yaml` schema validation. If an `azd` command runs with `language` unset, the following error would be observed:
`Error: parsing project file: parsing service myService: language property must be set`
Fixes #1645
> breaking: Do not default `language` to dotnet 

- cli/azd/internal/repository/testdata/empty/azureyaml_created.txt
- cli/azd/pkg/project/project_config.go
- ext/vscode/src/commands/azureWorkspace/wizard/PickResourceGroupStep.ts
- ext/vscode/src/services/AzureDevShowProvider.ts
- schemas/v1.0/azure.yaml.json
Make `services` not required; clean-up project config.
It's perfectly fine to have an `azure.yaml` that only does provision. I verified that creating a minimal `azure.yaml` and running `azd deploy` and `azd restore` works correctly.
Project config was also littered with unset properties when running `azd init` with "empty template" selected. This change cleans up the `azure.yaml` generated.
Before:
```yaml
name: test3
infra:
provider: ""
path: ""
module: ""
pipeline:
provider: ""
```
After:
```yaml
name: test3
```
Fixes #1162
> Make `services` not required; clean-up project config.

- cli/azd/cmd/config.go
- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
- cli/azd/pkg/config/config.go
- cli/azd/pkg/config/manager.go
- cli/azd/pkg/environment/environment.go
- cli/azd/test/mocks/mock_context.go
- cli/azd/test/mocks/mockconfig/mock_config.go
Previously, the identity of currently logged in user (either the home account id, when logged in as a user, or the client and tenant id when logged in as a service principal) as stored in user's `config.json`.
A downside of storing this information in `config.json` is that when a user did `azd config reset`, it would "log out" the current user, which is very surprising behavior. In addition, anyone looking at `config.json` would see properties that were much more like state of the auth subsystem instead of actual config values that a user would want to change.
So, this change moves this information out of `config.json` and instead stores it in `auth.json` (a new file) which is also stored in `~/.azd`.
On first use, we'll migrate the relevent properties from `config.json` into `auth.json`. …
> Move "current-user" settings out of `config.json`

- cli/azd/cmd/util_test.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
Improve `azd down` deletion logic, addressing two issues:
1. Change how resource groups were fetched from an ARM deployment. Previously, we relied on `deployment.DependsOn.ResourceName` to determine resource groups. This did not work for empty resource groups, as described in #619. This change modifies the logic to summarize resource groups based on `deployment.OutputResources` instead. Schema of deployment is documented [here](https://learn.microsoft.com/en-us/rest/api/resources/deployments/get#deploymentpropertiesextended). From observation, it includes all resources across resource groups from a subscription-level deployment. A sanitized example return response for `Microsoft.Resources/deployment` for a subscription-level deployment grabbed from running `azd up` on a ToDo template is …
> Fix `azd down` deletion logic

- cli/azd/cmd/env.go
- cli/azd/cmd/provision.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/azure_resource_manager_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display_test.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/infra/scope.go
- cli/azd/pkg/infra/scope_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/deployments.go
The `Scope` concept is something which is very ARM specific. The fact that it was a prameter on `Manager` and `Provider` is an artifact of how the interfaces were birthed (by refactoring the at the time only provider we had, which talked to to ARM) and the the fact that we were doing ARM deployments for ACA.
We are now at a point where we can remove it from the interface, so let's go ahead and do that.
> Remove `Scope` parameter from `infra.Provider` and `infra.Manager`

- cli/azd/cmd/init.go
- cli/azd/internal/repository/initializer.go
- cli/azd/internal/repository/initializer_test.go
This acts as a speed bump to avoid accidentally running `azd init` in the wrong directory.  If `azure.yaml` is present, no prompt is needed.
For other situations, the user can still confirm with 'y' explicitly and initialize the project in a non-empty directory (azdevifying from existing code),
Fixes #1638
> Add confirmation prompt when running init in non-empty directory

- cli/azd/internal/telemetry/fields/fields.go
- cli/azd/internal/telemetry/resource/ci.go
- cli/azd/internal/telemetry/resource/exec_environment.go
- cli/azd/test/functional/telemetry_test.go
Update `exec.environment` telemetry reporting to include `azure_app_space_portal`.
The existing logic for `exec.environment` reporting is also updated with two specific goals:
1. Refactor our CI detection to its own `ci.go` file. This allows reuse for other cases in the application when we need to detect CI. This means moving the logic for `AZD_IN_CLOUDSHELL` detection appropriately.
2. Add support for environment modifiers, which allows us to supplement the environment information. `azure_app_space_portal` takes advantage of this.
Partially addresses #1977
> Update `exec.environment` telemetry reporting

- cli/azd/pkg/azdo/utils.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/exec/command_runner.go
- cli/azd/pkg/exec/runargs.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/tools/git/git.go
Based on the feedback from https://github.com/Azure/azure-dev/pull/2068, we don't really want azd to set git credential-helpers. Specially if the helper is just a quick bridge to pull a PAT from an env-var.
We would prefer to let customer's git-config unchanged.
This PR introduces a different approach which uses `-c url.<PAT+Host>.insteadOf=<Host>` to use the PAT on https for pushing code. The configuration is not persisted to config,
Users might face a later challenge if they try to use git later, as git will either prompt for PAT again or fail if there is another configuration (like in Codespaces).  But, at least for azd, it will all work as expected.
I tested this on Codespaces :)
fix: https://github.com/Azure/azure-dev/issues/1993
Updating command runner as well to support getting a …
> codespaces azdo git config azd only

- cli/azd/cmd/util_test.go
- cli/azd/pkg/azure/tags.go
- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/scope.go
- cli/azd/pkg/infra/scope_test.go
- cli/azd/pkg/project/project_test.go
- cli/azd/pkg/project/resource_manager.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/deployments.go
Previously, when creating a deployment, `azd` would use the
environment name as the name of the deployment (a deployment is
represented in azure as a resource, and has a name).
When running `azd provision` twice, the second invocation would re-use
the previous deployment name, which would overwrite the history of the
old deployment.
This was not ideal, since we would lose all the history from the
previous deployment and could also lead to race conditions in our UI
where we would end up displaying information from the previous
deployment while the new deployment was waiting to start up (since the
deployment name was shared we would fetch the operations from the old
deployment, not the new one).
Also, in the case of subscription based deployments, the deployment
object also has a location …
> Use a unique deployment name when provisioning

- cli/azd/CHANGELOG.md
- cli/azd/pkg/project/framework_service_npm.go
- cli/azd/pkg/tools/npm/npm.go
Note: This change only introduces compatibility issues with previous `staticwebapp` services that also took advantage of `.env` file variables being automatically available at `azd deploy` time.
Unlike other language implementations, our current `npm` implementation auto-injects environment variables when calling `npm run build` during `azd deploy`. This was done to expediently allow static-frontend files to easily perform environment variable [embedding](https://create-react-app.dev/docs/adding-custom-environment-variables/), that allows app configuration to be part of the html/js that runs in the client web browser. This may break static web apps, or apps using older template versions of `azd`. In newer versions of our static web apps, we explicitly perform configuration injection using …
> breaking: Remove env variable overrides in `npm build`

- cli/azd/cmd/cmd_help.go
- cli/azd/cmd/init.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/templates_test.go
- cli/azd/cmd/testdata/TestUsage-azd-init.snap
- cli/azd/cmd/testdata/TestUsage-azd-template.snap
- cli/azd/internal/repository/initializer.go
- cli/azd/internal/repository/initializer_test.go
- cli/azd/pkg/templates/path.go
- cli/azd/pkg/templates/template.go
- cli/azd/pkg/templates/template_manager.go
- cli/azd/pkg/templates/template_manager_test.go
- cli/azd/resources/templates.json
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/telemetry_test.go
- ext/vscode/src/commands/cmdUtil.ts
`azd init` now displays friendly names for templates.
New:
Old:
With this change, the following template changes have also been made:
1. Rename 'Empty template' to 'Minimal'
2. Reshape internal template object based on #2075.
- `DisplayName` (newly added field) has been dropped in favor of `Name`.
4. Templates are now listed based on sorting order in templates.json.
Fixes #2075, #2057
> Display better names in `azd init`

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
Since we started to append a timestamp to the deployment name we ran into an issue where it was possible to generate a deployment name that was longer than the ARM allowed limit.
With this change, we now truncate the generated name to length (taking the last 64 chracters of the string, on the assumption that the "interesting" parts of the environment name are near the end of when you have a very long name).
The deployment object is still tagged with the full environment name so that `azd env refresh` and others who want to query by full environment name can find it.
> Ensure generated deployment name is not too long

- cli/azd/cmd/pipeline.go
- cli/azd/cmd/testdata/TestUsage-azd-pipeline-config.snap
- cli/azd/cmd/up.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/util.go
- cli/azd/test/functional/cli_test.go
Add prompts for subscription and location in `pipeline config`
`pipeline config` needs the environment is a provision-ready state. Instead of erroring out, we should prompt the user to fill it in. This restores the old behavior prior to #1752. 
Fixes #2058
> Add prompts for subscription and location in `pipeline config`

- cli/azd/pkg/tools/maven/maven_test.go
Test_extractVersion was failing on my machine due to `mvn` not being installed. Add a mock for `mvnw` so that the test is happy.
> Fix maven test failing when not installed

- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- eng/pipelines/template-tests.yml
- eng/pipelines/templates/jobs/run-template-tests.yml
- eng/pipelines/templates/steps/template-test-generate-jobs.yml
- eng/pipelines/templates/steps/template-test-run-job.yml
- eng/scripts/Set-TemplateTestMatrixVariable.ps1
- templates/tests/test-templates.sh
Template tests currently use template.Name instead of template.RepositoryPath to construct the reference to the template. This used to work fine since they were both always set to the same values, until #2093. This change fixes the incorrect logic in the test setup scripts.
> Fix template tests

- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/webpack.config.js
This version contains, among other things, the changeover to VSCode's native localization API, which means we can remove `vscode-nls`.
Also, the issue with `open` is fixed, so the copy of `xdg-open` can be removed.
> Bump `@microsoft/vscode-azext-utils` dependency

- templates/tests/test-templates.sh
Fix starters failing in template-tests.sh due to choosing the wrong working directory. Slightly improves the working directory changes to be isolated within a given function to avoid context-sensitivity.
> Fix test-templates for starters

- cli/azd/CHANGELOG.md
- templates/common/.github/workflows/bicep/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
- templates/todo/projects/java-postgresql/githubworkflow/azure-dev.yml
Updates `azd` templates to use GitHub [variables](https://docs.github.com/en/actions/learn-github-actions/variables) for non-secret configuration values.
> Requires build from #2125
> Updates github actions to use variables for non-secret values

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/docker/docker_test.go
As of Docker for Desktop build 4.19.0 the docker CLI expects os/arch when specifying the `--platform` flag.  This change is backwards compatible and also works for older docker versions.
Resolves #2118
> Set default docker platform to linux/amd64

- cli/azd/cmd/cobra_builder.go
- cli/azd/cmd/container.go
- cli/azd/internal/repository/initializer_test.go
- cli/azd/pkg/exec/command_runner.go
- cli/azd/pkg/exec/runargs.go
- cli/azd/pkg/exec/runargs_test.go
- cli/azd/pkg/exec/util_test.go
- cli/azd/pkg/tools/kubectl/kube_config_test.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/init_test.go
- cli/azd/test/functional/up_test.go
Enable command runner debug logging when `--debug` is set.
Command runner currently has a switch for debug logging. This makes some sense as debug logging does end up formatting large enough strings that deserves a performant happy path. This change enables debug logging based on `--debug` flag.
> Enable debug logging for command runner

- templates/common/.devcontainer/devcontainer.json/aks/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/terraform/devcontainer.json
Extension `eg2.vscode-npm-script` is deprecated:
Functionality is now supported by vscode directly:
https://code.visualstudio.com/updates/v1_23#_npm-script-running
> deprecated extension

- cli/azd/cmd/init.go
- cli/azd/cmd/util.go
- cli/azd/cmd/util_test.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
This change provides a suggessting for the initial environment name that the user needs to create during `azd init`.  The suggestion is based on the name of the current directory, suffixed with `-main`.
In addition, some help text is added to help give users some idea as to what this value is used for.
I had hoped that we would be able to default this value to something like `main` and simply not ask the question to the user, but that is more difficult than expected, given how `azd` is used today. Most existing `azd` templates assume that `AZURE_ENV_NAME` is going to be used in a way that forces it to be unique across the user's subscription (since it is used to both create the name of the resource group we provision resources into and used to generate the resource suffix that we append …
> Provide a sugesstion for an environment name during `init`

- cli/azd/cmd/build.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/package.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/up.go
- cli/azd/pkg/output/ux/time.go
- cli/azd/pkg/output/ux/time_test.go
This change adds timing information to the success messages printed by
`build`, `deploy`, `down`, `package`, `provision`, `restore` and `up`.
Fixes https://github.com/Azure/azure-dev/issues/414
> Add timing information to commands

- cli/installer/windows-actions/actions.vcxproj
Mitigates needing a specific CRT installed on the target machine.
Typically for CAs.
> Statically link CRT in CA

- eng/scripts/Update-VscodeExtensionVersion.Tests.ps1
- ext/vscode/README.md
- ext/vscode/package.json
- ext/vscode/src/commands/cmdUtil.ts
- ext/vscode/src/commands/env.ts
For #256
Per https://github.com/Azure/azure-dev/issues/256#issuecomment-1545965833, we will not change the install folder, so those references will remain untouched in `./ext/vscode/src/utils/azureDevCli.ts`.
> Rename "Azure Dev CLI" -> "Azure Developer CLI"

- templates/common/infra/bicep/core/host/container-app-upsert.bicep
- templates/common/infra/bicep/core/host/container-app.bicep
- templates/todo/common/infra/bicep/app/api-container-app.bicep
- templates/todo/common/infra/bicep/app/web-container-app.bicep
This update allows the `container-app` bicep module to support both private ACR registries or public registry images.
- `identityType` allows `None`, `SytemAssigned` or `UserAssigned` (optional, defaults to 'None')
- `imageName` Sets the image name (optional)
- `revisionMode` Supports `Single` or `Multipe` (optional, defaults to `Single`)
- `containerRegistryName` Sets the ACR registry name (optional, changed from required)
- `identityName` Sets the user assigned identity name to use (optional, changed from required)
When using public images use `identityType` as `None` or `System`
When using private ACR images use `identityType` as `UserAssigned`
If `imageName` is set on the module properties that will override any built in `upsert` behavior and default to the specified image.
> Updates container app modules to support public images

- templates/todo/projects/csharp-cosmos-sql/README.md
- templates/todo/projects/csharp-sql-swa-func/README.md
- templates/todo/projects/csharp-sql/README.md
- templates/todo/projects/java-mongo-aca/README.md
- templates/todo/projects/java-mongo/README.md
- templates/todo/projects/java-postgresql/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-aks/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/nodejs-mongo/.repo/bicep/README.md
- templates/todo/projects/nodejs-mongo/.repo/terraform/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
- templates/todo/projects/python-mongo/.repo/terraform/README.md
This reflects marketing approval for our name (we technically can't use Azure Dev CLI).
Closes #256
> Update "Dev" to "Developer" in template READMEs

- cli/azd/pkg/account/subscriptions.go
Addresses #2165 
`azd` already filters where `regionType == 'Physical'`. This change will additionally check to ensure that `physicalLocation` is also defined. This additional filter was the only other distinguishing factor. 
The following locations match this additional filter and will now be excluded from the location listing:
- (South America) Brazil US
- (US) Central US EUAP
- East US 2 EUAP
> Note: Just because a location is listed as available to not mean that all locations support all Azure resources.  Refer to resource provider documentation for each resource for more information on supported regions
> Filter Azure locations that do not have physical location listed

- cli/azd/cmd/actions/action.go
- cli/azd/cmd/cobra_builder.go
- cli/azd/cmd/templates.go
- cli/azd/pkg/templates/template.go
This change makes the default `template list` format more readable by removing Description (which is long text) from display. The UI changes can be seen in the issue linked below.
Two other improvements were also made as part of this change:
- Do not use `table` format for `template show` as it is a single item list. Display the items in a better human-readable format:
```
$ azd template show todo-csharp-sql 
RepositoryPath : todo-csharp-sql
Name           : React Web App with C# API and SQL Database
Description    : A blueprint for getting a React web app with a C# API and a SQL database on Azure. The blueprint includes sample application code (a ToDo web app) which can be removed and replaced with your own application code. Add your own source code and leverage the Infrastructure as …
```
> Remove Description from template list table format

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/ext/models.go
Fixes #2170 
More information about the `ErrorActionPreference` can be found in the [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#erroractionpreference)
> Error handling influenced from [GitHub](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)
> Automatically set `ErrorActionPreference` to `Stop` for pwsh inline hooks

- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/containerapps/container_app_test.go
Fixes #2178 
Max length of ACA resource name is 32 chars
Max length of ACA resource name + revision suffix is 54 chars
This leaves us with a maximum of 22 chars for revision suffix.  Our previous length was exactly at 22 but were still hitting the limit.
This reduces our revision to be `azd-<timestamp>` giving us a few extra buffer chars.
> Shorten revision suffix for ACA apps

- cli/azd/cmd/pipeline.go
- cli/azd/cmd/testdata/TestUsage-azd-pipeline-config.snap
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
- cli/azd/pkg/tools/azcli/ad.go
- cli/azd/pkg/tools/azcli/ad_test.go
- cli/azd/pkg/tools/azcli/azcli.go
Updates `azd pipeline config` default roles that are assigned to the created/updated service principal.
**Roles**
- [Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#contributor) (Existing)
- [User Access Administrator](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#user-access-administrator) (New)
Users can override and set their own roles by using one or more `--principal-role` flags.
**Example**
```bash
azd pipeline config --principal-role Role1 --principal-role Role2
```
> [Example run in GitHub](https://github.com/wbreza/aca-test-multiple-roles/actions/runs/4984195646/jobs/8922207829) with service principal generated from new build
> Updates pipeline default roles to include user access admin

- cli/azd/cmd/env.go
- cli/azd/cmd/testdata/TestUsage-azd-env-refresh.snap
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/initialize_test.go
- cli/azd/test/functional/up_test.go
With this change, `azd env refresh some-environment-name` is now supported and behaves the same as if the user had typed `azd env refresh -e some-environment-name`.
When an explicit environment name is not provided via the `-e` or `--environment` flag and there are no arguments, `azd env refresh` refreshes the default environment, as before.
Fixes #1746
> Support environment name as explicit argument for `env refresh`

- templates/common/infra/bicep/core/host/aks-agent-pool.bicep
- templates/common/infra/bicep/core/host/aks-managed-cluster.bicep
Updates AKS bicep templates to latest version `2023-03-02-preview`
Previous version was not properly enabling ingress which was causing deployment to hang and fail
Resolves #1708 
fix https://github.com/Azure/azure-dev/issues/2172
Resources
- [Microsoft.ContainerService managedClusters](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-bicep)
> Update AKS templates to latest Bicep version

- cli/azd/pkg/ext/models.go
The `-o pipefail` is not supported in `sh` and requires `bash`.  
Removing this so we only set `set -e` by default and we can add official `bash` support later.
> Removes unsupported -o pipefail for inline hooks

- cli/azd/cmd/cmd_help.go
- cli/azd/cmd/init.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/root.go
- cli/azd/cmd/testdata/TestUsage-azd-init.snap
- cli/azd/cmd/testdata/TestUsage-azd-pipeline-config.snap
- cli/azd/cmd/testdata/TestUsage-azd-pipeline.snap
- cli/azd/cmd/testdata/TestUsage-azd-provision.snap
- cli/azd/cmd/testdata/TestUsage-azd.snap
- cli/azd/pkg/commands/pipeline/pipeline_manager.go
Make it clear that user needs to create their pipeline definition or use one provided by an azd template.
While looking at other usage text, the other changes brought in:
- Remove env name prompt from `azd provision` as that is no longer true
- Fix `azd init` link to all templates
- Remove `.git` suffix from links
Fixes #2131, #2236
> Update usage text for pipeline config

- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/azdo/utils.go
- cli/azd/pkg/commands/pipeline/azdo_provider.go
- cli/azd/pkg/commands/pipeline/azdo_provider_test.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_test.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provisioning.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/test/functional/cli_test.go
This allows us to inherit values from the OS Environment which is nice behavior and also supports CI/CD cases where we set values which are normally stored in the .env file as environment variables (because the .env file is not persisted across CI runs).
For folks that care about getting at just the values in the `.env` file stored with the environment, `Environment.Dotenv()` now returns a copy of it. The most common use of this is tests which want to validate that the environment file was updated in someway.
Fixes #2208
> Use `os.Getenv` instead of accessing `Environment.Values`

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/pkg/tools/azcli/container_registry.go
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/docker/docker_test.go
- cli/azd/test/mocks/mockazsdk/container_registry.go
Today `azd` only support logging in with ACR admin user.  This is a bad practice and a security vulnerability.  
This PR addresses this issue by using the current identity to push containers.
This approach leverages exchanging an AAD token for an ACR refresh token based on the published [ACR docs](https://azure.github.io/acr/AAD-OAuth.html#calling-post-oauth2-exchange-to-get-an-acr-refresh-token)
**Other enhancements**
- Uses `--password-stdin` instead of using `--password` param on docker CLI
Resolves #2244
> Add support to login to ACR with current identity

- .vscode/cspell.misc.yaml
- cli/azd/test/functional/testdata/samples/springapp/azure.yaml
- schemas/alpha/azure.yaml.json
- templates/starter/terraform/azure.yaml
- templates/todo/projects/java-postgresql/.repo/terraform/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/azure.yaml
- templates/todo/projects/python-mongo/.repo/terraform/azure.yaml
We don't want to include any values in the schema that are tied to alpha features in the `v1.0` schema, since we may remove or change these values during development.
This change introduces a new copy of this schema and adds "terraform" as a supported member of an enum (this is a new value that is supported behind an alpha feature)
Fixes #1925
> Create an `alpha` version of `azure.yaml` schema

- cli/azd/cmd/auth_login.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/deploy_test.go
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/initialize_test.go
- cli/azd/test/functional/login_test.go
- cli/azd/test/functional/telemetry_test.go
- cli/azd/test/functional/up_test.go
- cli/azd/test/functional/version_test.go
- eng/pipelines/release-cli.yml
Previously, when `login` fails, there are cases where "Not logged in, run 'azd auth login' to login" would be printed out, but the returned exit code is zero. This is a problem in CI situations when auth isn't setup correctly, and yet `login` is deemed successful, the CI pipeline proceeds as normal, resulting in user confusion.
This change updates `login` to always exit with non-zero exit code if `login` fails. The code has been refactored so that `--check-status` plays nicely with this implementation.
Fixes #2221
> Return failed error when logging in

- templates/common/infra/bicep/core/host/container-app.bicep
- templates/common/infra/bicep/core/host/container-apps.bicep
Allow to pass in `daprEnabled` field as a parameter in `container-apps.bicep` module. 
Fix `URI` parsing in output in `container-app.bicep` file to only be done when `ingressEnabled` is true.
> add daprEnabled param to container-apps bicep

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli.yml
Finishes fixing #2183... This renames the ARM binaries contained in their compressed files as described in https://github.com/Azure/azure-dev/issues/2183#issuecomment-1545303694
> Rename the binaries inside the compressed files as well

- cli/azd/cmd/config.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/testdata/TestUsage-azd-config.snap
- cli/azd/cmd/testdata/TestUsage-azd-restore.snap
adding a couple missing letters in the help text for `config` and `restore`
> Fix typos in `config --help` and `restore --help`

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/.vscode/cspell.yaml
- cli/azd/cmd/middleware/telemetry.go
- cli/azd/cmd/middleware/telemetry_test.go
- cli/azd/internal/tracing/fields/domains.go
- cli/azd/internal/tracing/fields/fields.go
- cli/azd/internal/tracing/fields/key.go
With this change, only well-known domains are mapped and shown in error reporting data. Other domains are simply mapped to the value `other`.
Also, flatten the `error` schema instead of nesting data under `error.details`. This means reporting data that looks like `error.service.name` instead of `error.details` containing a JSON with `service.name`. This better suits azd's telemetry platform needs as data-processing happens at a field level.
> Anonymize host domains 

- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/tools/kubectl/models.go
- cli/azd/pkg/tools/kubectl/models_test.go
Fixes #2270
`targetPort` can reference a port or well known service name
**From the docs**
Number or name of the port to access on the pods targeted by the service. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME. If this is a string, it will be looked up as a named port in the target Pod's container ports. If this is not specified, the value of the 'port' field is used (an identity map). This field is ignored for services with clusterIP=None, and should be omitted or set equal to the 'port' field. 
https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
> Change AKS service spec 'targetPort' from int to string

- cli/azd/test/azdcli/cli.go
- cli/azd/test/azdcli/util.go
- cli/azd/test/functional/env_test.go
Add tests to verify `env get-values` (non-json).
Also, make a slight improvement to stream CLI output in end-to-end tests.
> Add test coverage for env get-values

- cli/azd/cmd/down.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
- cli/azd/test/functional/up_test.go
The tool had logic to this, but it had been broken for a while due to
a change in how `Environment.Save()` worked. In #1667 we made a change
such that when you save an environment, we would merge in new values
from the existing .env file into the file we were saving, in case the
.env file had been modified by an external hook.
However, that logic did not take into account that we may have
intentionally removed some values (to explicitly delete them) and if
they already existed in the `.env` files, they should be removed as
part of the save operation.
To address this, we now track the deletes that we have preformed so we
can replay them during saving.
To prevent regressing again we also add an end to end test.
Fixes #2217
> Remove infrastructure outputs from `.env` on `azd down`

- cli/Dockerfile
Currently running into some issues when building the docker container:
```
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
```
In https://github.com/kubernetes/release/issues/2862 there were similar issues (at the time the URL that served the key was 500'ing) and there was a link to an alternate location for this key file, published by the k8s team.
Pick up that key, as others on the thread have today when they hit issues as well.
> Fetch k8s GPG key from alternate location

- cli/azd/cmd/cobra_builder.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/test/functional/cli_test.go
Set the following environment variables: `TF_APPEND_USER_AGENT` and `ARM_CORRELATION_REQUEST_ID` appropriately when invoking the `terraform `CLI.
- `TF_APPEND_USER_AGENT` is a terraform CLI level environment variable, which gets appended to the terraform user agent variable. RM providers that build a user-agent string upon terraform user agent will thus inherit this. `azurerm` is confirmed to work with this model
- `ARM_CORRELATION_REQUEST_ID` is an `azurerm` provider environment variable. If unset, `azurerm` simply generates a UUID per-request. Note that users can explicitly disable this by setting `ARM_DISABLE_CORRELATION_REQUEST_ID` variable or configuring `disable_correlation_request_id` in `.tf`. `azapi` doesn't yet support this. Issue filed: …
> Add correlation for terraform

- cli/azd/pkg/tools/azcli/keyvault.go
- go.mod
- go.sum
`github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets` has been deprecated in favor of
`github.com/Azure/azure-sdk-for-go/sdk/security/keyvault/azsecrets`, update to use the newer package.
> Upgrade KeyVault SDK

- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/util.go
This fixes default subscription and location prompt selection not being saved after the initial provisioning attempt.
Existing logic was using `env.GetSubscriptionId()` and `env.GetLocationId()` but those values were not yet set in the environment.
Fixes #2325
> Fix saving of subscription and location defaults

- cli/azd/pkg/azsdk/zip_deploy_client.go
- cli/azd/pkg/graphsdk/application_request_builders.go
- cli/azd/pkg/graphsdk/fic_request_builders.go
- cli/azd/pkg/graphsdk/me_request_builder.go
- cli/azd/pkg/graphsdk/service_principal_request_builders.go
- cli/azd/pkg/httputil/util.go
- cli/azd/pkg/tools/azcli/container_registry.go
Remove `httputil.HandleRequestError` and its usage as it may be more correct to return the underlying `err` when `err != nil && response != nil`.
Reasoning is as follows: suppose that the transport, or an executor of the pipeline, had returned an `err` for some reason, with `resp` intact. The executing code has made a decision that the request should be considered an error. The server response, in this case, is not the cause of the error. Instead, something else has occurred.
For example, it is documented in [http.Client.Do](https://pkg.go.dev/net/http#Client.Do):
> On error, any Response can be ignored. A non-nil Response with a non-nil error only occurs when CheckRedirect fails, and even then the returned Response.Body is already closed.
In this case, it is more correct to attribute the …
> Remove `httputil.HandleRequestError`

- cli/azd/pkg/tools/azcli/spring_app.go
- go.mod
- go.sum
- Update ASA go sdk from `https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appplatform/armappplatform` to `https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appplatform/armappplatform/v2`, the newer one support ASA consumption dedicated plan.
- Add a new condition to extract Azure Spring Apps endpoint.
> Support Azure Spring Apps consumption dedicated plan

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli-choco.yml
- eng/pipelines/templates/steps/publish-cli-winget.yml
- eng/pipelines/templates/steps/publish-cli.yml
Partial: https://github.com/Azure/azure-dev/issues/2239
* Releases to `GA` in storage account when releasing a GA version (install script still uses `latest`)
* Disable publishing preview releases on WinGet, Choco (only releases GA releases to those channels now)
* Only release to latest tag on MCR when releasing GA
Another PR will contain the default installer switch to the GA channel.
> GA publishing tasks part 1

- cli/azd/cmd/pipeline.go
- cli/azd/pkg/commands/pipeline/github_provider.go
- cli/azd/pkg/commands/pipeline/github_provider_test.go
- cli/azd/pkg/commands/pipeline/pipeline.go
- cli/azd/pkg/commands/pipeline/pipeline_test.go
- cli/azd/pkg/exec/util_test.go
- cli/azd/pkg/httputil/http_client.go
- cli/azd/pkg/tools/azcli/ad.go
- cli/azd/pkg/tools/azcli/apim.go
- cli/azd/pkg/tools/azcli/appconfig.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/cognitive_service.go
- cli/azd/pkg/tools/azcli/deployments.go
- cli/azd/pkg/tools/azcli/deployments_operations.go
- cli/azd/pkg/tools/azcli/keyvault.go
- cli/azd/pkg/tools/azcli/resources.go
- cli/azd/pkg/tools/azcli/static_webapp.go
- cli/azd/pkg/tools/azcli/webapp.go
- cli/azd/test/mocks/mock_context.go
Update instances in the codebase where `httpClient` was created on-demand via `ctx.Context`, to now reference the shared `httpClient`.
Remove unneeded code for storing `httpClient` and retrieving `httpClient` from context as a result.
> Share `httpClient` instance

- cli/azd/cmd/build.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/middleware/telemetry.go
- cli/azd/cmd/package.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/up.go
- cli/azd/cmd/util.go
- cli/azd/internal/tracing/attributes.go
- cli/azd/internal/tracing/fields/fields.go
- cli/azd/pkg/input/console.go
Track time waiting for user. This currently only includes prompts generated by the CLI, and not indirectly by a tool.
Fixes #598
> Add tracking for user interaction time

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager_test.go
Allow bicep_provider to take in a `clock.Clock` instance, which is already injected [here](https://github.com/Azure/azure-dev/blob/9a995a2584fbee25441f52941bc56c9f7523008e/cli/azd/cmd/container.go#L332). This is the shared instance throughout the application.
> Reshare clock implementation for bicep provider

- cli/azd/cmd/show.go
- cli/azd/test/functional/show_test.go
Today, `azd show` is used by VS Code to get information about the current project, both the services that make it up (and information about where the code for these services is) as well as the target resources (if we can determine them)
In the case where an environment didn't exist (which is hard to have happen during a normal course of action, but possible if you manually go mucking around in `.azure`) `azd show` would prompt the user if they wanted to go create an environment.
This caused issues with the VS integration, since the editor would not expect `azd` to prompt in this case.
`azd show` already handles the case where the infrastructure for a project has not been deployed. This change extends this behavior so that if for some reason we can not fetch the current environment, we …
> Allow `show` to work when no environment exists

- cli/azd/pkg/project/service_target_springapp.go
- cli/azd/pkg/project/service_target_springapp_test.go
- cli/azd/pkg/tools/azcli/spring_app.go
As subject, this pr is to fix the application url fetched from ASA consumption plan is wrong:
This is caused by when getting the public endpoint of spring apps, azd used ASA app fqdn to constuct the app url, which is not applicable to consumption tier. Instead, we should use the url property of spring apps, which could fetch the application url for all of the basic/standard/consumption plan tiers.
> Fix asa url fetched from consumption plan incorrect

- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/tools/kubectl/models.go
- cli/azd/pkg/tools/kubectl/models_test.go
- cli/azd/test/testdata/k8s/ingress.json
- cli/azd/test/testdata/k8s/ingress.yaml
> Fixes error when unmarshalling AKS ingress resources with TLS hosts

- cli/azd/test/functional/cli_test.go
Skip update check in `Test_CLI_NoDebugSpewWhenHelpPassedWithoutDebug` that ensures `--help` is well formed. The test is asserting that `stderr` isn't polluted by unexpected debug spew when a simple `--help` is passed. The version update check is one of the things that could write to `stderr` but is outside the purpose of the test.
> Skip update check in test that ensures `--help` is well formed

- eng/pipelines/templates/steps/publish-cli.yml
There was a [failure in the release](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2846258&view=results) because a couple of parameterized variables were not provided properly. This sets up safe defaults for those. 
In the long term we should refactor the releases to use separate jobs and run in parallel when appropriate to minimize problems from intermittent failures and occasional syntax problems that are hard to test for. https://github.com/Azure/azure-dev/issues/2418
> Add parameters for AllowPrerelease and CliVersion with defaults

- templates/todo/projects/csharp-sql-swa-func/README.md
- templates/todo/projects/csharp-sql/README.md
- templates/todo/projects/java-mongo-aca/README.md
- templates/todo/projects/java-mongo/README.md
- templates/todo/projects/java-postgresql/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-aks/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
This PR fixes the README quickstart guide commands.
I have replaced `Azure-Samples/todo-csharp-cosmos-sql` in each command with the correct template reference that is mentioned a few lines above in each README where this was present.
I raised this with @savannahostrowski
> fix quickstart commands on the README in the todo projects

- cli/azd/main.go
In some mac scenarios brew's internal view of packages may be behind the current state of the azd homebrew tap. Add `brew update` to the command to prevent inaccurate warnings from brew that the latest version is already installed.
> Add "brew update" to upgrade message on brew install scenarios

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/exec/command_runner_test_unix.go
- cli/azd/pkg/exec/runresult.go
- cli/azd/pkg/exec/util_test.go
Previously, we only added the output from standard out and standard error in cases where the command we ran called exit() cleanly. In other cases, we would not include this information.
This did not work well in practice, for example, dotnet applications will exit via a signal (`SIGABRT`) if `libicu` is not installed on a linux machine, after printing very helpful text to standard error, which we would not include.
This changes our logic so that we always include this output, when we have it. So instead of:
```
ERROR: initializing provisioning manager: initializing infrastructure provider: failed resolving IaC provider 'bicep': checking bicep version: signal: aborted
```
To (the much longer, but much more helpful):
```
ERROR: initializing provisioning manager: initializing infrastructure …
```
> Include external command output in errors in all cases

- cli/azd/pkg/exec/command_runner.go
- cli/azd/pkg/tools/python/python.go
Apply same log and error handling logic to `commandRunner.RunList`. This allows `RunList` to correctly return `ExitError` for error classification, and also emit the same debug logs.
Fixes https://github.com/Azure/azure-dev-pr/issues/1556
> Apply same log and error handling logic to RunList

- cli/azd/main.go
When `azd` is about to exit, if there is telemetry that needs to be
uploaded, we spawn a separate copy of `azd` to go do the uploading and
then exit the current process.  This allows the upload of the
telemetry to happen in the background instead of pausing the
termination of `azd` until it is complete.
Previously, we reused the current working directory that the root
`azd` process was launched in (which, in the common case is whatever
directory the user ran `azd` from).
On Windows, if a process is running with a given CWD, that directory
can not be deleted until the process exits. This means that until the
upload process finishes and the uploader exits, the CWD of the initial
`azd` is in use and can not be deleted.
In CI our end to ends tests run in an ephemeral directory, created by …
> Set CWD for telemetry to fix Windows CI issues

- cli/azd/cmd/pipeline.go
- cli/azd/cmd/up.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/prompt/prompter.go
Different provisioning providers may require different values to be set in the environment to be able to do a provision operation.  For example, when using the bicep provider and doing a resource group scoped deployment, in addition to a subscription and a location, we need `AZURE_RESOURCE_GROUP` defined to name the target resource group to deploy to.
This change prepares us to have providers require different values to be set in the environment by moving `EnsureEnv` from `prompt.Prompter` and to the providers themselves.  `provisioning.Manager` also gains an `EnsureEnv` method which simply calls `EnsureEnv` on the underlying provider.
There should be no functional impact of this change, it is simply code motion to help with some future changes.
> Move `EnsureEnv` from `prompt.Prompter` to `provisioning.Provider`

- cli/azd/cmd/env.go
- cli/azd/cmd/testdata/TestUsage-azd-env-new.snap
- cli/azd/cmd/testdata/TestUsage-azd-env.snap
- cli/azd/test/functional/env_test.go
Also, update the help text for `azd env new` to call out that the new enviromnet is set as the default environment once it is created.
Fixes #2306
> Validate environment exists when running `azd env select`

- cli/azd/CHANGELOG.md
- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
Fixes #2428, #2040
Includes the current git branch name when setting up federated credentials for GitHub.
> GitHub CI Provider: Include current git branch in federated authentication

- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt_test.go
- cli/azd/pkg/pipeline/github_provider.go
When running `azd pipeline configure` we will now set an
`AZURE_RESOURCE_GROUP` variable, when the infrastructure targets
resource group scope.
Pipelines can then be configured to include this variable when running
`azd` commands where it will be respected.
These changes only impact new runs of `pipeline config`. There is no
requirement to have an updated version of `azd` in CI.  The existing
released version (1.0.2) will correctly use these values when set.
As an example, here's the diff to `azure-dev.yml` from the
todo-nodejs-mongo template showing the modifications needed.
The `AZD_ALPHA_ENABLE_RESOURCEGROUPDEPLOYMENTS` env var is used to
enable the alpha feature in CI. It will no longer be needed once the
feature is out of alpha.
```patch
diff --git a/.github/workflows/azure-dev.yml …
```
> Make `pipeline config` work with RG Scoped Deployments

- cli/azd/pkg/pipeline/github_provider.go
We now encode the name compontent so it can be stored in a path, as the error message recommends.
Fixes #2505
> Fix `pipeline config` when current branch contains a `/`

- cli/azd/cmd/provision.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
Updating the Provisioning provider to:
- Removing `plan()`
- Adding `Preview()` as the way to generate a provisioning preview
- Moving the current logic from `plan()` to be called by `Deploy()`
- Remove `DeploymentPlan` and do not make `Deploy()` to require a plan.  Deploy auto-generates a plan.
- Remove `WhatIf()`.   Move its logic to be called by `Preview()`
> [Refactoring] Merging provisioning provider Plan()->Preview()

- eng/pipelines/templates/steps/publish-cli.yml
Looking back through releases I found a couple failures which required intervention: 
1. [Jun 14 release build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2846258&view=logs&j=b7097f24-c4f3-5d67-8e4f-7a291a407709&t=5b99ed8b-cb08-5fde-dff1-b89d40c908d6)
2. [Jul 12 release build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2911902&view=logs&j=493e9ff3-1332-590a-730c-4fca05f30c58&t=4c7fa1e3-7572-57b4-94a9-fbe790ecd3ae)
As part of the [GA publishing tasks PR](https://github.com/Azure/azure-dev/commit/bfc7050577348db4070f8888676ea24d0b501e03) a [`Set SubmitBrewFormula` task was added](https://github.com/Azure/azure-dev/commit/bfc7050577348db4070f8888676ea24d0b501e03#diff-97440691b051b7593395361d95cba18f367e3e8155c120eff3a00a0c51ecfb18R232) which would …
> Fix error in publish-cli.yml

- cli/azd/CHANGELOG.md
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/testdata/failed-subscription-deployment.json
For subscription level deployments, `azd down` needs to discover the set of resource groups from the previous deployment, so it can go delete each one. We were using the `outputResources` property of an ARM Deployment to compute this, which is not populated for failed deployments.
In the failed deployments case, we revert back to trying to infer this information (as before d8863e44c25bad9e52a5c6a1c0b042a52b81edde) from the `dependsOn` portion of the deployment. This can miss some cases (e.g. empty resouce groups, which is why we moved away from this in failure cases (where often you really do want to tear down everything and start over)
Fixes #2508
> Fix `azd down` after a failed `azd provision`

- cli/azd/CHANGELOG.md
- cli/azd/cmd/container.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/testdata/TestUsage-azd-pipeline-config.snap
- cli/azd/pkg/graphsdk/application_request_builders.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/pipeline_manager_test.go
- cli/azd/pkg/tools/azcli/ad.go
- cli/azd/pkg/tools/azcli/ad_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/test/mocks/mockgraphsdk/mocks.go
Related to #2468 
Today every time a user runs `azd pipeline` config without any arguments a new service principal is created in Azure.  This causes the following issues:
1. Bloats number of service principals created in subscriptions
2. Unintended behavior and users would expect the same service principal to be used when available.
This PR introduces caching the service principal application client id in the `azd` environment.  On subsequent run of `azd pipeline config` this same service principal will be reused instead of creating a new one.
- When setting `--principal-name` `azd` will continue to create/update the specified service principal name
- When creating new `azd` environment and running `azd pipeline config` a new service principal will still be created
When developing using …
> Pipeline Config - Reuse previous service principal when available

- cli/azd/pkg/input/asker.go
While reading a `survey.Select` prompt choice from a non-tty `stdin` (such as a file, or `strings.Reader` in tests), an invalid choice causes the application to stall indefinitely. This is due to the use of a for-loop, where our `asker` implementation was re-prompting for invalid input instead of erroring out.
This change fixes the behavior to error out if an invalid choice is provided while reading in non-tty mode. Other prompt modes did not have the same issue.
Example output:
```
2023-07-24T20:39:31.0014647Z === FAIL: cli/azd/test/functional Test_CLI_Telemetry_NestedCommands (unknown)
2023-07-24T20:39:31.0032809Z     telemetry_test.go:228: DIR: /tmp/Test_CLI_Telemetry_NestedCommands4125947061/001
2023-07-24T20:39:31.0038932Z     cli.go:218: 10ms [stdout] 
2023-07-24T20:39:31.0041844Z …
```
> [asker] Fix asker prompting indefinitely due to invalid choice selection on non-tty mode

- cli/azd/cmd/root.go
the hooks middleware won't be registered when running `azd provision --preview`.
> use condition for registering hooks on provision

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/env.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/testdata/TestUsage-azd-env-refresh.snap
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/manager_test.go
- cli/azd/pkg/infra/provisioning/options.go
- cli/azd/pkg/infra/provisioning/provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider_test.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/infra/scope.go
- cli/azd/pkg/output/colors.go
Adds support to use AZD with projects where the underlying Azure infrastructure was provisioned outside of `azd`.
- Supports both subscription and resource group scoped Bicep deployments
Use the matching deployment without confirmation. Display the matching deployment with highlight color
Prompt the user with a list of matching deployments including the name and timestamp of the deployment
**After Selection**
Display selected deployment and actions performed
@Austinauth Please let me know if you have any feedback on the updated UX.
Devs were not able to link infra to `azd` when infrastructure is provisioned by DevCenter environments.  `azd env refresh` would fail because the deployment was not matched by the default lookup strategy.
Now a dev can run the following after provisioning …
> `azd env refresh` - Support for BYOI

- cli/azd/cmd/auth_login.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/remote_credential.go
- cli/azd/test/functional/auth_test.go
- ext/vscode/.vscode/cspell-dictionary.txt
- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/package.nls.json
- ext/vscode/src/commands/loginCli.ts
- ext/vscode/src/utils/VsCodeAuthenticationCredential.ts
- ext/vscode/src/utils/authServer.ts
- ext/vscode/src/utils/azureDevCli.ts
- ext/vscode/src/utils/executeAsTask.ts
- ext/vscode/src/utils/process.ts
This change sketches out a possible way for `azd` to delegate
authentication to an external process and teaches the VS Code
extension to use this strategy to provide authentication for `azd`
based on the credential associated with the Azure Account extension.
This works by introducing a new "Remote Credential" type in `azd`, is
used when `AZD_AUTH_ENDPOINT` and `AZD_AUTH_KEY` are defined in the
system environment.  When these values are set and `azd` needs to
request a token, it makes a request to
`${AZD_AUTH_ENDPOINT/token?api-version=2023-07-12-preview` using
`${AZD_AUTH_KEY}` as an bearer token to secure the request.
The body of the request body contains a serialized version of the
`TokenRequestOptions` struct:
```
{
scopes: []string
tenantId: string?
}
```
The server is expected to …
> WIP: Support fetching credentials from an external process

- templates/common/infra/bicep/core/host/appservice-appsettings.bicep
- templates/common/infra/bicep/core/host/appservice.bicep
- templates/common/infra/bicep/core/host/functions.bicep
- templates/todo/common/infra/bicep/app/api-appservice-dotnet.bicep
- templates/todo/common/infra/bicep/app/api-appservice-java.bicep
- templates/todo/common/infra/bicep/app/api-appservice-node.bicep
- templates/todo/common/infra/bicep/app/api-appservice-python.bicep
- templates/todo/common/infra/bicep/app/api-functions-dotnet-isolated.bicep
- templates/todo/common/infra/bicep/app/api-functions-node.bicep
- templates/todo/common/infra/bicep/app/api-functions-python.bicep
This allows users to set secret values as app settings for `appservice`, `function` host services. App service handle secrets in [app settings](https://learn.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#configure-app-settings) by defaults, so there isn't any additional configuration there.
Fixes https://github.com/Azure/azure-dev-pr/issues/1563
> Make `appSettings` a secure object by default

- templates/common/.github/workflows/java/terraform/azure-dev.yml
- templates/common/.github/workflows/nodejs/terraform/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
fix: https://github.com/Azure/azure-dev/issues/2231
Adding `az` login and account setup for terraform's pipeline definitions.
This is required after we added `az` commands to the end of `azd provision` for terraform templates to set up basic auth.
This was not catch during CI because we did add the az and az account sync to test-templates CI.  However, we also need this fix for the GitHub pipeline definition.
We don't need to do this for the Azure DevOps pipeline definition because it still uses az-cli auth and automatically sets the az-account based on the connection.
> sync az and azd for terraform pipeline definition

- templates/common/.devcontainer/Dockerfile/java/Dockerfile
- templates/common/.devcontainer/devcontainer.json/java/terraform/devcontainer.json
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/java-postgresql/.repo/terraform/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/repo.yaml
- templates/todo/projects/python-mongo/.repo/terraform/repo.yaml
- Update todo-java-postgresl-terraform devcontainer
- Fix templates to copy the devcontainer definition explicitly
> fix devcontainer for todo-java-postgresql-terraform

- cli/azd/pkg/input/console.go
Fixing `azd` to check `--no-prompt` global flag when running `azd auth login --use-device-code`.
When the flag is used, waiting for Enter should be skipped.
fix: https://github.com/Azure/azure-dev/issues/2605
> check no-prompt on auth login

- cli/azd/pkg/auth/cloudshell_credential.go
Adds logs to console. Fixes https://github.com/Azure/azure-dev/issues/2410 by adding details to error logs in the console. 
Example error using a contrived audience URL (error messages will vary based on the user's situation): 
This error is expected to only occur in scenarios like those described in https://github.com/Azure/azure-dev/issues/2410 where a browser or machine is not fully permitted by policy to perform certain interactions. In those cases the user may also see an error in their browser indicating that they need to ensure that their device is properly authenticated.
I also explored using a pipeline to log the requests and using `AZURE_SDK_GO_LOGGING=all` and `--debug` to get more detail on a request. The resulting logs did not include the response body which renders the …
> Cloud Shell auth error logging

- cli/azd/cmd/up.go
Adding the follow-up message back to `up`. The up command is supposed to print out the final resource group link, which used to work in much older versions. This was regressed awhile back.
After this change: ![image](https://github.com/Azure/azure-dev/assets/2322434/992947d5-6d22-4544-a5d8-410a498c4c0f)
> up: fix follow-up message not displayed

- templates/todo/projects/csharp-cosmos-sql/README.md
Update readme from mentioning MongoDB to NoSQL
fix: https://github.com/Azure/azure-dev/issues/2527
> update readme for template noSQL

- cli/azd/pkg/output/ux/preview_provision.go
The `OperationTypeIgnore` should be rendered in grey instead of yellow, since no action will be taken on the resource.
Something I noticed while getting content ready for this week's community call.
Before:
After:
Note how the "Skip" color for the Web App resource has changed from yellow to grey.
/cc @Austinauth @savannahostrowski
> Fix coloring for `OperationTypeIgnore` in `--preview`

- .github/workflows/cli-ci.yml
- cli/azd/ci-build.ps1
- cli/azd/ci-test.ps1
- cli/azd/cmd/cmd_help.go
- cli/azd/cmd/cobra_builder.go
- cli/azd/internal/repository/initializer_test.go
- cli/azd/internal/telemetry/storage_test.go
- cli/azd/internal/telemetry/uploader_test.go
- cli/azd/internal/tracing/baggage/baggage.go
- cli/azd/pkg/account/manager.go
- cli/azd/pkg/account/manager_test.go
- cli/azd/pkg/auth/errors.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/prompt/prompter.go
- cli/azd/pkg/tools/azcli/container_registry.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/recording/proxy.go
- cli/azd/test/recording/recording.go
- eng/pipelines/templates/steps/setup-go.yml
- go.mod
- go.sum
This change moves us to use Go 1.21 for building `azd`.
As part of go 1.21, the `maps`, `slices` and `slog` packages, previously in `golang.org/x/exp` have been moved into the standard libary. As part of this change, I've moved to use these versions of the packages instead of using the experimental versions.
However, there were a few places where we were using `maps.Keys`, which was not added to the standard
library. https://go-review.googlesource.com/c/go/+/513715 explains the rationale here, they may want `Keys` to return an iterator, and were not comfortable locking the name at this time. This functionality will be added to the `maps` package in a future release, it seems, likely under a name like `KeysSlice`.  For now, I just kept the existing use of the the experimental package. We …
> Adopt go 1.21

- .gitignore
- cli/azd/.vscode/cspell.yaml
- cli/azd/internal/tracing/fields/fields.go
- cli/azd/internal/tracing/resource/machine_id.go
- cli/azd/internal/tracing/resource/resource.go
- cli/azd/main.go
- cli/azd/pkg/experimentation/assignment.go
- cli/azd/pkg/experimentation/assignment_test.go
- cli/azd/pkg/experimentation/client.go
- cli/azd/pkg/experimentation/client_test.go
- cli/azd/pkg/experimentation/doc.go
- cli/azd/test/functional/experiment_test.go
This change adds support for using the Azure Experimentation service to compute assignment information, which will be used to allow us to do experimental A/B testing in `azd`.  This change introduces the machinery to fetch an assignment, based on the machine ID of the current machine.  This assignment contains information about what experiments have been enabled as well as an assignment context, which needs to be included in the telemetry events that we emit.  This assignment context allows us to compute what experiments the user is running against, which we use to understand if the experiment is a success or not.
There is not an existing SDK for the Azure Experimentation service for Golang.  The team did a small spike of one, which I had intended to vendor here as is, but I instead made …
> Assignment for experimentation

- cli/azd/pkg/azdo/pipeline.go
This is required for migrating azdo-pipelines to use `azd auth login` the same way as github actions.
Before this change, azdo-pipelines were relying on `az cli` task with a `service-connection` on azdo to authenticate.
The `service-connection` will still be created, as it will be used by `terraform` pipeline (still req az-cli).
> set AZURE_CREDENTIALS on pipeline for azd auth

- cli/azd/pkg/experimentation/assignment_test.go
The properties included in the assignment request are built by walking a map of key value pairs. In go, the order of enumeration of a map is non determinsitc, so we need to relax the check from strict equality to just elements match in a test.
> Fix flakiness in `TestParametersAreSent`

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/auth/cache.go
- cli/azd/pkg/auth/cache_test.go
When retrieving cache entries, automatically upgrade cache entries that were saved in msal cache v1.0 format to v1.1 format to avoid stale cache entries causing random auth failures.
Related to https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/453
Fixes #2659
> Add msal cache 1.0 -> 1.1 upgrade 

- cli/azd/cmd/templates.go
- cli/azd/pkg/templates/awesome_source_test.go
- cli/azd/pkg/templates/source_manager.go
- cli/azd/pkg/templates/source_manager_test.go
- cli/azd/pkg/templates/template_manager_test.go
Adds `awesome-azd` as the default template source when template sources has not been defined.
- When `template.sources` is not defined in `config.json` => Add `awesome-azd`
- When `template.sources` is empty => Empty template sources
`template.sources` will not be defined, `awesome-azd` will automatically get added and saved
User has used `azd template source remove <key>` for all registered template sources.  New sources will need to be manually registered for anything to show up in `azd template list` or `azd init` experience.
> [!NOTE] 
> `Minimal` will still show in `azd init` experience with empty template sources.
Fallback to 1st run experience above where template sources have not been defined.
> Adds awesome azd as default template source when not defined

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/project_config_test.go
Noticed that `buildArgs` was not actually working when setting the args on `azure.yaml`
This quick change makes it work as expected.
> fix using build args from docker

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/tracing/events/events.go
- cli/azd/pkg/alpha/alpha_features.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/tools/docker/docker.go
- cli/azd/pkg/tools/pack/pack.go
- cli/azd/pkg/tools/pack/pack_test.go
- cli/azd/resources/alpha_features.yaml
- cli/azd/test/mocks/mockzip/mockzip.go
Buildpacks allows source to container image transformation without Dockerfiles. When a `Dockerfile` isn't found in `azure.yaml`, and the alpha feature `buildpacks` isn't enabled, `azd` will use [pack](https://buildpacks.io/docs/tools/pack/) CLI to invoke the dockerization build.
Limited build customization is provided with this initial release. The only allowed customization is the builder image to use.
Closes #2677
> Add buildpacks (`pack` cli) integration

- templates/common/infra/bicep/core/host/appservice.bicep
removing warnings from building bicep:
> removing not existing property to avoid warning during compile

- cli/azd/cmd/init.go
- cli/azd/cmd/util.go
- cli/azd/cmd/util_test.go
Refactor `init.go` to allow the upcoming feature work for fingerprinting to land more cleanly.
Also, environment name prompt now provides examples instead of a default value.
> Refactor `init.go`

- templates/common/infra/bicep/core/storage/storage-account.bicep
See AZR rule https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Storage.SecureTransfer/
Removes a false-positive for rule analyser security issues on the storage account (true is already the default value from 2019-04-01)
> Default supportsHttpsTrafficOnly in storage accounts to true

- cli/azd/CHANGELOG.md
- eng/pipelines/repoman.yml
- eng/pipelines/template-tests.yml
- eng/pipelines/templates/jobs/run-template-tests.yml
- eng/pipelines/templates/steps/template-test-generate-jobs.yml
Since `azd template test` now include all Awesome AZD templates by default we want to filter the testing templates to only the `Azure-Samples/todo-*` templates.
> Filters Todo templates for template testing matrix

- cli/azd/cmd/middleware/experimentation.go
- cli/azd/cmd/root.go
- cli/azd/main.go
- cli/azd/pkg/alpha/alpha_feature_manager.go
Allow experimentation rollouts to control the default alpha feature enablement.
- If a feature flag for `alpha_<featureId>` is set to true, the alpha feature is enabled by default. User config takes precedence over the default.
Also, moving the experimentation initialization to later in app initialization so that initialization only occurs when a command is fully parsed. Error commands should not trigger the flow.
Partially addresses #1260
> Enable experimentation-alpha integration

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
Update the ordering function for deployments to have a DESC slice where the first deployment will be the most recent on time, instead of the oldest one.
> Sort deployments desc to get the most recent deployment instead of the oldest

- cli/azd/cmd/deploy.go
- cli/azd/cmd/package.go
- cli/azd/cmd/testdata/TestUsage-azd-package.snap
- cli/azd/pkg/project/project_utils.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
- cli/azd/pkg/project/service_models.go
- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_functionapp.go
- cli/azd/test/functional/package_test.go
Resolves #2543
Adds ability for a user to specify a `--output-path` param to the `azd package` command to control the output location of file based packages.
For top level commands it would be expected that user specify a absolute or relative folder path.  If the path does not exist azd will create it automatically.
`azd package --output-path ./dist`
`azd package api --output-path ./dist/api-app.zip`
Package artifact naming convention now follows the format of `{project_name}-{service_name}-azddeploy-{timestamp}.zip` to provide more information to the user to more easily find the correct generated artifact and distinguish them from one another.
When running AZD in CI a common scenario would be to package service artifacts into a well known location that can then be referenced and stored …
> azd package support for user specified output paths

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/bicep/bicep_test.go
This matches the behavior of the `az` CLI, which uses this same logic. When we orginally implemented this, `az` did not have this special case, it was added later.
Fixes #2683
> Prefer glibc based Bicep when both musl and glibc are installed

- cli/azd/test/functional/package_test.go
Fixes azd package tests that fail when running in parallel.
Based on recent temp file naming for package command there is an opportunity that if multiple package commands are run at the same time that it can generate the same package name which causes the tests to clash.
This case doesn't exist in user scenarios since the temp file name is a combination of project name, service name and current unix timestamp.
> Fixes azd package tests that fail when running in parallel

- templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep
Suggested from @kjaymiller : 4.2 is the most recent version that is currently supported, so its better to use 4.2 than 4.0. We are using 4.2 successful in our cookiecutter-relecloud templates.
> Update cosmos-account.bicep to 4.2

- templates/common/.azdo/pipelines/bicep/azure-dev.yml
- templates/common/.azdo/pipelines/java/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/java/azure-dev.yml
- templates/todo/projects/csharp-cosmos-sql/README.md
- templates/todo/projects/csharp-sql-swa-func/README.md
- templates/todo/projects/csharp-sql/README.md
- templates/todo/projects/java-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo-aca/README.md
- templates/todo/projects/java-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo/README.md
- templates/todo/projects/java-postgresql/.repo/terraform/repo.yaml
- templates/todo/projects/java-postgresql/README.md
- templates/todo/projects/nodejs-mongo-aca/README.md
- templates/todo/projects/nodejs-mongo-aks/README.md
- templates/todo/projects/nodejs-mongo-swa-func/README.md
- templates/todo/projects/nodejs-mongo/.repo/bicep/README.md
- templates/todo/projects/nodejs-mongo/.repo/terraform/README.md
- templates/todo/projects/python-mongo-aca/README.md
- templates/todo/projects/python-mongo-swa-func/README.md
- templates/todo/projects/python-mongo/.repo/bicep/README.md
- templates/todo/projects/python-mongo/.repo/terraform/README.md
Fix #2642 
Update todo templates to consume Azure DevOps Task (setup-azd)
@rajeshkamal5050 , @hemarina and @vhvb1989 for notification
> Add Azure DevOps Task (setup-azd) to todo templates

- templates/todo/api/js/package-lock.json
Partial #2625 
This PR fixes the build break which appears in the nodejs projects. The version of `v8-compile-cache` used in `package-lock.json` is not compatible with variations in architecture on the same machine. The later version does support. 
This was tested with `Azure-Samples/todo-nodejs-*` templates and works properly. 
The scenario in question: 
1. Install `azd` on an Apple Silicon Mac in x86_64 mode and init a template 
2. Run `azd package` (or some superset command) on the template
3. Upgrade `azd` to a later version using ARM64 binary instead of x86_64 binary
4. Run `azd package` (or some superset command) on the template from step 2
In the past this failed with a segfault during the `npm run lint` step in the `api`.
> Upgrade v8-compile-cache

- schemas/v1.0/azure.yaml.json
The buildArgs field is not an alpha feature and it is mentioned on changelog.
However, it is only available from the alpha schema.
This PR is updating the 1.0 schema with to support this fieldy
> update azd schema with build args

- cli/azd/.vscode/launch.json
re-ordering debugging options (as suggested by @Petermarcu ) .
Having `Debug azd cli` with prompt for args with `"${input:cliArgs}"` provides the simplest approach for contributors to run azd with debugger.
Moving the `attach` strategy to the second place as it requires some special considerations when contributors are using Linux (like codespaces or WSL).
Adding one last manual configuration for launching azd where contributors can manually define all the debuging settings.
> use Debug azd cli as first alternative

- cli/azd/CHANGELOG.md
- cli/azd/docs/feature-stages.md
- cli/azd/resources/alpha_features.yaml
- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
- templates/common/.azdo/pipelines/terraform/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/java/azure-dev.yml
- templates/common/.github/workflows/java/terraform/azure-dev.yml
- templates/common/.github/workflows/nodejs/terraform/azure-dev.yml
- templates/common/.github/workflows/terraform/azure-dev.yml
- templates/starter/terraform/README.md
- templates/todo/projects/java-postgresql/README.md
- templates/todo/projects/nodejs-mongo/.repo/terraform/README.md
- templates/todo/projects/python-mongo/.repo/terraform/README.md
fix: https://github.com/Azure/azure-dev/issues/2035
> make terraform non alpha

- cli/azd/cmd/hooks.go
- cli/azd/cmd/middleware/hooks.go
- cli/azd/cmd/root.go
- cli/azd/cmd/testdata/TestUsage-azd-hooks-run.snap
- cli/azd/cmd/testdata/TestUsage-azd-hooks.snap
- cli/azd/cmd/testdata/TestUsage-azd.snap
- cli/azd/pkg/ext/hooks_runner.go
- cli/azd/pkg/ext/hooks_runner_test.go
- cli/azd/pkg/ext/models.go
- cli/azd/pkg/tools/bash/bash.go
- cli/azd/pkg/tools/bash/bash_test.go
- cli/azd/pkg/tools/powershell/powershell.go
- cli/azd/pkg/tools/powershell/powershell_test.go
- cli/azd/pkg/tools/script.go
Adds `azd hooks run <name>` command to help develop, test and run hooks for an azd project & services.
Resolves #1642 
- An easy way for developers to test and troubleshoot their azd hook scripts without the overhead of waiting for azd commands to run
- Developers can develop a suite of hooks/scripts to support their day to day inner-loop development
- Call into other hook scripts from azd hook lifecycle events
Dev wants to validate their deployment to run a series of UX smoke test across their services
- Dev creates a `vaildate` hook in each service that they want to test. These tests could run playwright or some other UX test framework
- Dev adds a `postdeploy` hook that calls `azd hooks run validate`
- This ensures that the `validate` hook would run for each service after deployment …
> Add `azd hooks run` command for testing `azd` hooks

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
This PR updates the Azure-dev devcontainer for a better experience to contributors.
- The golangci-lint cli is automatically installed after running the devcontainer. This ensures to run the latest version all the time.
- Java, Node, Python and .Net are all integrated to the container. This makes it easier to a contributor to run any template.
- gh, terraform, az and kubectl cli are included as well.
After this PR, a contributor can create a new Codespace or WSL instance, cd to `cli/azd` and start hacking. For example:
- Run azd with debuger.
- Run linter `golangci-lint run ./...` 
- Run and deploy any template (languages already installed). // might require some logging-in
> contributors devcontainer

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
As I was doing some more validations for `provision-state`, I found that azd was using the state from the last deployment even if the deployment was failed.
This change makes sure to ignore the state if the last deployment was failed.
> make state to be valid only when deployment did not fail

- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
Continuation of: https://github.com/Azure/azure-dev/pull/2793
As I was testing the new provision-state with `.bicepparam` files, I also used some user-defined types and got an error when using the types for the outputs.
This PR applies the same patch to outputs as we did before for input parameters.
The only difference is that for `outputs` we only need to resolve the `type`, while keeping the value and metadata.
This PR also adds a few more update to the input parameters:
- Combining `metadata` from user-defined type and parameter. This is required to allow folks to use `azd` metadata from user-defined types, like
```bicep
@metadata({
azd: "location"
})
type userDefinedLocation = 'eastus' | 'centralus'
param someLocationA userDefinedLocation
param someLocationB userDefinedLocation
```
In …
> handle user-defined type as outputs

- cli/azd/cmd/hooks.go
- cli/azd/pkg/ext/hooks_runner.go
- cli/azd/pkg/ext/models.go
- cli/azd/pkg/input/console.go
Updates all hook output to use the new previewer when not running in interactive mode.
Fixes #2213 
**Project level command hooks:**
**Service level command hooks:**
> Updates hook output to use previewer

- cli/azd/pkg/azsdk/storage/storage_blob_client_test.go
Resolves issue when running test in `live` mode where test fails do to `nil` pointer accessing the `httpClient` uses for test.
> Fixes failing storage client crud test

- cli/azd/pkg/azsdk/storage/storage_blob_client_test.go
Skipping test due to intermittent test failures while we troubleshoot.
Skips `Test_StorageBlobClient_Crud` test.
> Skips failing storage account crud test

- cli/azd/internal/repository/detect_confirm_test.go
- cli/azd/internal/repository/infra_confirm_test.go
Fix spurious test output in CI.
In CI, we see these tests reported as FAILED in the log, but not actually failing. The reason is that `gotestsum` is unable to find the actual "PASS" event emitted, but `go test` does succeed correctly. We have trailing output that isn't newline terminated (while waiting for stdin), which results in the behavior.
Example:
```
=== FAIL: cli/azd/internal/repository TestInitializer_infraSpecFromDetect/api_and_web_with_db (unknown)
Input the name of the app database (PostgreSQL) --- PASS: TestInitializer_infraSpecFromDetect (0.00s)
```
> Fix spurious test output

- ext/vscode/.vscode/cspell-dictionary.txt
- ext/vscode/package.nls.json
- ext/vscode/src/commands/devCenterMode.ts
@wbreza FYI
Instead of the old way we now set dev center mode with
`azd config set platform.type devcenter`
and unset with
`azd config unset platform.type`
> React to changes to DevCenterMode

- cli/azd/pkg/environment/manager.go
- cli/azd/pkg/environment/manager_test.go
Resolves #2852, #2797
Fixes the issue where `DotEnvPath` was unintentionally removed from the `azd env list --output json`
> Fixes issue with running Tasks that relay on environment configuration path

- cli/azd/cmd/templates.go
- cli/azd/pkg/templates/path.go
- cli/azd/pkg/templates/template.go
The command `azd template list` gt the feature of clickable repository paths in release 1.4.2. This PR brings this feature also to the command `azd template show xyz` transfering the logic implemented in #2845 to the show command. 
To avoid code duplication the formatting logic is trenafered to the `path.go` file which looks like a good fit for this kind of logic. 
The sequence of the output of the `template show` command was not changed. If this should be aligned with the `template list` command, just comment and I add a commit
> feat: clickable url for azd template show

- cli/azd/cmd/env.go
Fix regression on `azd env get-values` after https://github.com/Azure/azure-dev/pull/2840/files
Root cause:
azd is checking if there is a default environment and fail when that's false. But when that is true, azd is using the default environment name and not honoring if there is a flag setting the name of the environment.
This fix makes azd to honor the name of the environment from a flag, when it is provided.
> use env-flag as default to override

- .vscode/cspell.global.yaml
- cli/azd/test/recording/recording.go
- cli/installer/choco/azd.nuspec
- cli/installer/install-azd.ps1
- cli/installer/install-azd.sh
- cli/installer/test-installer-containers.ps1
- cli/installer/test-pwsh-xplat-install.ps1
- cli/installer/test-win-install.ps1
- ext/azuredevops/setupAzd/index.ts
- ext/azuredevops/setupAzd/task.json
- ext/azuredevops/vss-extension.json
Migrate to new CDN 
@vhvb1989 -- This also includes a change to the DevOps task which will need a new version released. Should I update the package.json?
> CDN migration

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/publish-cli.yml
- eng/scripts/Wait-ChocoPackage.ps1
- eng/scripts/Wait-WinGetPackage.ps1
Temporary fix for #2864. The long term fix here should be [azd upgrade](https://github.com/Azure/azure-dev/issues/2003).
This adds a stage which runs after release of the CLI. The stage checks for expected versions in winget and choco. If the expected versions aren't found the job fails and can be re-run. If the expected versions are found then `version.txt` is updated in the CDN. To complete the release this stage must run successfully.
Example test of the job when the version is not available (failure expected): https://dev.azure.com/azure-sdk/playground/_build/results?buildId=3173181&view=results
Example test of the job when the version is available: https://dev.azure.com/azure-sdk/playground/_build/results?buildId=3173178&view=results
Release steps:
Here's an example of the relevant …
> Update version.txt in a separate stage

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
Fixes #2895 & #1910
When `main.parameters.json` references an empty or not set value expression `azd` will prompt the user for a value unless the parameter also defines a default value.
The only edge case scenario I could think of where this would be undesired is if the bicep param does define a non-empty default string value but the user explicitly wants to specify/override with an empty string.
bicep param | main.paramters.json | env expression | azd result | Suggestion |
| --- | --- | --- | --- | --- |
| No Default | Not defined | N/A | Prompt user for value | N/A |
| No Default | ${ENV_VAR} | Not Defined | Prompt user for value | N/A |
| No Default | ${VAR_1}-${VAR_2} | Any env var not defined | No prompt, rely on bicep validation | User should specify @minlengh in bicep
| No Default …
> Allows prompting for for bicep parameters that reference empty or not set environment variables

- cli/azd/internal/scaffold/funcs.go
- cli/azd/internal/scaffold/scaffold.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/resources/scaffold/templates/host-containerapp.bicept
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/main.parameters.jsont
- cli/azd/resources/scaffold/templates/next-steps.mdt
Allow app settings to be configured in `main.parameters.json` for simplified init apps.
To this end, the bicep files in simplified init apps has been updated to allow flowing of any required app settings to the container app host, which enables configuration to be done simply as the following:
**main.parameters.json**
```json
"apiDefinition": {
"value": {
"settings": [
{
"name": "AZURE_ENV_NAME",
"value": "${AZURE_ENV_NAME}",
},
{
"name": "OPENAI_API_KEY",
"value": "${OPENAI_API_KEY}",
"secret": true
}
]
}
}
```
To ease discovery, the generated `main.parameters.json` includes placeholder values and documentation. `next-steps.md` has also been updated to include the information.
Fixes #2739
> Allow app settings to be configured in `main.parameters.json` for simplified init apps

- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/pkg/project/framework_service_docker.go
When a containerized static frontend (with no Dockerfile) specifies an output directory `dist`, azd will configure Oryx builder to serve static content from the output directory using nginx.
The azure.yaml generation logic in simplified init is updated to include better `dist` defaults for specific web frameworks, supporting angular, react, and vue at minimum.
Finally, Oryx has surfaced `ORYX_RUNTIME_PORT` as a configuration knob. azd will always set this to port 80 for consistency and avoid dealing with language-specific ports.
Fixes #2750
> Add static frontend support for azd buildpacks

- cli/azd/appdetect/main.go
- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/appdetect_test.go
- cli/azd/internal/appdetect/dotnet.go
- cli/azd/internal/appdetect/java.go
- cli/azd/internal/appdetect/javascript.go
- cli/azd/internal/appdetect/python.go
- cli/azd/internal/repository/app_init.go
Detection logic may want to preform operations which take a context, so let's introduce one in the API and pass a context along.
> Add `Context` parameter to `DetectProject`

- cli/azd/pkg/azdo/azdo.go
- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/azdo/service_connection.go
- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/azdo_provider_test.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/github_provider_test.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/pipeline_manager_test.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/tools/azcli/ad.go
- cli/azd/pkg/tools/azcli/ad_test.go
Fixes #2883 
Updates pipeline config to only set client credential app passwords when `--auth-type client-credentials` is explicitly specified.
TODO:
> Updates for pipeline config credential flows

- cli/azd/pkg/devcenter/prompter.go
- cli/azd/pkg/devcenter/prompter_test.go
When prompting for devcenter configuration values validate that prompts have available values otherwise throw error.
> Verifies that devcenter prompts have values otherwise return error

- cli/azd/cmd/container.go
- cli/azd/cmd/root.go
- cli/azd/pkg/devcenter/prompter_test.go
- cli/azd/pkg/platform/platform.go
- cli/azd/pkg/platform/platform_test.go
Relaxes platform configuration panics when an invalid platform configuration is detected.
If a platform configuration issue is detected the following warning will be displayed before the output of any command.
> Relaxes platform configuration issues

- cli/azd/pkg/devcenter/template_source.go
- cli/azd/pkg/devcenter/template_source_test.go
Fixes an issue where a template with multiple allowed values was not showing each value as an expanded template choice.
> DevCenter Template Source: Prefer list of allowed values vs default param values

- cli/azd/cmd/build.go
- cli/azd/cmd/container.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/cmd/hooks.go
- cli/azd/cmd/middleware/hooks.go
- cli/azd/cmd/middleware/hooks_test.go
- cli/azd/cmd/package.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/show.go
- cli/azd/cmd/up.go
- cli/azd/cmd/util.go
- cli/azd/pkg/devcentersdk/developer_client_test.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/pipeline_manager_test.go
- cli/azd/pkg/project/importer.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/project_manager.go
- cli/azd/pkg/project/project_test.go
- cli/azd/test/functional/telemetry_test.go
We are going to be adding support for services to contribute auto-generated infrastructure as well as sub services in a future set of changes.
This means that direct access to both the `.Infra` and `.Services` property of a `*ProjectConfig` may be incomplete. To address this, a new (somewhat poorly named) `ImportManager` is introduced. The `ImportManager` is tasked with getting the complete set of services or a `provisioning.Options` for the infrastructure.
For now, we have no Importers, so this change is a no-op. However, it lays the groundwork for future changes and will make follow on commits easier to review.
Longer term, we should look at not directly exporting `Infra` and `Services` from the `ProjectConfig` and force other packages to consume these via the `ImportManager`. For now, …
> Add `project.ImportManager` infrastructure

- cli/azd/cmd/init.go
- cli/azd/internal/repository/app_init.go
This will allow it to be modified as part of application initialization. This feature is not used yet, but will be in some upcoming PRs, so deal with the ceremoy of the change here.
> Have `(*initAction).initializeEnv` return the created env

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/container.go
- cli/azd/cmd/package.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/framework_service_dotnet.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/pkg/tools/dotnet/dotnet.go
This adds support for a new (presently internal) service target, which is a containerized dotnet application, running on ACA. There are two major differences between this target type and the existing container app type:
1. Instead of using `docker build` and `docker push` to build and push the container, we use `dotnet package` and the new container building support that is in .NET 7 (and being improved in .NET 8) to build and push the ccontainer. This experience is like Oryx in that it does not require a Dockerfile.
2. We use a deployment strategy for the container that looks more like AKS. We expect a `containerApp.tmpl.yaml` file in a `manifests` folder in the root of the service. We use go text templating (as we do in AKS) and then deploy this yaml in the same manner as `az …
> Add `project.DotNetContainerAppTarget`

- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/tools/pack/pack.go
Add a nil-check to handle when a python project is undetected. In this case, the python project will still be attempted to be built by the Oryx builder. This would likely result in a different, but friendlier error message and avoids the panic.
With this change, better error messaging is also provided when building a containerized project fails due to no Dockerfile and failed detection.
Fixes #2961
> Handle if project is undetected

- cli/azd/cmd/package.go
- cli/azd/cmd/testdata/TestUsage-azd-package.snap
This PR contains a minor fix for the output of the metadata of `azd package --help`. It changes the description for the `--all` option from `Deploys` to `Packages`.
Remark: The footer already contained the right description.
> docs: fix --all option description for azd package command

- cli/azd/resources/apphost/templates/resources.bicept
Instead of having `azd` provision the container, the consumer of the blob storage account will hanlde this at runtime.
> Don't create blob storage containers

- cli/azd/pkg/devcenter/environment_store.go
- cli/azd/pkg/devcenter/environment_store_test.go
**Issues resolved:**
1. Prompts for configuration during `azd env select` if dev center configuration is missing (dev center name, project & env definition)
2. Persist ADE provisioning parameters from previous deployment to `azd` env config
> ADE: Persist environment provisioning parameters when selecting environment

- cli/azd/cmd/deploy.go
- cli/azd/cmd/testdata/TestUsage-azd-up.snap
- cli/azd/cmd/up.go
Adds the following minor updates:
Updates the help description to make it clear that current implementation of `azd up` calls package, provision & deploy.
Displays skipped services in calls to `azd deploy <service-name>` when a service name is specified. 
This change brings `azd deploy` inline with conventions used in other command that target multiple services including restore, build & package.
> fix: Updates `azd up` inline docs and `azd deploy` output

- cli/azd/cmd/show.go
> use spinner for azd show

- cli/azd/pkg/project/service_config_test.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/tools/azcli/managed_clusters.go
- cli/azd/pkg/tools/kubectl/kube_config.go
- cli/azd/pkg/tools/kubectl/kube_config_test.go
- cli/azd/pkg/tools/kubectl/kubectl.go
- cli/azd/pkg/tools/kubectl/models.go
- cli/azd/pkg/tools/kubectl/util.go
This change builds on smaller set of changes from other open PRs:
- #2455 
- #2464
Additionally this adds support to override behavior of the `KUBECONFIG` environment variable.
When provisioning is complete `azd` will automatically attempt to authenticate to the cluster with local admin credentials.  A new `KUBECONFIG` is created with the same name as the AKS cluster name and merged into the default `KUBECONFIG`.  
The default context within the `KUBECONFIG` now also includes the default project/service namespace.
> **Note**
> Namespaces can be set within resource yaml definitions.  If not specified `azd` will use the default service namespace. Services can specify namespace name in the `k8s` section of the service yaml.  
> 
> If no namespace has been set for the service the `azd` …
> AKS Service Target - Overriding KUBECONFIG handling

- templates/common/infra/bicep/core/ai/cognitiveservices.bicep
This PR adds networkAcls to cognitiveservices.bicep. It defaults to "Allow" which is not the most secure option but is needed for OpenAI deployments (https://github.com/Azure-Samples/azure-search-openai-demo/issues/133), Azure AI studio usage, etc.
It also permits passing in IPs to specifically allow, which can be used in conjunction with a VNet (as demonstrated in this PR: https://github.com/Azure-Samples/azure-search-openai-demo/pull/864/files#diff-8a64001dc63e4053382af7bbd6519e074e3a637a9e0a50b5b6e8ca136b4224ce), for heightened security.
> Update cognitiveservices.bicep with networkAcls

- cli/installer/windows/azd.wxs
Mitigate [winget issue](https://github.com/microsoft/winget-cli/issues/3825) with MSI upgrade by removing default display of the custom uninstall UI. 
Users of 1.5.0 (N) upgrading to the next version (N+1) using winget will still have to use the uninstall/install workaround. However, once the N+1 version is installed, subsequent versions will upgrade properly. 
@heaths -- Please have a look. 
1. Create MSI with hypothetical version 1.6.0 
2. Create MSI with hypothetical version 1.7.0 
3. Create winget manifests for MSIs 
4. `winget install` 1.6.0 from manifest
5. `winget upgrade` to 1.7.0 from manifest
Upgrades work as expected. Uninstallation from `winget uninstall Microsoft.Azd` or ARP dialog does not result in display of warning. Running uninstall with `/qf` does display UI.
> Mitigate winget upgrade issue

- templates/common/infra/bicep/core/host/appservice.bicep
Honor settings from `appInsightsName`, `keyVaultName`, and apply default app settings even when `appSettings` is empty.
Fixes #3025
> core bicep: apply appsettings by default

- cli/azd/pkg/apphost/generate.go
In addition to setting `allowInscure` for HTTP2 (i.e. gRPC) services, we now also set this to true by default for any service that is not publicly exposed.
This allows inscure traffic to internal nodes, to allow requests to things like `http://backend` from one internal service to another.
Fixes #3201
> aspire: Set `allowInsecure` to true for internal services

- cli/azd/pkg/apphost/service_ingress_configurer.go
- cli/azd/pkg/azdo/pipeline.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/environment/environment_test.go
- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/project/dotnet_importer.go
fix: https://github.com/Azure/azure-dev/issues/3027
Implementing a bootstrapping strategy to azd-environment creation. By using env-var `AZURE_INITIAL_ENVIRONMENT_CONFIG`, azd would parse the value (when it exists) when a new environment is created to define the initial env-config (instead of an empty config).
This strategy enables `azd pipeline config` to create a string out of the env-config and set AZURE_INITIAL_ENVIRONMENT_CONFIG as a pipeline secret.  
A pipeline definition can use the secret as a way to bootstrap the env-config.
As a side effect, the settings persisted in env-config at the moment of running `azd pipeline config` would be restored during CI, fixing the aspire pipelines use case and also the bicep-input saved-params.
> Support Aspire journey for pipeline config

- cli/azd/cmd/init.go
- cli/azd/test/functional/init_test.go
This restores the init behavior prior to 1.4.0 regression. `azd init` simply considers the current working directory when initializing, without attempting to resolve a parent directory project which is counterintuitive.
Fixes #2946
> init: restore old behavior, do not consider parent projects

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/input/console.go
Handle interrupt to unhide terminal cursor from a potentially active spinner
#2194
> console: handle interrupt to unhide cursor

- cli/azd/resources/apphost/templates/resources.bicept
Our intention is to use Azure RBAC to secure access to the container registry, and the exchange our AAD token for a time limited access token that we use to log into the registry. That has worked for some users, but others have run into issues like what we see in #2980
While we're still trying to root cause the actual issue, we have discovered that if the admin account is enabled, the end to end seems to work.
This change enables the admin account to allow `azd` to fall back to that when the token exchange doesn't work.
Contributes To: #2980
> aspire: Enable Admin User on Container Registry

- cli/azd/pkg/tools/dotnet/dotnet.go
When publishing an .NET Application, you have two choices as to how to reference the .NET Runtime.  You can either publish as a framework dependent project, where your app will use a pre-deployed copy the .NET Runtime, or self contained, where your app will care the .NET Framework for your target platform with it.
Framework dependent projects are the default, because they are smaller (you don't need to bring along an entire .NET runtime with your application).
In Aspire, we were publishing as self contained because we needed the latest and greatest version of the .NET Runtime, since there were some breaking changes that impacted Aspire and it depended on, and the public base container images on MCR had `rc2` bits.
Now that .NET 8 has shipped, this is no longer a problem, and we can …
> aspire: Publish projects as framework dependent

- cli/azd/pkg/apphost/generate.go
Based on https://github.com/dotnet/aspire/issues/693, this should be a required property. However, we should still avoid a panic and provide a better error message.
Related to: #3070
> aspire: Better error msg for missing containerPort in binding

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/container.go
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/apphost/service_ingress_configurer.go
- cli/azd/pkg/apphost/testdata/.gitattributes
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-main.parameters.json.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-docker.json
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_noop.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
As part of Preview 2, Aspire is adding support for a new resource, `dockerfile.v0`. This represents an image that should be built (from a Dockerfile) and deployed.
Consider the following AppHost:
```csharp
var builder = DistributedApplication.CreateBuilder(args);
builder.AddNodeApp("nodeapp", "../NodeApp/index.js")
.WithServiceBinding(3000, scheme: "http", env: "PORT")
.AsDockerfileInManifest();
builder.Build().Run();
```
The resulting manifest looks like this:
```json
{
"resources": {
"nodeapp": {
"type": "dockerfile.v0",
"path": "../NodeApp/Dockerfile",
"context": "../NodeApp",
"env": {
"NODE_ENV": "development",
"PORT": "{nodeapp.bindings.http.port}"
},
"bindings": {
"http": {
"scheme": "http",
"protocol": "tcp",
"transport": "http",
"containerPort": 3000
}
}
}
}
}
```
From a high …
> aspire: Add support for `dockerfile.v0`

- cli/azd/pkg/azdo/pipeline.go
- templates/common/.azdo/pipelines/bicep/azure-dev.yml
- templates/common/.azdo/pipelines/java/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/java/azure-dev.yml
fix: https://github.com/Azure/azure-dev/issues/3088
The changes here are to restore the old behavior on azdo pipelines using a service-connection and delegating auth to az.
The reason is to be idiomatic to azdo, where a service connection is used instead of setting a secret with a credential (like in gh-action).
In the future, if this https://github.com/Azure/azure-dev/issues/3093 gets implemented, we could remove the az auth delegation.
> Update ado pipeline definition to use service-connection

- cli/azd/pkg/apphost/eval.go
- cli/azd/pkg/apphost/eval_test.go
- cli/azd/pkg/apphost/generate.go
When we started the Aspire work, we thought we might only support simple binding expressions with a single reference, e.g.: `"{api.bindings.http.url}"`. Over time, this allow grew to allow literals (e.g.: `"true"`). In Preview 2, the manifests now supports multiple replacements in a single expression, to support things like connection strings where you need multiple parts:
`"Host={api.bindings.tcp.host},Port={api.bindings.tcp.port}"`
To prepare for this, I've split the string evaluation logic from the value resolution logic and then enhanced the string evaluation logic to support more complex strings, while adding some tests to ensure things behave as expected.
> aspire: Improve binding expression evaluator

- cli/azd/pkg/project/framework_service_docker.go
Upgrade dotnet base images to be based on bullseye-20131107.2 which is the current stable version and supports .NET 8.
Fixes https://github.com/Azure/azure-dev/issues/3108
> buildpacks: Update dotnet base image to bullseye

- cli/azd/pkg/account/subscriptions_manager.go
This spinner used to be ephemeral, an internal refactor had changed it to non-ephemeral. This change restores the old behavior which has been signed off by PM and designer.
Before:
After:
> make loading locations ephemeral

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/appdetect_test.go
- cli/azd/internal/appdetect/dotnet.go
- cli/azd/internal/repository/app_init.go
- cli/azd/pkg/tools/dotnet/dotnet.go
This change relaxes the project detection logic during `azd init` to warn for projects unreferenced by the app host.
With this change, for dotnet app detection, we also exclude wasm based projects such as BlazorAssembly as hostable. These projects can be referenced by a Blazor server and act as a library.
Fixes #3024
> aspire: Do not error when other projects present

- templates/common/infra/bicep/core/host/appservice.bicep
Reintroduce a `dependsOn` ordering that is required to avoid race conditions with updating `Microsoft.Web/sites/config` within the same deployment.
> bicep core: Serialize updates for config-appsettings and config-logs

- cli/azd/cmd/provision.go
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-docker.json
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/password/generator.go
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/importer.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/resources/apphost/templates/main.bicept
- cli/azd/resources/apphost/templates/resources.bicept
This change adds supports for `inputs` which is a new (optional) property on resources in the Aspire manifest. These inputs represent values that deployment tools like `azd` need to provide "somehow".
For our initial support, we support string inputs which contain metadata on how to generate a default value, based on a minumum random length. Aspire uses this today to model passwords for cases like `AddMySqlContainer()` where a deployment tool needs to provide a password for the root user.
Consider the following AppHost manifest:
```json
{
"resources": {
"demoapp": {
"type": "project.v0",
"path": "../AspireContainers.DemoApp/AspireContainers.DemoApp.csproj",
"env": {
"ConnectionStrings__MySql": "{mysqlabstract.connectionString}"
},
"bindings": {
"http": {
"scheme": "http",
"protocol": …
```
> aspire: Support inputs and improve container.v0 support

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/testdata/TestAspireStorageGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireStorageGeneration-main.parameters.json.snap
- cli/azd/pkg/apphost/testdata/TestAspireStorageGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-storage.json
azd was parsing manifest into unordered map, and the manifest->azure resource translation had a bug that would present itself with the ordering:
If the ordering was:
StorageAccount
Blob
Queue
This would work fine.
But if the ordering was:
Queue
StorageAccount (resets whatever was added by Queue)
Blob
Would lead to missing queue output
fix: https://github.com/Azure/azure-dev/issues/3137
> [NetAspire] Fix storage overriding after reading manifest

- templates/common/.devcontainer/devcontainer.json/csharp/func/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/nodejs/func/devcontainer.json
- templates/common/.devcontainer/devcontainer.json/python/func/devcontainer.json
Increase resiliency of devcontainer install scripts for function tools:
- Install under `/opt/microsoft/azure-function-core-tools`
- Symbolic link just `func` instead of installing binaries into `/usr/bin`
Tested `func` in devcontainer install:
> templates: Increase resiliency of devcontainer install for function tools 

- templates/todo/api/python/requirements.txt
- templates/todo/common/infra/bicep/app/api-functions-python.bicep
Fixes python function app failing to start due to `opentelemetry-sdk` library incompatibility with the runtime environment. Also, bumping function host runtime (missing change from #1463).
> py-func: upgrade packages and function-host runtime

- cli/azd/pkg/apphost/generate.go
Might not an issue anymore on latest go, but still think it is worth it to have it fixed.
> Fix memory aliasing

- .devcontainer/devcontainer.json
- cli/azd/.vscode/extensions.json
- cli/azd/.vscode/settings.json
A little syntax highlighting for go-templates is better than nothing:
This PR:
- Adds the vscode extension as part of devcontainer
- Adds the vscode extension as part of project config
- Creates file association for go-template to `.bicept`
> association for .bicept as go-template and extension for syntax

- .devcontainer/devcontainer.json
- cli/azd/.vscode/extensions.json
- cli/azd/.vscode/settings.json
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/resources/apphost/templates/main.bicept
- cli/azd/resources/apphost/templates/resources.bicept
- association for .bicept as go-template and extension for syntax (https://github.com/Azure/azure-dev/pull/3163)
- net aspire - support cosmos db
fix: https://github.com/Azure/azure-dev/issues/3066
Strategy:
- Assigning `Cosmos DB Account Reader Role` and `Cosmos DB Operator` for the Cosmos DB Account. 
- Setting Documents Endpoint to the ENV for application to connect using managed identity (similar to Storage account)
> net aspire support cosmos

- templates/common/infra/bicep/core/host/container-apps.bicep
- templates/todo/projects/java-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo-aca/.repo/bicep/infra/main.bicep
This enables the admin user on the provisioned container registry so that `azd` can connect to it to push even if RBAC is not working because the user is not anowner of the resource.  We've seen cases where users who's accounts where created a long while back are set as [classic adminisrators](https://learn.microsoft.com/en-us/azure/role-based-access-control/classic-administrators) and not Owners on their accounts and ther is presently a service issue that prevents these users from exchanging their AAD creds for an access token.
Fixes #3157
> Enable admin user for registry in ACA sample

- templates/common/infra/bicep/core/search/search-services.bicep
The free tier of search service doesn't support managed identity, so you get an error if you try to provision with current Bicep. This PR sets identity to null for free tier.
> Update search-services.bicep to support free tier

- cli/azd/pkg/apphost/generate.go
Aspire removed the `.connection.v0` resource types in Preview 2. We kept our support in because it was easy to do so and gave folks a chance to migrate from Preview 1 to Preview 2.
However, as we get ready for Aspire Preview 3, it's time for us to remove support from `azd`. We'll never see these in manifests anymore, so it is safe to remove the code.
> Remove support for `.connection.v0` resource types.

- cli/azd/pkg/ioc/binding.go
- cli/azd/pkg/ioc/container.go
- Remove `lifetime`, it was only ever set to Scoped and only in the `scopedBindings` slice. We don't need to track it, since by construction all bindings in that slice are scoped.
- Remove `parent` from `NestedContainer`. It was never read, so there is no need to track it.
> Simplify `ioc.NestedContainer` implementation

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- schemas/alpha/azure.yaml.json
Adds more flexibility when resolving container registry names
**Options:**
1. From `AZURE_CONTAINER_REGISTRY_ENDPOINT` env var
2. From `registry` property of the `docker` configuration section of a service (Supports expandable strings)
> Adds flexibility when resolving container registry names

- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
Adds more flexibility when resolving AKS cluster names
**Options:**
1. From `AZURE_AKS_CLUSTER_NAME` env var
2. From `resourceName` of the service in `azure.yaml` (supports simple string or expandable string)
> Adds flexibility when resolving AKS cluster names

- cli/azd/pkg/tools/dotnet/dotnet.go
We often need to run `dotnet` an parse the output of it. When workloads are out of date the tool may print a warning, which harms our output parsing logic. Supress this warning by setting `DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE=1` when running `dotnet`
Fixes #3258
> Set DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE when running `dotnet`

- cli/azd/cmd/build.go
- cli/azd/cmd/container.go
- cli/azd/cmd/deploy.go
- cli/azd/cmd/down.go
- cli/azd/cmd/env.go
- cli/azd/cmd/hooks.go
- cli/azd/cmd/infra_synth.go
- cli/azd/cmd/init.go
- cli/azd/cmd/monitor.go
- cli/azd/cmd/package.go
- cli/azd/cmd/pipeline.go
- cli/azd/cmd/provision.go
- cli/azd/cmd/restore.go
- cli/azd/cmd/show.go
- cli/azd/cmd/up.go
- cli/azd/cmd/util.go
- cli/azd/internal/env_flag.go
The VS Server work is going to want to reference this type (it needs to register a provider for it in the IoC container because our actions pull it when loading an Environment) which means it can't live in the `cmd` package.
The `internal` package is not a great long term home for this, but it is where `GlobalCommandOptions` lives today and these two types are deeply related. Long term I'd like to move these both somewhere else since bare `internal.Xyz` imports read very poorly to me, but now at least these two types live in the same package and can move to a their final home together.
> Move `envFlag` out of `cmd`

- cli/azd/cmd/root.go
- cli/azd/cmd/usage_test.go
- cli/azd/docs/docgen.go
- cli/azd/main.go
- cli/azd/test/functional/initialize_test.go
This change adds a parameter to `NewRootCmd` to allow a caller to pass the IoC container that is used during construction of the root cobra command. Doing so allows a caller to change the result of registrations (as our vs-server needs to do).
Because `NewRootCmd` registers dependencies itself, a caller needs to take care to override whatever they want after calling `NewRootCmd` but before trying to actually run any methods on the returned `*cobra.Command`.
In an ideal world, `NewRootCommand` would not do any registrations and the caller would be required to do all the registrations.  We'll get there next. Right now this change provides the surgical hook needed by the VS sever work without being overly distruptive to the codebase.
> Allow caller to control root container in `NewRootCmd`

- cli/azd/cmd/container.go
- cli/azd/pkg/input/asker.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/input/console_test.go
The spinner library we're using triggers a paint update when any data update occurs in non-tty scenarios. This unfortunately results in a lot of unexpected extra output in non-tty scenarios.
With this change, we sidestep the issues here by being more careful on how we use the spinner and add tests to verify the desired behavior. Perhaps down the line we could consider addressing this cleanly with our own spinner implementation.
 
Fixes #3254
Post-change output:
> Fix duplicated output for spinner updates in non-tty scenarios

- cli/azd/cmd/container.go
- cli/azd/cmd/infra_create.go
- cli/azd/cmd/root.go
- cli/azd/cmd/up.go
- cli/azd/internal/cmd/cmd_help.go
- cli/azd/internal/cmd/deploy.go
- cli/azd/internal/cmd/provision.go
- cli/azd/internal/cmd/util.go
The VS Server will want to consume these types, so remove them from the root command packge to prevent import cycles and then export them so that both `cmd` and `internal/vsrpc` can reference them.
> Move deploy and provision actions to `internal/cmd`

- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/internal/vsrpc/handler_test.go
- cli/azd/internal/vsrpc/observer.go
- cli/azd/internal/vsrpc/observer_test.go
- cli/azd/internal/vsrpc/server.go
- cli/azd/internal/vsrpc/server_test.go
- cli/azd/internal/vsrpc/stream.go
- cli/azd/internal/vsrpc/writer_multiplexer_test.go
This change adds some tests around the infrastructure for serving our RPC endpoints.
We now have coverage of our logic for cancellation and our support for `IObserver` as well as coverage of all our `Handler[Action|Func][0-3]` functions which validate the core marshalling logic of our server.
While writing these tests, I discovered a small functional bug in our logic for unmarshalling `IObserver`. We intended to validate that the tag when present was 1, but due to a logic error this was not happening.
> Improve test coverage in `internal/vsrpc`

- .vscode/cspell-github-user-aliases.txt
- cli/azd/pkg/project/framework_service_dotnet.go
For containerized projects, we publish the produced container image in a single call `dotnet publish /p:PublishProfile=DefaultContainer`. Thus, running the default `dotnet publish` command is not required. Similar to `package.go`'s treatment of `DotNetContainerAppTarget `, we skip packaging for these projects.
Fixes #3300
> Skip unnecessary packaging for containerized dotnet apps

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/cmd/container.go
- cli/azd/pkg/kubelogin/cli.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/tools/azcli/managed_clusters.go
- cli/azd/pkg/tools/kubectl/kube_config.go
When a cluster is provisioned with Azure RBAC and local accounts are disabled `azd` will leverage `kubelogin` to use exec auth module with azd authentication.
Requires `azd` login method [feature](https://github.com/Azure/kubelogin/pull/398) for `kubelogin` 
>[!IMPORTANT]
> Requires that the principal logged into `azd` has been granted the required RBAC roles to the AKS cluster during provisioning.
> AKS Service Target: Adds support for Azure RBAC when local user accounts are disabled

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
- cli/azd/pkg/project/service_models_test.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/pkg/tools/docker/container_image.go
- cli/azd/pkg/tools/docker/container_image_test.go
- cli/azd/pkg/tools/docker/docker.go
- schemas/alpha/azure.yaml.json
Adds the ability to reference public or prebuilt image references.
- Adds new `image` property at the root of service configuration only valid for `containerapp`
- Allows specifying a source image that will be used for the container app service 
- Adds new `image` property within docker configuration options to set image name generation
- Works in tandem with `tag` property for generating final docker image path & tags
- When a service configuration does not contain a path to a source code project (no `project` defined) the docker configuration options allow developer to reference existing container images.
- When the `image` setting does not contain a registry endpoint then docker hub is assumed. 
- `project` and `image` are mutually exclusive and cannot be set at the same time
- Fully …
> Adds support to reference external or prebuilt image references

- cli/azd/pkg/tools/bicep/bicep.go
Moving min version to 0.25.3 per user request:
> I need to use bicep v0.25.3 for a feature I am developing (import types from file) -
> update min bicep version

- cli/azd/cmd/vs_server.go
- cli/azd/pkg/contracts/vs_server.go
To simplify consumption for diagnostics purposes, we also include version information in `azd vs-server` invocation.
```
./azd vs-server                  
{"port":40899,"pid":74476,"azd":{"version":"1.2.3-dev.0","commit":"8a49ae5ae9ab13beeade35f91ad4b4611c2f5574"}}
```
Fixes #3314
> Add version to vs-server

- cli/azd/.vscode/cspell.yaml
- cli/azd/cmd/container.go
- cli/azd/pkg/helm/cli.go
- cli/azd/pkg/helm/cli_test.go
- cli/azd/pkg/helm/config.go
- cli/azd/pkg/kustomize/cli.go
- cli/azd/pkg/kustomize/cli_test.go
- cli/azd/pkg/kustomize/config.go
- cli/azd/pkg/osutil/expandable_string.go
- cli/azd/pkg/osutil/expandable_string_test.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/tools/kubectl/kubectl.go
- cli/azd/resources/alpha_features.yaml
- schemas/alpha/azure.yaml.json
This PR adds [Helm](https://helm.sh/) support for using `azd` with AKS.
Resolves: #1618 
> [!IMPORTANT]
> To enable Helm support ensure you have the Helm CLI installed
> Enable the helm feature flag by running `azd config set alpha.aks.helm on`
```yaml
name: todo-nodejs-mongo-aks
metadata:
template: todo-nodejs-mongo-aks@0.0.1-beta
services:
argocd:
host: aks
k8s:
namespace: argo
service:
name: argocd-server
helm:
repositories:
- name: argo
url: https://argoproj.github.io/argo-helm
releases:
- name: argocd
chart: argo/argo-cd
verson: 5.51.4
jupyterhub:
host: aks
k8s:
namespace: jupyterhub
service:
name: proxy-public
helm:
repositories:
- name: jupyterhub
url: https://hub.jupyter.org/helm-chart/
releases:
- name: jupyterhub
chart: jupyterhub/jupyterhub
version: 3.1.0
```
> [!IMPORTANT]
> …
> Adds support for Helm and Kustomize for AKS service target

- templates/common/infra/bicep/core/search/search-services.bicep
We realized we needed a conditional when outputting the principal ID since we don't have it in the case of free SKU.
> Conditional around search identity

- templates/common/infra/terraform/core/database/cosmos/cosmos.tf
- templates/todo/common/tests/playwright.config.ts
- templates/todo/common/tests/todo.spec.ts
Background:
MongoDB allows you to create indexes on fields to optimize query performance.
The _id field is automatically indexed with a unique constraint, ensuring each document has a unique identifier.
You can also create custom indexes on other fields to improve query efficiency.
The Error:
When you attempt to create an index on the _id field with the unique: true option, MongoDB throws an error.
> This behavior changed in MongoDB version 3.4.2.
Why?:
The _id field already has an automatically created index (usually ascending order).
MongoDB prevents you from creating a second index with the same fields as the existing _id index.
The unique and background attributes are not allowed for the _id index.
Workaround:
omit unique field.
> remove index unique attribute to fix cosmos terraform module - fixes terraform template tests

- cli/azd/pkg/tools/github/github.go
Updating the implementation for `gh secret` and `gh variable` to read the value from stdin.
The previous implementation, using `--body value`, does not work on Windows if the `value` contains special characters like double-quotes (used to serialize a json value).  The issue is for how parameters are parsed by either powershell or cmd and passed to `gh cli`.
Using `stdin`, the `value` is not parsed by a shell and `gh cli` reads the value directly from stdin stream. 
fix: https://github.com/Azure/azure-dev/issues/3199
> use stdin for gh variable and secret values

- cli/installer/fpm/fpm.Dockerfile
- eng/pipelines/release-cli.yml
- eng/pipelines/templates/steps/build-linux-packages.yml
- eng/scripts/Test-LinuxPackages.ps1
Example build/test showing Linux packages built using Ubuntu 22.04. 
Moving up to Ubuntu 22.04 alleviates the version concerns that were causing errors in other builds. There is no hard requirement that packages be built on Ubuntu 20.04.
> Update fpm to use Ubuntu 22.04 and use optional prefix

- cli/azd/cmd/container.go
- cli/azd/cmd/vs_server.go
Reverts changes to the `ProjectConfig` lifetime from `transient` back to `singleton` to persist project/service level event handlers across the component.
> Reverts ProjectConfig to have a singleton lifetime to fix hook registrations

- ext/vscode/src/commands/init.ts
I'm adding options to the init command so that I can call it with a template url and environment name. We're leveraging it for vscode.dev/azure so that the selected azd template is immediately initialized when VS Code loads. 
We plan to call this command directly.
> Add template url and env name arguments to init VS Code command

- eng/pipelines/templates/steps/publish-cli-choco.yml
- eng/scripts/Set-GitHubReleaseTag.ps1
- eng/scripts/Update-WinGetManifest.ps1
- eng/scripts/Wait-ChocoPackage.ps1
- eng/scripts/Wait-WinGetPackage.ps1
These tasks did not run in the last release as a PowerShell problem prevented them from executing. After some investigation it's possible that these tasks/scripts might be affected by the recent PowerShell upgrade and so this change increases the chances that these commands will work.
> Defense in depth changes for potential $PSNativeCommandArgumentPassing problems

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/service_target_aks.go
Resolves #3376
Fixes a few issues for AKS service target when building containers with yaml manifests.
A couple merge issues resulted in some missed changes:
> fix: AKS deploy issues with containers & manifests

- cli/azd/pkg/project/importer.go
- cli/azd/pkg/project/importer_test.go
Resolves #3365
When users are leveraging ADE and devcenter it is expected that a local `infra` folder will not exist.
In the `importer` package we are unable to take a dependency on platform configuration and the importer should not enforce infra provider constraints
> fix: Removes requirement that infra must always exist for ADE/devcenter projects

- cli/azd/docs/external-authentication.md
This feature was added in #2541, but at the time we did not write complete documentation for how the feature worked, instead there was just a good commit message that outlined the work.
We now want to use a similar strategy with VS, so this document outlines the protocol that we came up with to be able to hand authentication off to an external process.
> Document external authentication prototcol

- cli/azd/cmd/container.go
- cli/azd/pkg/environment/manager.go
- cli/azd/pkg/environment/manager_test.go
- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/package_test.go
- cli/azd/test/functional/restore_test.go
- cli/azd/test/functional/up_test.go
- cli/azd/test/mocks/mockenv/mock_manager.go
When a command requires an environment, and no default environment is set, the user is prompted to "Enter a new environment name".
This change updates the prompt slightly to allow selecting an existing environment.
Before:
After:
"Create a new environment"
"Select 'prod'"
I suspect that this is a good change overall, and will work nicely with upcoming work to delete environments: #937
> Allow selecting an existing environment when no default environment is set

- templates/common/infra/bicep/core/database/mysql/flexibleserver.bicep
adding mysql bicep to core infra templates as it doesn't exist.
> add mysql bicep to core templates

- cli/azd/internal/vsrpc/models.go
- cli/azd/internal/vsrpc/utils.go
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
Neither Aspire nor `azd` proper have the concept for a "kind" for a service. Instead of forcing us to come up with some meaning, simply return the full path to the project, as we would in other cases like `azd show`. Consumers can use the path to determine the "kind" of service it is, using whatever huristics they like.
Fixes #3374
> vs-server: Include `path` to service instead of `kind`

- cli/azd/cmd/container.go
- cli/azd/internal/vsrpc/environment_service_load.go
- cli/azd/pkg/project/dotnet_importer.go
Restore dotnet importer as singleton to cache manifest reads in a single `up` execution. Reuse dotnet importer in vsrpc to cache per-request.
Fixes #3303, #3405
> Cache manifest reads in a single execution

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/vsrpc/aspire_service.go
- cli/azd/internal/vsrpc/environment_service_create.go
- cli/azd/internal/vsrpc/environment_service_load.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/importer_test.go
- cli/azd/pkg/tools/dotnet/dotnet.go
- cli/azd/test/functional/aspire_test.go
- Flow `DOTNET_ENVIRONMENT` into the process environment from the  `.env` file when running the app host program to generate the manifest.
- Use `ASPIRE_ENVIRONMENT` (when set, VS will likely remove it soon as we have decided to not introduce yet another concept) to influence `DOTNET_ENVIRONMENT` during environment creation in the VS Server RPC.
- When caching manifests in the `DotNetImporter`, use the tuple of  `{app-host-path, DOTNET_ENVIRONMENT}` as the   cache key, instead of just the path to the manifest as the output of these manifest can depend on these values.
Fixes: https://github.com/Azure/azure-dev/issues/3233
> Set `DOTNET_ENVIRONMENT` when running AppHost

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-sb-aspire.hosting.azure.bicep.servicebus.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-bicep.json
Fix to support array of objects as input parameters for bicep.v0
A param like:
```json
"params": {
"topics": [
{
"name": "topic1",
"subscriptions": [
"subscription1",
"subscription2"
]
}
}
```
should be modeled into bicep:
```bicep
params: {
topics: [{name:'topic1',subscriptions:['subscription1','subscription2']},{name:'topic2',subscriptions:['subscription1']}]
}
```
> Aspire fix for json arrays

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
Fixes issues where deploying to AKS fails when service does not build any container
**Valid use cases:**
- Helm charts that reference external images
- Kustomize or vanilla manifests that reference external images
> Fixes issues where deploying to AKS fails when service does not build any container

- cli/azd/cmd/deps_record.go
- cli/azd/internal/cmd/deploy.go
- cli/azd/internal/vsrpc/environment_service_deploy.go
- cli/azd/internal/vsrpc/environment_service_refresh.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/test/azdcli/cli.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_VsServer/LiveDeployRefresh.dotnet.yaml
- cli/azd/test/functional/testdata/recordings/Test_CLI_VsServer/LiveDeployRefresh.yaml
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
- cli/azd/test/functional/testdata/vs-server/tests/TestBase.cs
- cli/azd/test/functional/vs_server_test.go
- cli/azd/test/ostest/ostest.go
- cli/azd/test/recording/recording.go
- cli/azd/test/recording/sanitize.go
Expose provisioned resources in both `DeployAsync` and `RefreshEnvironmentAsync`.
Add acceptance tests for this scenario, which included surrounding test helper changes:
- Support multiple command recorders
- Add `dotnet publish <container>` as default global recording option
- Avoid `HTTPS_PROXY` passthrough in recordings
Fixes #3317
> vsrpc: Expose provisioned resources

- cli/azd/internal/cmd/provision.go
- cli/azd/pkg/project/service_target_aks.go
Resolves #3447 
When calling `azd provision` with `--preview` AKS service target should not attempt to set the K8s context since resources are not expected to exist at this stage.
> Don't set AKS context during provision preview

- cli/azd/cmd/container.go
- cli/azd/cmd/container_test.go
- cli/azd/cmd/deps_record.go
- cli/azd/pkg/devcenter/manager.go
- cli/azd/pkg/devcenter/platform.go
- cli/azd/pkg/devcenter/prompter.go
- cli/azd/pkg/devcenter/provision_provider.go
- cli/azd/pkg/devcenter/template_source.go
- cli/azd/pkg/devcentersdk/environment_request_builders.go
- cli/azd/pkg/environment/environment.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_DevCenter_Init_Up_Down.yaml
Adds e2e tests for ADE deventer integration and performs a complete `azd init` + `azd up` + `azd down` flow.
**Adds the following to support better testability:**
- Ability to set platform type via environment variable `AZD_PLATFORM_TYPE`
- Adds ability to filter dev center templates by catalog name
- Removes unnecessary custom poller implementation (works better with recorder as well)
**Fixes some minor ADE bugs found in testing**
- Fixes bug with incorrect environment variable reference for devcenter name 
- Ensures devcenter configuration parameters are stored back into environment configuration
> Adds Devcenter (ADE) e2e functional test

- templates/tests/test-templates.sh
Re-enable provision preview to run after fixing #3449
> Re-enable provision preview in template tests

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
Resolves #3241 
Allows pushing container images to external container registries.  
> [!IMPORTANT]
> Do to the various configurations and complexities of using each external container registry users will need to manually authenticate to the registry prior to calling `azd deploy`
- Run `docker login` and authenticate to your external container registry following the setup/configuration of your registry provider
```yaml
name: todo-nodejs-mongo-aca
metadata:
template: todo-nodejs-mongo-aca@0.0.1-beta
services:
nginx:
image: docker.io/wbreza/nginx:latest
```
In this example during `azd deploy` the container will be pulled from `docker.io/wbreza/nginx:latest` and directly referenced by the container app service.
> [!IMPORTANT]
> Your containerapp infra configuration must …
> Adds support for external container registries

- cli/Dockerfile
Updates the install strategy used for `kubectl` CLI.  Does not require any version pinning and will always install latest.
Follows the `curl` based install from [official docs](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux)
> Updates install strategy for kubectl

- cli/installer/README.md
The `-ex AllSigned` parameter causes the snippet to fail if the user has a profile.ps1 that isn't signed (usually the case). Adding `-NoProfile` up front ensure the script is executed in a session without the user's profile.
> Add -NoProfile to PowerShell installer instructions

- cli/azd/cmd/container.go
- cli/azd/internal/repository/detect_confirm_test.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/internal/vsrpc/environment_service_deploy.go
- cli/azd/internal/vsrpc/message_writer.go
- cli/azd/internal/vsrpc/message_writer_test.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/internal/vsrpc/server_session.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/input/console_test.go
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
- cli/azd/test/functional/vs_server_test.go
Expose spinner updates to VS.
Progress messages that are marked as Important are prominently displayed in VS as a spinner:
While doing this, `lineWriter` is updated to support line-ending trimming and reduced memory allocations by reusing pre-allocated buffers.
Fixes #3313
> vsrpc: Expose spinner updates in VS

- cli/azd/cmd/deps.go
- cli/azd/cmd/deps_record.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_DevCenter_Init_Up_Down.yaml
Updates `azd` to always return the `http.DefaultClient`.
Any transport/proxy settings required for the record/playback are also set on the default client
> [!NOTE]
> What this means though is that somewhere in the app it is not using the correct http client instance.  The recorder is catching more requests with this change than previously.
> Updates `azd` to use default http client/transport

- cli/azd/pkg/project/service_target_aks.go
> Fixes edge case issue of a false positive AKS deployment failure

- cli/azd/resources/scaffold/templates/host-containerapp.bicept
Update environment variables for postgres to match the standard variable names when a postgres ACA add-on is used, based on user feedback.
> Adopt env variables used by postgres add-on

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-main.bicep.snap
- cli/azd/resources/apphost/templates/main.bicept
fix: https://github.com/Azure/azure-dev/issues/3505
explanation:
There were 2 issues:
- Writing multiple auto-gen inputs from un-ordered map[string] was causing indeterministic result for the snapshot
- When having more than one auto-gen input, there was only one written to the bicep file.  This is b/c azd handles auto-gen inputs internally with a `map[string]input` , using a string key like `resource.paramName` to be unique.  But, for writing the metadata, azd splits the key into resource and paramName, and a new structur `map[string][]input` is required to be constructed.
> fix for multiple inputs per resource and deterministic generation from map

- cli/azd/cmd/cobra_builder.go
- cli/azd/cmd/cobra_builder_test.go
- cli/azd/cmd/container.go
- cli/azd/cmd/env.go
- cli/azd/cmd/middleware/hooks.go
- cli/azd/pkg/ext/event_dispatcher.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_manager.go
Resolves #3499 
Fixes an issue where an event handler bound in one command within an `up` workflow could incorrectly fire when the event is raised in another command.
The `project.ProjectConfig` instance has a singleton lifetime which means the same instance was shared between commands within an `up` workflow.  Some of our service targets (ex. AKS) registers event handler such as `postprovision` during its initialization process.  This event registration is stored within the `ProjectConfig` mentioned above.
This was causing multiple event handlers to be registered for the service target and some of them were referencing scoped components from other commands.  Transient service target AKS was referencing scoped environment from previous commands.
When the `postprovision` event was finally …
> Fixes service config handlers referencing stale components

- eng/pipelines/release-cli.yml
Long term we hope to stop building this container - but we aren't yet sure who we might impact by doing so, so it will be a gradual effort.
To start, we can at least stop linking to it in our per PR build message - that way folks are less likely to notice it and take a dependency on it and if someone points out that it is missing we can ask them what they are using it for today and advise them on how to move away from it and onto something we'd like to support long term.
Contributes To: #3494
> Don't advertise the unified container in PR builds.

- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/internal/vsrpc/handler.go
- cli/azd/internal/vsrpc/server_test.go
This change modifies the behavior of the RPC server such that if a handler panics, instead of tearing down the entire process we have the RPC in question return an RPC error (with the Code set to `InternalError`).
In theory `azd` does not panic during any of these handlers. In practice, sometimes we make mistakes an getting an error back instead of `azd` crashing an the RPC failing when the connection is terminated is a much nicer experience and also ensures the error message makes its way back to to the caller.
> vs-server: Treat `panics` in handlers as RPC errors instead of crashing

- cli/azd/internal/vsrpc/handler.go
- cli/azd/internal/vsrpc/server_test.go
Our handler logic for RPCs ensured that the client at least as many arguments as an RPC required, but any extra arguments from the caller would be silently ignored.
This change ensures that when a caller passes more arguments than expected we correctly return an error, as we would if the caller passed too few.
> vs-server: Validate correct number of arguments for RPCs

- cli/azd/cmd/container.go
- cli/azd/docs/external-authentication.md
- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/internal/vsrpc/server.go
- cli/azd/internal/vsrpc/server_service.go
- cli/azd/internal/vsrpc/server_session.go
- cli/azd/internal/vsrpc/server_test.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/remote_credential.go
- cli/azd/pkg/devcentersdk/developer_client_test.go
- cli/azd/test/functional/remote_state_test.go
- cli/azd/test/functional/testdata/vs-server/tests/AcceptanceTests.cs
- cli/azd/test/functional/testdata/vs-server/tests/AzdServices.cs
- cli/azd/test/functional/vs_server_test.go
This change adds support for clients using the vs-server to provide an external authentication server (as described in
cli/azd/docs/external-authentication.md) when initializing a session. When a client does, all auth requests for that session will use the configured server, allowing the client to fetch a token on behalf of `azd`.  Visual Studio will use this to request a token using the current signed in user, instead of forcing users to also run `azd auth login`.
This configuation is optional - when not provided, `azd` will continue to use the user signed in via `azd auth login`.
The `InitializeServerAsync` RPC gains a new argument - `InitializeServerOptions` which allows the values that would normally be set via `AZD_AUTH_ENDPOINT` and `AZD_AUTH_KEY` environment variables. The …
> vs-server: Support External Auth

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/apphost/testdata/aspire-docker.json
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/dotnet_importer_test.go
fix: https://github.com/Azure/azure-dev/issues/3432
Updating netAspire generator to use the build args from the dockerfile resource 
Notes: 
Requires netAspire preview5
> set build args for dockerfile

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-container.json
- cli/azd/resources/apphost/templates/resources.bicept
fix: https://github.com/Azure/azure-dev/issues/3515
> net aspire volumens

- eng/pipelines/templates/stages/sign.yml
Successful run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3644327&view=results
> Artifacts now include a _manifest folder which breaks signing. Ensure that _manifest is removed when preparing to sign

- cli/azd/cmd/init.go
- cli/azd/cmd/testdata/TestUsage-azd-init.snap
Add a flag to `init` for initializing from existing code.
Fixes #3361
> init: add --from-code flag

- cli/installer/windows/azd.wixproj
Alternative fix that may be the right one.
> Remove workaround for WiX msbuild task load

- templates/todo/projects/csharp-cosmos-sql/.vscode/tasks.json
- templates/todo/projects/csharp-sql-swa-func/.vscode/tasks.json
- templates/todo/projects/csharp-sql/.vscode/tasks.json
- templates/todo/projects/java-mongo-aca/.vscode/tasks.json
- templates/todo/projects/java-mongo/.vscode/tasks.json
- templates/todo/projects/java-postgresql/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aca/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-aks/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/nodejs-mongo/.vscode/tasks.json
- templates/todo/projects/python-mongo-aca/.vscode/tasks.json
- templates/todo/projects/python-mongo-swa-func/.vscode/tasks.json
- templates/todo/projects/python-mongo/.vscode/tasks.json
After removing `VITE_APPLICATIONINSIGHTS_CONNECTION_STRING` from the bicep outpus (because there is already `APPLICATIONINSIGHTS_CONNECTION_STRING`), we need to create the mapping to a VITE env var to launch locally
fix: https://github.com/Azure/azure-dev/issues/3646
fix: https://github.com/Azure/azure-dev/issues/3644
> set app insights key when running web locally

- cli/azd/cmd/container.go
- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/pkg/auth/credential_providers.go
- cli/azd/pkg/azsdk/storage/storage_blob_client.go
- cli/azd/pkg/cosmosdb/cosmosdb.go
- cli/azd/pkg/devcenter/platform.go
- cli/azd/pkg/environment/manager_test.go
- cli/azd/pkg/sqldb/sqldb.go
- cli/azd/test/functional/remote_state_test.go
- cli/azd/test/mocks/mock_context.go
With this change, we avoid registering a tenant-specific `azcore.TokenCredential` in the DI graph and fix consuming code using the wrong tenant for their respective use cases. We do this to expose important implementation details of which tenant or subscription should be used to produce an `azcore.TokenCredential` (which by definition, is always tenant-specific). Such a detail is quite important in a multitenant application.
This change slightly reduces ease of writing code since the consumer needs to know about `auth.MultiTenantCredentialProvider` or `account.SubscriptionCredentialProvider`. In a follow-up change, I plan to simplify these details.
Fixes #3485
> Remove `azcore.TokenCredential` from DI graph.

- templates/common/infra/bicep/core/host/container-app-upsert.bicep
- templates/common/infra/bicep/core/host/container-app.bicep
This PR makes it so that you can securely pass secrets into the container-app modules, by wrapping it in a secure() decorator. Unfortunately, we can't mark arrays as `@secure`, so you have to instead pass in an object of the secret key/values, and we turn that back into the expected array format.
Note that I haven't tested these exact modules since I'm working off a fork of the modules (my use case isn't compatible with the azd modules.. will file an issue about that).
You can see my change here, which works:
https://github.com/Azure-Samples/langfuse-on-azure/pull/9
I don't think any of the TODO templates utilize secrets for container apps, so not sure there's a test to do on the azd template side.
> Add secure() for secrets

- cli/azd/pkg/project/service_target_aks.go
Resolves an issue in the AKS endpoint resolution strategy.  After removing the comma  between the endpoint URL and types this caused an issue parsing the endpoint used later in template validation.
> Updates resolution strategy for AKS endpoints

- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/azure.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/azure.yaml
- templates/todo/projects/java-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/java-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/java-postgresql/.repo/terraform/azure.yaml
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo-aks/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/nodejs-mongo/.repo/terraform/azure.yaml
- templates/todo/projects/python-mongo-aca/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo/.repo/bicep/azure.yaml
- templates/todo/projects/python-mongo/.repo/terraform/azure.yaml
This avoids `azd up` only deploying a targeted service when the current working directory is a service directory.
> Use `deploy --all`

- eng/pipelines/release-cli.yml
- eng/pipelines/templates/jobs/build-cli.yml
- eng/pipelines/templates/stages/build-and-test.yml
- eng/pipelines/templates/stages/code-coverage-upload.yml
- eng/pipelines/templates/steps/install-docker.yml
- eng/pipelines/templates/variables/image.yml
Example scheduled build: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3681487&view=logs&j=90dd592b-3d52-543c-a8c6-c88386b77a8c&t=721351df-310a-597d-818d-c5a9c6e01ca8
Note: We move up to a more recent version of Docker. The docker installer task requires a specific version number ("latest" or something similar does not work).
> Use Apple Silicon in scheduled builds

- cli/azd/pkg/apphost/generate.go
With the expection of `targetPort` we did not allow you to get at the properties of a binding (e.g `scheme`) when writing an expression, but this is useful to so when generating a URL from parts, for example:
`Endpoint={qdrant.bindings.grpc.scheme}://{qdrant.bindings.grpc.host}:{qdrant.bindings.grpc.port};Key={qdrant-Key.value}`
With this change, we support these properties which are already in the manifest, in addition to our synthetic ones like `url` and `host`.
> aspire: Support all Binding properties in expressions

- templates/common/infra/bicep/core/search/search-services.bicep
In order to remove the security alert "Protect Azure AI Search Instances by only allowing RBAC API Access", I needed to set disableLocalAuth to true. However, I discovered that authOptions must be null in that case, *not* an empty object, the default value. So this PR explicitly sets authOptions to null when disableLocalAuth is true.
Here's a full PR that uses this change:
https://github.com/Azure-Samples/azure-search-openai-demo/pull/1502/files
> Update search-services.bicep set disableLocalAuth compatibility

- cli/azd/cmd/vs_server.go
- cli/azd/internal/vsrpc/server.go
- cli/azd/internal/vsrpc/testdata/dotnet-azd-client/Program.cs
- cli/azd/internal/vsrpc/testdata/dotnet-azd-client/Settings.Template.cs
- cli/azd/pkg/contracts/vs_server.go
- cli/azd/test/functional/testdata/vs-server/tests/TestBase.cs
- cli/azd/test/functional/vs_server_test.go
While communication only happens over localhost, we'd still like the use TLS on the endpoint to prevent other processes from sniffing local traffic and to allow the client to validate that it is talking to the server it expects (which it can do by ensuring the certificate presented during the TLS Handshake matches what is expected).
With this change, `azd vs-server` gains a new parameter, `--use-tls`. When set, it generates a self-signed 2048 RSA certificate on each run and uses it to expose its endpoints over TLS. This certificate is ephemeral and re-generated each time the server is launched. The lifetime of the generated certificate is short (7 days) per guidence from the security team. This means the server will need to be recycled after seven days because the certificate it is using …
> vs-server: Add `--use-tls` for serving over TLS

- cli/azd/cmd/container.go
- cli/azd/internal/vsrpc/models.go
- cli/azd/internal/vsrpc/server_service.go
- cli/azd/internal/vsrpc/server_session.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/httputil/util.go
Enable https connecting to vs when AuthenticationCertificate is provided in vs-server.
Also, allow AZD_AUTH_CERT to inherit the same behavior when interacting with azd CLI.
> vs-server: https enabled with VS when AuthenticationCertificate is provided.

- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-frontend.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
- cli/azd/pkg/apphost/testdata/TestAspireEscaping-api.snap
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.ApiService/manifests/containerApp.tmpl.yaml
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.Web/manifests/containerApp.tmpl.yaml
This change does two things:
- Supports using a custom api-version of the ACA CreateOrUpdate request by allowing the yaml deployment template to have an `api-version` property at top level. When set, this value is used as the `api-version` of the request. The request body is the object, rendered as JSON, with the `api-version` key removed.
- Uses the above new feature to opt into the `2024-02-02-preview` in Aspire and sets the
`configuration.runtime.dotnet.autoConfigureDataProtection` property to `true`.
Fixes #3538
> Enable DataProtection Runtime feature in ACA

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/resources/alpha_features.yaml
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
This change does two things:
- Supports using a custom api-version of the ACA CreateOrUpdate request by allowing the yaml deployment template to have an `api-version` property at top level. When set, this value is used as the `api-version` of the request. The request body is the object, rendered as JSON, with the `api-version` key removed.
- Uses the above new feature to opt into the `2024-02-02-preview` in Aspire and sets the
`configuration.runtime.dotnet.autoConfigureDataProtection` property to `true`, but only when the alpha feature
`aspire.autoConfigureDataProtection` is turned on.
We are gating turning this feature on behind a feature flag the user must opt-into instead of always sending this request, as we had done in #3711, because currently regions in Azure are rejecting the …
> Support DataProtection Runtime feature in ACA

- cli/azd/cmd/container.go
- cli/azd/internal/vsrpc/server_service.go
Remove http timeout added recently in #3712 since external prompt requires waiting indefinitely on the server for a response.
This fixes an issue with VS integration where azd errors out after 5-10 seconds on the dialog.
> vs-server: Remove http timeout since external prompt requires waiting on server

- cli/azd/cmd/up.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/test/functional/telemetry_test.go
Avoid re-prompting for Bicep parameters.
azd currently prompts for Bicep parameters during Bicep provider `Initialize`. If an error occurs, such as user cancellation, the error is ignored and the program continues. This leads to azd later re-prompting for the same parameters.
This change makes `bicepProvider.Initialize` assert that all client-state is ready for provisioning.
To avoid any behavioral changes in regards to when prompting occurs during `up`, we have moved that logic into `up` explicitly until we decide directionally where it should go.
Example of the issue currently with reprompting. I cancelled the prompt multiple times:
```bash
~ azd up
? Select an Azure Subscription to use: 25. Azure SDK Developer Playground (faa080af-c1d8-40ad-9cce-e1a450ca5b57)
? Select an Azure location …
```
> Avoid re-prompting for Bicep parameters.

- cli/azd/pkg/devcenter/manager.go
- cli/azd/pkg/devcenter/provision_provider.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display_test.go
> [!NOTE]
> This is only a temporary solution to unblock some //BUILD scenarios. 
> A better future proof solution will be implemented when more dev capacity is available.
Initially ADE only supported ARM based deployments via their v1 runner implementation.
- v1 Runner does not support ADE OUTPUTS Api
- v1 runner tags ARM deployments that `azd` depended to find deployment to be used for incremental progress reporting
ADE v2 runner now supports Bicep, Terraform and any other custom providers but ARM has not been updated to use the newer v2 runner implementation.
- v2 Runner does support ADE OUTPUTS Api
- v2 Runner does NOT support tagged deployments
This change enables an alternative path to find the correct Azure deployment object if tags are not available.  Since both ARM & Bicep still …
> Adds workaround to support ADE Bicep deployments

- templates/common/infra/bicep/core/ai/cognitiveservices.bicep
This is necessary to turn off key-based API access.
> Update cognitiveservices.bicep with disableLocalAuth

- ext/vscode/CHANGELOG.md
- ext/vscode/package-lock.json
- ext/vscode/package.json
Did manually due to pipeline issues. Copied from #3501
> Increment VSCode Extension version after release

- cli/azd/pkg/input/console.go
Handle default value associated with OptionDetails so that they would match correctly.
Fixes #3786
> console: Handle default value associated with OptionDetails 

- eng/pipelines/templates/jobs/vscode-build.yml
Output path was incorrectly specified. This was a copy/paste error from the 1ES migration.
> Fix publishing for vscode extension

- cli/azd/pkg/config/config.go
- cli/azd/pkg/config/file_config_manager.go
- cli/azd/pkg/config/file_config_manager_test.go
Adds the following functions to the `Config` interface:
- `SetSecret`
The following functions have been updated:
- `Get/GetString` - If the config entry contains a vault reference, the secret value will automatically be retrieved from the vault and returned to the caller.
When secrets are stored a new config vault is created @ `${AZD_CONFIG_DIR}/vaults/${VAULT_ID}.json`
> [!IMPORTANT]
> Secrets stored in `azd` should only be used for development purposes.
> In production scenarios [managed identities](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) should be leveraged as much as possible.
> If [managed identities](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) are not supported a secure solution …
> Adds support to get/set secret values in AZD configuration

- cli/azd/test/functional/testdata/samples/resourcegroupterraform/infra/provider.tf
- cli/azd/test/functional/testdata/samples/resourcegroupterraformremote/infra/provider.tf
- cli/azd/test/functional/testdata/samples/springapp/infra-terraform/provider.tf
- templates/starter/terraform/infra/provider.tf
- templates/todo/projects/java-postgresql/.repo/terraform/infra/provider.tf
- templates/todo/projects/nodejs-mongo/.repo/terraform/infra/provider.tf
- templates/todo/projects/python-mongo/.repo/terraform/infra/provider.tf
This PR updates all provider.tf files where this could be a problem but the issue was originally uncovered in sovereign environments in the `todo` app. 
Fixes #3797
> Update provider.tf files with skip_provider_registration = "true"

- cli/azd/cmd/env.go
- cli/azd/test/functional/env_refresh_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_EnvRefresh_NoBicep.yaml
Minimal patch to fix regression of behavior for `env refresh` to proceed without bicep files. Add functional test to cover #2528.
Fixes #3787
> Allow `env refresh` without bicep

- cli/azd/pkg/config/config.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
Using the .SetSecret() functionality from Config to save secured parameters with bicep-provider
> use setSecret for secured bicep param

- cli/azd/cmd/up.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
Move prompting for subscription and location before compiling bicepparam. This avoids bicepparam from failing outright.
Failing test `Test_CLI_InfraBicepParam` (fails locally in record mode) passes after this change. Unsure yet why live tests on CI do not fail in the same manner.
> Add bicepparam handling for prompting

- eng/pipelines/templates/jobs/cross-build-cli.yml
Fix failure seen in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3738125&view=logs&jobId=f45fc40e-fed6-5690-00a4-8f5cef8e7f59&j=94ca385e-9655-5fbd-de13-6f931a1114dd&t=e5107889-11db-5ae5-3e13-abdcda2bed09&s=2b1cf740-7e83-5b38-9f56-89c750cf5d77
> Require success to upload artifact (on cross-build)

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/vsrpc/aspire_service.go
- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/internal/vsrpc/environment_service.go
- cli/azd/internal/vsrpc/environment_service_create.go
- cli/azd/internal/vsrpc/environment_service_deploy.go
- cli/azd/internal/vsrpc/environment_service_load.go
- cli/azd/internal/vsrpc/environment_service_refresh.go
- cli/azd/internal/vsrpc/server_session.go
- cli/azd/internal/vsrpc/utils.go
- cli/azd/internal/vsrpc/utils_test.go
- cli/azd/pkg/environment/azdcontext/azdcontext.go
Use the newly available information of the app host project to decide how the azd project context should be created an initialized from.
By default, use the app host project directory when none exists. Otherwise, find the nearest azd project that matches the current app host project.
fixes #3563
> vs-server: allow multiple app host projects

- cli/azd/test/functional/vs_server_test.go
CI is failing due to an infra limitation: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3752643&view=logs&j=3748a3ab-7269-5e9a-9cea-5ecb3b6f562c&t=9e8b103a-03c4-5ee7-7f93-050556e766a3&l=209
```
aspire_test.go:399: 1m12.607s [t-out]   Failed LiveDeployRefresh [1 m 10 s]
aspire_test.go:399: 1m12.607s [t-out]   Error Message:
aspire_test.go:399: 1m12.607s [t-out]    StreamJsonRpc.RemoteInvocationException : deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
aspire_test.go:399: 1m12.607s [t-out] 
aspire_test.go:399: 1m12.607s [t-out] Deployment Error Details:
aspire_test.go:399: 1m12.607s [t-out] InvalidTemplateDeployment: The template deployment 'resources' is not valid according to the validation procedure. …
```
> unblock daily skipping vsserver tests

- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-resources.bicep.snap
- cli/azd/resources/apphost/templates/resources.bicept
- cli/azd/test/functional/aspire_test.go
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/resources.bicep
- cli/azd/test/functional/vs_server_test.go
re-enabling tests skipped during: https://github.com/Azure/azure-dev/pull/3835
Using a fixed location to prevent over-utilization of location defined in tests during live tests.
> re-enable tests with fix location

- cli/installer/fpm/fpm.Dockerfile
- eng/pipelines/templates/jobs/verify-installers.yml
- eng/pipelines/templates/stages/publish.yml
- eng/pipelines/templates/steps/build-linux-packages.yml
- eng/pipelines/templates/steps/publish-cli-container.yml
- eng/pipelines/templates/steps/publish-cli.yml
Fixes [#7984](https://github.com/Azure/azure-sdk-tools/issues/7984)
* Uses 1ES tasks for building and pushing docker images (authenticates via service connection) 
* Switches `fpm` container to use Mariner
> 1ES container templates

- cli/azd/pkg/devcenter/devcenter_test.go
- cli/azd/pkg/devcenter/environment_store.go
- cli/azd/pkg/devcenter/environment_store_test.go
- cli/azd/pkg/devcenter/manager.go
- cli/azd/pkg/devcenter/platform.go
- cli/azd/pkg/devcenter/prompter.go
- cli/azd/pkg/devcenter/prompter_test.go
- cli/azd/pkg/devcenter/provision_provider.go
- cli/azd/pkg/devcenter/provision_provider_test.go
Resolves #3826 
Devcenter configuration can exist at multiple levels for `azd`
- Environment variables
- Global `azd` configuration
- Project configuration in `azure.yaml`
- `azd` envrionment configuration within `.azure/<env-name>/config.json`
Since the `config` object was being injected as a transient component changes to the config where not getting picked up when changes where made based on user prompts.
This PR removes the config from an injected param of a couple components and into a function param for consumed components.  This allows the correct config to flow through to the required functions.
In addition to this this enables us to now only save updates to the config based on what has changed from the originally loaded value as part of the `azd` environment configuration.
> Updates devcenter config usage

- cli/azd/cmd/init.go
- cli/azd/cmd/templates.go
- cli/azd/cmd/testdata/TestUsage-azd-init.snap
- cli/azd/cmd/testdata/TestUsage-azd-template-list.snap
- cli/azd/pkg/templates/awesome_source.go
- cli/azd/pkg/templates/template.go
- cli/azd/pkg/templates/template_manager.go
- cli/azd/pkg/templates/template_manager_test.go
- cli/azd/resources/templates.json
- Adds `tags` to JSON structure for AZD template sources
- Adds (`--filter, -f`) option to `azd template list`
- Adds (`--filter`) options to `azd init`
- Displays tags in `azd template show`
When specifying `--filter, -f` argument to `azd init` AZD will automatically enter template list mode showing only templates that match the specified tags.
When specifying `--filter, -f` argument to `azd template list` AZD will filter the template results to show only those templates that have matching tags.
Tags will now show along with other template metadata.
> Adds support to filter AZD templates by tags

- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/token.go
Expose `auth.ClaimsForCurrentUser` that returns access token claims for the current user.
This allows us to learn more about the user information even when no logged in information is available, when remote credential protocol is enabled.
This sets us up nicely to implement #3842
> Expose `auth.ClaimsForCurrentUser`

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-bicep.json
We were not taking the emitType flag into account when generating values for `.host` or `.url` binding expressions and just always emited the yaml format.  This caused invalid bicep generation when a module would have a pramater with a value like
`${project.bindings.https.url}`.
Fixes #3839
> aspire: Fix invalid bicep when using binding expressions

- cli/azd/test/functional/cli_test.go
daily build is broken by devcenter tests not finding some resources (key vault). 
Disabling test to unblock daily build as this is test infrastructure issue
> chore: Skip dev center configuration in test environment

- cli/azd/internal/cmd/provision.go
- cli/azd/internal/cmd/util.go
- cli/azd/pkg/infra/provisioning/provisioning_progress_display.go
- cli/azd/pkg/prompt/prompter.go
- cli/azd/pkg/prompt/prompter_test.go
When producing content, folks often spend time scrubbing or masking subscription IDs from the output of `azd`. Instead of folks having to spend their time on this, it would be nice if `azd` could do it itself.
This change adds support for setting an environment variable, `AZD_DEMO_MODE`, which controls if we will show subscription IDs or not.
In cases where we'd previously show a subscription name and ID (like the selection box when we ask a user to pick a subscription, or when a `provision` starts and we print the target subscription and location information) we now just show the name.
In cases where we'd show a link to the Portal in messages (e.g. during a deployment when we provide a link into the deployment status) we now just elide the link since the portal links contain the …
> cli: Add "Demo Mode" which hides subscription IDs

- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
- templates/todo/projects/csharp-sql/.repo/bicep/infra/main.bicep
- templates/todo/projects/java-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo/.repo/bicep/infra/main.bicep
Templates were using B1 which takes a long time to boot and be ready to deploy.
Also, when using Oryx, it takes more than 3 minutes to build a node app.
The experience from azd deploy is very bad for webApp using B1 and the cost benefit is not that much compared to B3 (.017 v/s .067 p/h).
The fact that B1 runs with only 1 vCPU drastically reduces its performance compared to B3 running with 4 vCPUs
> Updating service plan to B3.

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-main.bicep.snap
- cli/azd/resources/apphost/templates/main.bicept
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/main.bicep
If a bicep module is defined including the location parameter, azd will use that value instead of linking the `location` parameter from the main.bicep
fix: https://github.com/Azure/azure-dev/issues/3857
> Adding support for overriding the location in AppHost for a bicep module.

- cli/azd/pkg/config/config.go
- cli/azd/pkg/config/file_config_manager_test.go
- cli/azd/pkg/pipeline/pipeline_manager.go
Adding `ResolvedRaw()` to config for pulling all the config with any secret resolved
> Resolve secrets in pipeline config outside of the environment.

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/project/dotnet_importer.go
`azd infra synth` was not taking the path to the shared infrastructure folder inor the name of the root module from the `infra` of `azure.yaml` into account, and instead just always generated files into the `infra` folder at the root of the project.
Since these were getting generated to the wrong place, they were ignored during future `azd provision` runs.
We now take these values into account when generating filenames and paths.
> synth: Take `infra` section of `azure.yaml` into account

- cli/azd/pkg/containerapps/container_app.go
This change fixes KeyVault secrets not being preserved for container app deployments.
We currently do a client-side fetch and patch operation on container app revisions for traditional (non-manifest) container app deployments. This involves fetching and setting the secrets since it's not returned in the initial container app GET request. As such, we need to roundtrip all available information, which includes the KeyVault related properties.
Fixes #3871
> Sync container app revision KeyVault secrets 

- cli/azd/pkg/ext/event_dispatcher.go
Remove generic error wrapping for "failing invoking action".
> Remove err wrapping "invoking action"

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/appdetect_test.go
- cli/azd/internal/appdetect/javascript.go
- cli/azd/internal/appdetect/testdata/javascript-full/package.json
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/pkg/project/framework_service_docker.go
Add detection for vite as a static-front end. Remove Vue.js which uses Vite.
Update Java default port to 8080. Otherwise, Spring Boot fails to bind to port 80 in recent container images.
> easyinit: handle vite and Java

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/javascript.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/detect_confirm.go
- cli/azd/internal/repository/detect_confirm_test.go
- cli/azd/pkg/input/console.go
When no services are detected, we now allow the user manually add undetected services instead of erroring out. This allows the user to progressively discover languages supported.
We also provide a slight disclosure when adding a Python project without 'requirements.txt'.
Screenshot example:
> easyinit: Improve handling for empty state 

- cli/azd/pkg/input/console.go
The external prompt client returns us `json.RawMessage` values, per the API, but `PromptDialog` needs to return actual go values, as the rest of the system expects things like `string` or `int`.
Fixes #3902
> console: Fix type issues in `PromptDialog` with external prompting

- templates/todo/projects/python-mongo/.repo/terraform/infra/main.tf
B1 SKU seems to be too slow to run multiple Python apps.  
Upgrading this to B3 to match recent changes on the Bicep Todo versions.
Resolves #3893
> Upgrade Todo python apps to B3 sku

- cli/azd/pkg/project/framework_service_python_test.go
- cli/azd/pkg/tools/python/python.go
- cli/azd/pkg/tools/python/python_test.go
Fixes an issue activating python virtual environment within Windows.
Resolves #3927
This basically aligns both Windows & Posix implementations with the `RunList(...)` function with a slightly different environment activation command.
> Fixes running python scripts with virtual environment activation

- cli/azd/pkg/ai/util.go
- cli/azd/pkg/ai/util_test.go
- cli/azd/pkg/project/service_models.go
- cli/azd/pkg/project/service_target_ai_endpoint.go
- cli/azd/pkg/project/service_target_ai_endpoint_test.go
Adds links for AI studio workspace and deployment within the AI endpoint service target endpoints list.
> Display AI Studio links in endpoints list

- cli/azd/pkg/apphost/aca_ingress.go
- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-kafka.snap
- cli/azd/pkg/apphost/testdata/aspire-container.json
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
Fix issue: 
- Port was ignored when building the ingress for a non-http endpoint. Leaving the exposedPort as 0.
fix: https://github.com/dotnet/aspire/issues/4232
> fix exposedPort for Ingress

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
When using Helm with `azd` users can specify the `namespace` of where a helm release will be deployed to.  The Helm integration already supports this but the `namespace` property was unintentionally omitted in the schema.
> Adds missing `namespace` property to Helm configuration schema

- cli/azd/.vscode/settings.json
- cli/azd/pkg/devcenter/environment_store.go
- cli/azd/pkg/devcenter/environment_store_test.go
- cli/azd/pkg/devcenter/manager.go
- cli/azd/pkg/environment/data_store.go
- cli/azd/pkg/environment/local_file_data_store.go
- cli/azd/pkg/environment/local_file_data_store_test.go
- cli/azd/pkg/environment/manager.go
- cli/azd/pkg/environment/manager_test.go
- cli/azd/pkg/environment/storage_blob_data_store.go
- cli/azd/pkg/environment/storage_blob_data_store_test.go
- cli/azd/test/functional/initialize_test.go
- cli/azd/test/mocks/mockenv/mock_manager.go
Fixes #3861
What was happening in the linked issue is that the ARM deployment object was comparing the deployment object tags against the currently loaded devcenter environment instead of the found matching devcenter environment.
> Fixes issue selected environment with different environment type

- templates/todo/api/python/todo/models.py
- templates/todo/common/infra/bicep/app/apim-api-settings.bicep
- templates/todo/common/infra/bicep/app/applicationinsights-dashboard.bicep
- templates/todo/common/infra/bicep/app/sql-deployment-script.bicep
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/infra/main.bicep
- templates/todo/projects/csharp-cosmos-sql/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/infra/main.bicep
- templates/todo/projects/csharp-sql-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/csharp-sql/.repo/bicep/infra/main.bicep
- templates/todo/projects/csharp-sql/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/java-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/java-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/java-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-aks/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo-aks/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/nodejs-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/nodejs-mongo/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-aca/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo-aca/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo-swa-func/.repo/bicep/repo.yaml
- templates/todo/projects/python-mongo/.repo/bicep/infra/main.bicep
- templates/todo/projects/python-mongo/.repo/bicep/repo.yaml
Update the infra/core modules to AVM modules.
**1. Modules not replaced by AVM**
- **Monitoring (applicationinsights-dashboard)** : Missing the feature `Microsoft.Portal/dashboards`.
AVM issue link: https://github.com/Azure/bicep-registry-modules/issues/1130
AVM PR: https://github.com/Azure/bicep-registry-modules/pull/1974.
- **APIM**: Missing features `Microsoft.ApiManagement/service/loggers` and `Microsoft.ApiManagement/service/apis/diagnostics`.
AVM issue link: https://github.com/Azure/bicep-registry-modules/issues/1124
AVM PR: https://github.com/Azure/bicep-registry-modules/pull/2067
**2. Modules replaced by AVM**
- **App Service**
- **Key Vault**
- **App Service Plan**
- **SqlService**
- **Cosmos mongo**
- **Container registry**
- **Container app**
- **Container environment**
- …
> Update the infra/core modules to AVM modules

- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/containerapps/container_app_test.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/resources/alpha_features.yaml
Adding feature flag: `aca.persistDomains`
When turned on: `azd config set alpha.aca.persistDomains on` , azd will use any existing customDomains from a ACA before deploying  an update for it, preventing the deletion of any manually-configured custom domain from the Portal.
> [ACA] Persist current custom domain

- cli/azd/cmd/auth_login.go
- cli/azd/cmd/testdata/TestUsage-azd-auth-login.snap
- cli/azd/pkg/auth/manager.go
We had seen requests for this in the past, e.g., #2568. It would be useful to have for cases where you are running `azd` inside Azure (say as part of some deployment system you've put together) and want to use managed identity instead of having to have a long lived service princiapl.
By default `--managed-identity` uses the system assigned managed identity, but `--client-id` can be passed to use a user assigned one.
> Add `--managed-identity` to `azd auth login`

- templates/common/infra/bicep/core/host/container-apps.bicep
The template previously had this parameter exposed, to be passed on to the CA environment. It's used by multiple samples currently.
This fix restores the missing parameter.
> [core/bicep] Fix missing daprEnabled param in container apps template

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
This change adopts the same naming strategy that we use for non aspire based container workloads where we need to generate an image name.
This uses the same image name (but different tags) instead of creating a new image (with the timestamp baked into the image name) per deploy.
> aspire: Rework image naming strategy

- cli/azd/pkg/apphost/aca_ingress.go
- cli/azd/pkg/apphost/aca_ingress_test.go
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-kafka.snap
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-my-sql-abstract.snap
- cli/azd/pkg/apphost/testdata/TestAspireContainerGeneration-noVolume.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-nodeapp.snap
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
- cli/azd/test/functional/testdata/snaps/aspire-full/AspireAzdTests.AppHost/infra/pubsub.tmpl.yaml
fix: https://github.com/Azure/azure-dev/issues/4005
Using negative target port when resolving the `target port` as the way to communicate that the port should not be changed. When azd builds a net project and gets a port number from the build result, the port won't be used if the target port in the yaml template is negative. Instead, the negative target port is used (making it positive)
This fix is required for Aspire 8.1. For 8.0, folks need to add `launchProfileName: null` when adding a project so they can use this fix
> keep port when exists

- templates/common/infra/bicep/core/security/keyvault.bicep
In some scenario, it can be useful to access KV through the `getSecret()` function in Bicep/ARM templates.
> Add option to enable template deployment usage in Key Vault

- eng/pipelines/build-notice.yml
- eng/pipelines/templates/variables/image.yml
MacOS 11 devops images will be deprecated soon. This migration moves away from that process.
> Migrate from macos-11

- templates/common/infra/bicep/core/host/appservice.bicep
- templates/common/infra/bicep/core/host/functions.bicep
- add vnet option
- add option to enable managed identity on Functions backing storage (note: currently AZD isn't able to deploy Node/Python functions in that case, see https://github.com/Azure/azure-dev/issues/4025)
> Update functions/app service templates

- cli/azd/pkg/project/ai_helper.go
fix: https://github.com/Azure/azure-dev/issues/4037
We have started an internal conversation with AI service to check if the time it takes from creating a deployment to making it available is expected to be greater than 3 seconds, which is the current waiting time in azd.  
While we wait for the service, this PR unblocks templates using AI-Studio deployments by making azd to retry on 404 responses up to 5 times with a 10 sec interval. So, if after 50 sec the deployment is still returning 404, azd will return and fail
> ai helper wait for deployment

- cli/azd/CONTRIBUTING.md
Updates the local installation link of `golangci-lint`  in the CONTRIBUTING guide to the new location of the installation. The previous link returns a 404: Not found error
> Update golangci-lint local installation install link

- templates/common/infra/bicep/core/security/keyvault.bicep
- Allows KV to be referenced in ARM/Bicep template deployments using `getSecrets()` method.
- Fix description of `enabledForDeployment` option which specifically allows the KV to be accessed by compute resources during creation (for ex creation of a VM)
> Allow key vault to be used in template deployment

- cli/azd/pkg/tools/bicep/bicep.go
0.28.1 released 3 weeks ago. Support for MSGraph extension is in public preview.  
https://github.com/Azure/bicep/releases/tag/v0.28.1
> Update bicep to 0.28.1.

- cli/installer/fpm/test-rpm.Dockerfile
- cli/installer/test/Dockerfile.centos
- cli/installer/test/telemetry/centos.sh.telemetry.csv
centos7 is EOL since 6/30
https://www.redhat.com/en/topics/linux/centos-linux-eol
Moving to centos8 in this PR
fix: https://github.com/Azure/azure-dev/issues/4076
> Update cent os - dockerFile in tests with working mirrors

- cli/azd/cmd/env.go
- cli/azd/cmd/testdata/TestUsage-azd-env-get-value.snap
- cli/azd/cmd/testdata/TestUsage-azd-env.snap
- cli/azd/internal/repository/detect_confirm_apphost.go
- cli/azd/test/functional/env_test.go
Adds `azd env get-value keyName` command.
Fixes #3906
> Add azd env get-value

- cli/azd/resources/ai-python/ml_client.py
This pull request is a bugfix for a crash that occurs when using the `ai.endpoint` service host on a machine that has Python3.8 in $PATH.
#3718 introduces a new service host `ai.endpoint`, which works by leveraging the `azure-ai-ml` SDK in the [ml_client.py](https://github.com/Azure/azure-dev/blob/5bf8568b1566723be8bc2259c578df4f931cf430/cli/azd/resources/ai-python/ml_client.py) script. `azd` runs that script using whichever version of python is available in a user's $PATH.
The `ml_client.py` script type hints a function parameter by subscripting the builtin type `list`:
https://github.com/Azure/azure-dev/blob/5bf8568b1566723be8bc2259c578df4f931cf430/cli/azd/resources/ai-python/ml_client.py#L8
Support for subscripting the builtin "generic" types was only added to the language in Python …
> fix: Resolve `azd` crash when using the `ai.endpoint` service host with Python 3.8

- cli/azd/pkg/containerapps/container_app.go
- cli/azd/resources/alpha_features.yaml
Adding alpha feature `aca.persistIngressSessionAffinity`
Enable with `azd config set alpha.aca.persistIngressSessionAffinity on`
When enabled, Session Affinity is persisted (if manually turned on before) during deployment
fix: https://github.com/Azure/azure-dev/issues/3993
> persistIngressSessionAffinity

- cli/azd/cmd/config.go
I've been wanting to do this for a while.  It makes easier to see the output for what alpha features you have turned on
fix: https://github.com/Azure/azure-dev/issues/4119
> order azd config list-alpha output

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Pre/Post build hooks already exist but are missing from schema definition.  This enables more discoverability for scenarios where users need to perform an action after restoring but before package.
One scenario is for the VITE integration for front-end web apps.  Docker builds happen at the `build` state of the `azd` pipeline so users can hook into `prebuild` to set any `VITE_` environment variables needed for building container images.
Adds missing docs for `prebuild` and `postbuild` service lifecycle hook.
https://github.com/MicrosoftDocs/azure-dev-docs/pull/1399
> Adds pre/post build hooks to service hooks definitions schema

- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDashboardGeneration-resources.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireDockerGeneration-resources.bicep.snap
- cli/azd/resources/apphost/templates/resources.bicept
- cli/azd/test/functional/testdata/snaps/aspire-full/infra/resources.bicep
fix: https://github.com/Azure/azure-dev/issues/4147
> Remove Admin Access from Aspire - ACR

- cli/azd/internal/scaffold/scaffold_test.go
- cli/azd/pkg/azd/default.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/bicep/bicep_test.go
- cli/azd/test/functional/aspire_test.go
When we started to depend on external tools, we used a pattern of defining an interface to represent the capabilities of the tool which the rest of the system dependend on.  The thought was having this interface indirection would help us with unit-testing, because we could mock different parts of the tool directly instead of depending on mocks via the external command runner.
In practice, we never did this, when we test things, we just mock at the `exec.CommandRunner` layer or use something like the recorder to capture all the external tool interactions and replay them later.
Since we don't have multiple implementations of the interface, let's just remove it and write things in the more direct style as we haven been doing more recently where we don't have the intermediate interface.
With …
> tools/bicep: Remove `BicepCli` interface

- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/azdo_provider_test.go
fix: https://github.com/Azure/azure-dev/issues/1072
This PR updates the logic for validating Azure devops git remotes and how to extract the project and repo name from it
fix: https://github.com/Azure/azure-dev/issues/1896
> remove azdo git remote constraint for dev.azure.com only

- cli/azd/internal/appdetect/appdetect.go
- cli/azd/pkg/osutil/osversion/osversion.go
- cli/azd/test/cmdrecord/proxy/main.go
- cli/azd/test/mocks/mockaccount/mock_manager.go
This addresses a handful of issues identified by `gopls check` but which require some careful inspection:
- `appdetect.go` was ignoring a parameter for a directory entry, once that was removed, we were able to combine some methods together.
- `main.go` in the recorder proxy was using `errors.Is` when instead of `errors.As` leading to possible nil derefrences later.
- `mock_manager.go` was modifying state of a value which was discarded during loop iterations, it has been rewritten to mutate the value in the slice which will be returned, which seemed like what was intended.
- `osversion.go` has a return value mismatch on the platforms we don't care about, so the dummy implementation was fixed to match the others.
> Fix `gopls check` issues

- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_dotnet.go
- cli/azd/pkg/project/framework_service_maven.go
- cli/azd/pkg/project/framework_service_noop.go
- cli/azd/pkg/project/framework_service_npm.go
- cli/azd/pkg/project/framework_service_python.go
- cli/azd/pkg/project/framework_service_swa.go
- cli/azd/pkg/project/project_manager.go
- cli/azd/pkg/project/service_manager.go
- cli/azd/pkg/project/service_manager_test.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_ai_endpoint.go
- cli/azd/pkg/project/service_target_aks.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/pkg/project/service_target_functionapp.go
- cli/azd/pkg/project/service_target_springapp.go
- cli/azd/pkg/project/service_target_staticwebapp.go
This modifies the `RequiredExternalTools` method on both the `FrameworkService` and `ServiceTarget` interfaces to accept the `ServiceConfig` of the service in question we are fetching tools for.
This allows the set of tools a to be conditional based on the service configuration, which we will exploit later when supporting docker remote builds via ACR so we can say the docker CLI is not a required tool.
> project: Pass `ServiceConfig` to `RequiredExternalTools`

- cli/azd/internal/repository/detect_confirm_apphost.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/pipeline_manager_test.go
> Allow .yaml and .yml extension for azure-dev pipeline files

- cli/azd/pkg/infra/azure_resource_manager.go
- cli/azd/pkg/tools/bicep/bicep.go
We had a panic in our display code when rendering data if you were using a the microsoft graph provider in bicep (a new extensibility feature) because some of the properties of the ARM operation object were not present.
This change adds additional guards to our rendering logic to ignore operations that don't have a complete set of data.
Fixes #4169
> bicep: Fix panic during deployment progress rendering

- cli/azd/cmd/container.go
- cli/azd/pkg/devcenter/provision_provider_test.go
- cli/azd/pkg/tools/azcli/azcli.go
- cli/azd/pkg/tools/azcli/azcli_test.go
- cli/azd/test/functional/cli_test.go
- cli/azd/test/mocks/mockazcli/mocks.go
When we started the project, we used the `azcli` package to run an instance of `az` to do most of our management plane operations. Over time we moved away from this (mostly rewrting it implementation on top of `azure-sdk-for-go` packages) and as we did this we moved a bunch of the logic out of the `azcli` package and into other packages.
As we did that, we ended up leaving some dead code behind that wasn't obviously dead (either becaue it was exported but not consumed or because our DI pattern makes it non obvious when an injected value is unused because it is written to via an exported constructor).
This change cleans up this dead code, simplifying the codebase.
> azcli: Remove some dead code

- cli/azd/cmd/container.go
- cli/azd/internal/vsrpc/server_session.go
- cli/azd/pkg/auth/cloudshell_credential.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
- cli/azd/pkg/auth/remote_credential.go
- cli/azd/pkg/azsdk/azsdk.go
- cli/azd/pkg/azsdk/client_options_builder.go
- cli/azd/pkg/experimentation/assignment.go
- cli/azd/pkg/github/federated_token_client.go
- cli/azd/pkg/github/federated_token_client_test.go
- cli/azd/pkg/httputil/http_client.go
- cli/azd/pkg/input/console.go
- cli/azd/pkg/input/external_prompt_client.go
- cli/azd/pkg/templates/awesome_source.go
- cli/azd/pkg/templates/source_manager.go
- cli/azd/pkg/templates/url_source.go
- cli/azd/test/functional/up_test.go
- cli/azd/test/mocks/mock_context.go
We needed to control the ability to replace the HTTP Transporter to
use before we adopted any types from the azure-sdk. Now that we are
built around azure-sdk, instead of having our own copy of this
abstraction, just use the version from azure-sdk.
> Remove `httputil.HttpClient` in favor of `policy.Transporter`

- cli/azd/cmd/container.go
- cli/azd/pkg/environment/manager_test.go
- cli/azd/pkg/httputil/http_client.go
This type existed so that we could inject the UserAgent as a component in our DI container but we never exploited this in any interesting way.
> Remove `httputil.UserAgent`

- cli/azd/internal/tracing/events/events.go
- cli/azd/internal/tracing/fields/fields.go
- cli/azd/pkg/account/subscriptions_manager.go
- cli/azd/pkg/tools/bicep/bicep.go
- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/pack/pack.go
These events were added with some intent of utilization that hasn't come to fruition. Cleaning them up to make way for more important events.
> Remove under-utilized events

- cli/azd/pkg/project/framework_service_maven.go
- cli/azd/pkg/project/framework_service_maven_test.go
- cli/azd/pkg/tools/maven/maven.go
This change adds support for deploying Java applications to `function` host.
Manually tested for both normal and flex consumption function apps.
Addresses #4155
> project: Add support for Java functions

- cli/azd/pkg/exec/cmdtree_windows.go
To assign the process to the job object after we create it, we need the `windows.Handle` that backs the process we started with `os/exec`. This was not exported and so we used some gnarly casting to cast the `os.Process` to a structure we authored that had the same layout of `os.Process` so we could grab the handle property.
This is unsafe if the layout of the `os.Process` changes, which it did in Go 1.23.
Move to code that doesn't depend on the internals of `os.Process` by using the exported Pid to call `windows.OpenProcess` to get a handle and then pass that along to `windows.AssignProcessToJobObject`.
> exec: Don't depend on internals of `os.Process`

- cli/azd/test/recording/proxy.go
- cli/azd/test/recording/proxy_test.go
- cli/azd/test/recording/testdata/recordings/TestBlobClientGetProperties.yaml
When you call the `blockblob.GetProperties`, the azure-sdk-for-go makes a HEAD request to fetch information about the target blob, and uses the result to hydrate the properties object that is returned. The `ContentLength` property (which tells you how big the blob is) is set based on the `Content-Length` header in the response. The type of `ContentLength` is `*int` and if the `Content-Length` header is not set in the response, then the value will remain `nil`.
As part of the new ACR remote build feature, to stream logs from the remote build to the console we use `blockblob.GetProperties` to fetch the length of the remote build log file and then do a range request to fetch the content that we have not yet processed. When I wrote an end to end test and tried to record it, this code ended up …
> recording: Improvements to `Content-Length` handeling

- cli/azd/internal/tracing/attributes.go
- cli/azd/internal/tracing/attributes_test.go
Sometimes, we need to track "a unique set of strings". This helps with that.
> tracing: Add the ability to append attributes with unique elements

- cli/azd/test/recording/proxy_test.go
- cli/azd/test/recording/recording.go
- cli/azd/test/recording/testdata/recordings/TestBlobClientGetProperties.yaml
When developing the test I unintentionally set
`recorder.ModeRecordOnly` causing us to recrate the recording per run. Turning that off exposed an issue where since the `httptest` package picks a different port each run it meant that the recording would not match because the port was different, causing us to fail to playback the test.
For now, use a fixed port for our test server, which ensures we have a stable `host` value across runs, at the expense of disallowing multiple copies of the test from running at the same time.
> recording: Use fixed port in `TestBlobClientGetProperties`

- cli/azd/pkg/pipeline/github_provider.go
Allow a hostname without a .xxx suffix. This will allow hostname alias like `foo` to be a valid hostname
fix: https://github.com/Azure/azure-dev/issues/4185
> relax gh pipeline provider even more

- cli/azd/cmd/hooks.go
- cli/azd/cmd/middleware/hooks_test.go
- cli/azd/pkg/ext/hooks_manager.go
- cli/azd/pkg/ext/hooks_manager_test.go
- cli/azd/pkg/ext/hooks_runner.go
- cli/azd/pkg/ext/hooks_runner_test.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/testdata/Test_Hooks_Config_Yaml_Marshalling-Multiple_hooks_per_event.snap
- cli/azd/pkg/project/testdata/Test_Hooks_Config_Yaml_Marshalling-No_hooks.snap
- cli/azd/pkg/project/testdata/Test_Hooks_Config_Yaml_Marshalling-Single_hooks_per_event.snap
As we start to mature the `azd` hooks experience with specialized hook implementations / operations we will need to support the concept of running multiple hooks per event.
For example post provisioning you may want to run a custom azd operation hook followed by a more generic script hook.
This PR extends the hook configuration to support single hook configuration as supported today as well as multiple hooks per event name.
```yaml
name: test-proj
services:
api:
project: src/api
language: ts
hooks:
postprovision:
shell: sh
run: scripts/postprovision.sh
hooks:
postprovision:
shell: sh
run: scripts/postprovision.sh
```
```yaml
name: test-proj
services:
api:
project: src/api
language: ts
hooks:
postprovision:
- shell: sh
run: scripts/postprovision1.sh
- …
```
> Adds support for multiple hooks per event

- cli/azd/cmd/container.go
Fixes the blinking provisioning output when calling `azd up`
Fixes #4266
The new `DeploymentManager` component was registered as a `singleton` within our IoC container and was also taking a dependency on a scoped `console` component.  
Since `azd up` creates a separate container scope per command invocation it was causing the console instance to be used from the root command invocation instead of the scoped instance of the provision command.
The calls to `console.ShowSpinner` used in the bicep provider vs the progress display component used different instances of the console component which allowed the bypassing of the mutex to ensure a progress lock was not already in place.
The fix was to update the `DeploymentManager` to also be registered as a scoped component to leverage the correct …
> Fixes blinking provisioning output

- cli/azd/pkg/project/resource_manager.go
Fixes issue/panic where an empty ServiceTarget should be resolved for service targets that support delayed provisioning.
(Regression from Deployment stacks work)
> Fixes issues resolving target resource for service targets that support delayed provisioning

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_test.go
Since we expect an `azd` project to be used across operating systems which use `/` and `\` as path seperators, we need a common way of writing paths in `azure.yaml` that works across both. In the path we supported using both `\` and `/` in `azure.yaml` (and went out ouf or way in the Aspire case to write the platform specific version during `init`) but in some cases this would lead to weird behavior when you then puth the project into GitHub actions and *nix runners would look for files that may not exist, due to the path seperator.
To address this, we update our `ProjectConfig` yaml parsing and saving to assume forward slash seperated paths, and then use `filepath.FromSlash` and `filepath.ToSlash` on the boundaries. This means the data stored at runtime inside `ProjectConfig` is using …
> project: Use `/` as path seperator in `azure.yaml`

- cli/azd/pkg/azureutil/location.go
fix #4184 
STG location was originally used for some testing on Aspire. With current usage, we should delete it as we are not using it anymore and we shouldn't expose and confuse users these internal STG locations.
> filter out location for STG

- cli/azd/pkg/tools/github/github.go
- cli/azd/pkg/tools/github/github_test.go
Updating the expected message for gh-cli not-logged-in error after a regression on newer gh-cli version.
The wording was changed for newer version making azd to fail to recognize the error message. The change here make make azd
to know when this error happens again.
fix: https://github.com/Azure/azure-dev/issues/4275
> fix gh cli breaking change parsing err msg

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Updates `azure.yaml` schema to support both single and multi-hook configuration
> [!IMPORTANT] 
> Should not merge till release day since schema updates are not managed as part of the release.
```yaml
name: test-proj
services:
api:
project: src/api
language: ts
hooks:
postprovision:
shell: sh
run: scripts/postprovision.sh
hooks:
postprovision:
shell: sh
run: scripts/postprovision.sh
```
```yaml
name: test-proj
services:
api:
project: src/api
language: ts
hooks:
postprovision:
- shell: sh
run: scripts/postprovision1.sh
- shell: sh
run: scripts/postprovision2.sh
hooks:
postprovision:
- shell: sh
run: scripts/postprovision1.sh
- shell: sh
run: scripts/postprovision2.sh
```
> Updates `azure.yaml` schema to support single or multi hook configuration

- cli/azd/pkg/pipeline/azdo_provider.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
Fixing a nil credential due to a wrong validation when user did not use --auth-type arg.
The azdo provider was taking the empty argument as a way to default to Federated Credential, ignoring if
Terraform forced the use of client-secret before.
This fix uses the CI provider's credential options that are generated before configuring the pipeline to know
the authentication type, instead of looking at the commands arguments again.
Fix: https://github.com/Azure/azure-dev/issues/4273
> Fix azd-pipeline-config for terraform forced client secret)

- cli/azd/.vscode/cspell.yaml
- cli/azd/pkg/config/config.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/containerapps/container_app_test.go
- cli/azd/pkg/convert/util.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_target_containerapp.go
- cli/azd/pkg/project/service_target_dotnet_containerapp.go
- cli/azd/test/mocks/mockazsdk/container_apps.go
- cli/azd/test/mocks/util.go
- Adds support to specify an explicit `api-version` to use for Container apps that is leveraged during container app deployment to avoid getting and unmarshalling to incompatible api-versions and losing configuration data set in bicep.
- Updates deployment scenarios to be more loosely coupled to avoid loosing custom configuration data during JSON marshalling to hard coded SDK versions.
If an `apiVersion` is not set in the service config the SDK will fall back to use the SDK `api-version` it was originally from.
Fixes: #4264
```yaml
name: todo-nodejs-mongo-aca
services:
web:
project: ./src/web
language: js
apiVersion: 2024-02-02-preview # Force `azd` to use this API version for GET/PATCH operations
api:
project: ./src/api
language: js
apiVersion: …
```
> Support configurable `api-version` for container app deployments

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
Small change to add a spinner message to `azd down`.  Remove remaining to-dos.
Before:
After:
> bicep: add spinner to `azd down`

- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/deployment_stacks_test.go
- cli/azd/test/functional/login_test.go
- eng/pipelines/templates/jobs/build-cli.yml
- eng/pipelines/templates/steps/azd-login.yml
Move away from a long lived client secret for auth during CI testing
in favor of federated credentials via a service connection.
(To unblock the builds I am seeing how far we can get with our old
trick of delegating stuff to `az` before we teach `azd` how to use
`AzurePipelinesCredential`.)
Contributes To #4341
> ci: Use federated auth in CI

- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_ProvisionState.yaml
Updates functional test to run provision preview to validation the creation or skipping of resources.
> Updates functional test to run provision preview

- templates/tests/test-templates.sh
Removing `--preview` checks from test-template.
We decided to do this because `--preview` is not compatible with deployment stacks, which is ON for test-template pipeline after turning all alpha features ON.
The `provision --preview` tests will be covered as functional test in azd-cli pipelines.
> remove preview from test templates

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
This adds the `remoteBuild` configuration knob which was added in azure/azure-dev#4161 to our schema for `azure.yaml`.
Fixes #4353
> core: Update `azure.yaml.json` for `remoteBuild`

- README.md
As discussed with @spboyer, this PR adds reference to template artifacts for standardization for discoverability.
> docs: add template authoring guidelines to readme

- cli/azd/pkg/project/service_target_aks.go
Fixes #4376,  Enables remote build support for AKS. 
Set the `docker.remoteBuild` property to `true` in the `azure.yaml` file.
```yaml
name: todo-nodejs-mongo-aks
metadata:
template: todo-nodejs-mongo-aks@0.0.1-beta
services:
web:
project: ./src/web
dist: dist
language: js
host: aks
docker:
remoteBuild: true
api:
project: ./src/api
language: js
host: aks
docker:
remoteBuild: true
k8s:
ingress:
relativePath: api
```
> Enable remote build support for AKS

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
With this change, we remove the in-memory `main.parameters.json` cache.
Backstory: In the old days of `azd`, we introduced in-memory caching for `main.parameters.json` with #3155 to avoid a re-prompt when the user declines the prompt "Save the value in the environment for future use?". We added this as a way to communicate within `azd` that "this value is configured for the current azd process lifetime".
After #3479, we ended up always saving the values to `config.json` and remove the "Save the value in the environment for future use?" prompt. Since then, the in-memory caching just reduces an extra load from disk, but behaviorally act the same.
Fixes #3973, #4310, 
Since #4310 is implemented as an internal `preprovision` hook that sets `SERVICE_X_RESOURCE_EXISTS` and shares the same root …
> bicep: remove `main.parameters.json` caching

- cli/azd/pkg/input/console.go
In this change, we introduce `AZD_FORCE_TTY` as a mechanism to force TTY output behavior.
Helps with #4311
> Make TTY output a forceable thing

- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/project_config_test.go
Resolves #4062 
Updates docker `buildargs` in `azure.yaml` to support environment variable substitutions.
> Updates docker `buildargs` to expandable strings

- cli/azd/cmd/root.go
- cli/azd/test/functional/experiment_test.go
While we troubleshoot blocking issues when communicating with our backend experimentation we will remove the experimentation middleware from the global middleware list since we are not running any active experiments.
fix: https://github.com/Azure/azure-dev/issues/4410
> Remove experimentation middleware from global middleware list

- .vscode/cspell.global.yaml
- .vscode/cspell.misc.yaml
- schemas/alpha/azure.yaml.json
> [!IMPORTANT]
> Do not merge till after release
Updates the alpha schema for `azure.yaml` to include the optional deployment stacks configuration.
The `deploymentStacks` property will light up when `provider: bicep`. When specifying the `deploymentStacks` property the user must configure at least one of the properties otherwise the whole property can be omitted and use the internal defaults.
> Updates `azure.yaml` schema for deployment stacks configuration

- cli/azd/internal/scaffold/funcs.go
- cli/azd/internal/scaffold/funcs_test.go
Improve `BicepName` to automatically convert casing for fully upper-cased character.
Example: `THIS_IS_MY_VAR_123` is now translated to `thisIsMyVar123`.
> scaffold: `BicepName` to handle full-upper-cased characters

- cli/azd/pkg/tools/dotnet/dotnet.go
SDK_CONTAINER_ are now prefixed with DOTNET_CONTAINERS_ in .NET 9 (old vars work as a fallback). Set both for now until .NET 8 is out of support.
>  Use DOTNET_CONTAINER_*

- .vscode/cspell-github-user-aliases.txt
- cli/azd/pkg/ai/config.go
- cli/azd/pkg/alpha/alpha_feature.go
- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/containerapps/container_app.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/osutil/expandable_string_test.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config_test.go
- cli/azd/pkg/project/project_test.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/tools/kubectl/kube_config.go
- cli/azd/pkg/tools/kubectl/models_test.go
- cli/azd/pkg/tools/kubectl/util.go
- cli/azd/pkg/workflow/config_test.go
- cli/azd/pkg/workflow/workflow.go
- cli/azd/test/cmdrecord/cassette.go
- cli/azd/test/cmdrecord/cmdrecorder_test.go
- cli/azd/test/cmdrecord/proxy/main.go
- cli/azd/test/recording/recording.go
- go.mod
- go.sum
Update library gopkg.in/yaml.v3 to github.com/braydonk/yaml.
> Note: gopkg.in/yaml.v3 library has not had any activity since May 27, 2022.
In upcoming features for azd, we will start round-tripping YAML by marshaling and unmarshaling text. When YAML is round-tripped this way using the current gopkg.in/yaml.v3 library, certain textual characteristic is lost.
```yaml
cmd: >
echo "Hello"
echo "World!"
```
When marshaled, then unmarshaled, results in:
```yaml
cmd: echo "Hello" echo "World"
```
```yaml
sequences:
- a
- b
```
When marshaled, then unmarshaled, results in:
```yaml
sequences:
- a
- b
```
i.e. Sequences are always indented once.
Fortunately, [github.com/braydonk/yaml](https://github.com/braydonk/yaml) is a fork of gopkg.in/yaml.v3 that powers …
> go.mod: update library gopkg.in/yaml.v3 to github.com/braydonk/yaml

- cli/azd/pkg/ext/hooks_manager.go
- cli/azd/pkg/ext/hooks_manager_test.go
Fixes #4451 
Resolves an issue when an `azure.yaml` has missing hook configuration:
```yaml
hooks:
preprovision:                      # Missing configuration block
postdeploy: 
run: ./myscript.sh
```
> Fixes panic on missing hook configuration

- cli/azd/pkg/azsdk/funcapp_host_client.go
Add polling delay and retries for deployments that take awhile to "come alive"
Fixes #4439
> func: add mitigation for deployments that take awhile to "come alive"

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireProjectV1Generation-cache.snap
- cli/azd/pkg/apphost/testdata/aspire-projectv1.json
fix: https://github.com/Azure/azure-dev/issues/4483
> fix missing quotes for bicepparams

- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/initializer.go
- cli/azd/internal/repository/initializer_test.go
Refactor infra generation logic into a new method.
To set up a cleaner future diff, add alpha feature manager as well.
> chore: refactor infra generation app_init.go 

- ext/azuredevops/CONTRIBUTING.md
- ext/azuredevops/setupAzd/package-lock.json
- ext/azuredevops/setupAzd/package.json
- ext/azuredevops/setupAzd/task.json
- ext/azuredevops/setupAzd/tests/InstallFail.ts
- ext/azuredevops/setupAzd/tests/InstallSuccess.ts
- ext/azuredevops/setupAzd/tests/invalidVersion.ts
- ext/azuredevops/vss-extension.json
This PR updates the Install azd task for Azure DevOps to remove a warning b/c node 20 is not defined in the execution.
Updating also npm packages and releasing version 0.14
Fix: https://github.com/Azure/azure-dev/issues/4492
> azdo ext add node 20 for warning

- cli/azd/internal/repository/app_init.go
- cli/azd/test/functional/init_test.go
A small refactor to integrate the alpha switch change.
In the easy init flow, we would want `azd init` without composability alpha feature enabled to continue materializing infrastructure as-is. If composability is enabled, we would want to hold the infrastructure in-memory.
> compose: refactor to add alpha switch

- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
Refactor db prompt logic in infra_confirm.go
> chore: refactor db prompt in infra_confirm.go

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/pkg/project/scaffold_gen_test.go
- cli/azd/pkg/project/scaffold_gen_util.go
- cli/azd/pkg/project/scaffold_gen_util_test.go
Add primitive support for envsubst expressions configuration.
> compose: add experimental envsubt 

- .devcontainer/devcontainer.json
- .devcontainer/light/devcontainer.json
The old repo used for the golangci-lint feature is abandoned and a new working release was created in a new repo.
The current release properly supports ARM-based computers.
This PR Fixes #4505
> Remove the feature to include `golangci-lint` since it's already included with `ghcr.io/devcontainers/features/go:1`

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/yamlnode/yamlnode.go
- cli/azd/pkg/yamlnode/yamlnode_test.go
Add functionality for YAML node manipulation using dotted-path syntax.
This will be used in upcoming work that is aimed to manipulate YAML nodes.
> yamlnode: Dotted-path YAML manipulation

- cli/azd/pkg/devcenter/manager.go
- cli/azd/pkg/devcenter/manager_test.go
- cli/azd/pkg/devcenter/provision_provider.go
- cli/azd/pkg/devcentersdk/api_version_policy.go
- cli/azd/pkg/devcentersdk/developer_client_test.go
- cli/azd/pkg/devcentersdk/environment_request_builders.go
- cli/azd/pkg/devcentersdk/models.go
- cli/azd/pkg/devcentersdk/outputs_request_builder.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_DevCenter_Init_Up_Down.yaml
Resolves #3958 
This update moves away from manually reading Azure deployment outputs to leveraging the Outputs API directly from the ADE team. This enables a seamless outputs experience across their supported runners including ARM, Bicep, Terraform and other custom runners.
> Devcenter environments Outputs API Integration

- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/pkg/tools/dotnet/dotnet.go
Per https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_nologo:
> Specifies whether .NET welcome and telemetry messages are displayed
on the first run. Set to true to mute these messages (values `true`,
`1`, or `yes` accepted) or set to false to allow them (values
`false`, `0`, or `no` accepted). If not set, the default is `false`
and the messages will be displayed on the first run.
Since there are cases where we interpret the output of the `dotnet` CLI (for example, when calling `dotnet msbuild
--getProperty:IsAspireHost`) we should set this value to ensure that this message is not printed, which would break our deserialization logic, which expects just JSON data to be printed to stdout.
Fixes #4513
> dotnet: Set `DOTNET_NOLOGO` when running external commands

- cli/azd/internal/appdetect/dotnet_apphost.go
- cli/azd/internal/vsrpc/utils.go
- cli/azd/pkg/project/dotnet_importer.go
- cli/azd/pkg/project/importer_test.go
- cli/azd/pkg/tools/dotnet/dotnet.go
In addition to the `IsAspireHost` property we will now look at the project capabilities to see if an `Aspire` capability is listed and if treat the project as an AppHost project. This aligns `azd`'s behavior with other tooling like Visual Studio which uses the project capabilities to determine if the project is an App Host or not.
The .NET Team asked us to include this in our sniffing logic (but to continue to check `IsAspireHost` as well).
Fixes #4364
> aspire: Consider Aspire Capability when detecting AppHost

- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/app_init_test.go
- cli/azd/pkg/alpha/alpha_features.go
- cli/azd/pkg/project/importer.go
- cli/azd/pkg/project/importer_test.go
- cli/azd/resources/scaffold/templates/next-steps-alpha.mdt
Generate resources in `azure.yaml` and delay infrastructure generation if `alpha.compose` is enabled
> easy-init: generate resources in `azure.yaml`

- eng/pipelines/templates/steps/configure-oidc-auth.yml
- eng/pipelines/templates/steps/template-test-run-job.yml
This change reworks the `test-templates` test legs to use OIDC and move to our TME subscription.
To do so, we capture the relevent `AZURESUBSCRIPTION_` environment variables that are set by the AzureCLI task and then flow them into the dev container when we run tests. This allows us to do `azd auth login` inside the devcontainer but still use OIDC so we don't have a long lived secret.
The call to `az login` was removed because we don't yet have a way to have this work well with ODIC in the container. This means the terraform flavor of the tests won't work (since auth is broken) but these legs have been broken in both the bicep and terraform flavors for a while, so this moves us in a better direction (and gets us off of client secrets and onto TME for these tests).
Contributes To #4341
> ci: Use ODIC and TME for `test-templates`

- cli/azd/cmd/init.go
- cli/azd/pkg/project/project.go
- cli/azd/pkg/project/project_config.go
- cli/azd/pkg/templates/template_manager.go
- cli/azd/test/functional/init_test.go
This change surfaces "Create a minimal project" as a main menu option in `init`.
**Background**: Before this change, initializing a minimal project would require selecting "Initialize a template -> Minimal". This was found to be confusing for users during user studies. There has also been general user feedback about discoverability with this flow.
**Functional changes**: When compose is enabled, only a project file is generated. When compose is not enabled, the previous functional behavior is retained -- no UX changes made.
UX (compose enabled):
> init: surface minimal option

- cli/azd/resources/scaffold/templates/resources.bicept
Fix some errors found in scenario: frontend + backend + mongodb
- Check the comments below to see the detailed error.
- Link to related PR: https://github.com/azure-javaee/azure-dev/pull/14
- Link to sample project: https://github.com/rujche/todo-java-mongo-aca/tree/sample-project-used-todemo-detect-mongodb-in-azd
> Fix some errors found in scenario: frontend + backend + mongodb

- schemas/alpha/azure.yaml.json
> compose: update schema for alpha

- cli/azd/cmd/show.go
- cli/azd/cmd/testdata/TestUsage-azd-show.snap
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/pkg/environment/environment.go
- cli/azd/pkg/infra/util.go
- cli/azd/pkg/output/ux/show.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/resources.bicept
- go.mod
- go.sum
Allow for `show <resource>`
The only supported resources are: Container Apps, and Open AI Models.
> compose: `show <resource>`

- cli/azd/pkg/project/scaffold_gen.go
Fix error about passing by value in `for range`. 
Refs: https://go.dev/wiki/Range
> ![image](https://github.com/user-attachments/assets/2bc38735-6546-49b2-9f1d-8ee2c45ad9a4)
> Fix error about passing by value in `for range`

- .github/workflows/lint-bicep.yml
The current version that is installed on the runners (0.31.34) has some bugs around linting and causes lint warnings during our legs. These errors are not present on the latest Bicep CLI.
Force an upgrade of the binary that is installed as part of the test runner to latest version. We should be able to remove this step once new image is built with an upgraded bicep (the `README.md` at https://github.com/actions/runner-images/tree/main/images/ubuntu has information about what is on the runner.)
>  ci: Update bicep in lint-bicep to v0.31.92

- cli/azd/test/functional/cli_test.go
- cli/azd/test/functional/deployment_stacks_test.go
- cli/azd/test/functional/login_test.go
We should be able to re-enable the tests now. The one exception is the `azd login` test that validated login with a long lived client secret, since we no longer have a service principal with a long lived client secret.
We'll have to make due without the end to end coverage here - but in practice we have good coverage at the unit test level of much of the code here, so we should be okay.
> tests: Re-enable tests disabled against #4341

- cli/azd/internal/cmd/add/add_configure_host.go
- cli/azd/internal/repository/app_init_test.go
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/pkg/project/container_helper.go
- cli/azd/pkg/project/container_helper_test.go
- cli/azd/pkg/project/framework_service.go
- cli/azd/pkg/project/framework_service_docker.go
- cli/azd/pkg/project/framework_service_docker_test.go
- cli/azd/pkg/project/service_config.go
- cli/azd/pkg/project/service_target_aks_test.go
- cli/azd/pkg/project/service_target_containerapp_test.go
- cli/azd/test/functional/testdata/recordings/Test_CLI_Up_Down_ContainerAppDotNetPublish.dotnet.yaml
- cli/azd/test/functional/testdata/recordings/Test_CLI_Up_Down_ContainerAppDotNetPublish.yaml
- cli/azd/test/functional/testdata/samples/containerapp/infra/web.bicep
- cli/azd/test/functional/testdata/samples/containerapp/src/dotnet/Dockerfile
- cli/azd/test/functional/up_test.go
- cli/azd/test/recording/sanitize.go
The `dotnet` tool has native support for producing (and pushing) a container image. This does not require a local docker daemon and in general "does the right thing" and is the prefered way for .NET customers to produce container
images. https://learn.microsoft.com/dotnet/core/docker/publish-as-container gives a good overview of how this support works and we've been using it to build and push container images for Aspire apps.
This change updates things such that we can use this support when building a non Aspire based .NET app. If a `Dockerfile` exists, we respect it, but otherwise instead of trying to use Oryx to produce a container image, we will use `dotnet publish`.
A new recorded test was added - it builds on top of the existing `containerapp` sample, and the test aranges to remove …
> dotnet: Support `dotnet publish` to produce container image

- eng/pipelines/templates/stages/1es-redirect.yml
- eng/pipelines/templates/stages/vscode-publish-manual.yml
- eng/pipelines/templates/stages/vscode-sign.yml
- eng/pipelines/templates/steps/publish-vscode.yml
- eng/scripts/New-VsixSigningManifest.ps1
**DO NOT MERGE UNTIL 1es-redirect.yml is reverted** 
Uses `vsce` to prepare extension for signing and signs using ESRP. 
Signature verification example: 
```
> vsce verify-signature --packagePath E:\temp\vsix-sign\vsix-4\azure-dev-0.9.0-alpha.1.vsix --manifestPath E:\temp\vsix-sign\vsix-4\azure-dev-0.9.0-alpha.1.manifest --signaturePath E:\temp\vsix-sign\vsix-4\azure-dev-0.9.0-alpha.1.signature.p7s
Signature verification result: Success
Package file size:  722521
Signature archive file size:  9075
Manifest file size:  2644
Signature file size:  10359
Manifest file hash:  l6nQX6H2kYvVDTeM5Q+6+v3H6OLwvNgMKHTGQySTnWY=
Signature file hash:  1nMULsj/wyU9SApKOhgKu5d5O/jve4+oLOUaSQAgADg=
Package file hash:  rgG6yUjfu1vC4qJAhwRxA6zduhgx9oozVb68Q5HUHag=
ManifestPackageIntegrityPolicy succeeded. …
```
> vscode signing

- cli/azd/.vscode/cspell.yaml
- cli/azd/test/internal/tfoidc/main.go
- eng/pipelines/templates/steps/template-test-run-job.yml
The terraform legs in our template test pipelines have been broken since we moved to ODIC and this change gets them working again. Because we run the template tests inside a dev container, we can't leverage the AzureCLI task to configure OIDC for `az`, so we have to do things the hard way.
The AzureRM Terraform Provider does support OIDC auth an even has knobs to configure the URL and token used when fetching the federated token used to do the ODIC dance, but it expects a slightly different protocol than what Azure Pipelines provides, so we now have a small adapter program `tfoidc` which exposes the endpoint in the format that the provider expects (it's the format spoken by GitHub Actions) which proxies to the Azure Pipelines version.
In addition, to support local-exec scenarios where …
> tests: Use OIDC for Terraform in template-tests

- cli/azd/cmd/templates.go
- cli/azd/cmd/testdata/TestUsage-azd-template-source-add.snap
- cli/azd/cmd/testdata/TestUsage-azd-template-source.snap
Fixes #4608
I also added some missing examples, but if people think there are too many examples, I'm fine with reverting them as well.
> Update `azd template source` help text

- cli/azd/pkg/auth/errors.go
- cli/azd/pkg/auth/errors_test.go
Fixes #4559 so that the full Entra error description is shown to the user when there's an auth failure. In addition, the instruction text to reauthenticate is now wrapped in a suggestion.
**Existing behaviour:**
**New behaviour:**
> Show full Entra error description on auth failure

- cli/azd/test/functional/restore_test.go
- cli/azd/test/functional/telemetry_test.go
These tests are failing on macOS in CI due to the docker daemon not being configured correctly. Disable them against #4612 which tracks fixing the issue.
> ci: Disable tests against azure/azure-dev#4612

- cli/azd/cmd/build.go
- cli/azd/cmd/env.go
- cli/azd/cmd/restore.go
- cli/azd/internal/cmd/provision.go
- cli/azd/internal/vsrpc/environment_service_refresh.go
- cli/azd/pkg/project/project_manager.go
- cli/azd/test/functional/restore_test.go
- cli/azd/test/functional/telemetry_test.go
When running `azd restore` for a Docker based project, we were requiring that the docker tool itself was installed instead of whatever tool would be used by the actual source project. This has two implications:
1. If you didn't have the tool that was going to be invoked during `restore` installed (i.e. you didn't have `npm` for a node based project), we wouldn't detect the fact upfront and provide a nice error, we'd fail later when we tried to invoke the tool.
2. As of #4567, we now require that the docker daemon be running to consider docker "installed" (which is reasonable for cases where we are going to invoke docker commands) and so `azd restore` now fails if you have a docker based project but are not running the docker deamon (as is the case in the macOS environment in CI).
To fix …
> restore: Don't require `docker` for `restore`

- cli/azd/.vscode/cspell.yaml
- cli/azd/test/recording/recording.go
- cli/installer/choco/azd.nuspec
- cli/installer/install-azd.ps1
- cli/installer/install-azd.sh
- cli/installer/test-installer-containers.ps1
- cli/installer/test-pwsh-xplat-install.ps1
- cli/installer/test-win-install.ps1
- ext/azuredevops/setupAzd/index.ts
- ext/azuredevops/setupAzd/task.json
- ext/azuredevops/vss-extension.json
Fixes #4621
Impacted areas: 
* Install Scripts 
* Azure DevOps 
* GitHub Actions
* Some testing
* Choco image location (choco makes local copies of these so the image shouldn't go away and if it does, later releases will show the correct image)
> Migrate to new CDN endpoint 

- cli/azd/pkg/azapi/resource_service.go
This addresses the incorrect behavior of: when deleting a resource group in `azd down`, azd currently fails.
A delete on a resource group that does not exist should result in a no-opt.
Fixes #4628
> down: idempotent delete on resource groups

- cli/azd/internal/vsrpc/aspire_service.go
- cli/azd/internal/vsrpc/debug_service.go
- cli/azd/internal/vsrpc/environment_service.go
- cli/azd/internal/vsrpc/environment_service_create.go
- cli/azd/internal/vsrpc/environment_service_deploy.go
- cli/azd/internal/vsrpc/environment_service_load.go
- cli/azd/internal/vsrpc/environment_service_refresh.go
- cli/azd/internal/vsrpc/handler.go
- cli/azd/internal/vsrpc/handler_test.go
- cli/azd/internal/vsrpc/message_writer.go
- cli/azd/internal/vsrpc/observer.go
- cli/azd/internal/vsrpc/observer_test.go
- cli/azd/internal/vsrpc/server.go
- cli/azd/internal/vsrpc/server_service.go
- cli/azd/internal/vsrpc/server_test.go
Previously, we had of hand written adapters that allowed exposing go functions over our JSON-RPC boundary.  Changes to the number of arguments or return values would require changes to the adapter used (or writing a new adapter by copy/pasting an existing one).
Now, we have a single `NewHandler` which allows exposing arbitrary go functions over the RPC boundary (as long as the follow some rules, like taking a `context.Context` as the first paremeter, and returning a value and `error` or just an `error`.
As part of this change, the `IObserver` type is now called `Observer` and it is passed by reference instead of value in signatures.
> rpc: Support handlers of any arity

- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
When the `@sealed()` decorator is applied on user defined types, it causes an `additionalProperties: false` property to be added to the type defintition in the generated arm deployment. Our unmarshalling logic did not understand this pattern and so it would cause an error when trying to unmarshall this, since it expected if `additionalProperties` was set, it would be to set to an object that described information about the additional properties.
I've updated the marshalling code to support `false` as a valid value for the additional properties node when parsing an ARM template. Since Go doesn't have great support for modeling descrimited unions, the new `ArmTemplateParameterAdditionalPropertiesValue` type is used to provide the logcal descrimited union of `false` or a object like value. …
> bicep: Support `@sealed()` decorator on user defined types

- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_App_host_-_fed_Cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_github_selected_-_App_host_-_fed_Cred.snap
- cli/azd/resources/pipeline/.azdo/azure-dev.ymlt
- cli/azd/resources/pipeline/.github/azure-dev.ymlt
fix: https://github.com/Azure/azure-dev/issues/4691
> Use NET SDK with no Aspire workload in auto-gen pipelines

- templates/todo/api/js/package-lock.json
- templates/todo/api/js/package.json
Fixes #4655
One of the NPM dependencies (`config`) used in our Node.js TODO templates uses some APIs that are deprecated in Node.js 23 (latest current release), causing the `Run Task: Start API` to fail in VS Code on that Node version.
This PR updates `config` to the latest version (3.3.12), which no longer uses those deprecated calls ([release notes](https://github.com/node-config/node-config/releases/tag/v3.3.12)). Some other dependencies were flagged as vulnerabilities and were updated using `npm audit fix`:
```
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix`
node_modules/braces
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in …
```
> Bump "config" package version to 3.3.12

- cli/azd/internal/scaffold/scaffold.go
- cli/azd/resources/scaffold/templates/resources.bicept
Fixes #4574 
These changes are based on [prior discussion here](https://github.com/Azure/azure-dev/pull/4473#discussion_r1913915088) to only export database secrets to AKV when there is a service to bind to. We export Redis access keys using a custom Bicep module, hence the additional change to `scaffold.go`.
> Export database secrets only when there's a service to bind to

- cli/azd/internal/cmd/add/add.go
- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_configure_host.go
- cli/azd/internal/cmd/add/add_select.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/internal/repository/app_init.go
- cli/azd/internal/repository/detect_confirm.go
- cli/azd/internal/repository/infra_confirm.go
This change reshares UI prompting logic between `init` and `add`.
**Context**
`init` logically depends on `add` since it is essentially a quick wizard that ends up prompting attributes for each resource. In the limit, `init` can be thought of as a series of `add` calls, though this is not reflected in practice due to difference in UX design considerations.
This is a pure refactor and does not introduce any functional changes. The UI prompting is covered by existing tests.
> chore: `init` to depend on `add.Configure`

- cli/azd/cmd/auth_login.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/output/ux/logged_in.go
This pull request updates to the login functionality in the Azure CLI. The main changes involve improving the login status messaging and adding detailed account information after a successful login.
closes #1745
> Feature Show Logged in account email or client ID for `azd auth login` and `azd auth login --check-status`

- cli/azd/.vscode/cspell.yaml
- cli/azd/internal/appdetect/appdetect.go
- cli/azd/internal/appdetect/java.go
- cli/azd/internal/appdetect/java_test.go
- cli/azd/internal/appdetect/testdata/java/pom.xml
- cli/azd/pkg/tools/maven/maven.go
Use effective to construct mavenProject.
> Use effective to construct mavenProject

- cli/azd/pkg/tools/bicep/bicep.go
update from bicep: https://github.com/Azure/bicep/releases/tag/v0.33.93
Highlights
•	Address v0.33.13 language server crash/stack overflow (#16235)
•	Address v0.33.13 deployment failures when depending on looped resources in non-symbolic name templates (#16236)
•	Release Deployment Pane as a non-experimental feature (#16173)
Other bugs and features
•	Offer code fix to fully qualify function call for shadowed decorator functions (#16116)
> update bicep 33.93

- cli/azd/cmd/env.go
- cli/azd/cmd/up.go
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/pkg/azure/arm_template.go
- cli/azd/pkg/azureutil/location.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
- cli/azd/pkg/infra/provisioning/manager.go
- cli/azd/pkg/infra/provisioning/terraform/terraform_provider.go
- cli/azd/pkg/infra/provisioning/test/test_provider.go
- cli/azd/pkg/prompt/prompter.go
This PR adds the ability to set a default location, as part of the bicep definition, to be selected by azd during user prompt.
This feature works with priority levels. The default location setting priority is as follows, from highest to lowest:
- 1. Set AZURE_LOCATION in system environment for the main project `location`.  Azd skips the location prompt for main location and uses the value from the system environment when set.
- 2. Use azd metadata for bicep parameter like:
```bicep
@metadata({azd: { 
type: 'location'
defaultLocation: 'southcentralus'
}})
param foo string
```
When using metadata type `location` plus `defaultLocation`, azd will list all locations and select the `defaultLocation` from the list.
- Use the `@allowed` tag in the bicep parameter like
```bicep
@allowed([ …
```
> support for default location

- cli/azd/CHANGELOG.md
Correction: #4595 *does not* execute `pwsh` hook scripts with `-NoProfile`. It only adds support for it.
> Correct changelog entry for #4595

- cli/azd/cmd/extension.go
- cli/azd/cmd/init.go
- cli/azd/extensions/registry.schema.json
- cli/azd/pkg/extensions/manager.go
- cli/azd/pkg/extensions/manager_test.go
- cli/azd/pkg/extensions/source_manager.go
- cli/azd/pkg/project/project_config.go
- go.mod
- go.sum
- schemas/alpha/azure.yaml.json
- Extensions can now be referenced directly within `azure.yaml` under the `requiredVersions.extensions` configuration element.
- Referenced extensions are automatically installed during `azd init` command when the extensions alpha feature is enabled.
- Extension dependencies now support semver constraints
- Minor updates on `azd extension` commands
When a users project is dependent on `azd` extensions and another team member onboards or a new machine/workstation is used users will need to manually install the required extensions otherwise downstream failure will occur when those extensions are expected to be invoked.  With this feature, any time a template is initialized `azd` will ensure that any referenced extensions are installed with based on the required version constraints.
```yaml …
```
> Extensions: Auto install extensions during `azd init` command

- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_configure_storage.go
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/internal/cmd/add/add_select.go
- cli/azd/internal/names/label.go
- cli/azd/internal/names/label_test.go
- cli/azd/internal/repository/app_init_test.go
- cli/azd/internal/scaffold/scaffold_test.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
Closes #4716
This PR adds `azd add` support for storage accounts (blob service). These changes allow only one storage account resource to be added. The app is set up to connect to the storage account using keyless authentication. The "Storage Blob Data Contributor" role assignment is given to the local user and the user-assigned identity.
`azure.yml` supports multiple blob container names and `azd provision` will create them, but the `azd add` experience will only add one blob container for now.
```yaml
resources:
storage
type: storage
containers:
- <user-provided name>
```
`AZURE_STORAGE_ACCOUNT_NAME` - Storage account name
`AZURE_STORAGE_BLOB_ENDPOINT` - Storage account blob endpoint
https://github.com/user-attachments/assets/ddd731e4-b1f9-4f33-8997-863f67f535b1
> compose: Add `azd add` support for storage accounts (blob service)

- cli/azd/pkg/apphost/manifest.go
- cli/azd/pkg/azsdk/storage/storage_file_share_service.go
Fix: https://github.com/Azure/azure-dev/issues/4413
This PR addresses issues with the `bindMount` implementation on Windows and adds support for binding single files.
- Corrects the source path creation when the workspace is not on the `C:\` drive.
- Adds support for binding a single file, in addition to the previously supported folder binding.
> Fix: bindMounts in Windows and adding support for single file binding

- cli/azd/CONTRIBUTING.md
I ran into this while trying to open a new issue for something unrelated. The previous links pointed to the cli/cli repo for some reason, and I accidentally opened an issue in that repo instead of this one. The permalinks added here should work as intended.
> Minor correction to links in documentation

- cli/azd/extensions/azd.internal.pack/extension.yaml
This is an example extension that is an extension pack.  An extension pack by itself does not contain any executable artifacts but includes dependencies for other extensions.
```yaml
id: azd.internal.pack
displayName: The AZD internal extension pack
description: Includes AZD internal extensions
version: 0.0.1
dependencies:
- id: azd.internal.registry
version: latest
```
Update the registry
`azd registry package -p azd.internal.pack`
> [!NOTE]
> Generates registry updates with the following:
```jsonc
// registry.json
{
"id": "azd.internal.pack",
"displayName": "The AZD internal extension pack",
"description": "Includes AZD internal extensions",
"versions": [
{
"version": "0.0.1",
"dependencies": [
{
"id": "azd.internal.registry",
"version": "latest"
}
]
}
]
}
```
```bash
azd ext install …
```
> Extensions: Adds sample extension pack

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/generate_types.go
- cli/azd/pkg/apphost/testdata/TestAspireContainerArgs-container0.snap
- cli/azd/pkg/apphost/testdata/aspire-container-args.json
- cli/azd/resources/apphost/templates/containerApp.tmpl.yamlt
Fix: https://github.com/Azure/azure-dev/issues/4786
This PR addresses an oversight in the `container.v0` schema support. While `container.v1` was introduced with support for `entrypoint`, the corresponding update for `container.v0` to handle `entrypoint` in the `yaml` deployment file was not implemented. This PR rectifies that by adding the necessary support for `entrypoint` in `container.v0`.
- **Background**: When `container.v1` was added, `container.v0` was also updated to support `entrypoint` as defined in the schema manifest.
- **Issue**: The deployment files generated by Aspire for `container.v1` included `entrypoint` support, but this was missing for `container.v0`.
- **Fix**: This PR implements the missing `entrypoint` support for `container.v0` in the `yaml` deployment file. …
> Fix: missing support for entrypoint in container.v0

- cli/azd/cmd/init.go
This bug fix fixes a null reference exception when project does not contain any extension requirements.
> Fix: Fixes issue running `azd init` when extension requirements have not been defined.

- cli/azd/internal/tracing/fields/fields.go
- cli/azd/internal/tracing/resource/exec_environment.go
- cli/azd/internal/useragent.go
Add environment detection for `@azure` agent
> useragent: onboard azure agent

- cli/azd/pkg/azsdk/storage/storage_file_share_service.go
Fix: https://github.com/Azure/azure-dev/issues/4413
This PR updates the logic to obtain the relative path for file share uploads on Windows. The previous implementation worked correctly on Linux but encountered issues on Windows due to different backslash handling in paths. This change leverages `filepath.Rel()`, ensuring compatibility across all operating systems.
- Fixes [#4413](https://github.com/Azure/azure-dev/issues/4413)
- Updated the path handling logic to use `filepath.Rel()` for cross-platform compatibility.
- Verified the relative path calculation on both Windows and Linux environments.
- This change should resolve the path handling discrepancies between different operating systems.
-
> Fix bind mounts for Windows

- cli/azd/resources/apphost/templates/next-steps.mdt
- cli/azd/resources/scaffold/templates/next-steps.mdt
Fix issue https://github.com/Azure/azure-dev/issues/4799.
This PR removes the link to the 404 error and provides a new guide on how to configure the deployment pipeline using the `azd pipeline config` command.
@rajeshkamal5050 for notification.
> Update the `Configure CI/CD pipeline` content in `next-steps.md`

- cli/azd/pkg/yamlnode/yamlnode.go
- cli/azd/pkg/yamlnode/yamlnode_test.go
Fix node creation terminating after the first optional node.
In `find`, if a node was created, we terminated the recursion instead of iterating until `parts` is empty.
This was discovered while prototyping an `application.yaml` binding generation for Java.
> yamlnode: fix nested create operations

- cli/azd/internal/appdetect/java_test.go
- cli/azd/pkg/tools/maven/maven.go
For a pom which contains multiple modules:
1. Before current PR, the `mvn help:effective-pom -f xxx/pom.xml` will output effective pom for both root pom and child poms. The `getEffectivePomFromConsoleOutput` func will always return the last one. But the actually, the effective pom of root pom is not always appear at last.
2. After current PR, the `mvn help:effective0pom -f xxx/pom.xml -pl pom.xml` will only output effective pom for root pom. Link to "-pl" related doc: https://maven.apache.org/ref/3.1.0/maven-embedder/cli.html
> Fix error: failed to get effective pom for multiple module pom

- .github/workflows/lint-bicep.yml
Update Bicep CLI version in CI/CD for linting to match the current version used by AZD.
> lint with current bicep version

- cli/azd/internal/repository/detect_confirm_apphost.go
fix: https://github.com/Azure/azure-dev/issues/3093
Allow running `azd init --from-code --no-prompt` in CI to initialize and deploy Aspire Applications.
This should remove the need of running `azd init` like: 
```sh
yes "Confirm and continue initializing my app" | azd init --from-code
```
> set default for apphost confirmation

- cli/azd/pkg/project/framework_service.go
- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Enables `docker` to be a supported language for `azd` services.  This enables scenarios for developers to use languages like `Go` or others that don't have native built-in support in `azd` but can still but leverage in containerized applications.
> Adds support for `docker` language type

- ext/vscode/package.json
- ext/vscode/package.nls.json
- ext/vscode/src/commands/registerCommands.ts
This PR is to enable running `azd init` on a Java Maven project, when right click on the pom file. The expected output is the `azure.yaml` after analyzing the project. This PR changes the title of running `azd init` from `Initialize App` to `Generate Azure Deployment Script`.
Below are the screenshots:
1. Initialize from a pom file
2. Right click on `azure.yaml` (nothing changed)
> Enable run azd init from a Maven project's pom file on right click

- cli/azd/extensions/microsoft.azd.demo/extension.yaml
- cli/azd/extensions/microsoft.azd.demo/internal/cmd/colors.go
- cli/azd/extensions/microsoft.azd.demo/internal/cmd/root.go
Adds colors command to display the list of standard colors
> Demo Extension: Adds colors command to display the list of standard colors

- cli/azd/.vscode/cspell.yaml
- cli/azd/internal/appdetect/java.go
- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/repository/detect_confirm.go
- cli/azd/internal/repository/infra_confirm.go
1. Enhance add databaseDepMap by maven dependency. 
2. Fix some lacking codes about `appdetect.DbMySql`.
3. `DbCosmos` is not added now, my current plan is add it in next PR, after current PR merged.
> Enhance add databaseDepMap by maven dependency

- .config/guardian/.gdnbaselines
- cli/azd/ci-build.ps1
Set `buildmode=pie` for Windows. Clean up ineffectual build flags.
Before this change, the flag `--high-entropy-va` was set explicitly. However, this turned out to be ineffectual since the build mode was set explicitly to `exe`. [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) security techniques requires [PIE](https://en.wikipedia.org/wiki/Position-independent_code#PIE).
Enabling `buildmode=pie` automatically sets the additional flags on Windows to fully enable ASLR. With these changes, the PE header using DUMPBIN now reads:
```
DLL characteristics
High Entropy Virtual Addresses
Dynamic base
NX compatible
Terminal Server Aware
```
> ci: set `buildmode=pie`

- cli/azd/pkg/azapi/azure_client_linuxwebapp_test.go
- cli/azd/pkg/azapi/webapp.go
- cli/azd/pkg/azsdk/zip_deploy_client.go
Contributes to #4844
This PR makes a change to allow Linux App Service deployments to continue and not fail when it encounters a 500 Internal Server Error response from polling the [deploymentStatus API](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-production-site-deployment-status?view=rest-appservice-2024-04-01&tabs=HTTP).
I'm using the existing `progressLog` to log the 500 error, which, as seen in the video below, disappears after the operation completes. If we want to have a persisted warning message, I'm not sure how straightforward it is to add that to the `deploy` flow and would need some guidance there.
https://github.com/user-attachments/assets/8851b4f7-4b24-4cb5-bcf4-2ecb0c732621
> Allow Linux App Service deployments to resume on 500 deployment status response

- cli/azd/pkg/infra/provisioning/bicep/prompt.go
Adding trim before parsing usage name to avoid cast error for capacity
> fix quota missing trim

- cli/azd/pkg/infra/provisioning/bicep/prompt.go
fix: https://github.com/Azure/azure-dev/issues/4920
Current filter is only looking for locations where S0 sku capacity for cognitive accounts is greater than 0.
This can still lead to a failure b/c S0 requires at least 2 capacity units.
> require min 2 capacity for s0 sku

- .vscode/cspell-github-user-aliases.txt
- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/internal/cmd/show/show.go
- cli/azd/internal/cmd/show/show_resource.go
- cli/azd/internal/scaffold/funcs.go
- cli/azd/internal/scaffold/resource_expr.go
- cli/azd/internal/scaffold/resource_expr_eval.go
- cli/azd/internal/scaffold/resource_expr_eval_test.go
- cli/azd/internal/scaffold/resource_expr_test.go
- cli/azd/internal/scaffold/resource_meta.go
- cli/azd/pkg/azapi/resource_service.go
- cli/azd/pkg/infra/util.go
- cli/azd/pkg/output/ux/show.go
- cli/azd/pkg/project/resources.go
- cli/azd/tools/avmres/main.go
- go.mod
- go.sum
Add ability to `azd show <name>` for all existing supported resources.
With this change, we add the ability to display fully-evaluated connection variables for resources without provisioning a `host` resource.
To do this, we create a generic mapping between ARM and the app representation. This mapping, which is comprised of simple templating-like expressions, are evaluated against live Azure in the `show` command. 
Example output:
1. This contributes to #4577, in which `azd show <full resource ID>` could be used to display, or as a base layer, for obtaining connection information to an existing resource. The schema does not track managed identity vs key-based approaches, but I do see a somewhat straightforward pathway there.
2. This also contributes to #4747, as we are laying down a …
> compose: show resources

- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_select.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/internal/scaffold/resource_meta.go
- cli/azd/internal/scaffold/scaffold.go
- cli/azd/internal/scaffold/scaffold_test.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/base/modules/ai-search-conn.bicep
- cli/azd/resources/scaffold/templates/ai-project.bicept
- cli/azd/resources/scaffold/templates/ai-search-conn.bicept
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
Closes #4889 
This PR adds `azd add` support for Azure AI Search (aka Azure Cognitive Search). **Azure AI Search** now appears as an option under the **AI** group (previously **AI models**) in the `azd add` menu:
Support for dataplane resources (indexes, index aliases, indexers, data sources, skillsets, debug sessions) are out of scope of this PR.
The AI Search resource is configured with a "hybrid" authentication configuration, allowing access via API keys and Entra/RBAC. The [**Search Service Contributor** and  **Search Index Data Contributor** roles](https://learn.microsoft.com/en-us/azure/search/search-security-rbac#built-in-roles-used-in-search) are assigned to the user and host identity (if host **uses** `search`). 
If both an Azure AI Search resource and a Foundry model are present …
> compose: `azd add` support for Azure AI Search

- cli/azd/pkg/apphost/generate.go
Support setting up PrincipalId for the logged in user for Aspire with AppHost migration mode enabled.
When looking at a bicep parameter with name `userPrincipalId` with empty value, AZD uses the `principalId` special parameter for the bicep module.
> handle userPrincipalId for Aspire

- cli/azd/cmd/env.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/prompt/prompter.go
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Closes #4838
This PR adds "shortcuts" to `azd env set-secrets <name>` so that if a Key Vault added by `azd add` exists, the user can directly pick that one to use instead of having to go through the typical **Subscription > Resource Group > Key Vault** flow.
If a key vault resource is defined in `azure.yaml`, but hasn't been provisioned yet, the following warning message is displayed, and the user is asked if they want to pick another KV or cancel the operation.
These changes do not touch the **Create a new Key Vault** flow, but in the future we could consider adding logic to detect if it's a compose project and ask if the user wants to add one to `azure.yaml` and provision it.
1. Update generated Bicep code for Key Vault to set the "set secret" permission on `principalId` so `azd env …
> set-secrets: Add shortcuts for using the Key Vault created by `azd add`

- cli/azd/test/functional/cli_test.go
Functional tests are failing after merging #4874 because one of the inputs for a `set-secret` functional test is invalid:
```
cli.go:244: 13.08s [stdout] ERROR: prompting for resource group: selecting resource group: 'Create a new resource group' is not an allowed choice. allowed choices: 1. Create a new resource group,2. AzSec...
cli_test.go:409: 
Error Trace:	D:/a/_work/1/s/cli/azd/test/functional/cli_test.go:409
Error:      	Received unexpected error:
command 'azd env set-secret SEC_REF in C:\Users\CLOUDT~1\AppData\Local\Temp\Test_CLI_EnvironmentSecrets2416717770\001' had non-zero exit code: exit status 1
Test:       	Test_CLI_EnvironmentSecrets
```
> Correct input for failing `env set-secret` functional test

- cli/azd/ci-test.ps1
- cli/azd/internal/repository/infra_confirm.go
- cli/azd/internal/repository/infra_confirm_test.go
- cli/azd/internal/scaffold/scaffold.go
- cli/azd/internal/scaffold/scaffold_test.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/templates/next-steps-alpha.mdt
- cli/azd/resources/scaffold/templates/next-steps.mdt
- cli/azd/resources/scaffold/templates/resources.bicept
- cli/azd/tools/avmres/main.go
This change updates the SKU for service bus to Standard, as opposed to the default value in AVM which is Premium. Premium sku was accounting for a cost total of 200+ per month.
It also includes the following the changes:
1. **Remove `main.parameters.json` setting passing**: Remove an old feature of passing host settings through main.parameters.json. This was previously introduced in #2875 for simplified init (`azd init` with `azd config set alpha.compose off`), that hasn't been widely adopted in real world usage. It is also unused when `alpha.compose` is enabled.
2. **Fix simplified init and tests**: Fixes simplified init not automatically setting a KeyVault and failing to provision in the process. This was caught by `TestExecInfra` in scaffold_test.go, but this test was not running in …
> compose: update service-bus sku, remove api passing

- cli/azd/cmd/init.go
- cli/azd/internal/env_flag.go
- cli/azd/internal/repository/initializer.go
Fix: [Issue #4935](https://github.com/Azure/azure-dev/issues/4935)
This PR enhances the `azd init` command to utilize an initial `.env` file, allowing it to influence the initial state of the environment created during initialization. 
With this feature, users can run `azd init -t some-template` from a directory containing a pre-configured `.env` file with the necessary values for the environment's starting state. This is particularly useful for connecting to existing resources when initializing a template.
Additionally, users can set the key `AZD_ALLOW_NON_EMPTY_FOLDER=` in the `.env` file to bypass the warning about initializing a template in a non-empty directory. This assumes that the `.env` file and the current directory are pre-configured and ready for `azd init -t template-name`. …
> azd init with env file

- cli/azd/internal/cmd/show/show.go
- cli/azd/internal/cmd/show/show_resource.go
- cli/azd/internal/scaffold/resource_meta.go
Fix `AZURE_OPENAI_ENDPOINT` not showing in add preview.
In #4914, we shifted the preview to leverage the newly added resource metadata. Azure OpenAI models had a resource specific show implementation built that wasn't immediately refactored in the change. This change shifts the Azure OpenAI implementation and fixes the add preview
Contributes to #4933
> compose: openai endpoint

- schemas/alpha/azure.yaml.json
This PR adds the `ai.project` resource type to the alpha azure.yaml schema
> compose: add `ai.project` resource type to alpha azure.yaml schema

- cli/azd/pkg/apphost/generate.go
Adding support for a bicep.v0 expressing secrets.
For any resource referencing secrets, like
```json
"cosmos": {
"type": "azure.bicep.v0",
"connectionString": "{cosmos-kv.secrets.connectionstrings--cosmos}",
"path": "cosmos.module.bicep",
"params": {
"keyVaultName": "{cosmos-kv.outputs.name}"
}
},
```
a resource `cosmos-kv` is expected to provide a connectionString which reference itselft's outputs and a name. like:
```json
"cosmos-kv": {
"type": "azure.bicep.v0",
"connectionString": "{cosmos-kv.outputs.vaultUri}",
"path": "cosmos-kv.module.bicep"
},
```
The output `vaultUri` represents the bicep output where the KV URL is defined and AZD uses to write the expression for YAML, like:
```yaml
secrets:
- name: connectionstrings--db
keyVaultUrl: '{{ .Env.COSMOS_KV_VAULTURI …
```
> aspire secrets impl change

- cli/azd/pkg/apphost/generate.go
- cli/azd/pkg/apphost/testdata/TestAspireBicepGenerationAppHostOwnsCompute-frontend.snap
- cli/azd/pkg/apphost/testdata/TestAspireBicepGenerationAppHostOwnsCompute-main.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-apphost-owns-compute.json
- cli/azd/pkg/environment/environment.go
This PR updates AZD to utilize the `AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN` variable for determining when to display the link to the Aspire dashboard. The change ensures that output references from any resource in the manifest are elevated to a top-level output.
These updates are specifically designed for scenarios where Aspire owns the compute resources.
fix: https://github.com/Azure/azure-dev/issues/4998
> [Aspire] Promote ACE domain from outputs

- cli/azd/internal/cmd/add/add.go
- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_configure_existing.go
- cli/azd/internal/cmd/add/add_preview.go
- cli/azd/internal/cmd/add/add_select.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/internal/cmd/show/show_resource.go
- cli/azd/internal/scaffold/funcs.go
- cli/azd/internal/scaffold/resource_expr.go
- cli/azd/internal/scaffold/resource_expr_eval.go
- cli/azd/internal/scaffold/resource_meta.go
- cli/azd/internal/scaffold/scaffold.go
- cli/azd/internal/scaffold/spec.go
- cli/azd/pkg/azapi/resource_service.go
- cli/azd/pkg/infra/util.go
- cli/azd/pkg/project/resources.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/scaffold/base/modules/role-assignment.bicep
- cli/azd/resources/scaffold/base/modules/role-assignment.json
- cli/azd/resources/scaffold/templates/resources.bicept
- schemas/alpha/azure.yaml.json
This change adds support for referencing `existing` resources.
`azd add` now supports adding existing resources by listing resources interactively. In the schema, a new `existing` keyword is added.
An example resulting schema looks like:
```yaml
shared:
type: storage
existing: true
```
The resource ID, in the format of, `AZURE_RESOURCE_SHARED_STORAGE_ID` is stored in azd's `.env` file to support cross environment.
Existing resources support `uses` linking, just as before:
```yaml
stg-exist:
type: host.containerapp
port: 80
uses:
- shared # Adds env variables `AZURE_STORAGE_SHARED_ACCOUNT_NAME`,  `AZURE_STORAGE_SHARED_ACCOUNT_BLOB_ENDPOINT`
```
`azd show <resource>`, i.e. `azd show shared` also works to display the environment variables for existing resources.
1. The resource is added as …
> compose: `existing` support

- cli/azd/internal/repository/app_init.go
- cli/azd/resources/scaffold/templates/main.bicept
- cli/azd/resources/scaffold/templates/resources.bicept
This change forces the schema version to `alpha` when `azd init` runs with compose enabled. This avoids the `resources` node from showing up as unrecognized.
Also, including a small fix to rename `AZURE_AIPROJECT` -> `AZURE_AI_PROJECT`.
Fixes #4572
> compose: force alpha flag

- cli/azd/pkg/apphost/generate_test.go
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-frontend.snap
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-kv-kv.bicep.snap
- cli/azd/pkg/apphost/testdata/TestAspireBicepGeneration-main.bicep.snap
- cli/azd/pkg/apphost/testdata/aspire-bicep.json
Missing tests for supporting the new `.secrets` field that replaces the previous `.secretOutputs` field for Aspire manifest
> add test for aspire secrets support

- eng/pipelines/templates/steps/publish-vscode.yml
The error seen is happening when the path to the signature file is incorrect. 
```
$ npx @vscode/vsce verify-signature -i azure-dev-0.9.0.vsix -m azure-dev-0.9.0.manifest -s azure-dev-0.9.0.p7s
ERROR  ExtensionSignatureVerificationResult {
code: 'SignatureIsUnreadable',
internalCode: 10,
didExecute: true,
output: undefined
}
```
In this case, the `-s` parameter needs `azure-dev-0.9.0.signature.p7s` instead of `azure-dev-0.9.0.p7s`.
> Fix vscode publishing

- cli/azd/pkg/pipeline/pipeline.go
- cli/azd/pkg/pipeline/pipeline_manager.go
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_App_host_-_fed_Cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_branch_name.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_client_cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_fed_Cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_variables_and_secrets.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles_azureDevOpsDirectory-no_files_-_azdo_selected_-_azuredevops_dir_-_client_cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles_azureDevOpsDirectory-no_files_-_azdo_selected_-_azuredevops_dir_-_fed_Cred.snap
- cli/azd/pkg/project/importer.go
- cli/azd/pkg/project/scaffold_gen.go
- cli/azd/resources/pipeline/.azdo/azure-dev-tf.yml
- cli/azd/resources/pipeline/.azdo/azure-dev.ymlt
- cli/azd/resources/pipeline/.github/azure-dev.ymlt
- templates/common/.azdo/pipelines/bicep/azure-dev.yml
- templates/common/.azdo/pipelines/java/azure-dev.yml
- templates/common/.azdo/pipelines/nodejs/aks/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/azure-dev.yml
- templates/common/.azdo/pipelines/terraform/java/azure-dev.yml
This changes make AZD pipeline config manager aware of what alpha features to turn on as part of the CI yaml definition.
After supporting turning alpha features ON as part of the pipeline, the pipeline manager includes `compose` when the infrastructure is detected as using composability.
> Support generate CI definition for composability mode as alpha

- eng/pipelines/templates/steps/publish-cli.yml
* Exit 0 so the job continues. `gh release view...` is the last thing to set `$LASTEXITCODE` and it is expected to return a nonzero exit code (meaning that the tag is not found and can therefore be created).
* Replace direct references of `Azure/azure-dev` repo with `$(Build.Repository.Name)`
> Fix publishing issue: exit 0

- cli/azd/test/functional/testdata/samples/springapp/pom.xml
- templates/todo/api/java-postgresql/pom.xml
- templates/todo/api/java/pom.xml
Validated by running `azd up` on todo-java-mongo-aca and todo-java-mongo templates and testing out the web app.
> Update Java dependencies in TODO templates and tests

- cli/azd/pkg/project/service_target_aks.go
Resolves #5074 by adding tenant id to kubeconfig convert options when cluster is Azure RBAC enabled or local account is disabled.
> fix: resolves #5074

- cli/azd/cmd/middleware/extensions.go
- cli/azd/internal/grpcserver/event_service.go
- Adds 2 second timeout for extension initialization for lifecycle events
- Fixes event namespacing when multiple extensions are handling the same lifecycle events.
If timeout occurs the extension cannot participate in lifecycle events.  This avoids extension initialization to perform and blocking or long running operations which should not be happening at this point.
> Extension Framework: Fixes event handling issues

- cli/azd/cmd/extensions.go
- cli/azd/pkg/ux/printer.go
- cli/azd/pkg/ux/ux.go
When a command is invoked through a sub process/shell, the called extension is unable to determine the correct console width using the `consolesize.GetConsoleSize()` that is used within `azd`.
To work around this issue, the currently detected console width will be set in a `COLUMNS` environment variable and then read by the extensions if unable to detect the size using standard libraries.
The `COLUMNS` environment variable is a semi-standard used in some Mac/unix based terminals.  If a console width is still unable to be detected we fallback to a default of `120`.
> Extensions: Pass console width to extensions when invoked

- cli/azd/resources/scaffold/templates/ai-project.bicept
- cli/azd/resources/scaffold/templates/main.bicept
Contributes to #4879.
In certain Azure tenants with stricter policies, deploying an AI project through composability can fail because the storage account created for the Foundry Hub has anonymous blob access and account key access enabled.
This PR disables anonymous blob access and account key access, and configures the Foundry Hub to use Identity-based access to access the storage account.
It also sets the appropriate role assignments for the user, **Storage Blob Data Contributor** and **Storage File Data Privileged Contributor** ([documentation](https://aka.ms/ai-hub-storage-account-role-assignments)).
> compose - configure Foundry Hub to use identity-based storage access

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/test/functional/testdata/mock-samples/webapp/infra/main.parameters.json
This PR aims to solve #5151.
I have implemented additional checks for the type of a parameter that is read from the `main.parameters.json` file. I have defined the following restrictions. Please let me know if you all agree with these or whether I should change it up!
- `string`  is valid when it's not `null` (this was already implemented).
- `array`  is always valid. So this means that `[]` and `[...]` is supported.
- `object` is only valid when at least one element is defined. This means that `{}` is invalid and any form of `{key:value}` will be accepted.
Looking forward to any reviews/comments on my first contribution to this repository.
> Properly reading objects and arrays from parameter file

- cli/azd/internal/appdetect/testdata/java-multimodules/application/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/library/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/module2/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/module2/submodule1/pom.xml
- cli/azd/internal/appdetect/testdata/java-multimodules/notmodule/pom.xml
- cli/azd/test/functional/testdata/samples/springapp/pom.xml
- eng/pipelines/templates/steps/template-test-run-job.yml
- templates/todo/api/java-postgresql/pom.xml
- templates/todo/api/java/pom.xml
- templates/todo/projects/nodejs-mongo-aks/.repo/bicep/infra/main.bicep
This should hopefully address the remaining Maven CG security vulnerability alerts.
This PR also fixes several failing template tests due to:
- Unsupported/retired Kubernetes version in the AKS TODO templates:
```
K8sVersionNotSupported: Preflight validation check for resource(s) for container service aks-eqlqwhy6oyc4a in resource group rg-azd-template-test-todo-nodejs-mongo-aks-4820260-3 failed. Message: Managed cluster aks-eqlqwhy6oyc4a is on version 1.29.15, which is only available for Long-Term Support (LTS).
```
- `tfoidc` binary failing to run causing Terraform templates to fail in test pipeline:
```
./tfoidc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tfoidc)
./tfoidc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by …
```
> Update Java dependencies and fix failing template tests

- cli/azd/extensions/microsoft.azd.ai.builder/internal/cmd/start.go
- cli/azd/internal/grpcserver/compose_service.go
https://github.com/user-attachments/assets/2fd32fdf-a506-4071-9509-a208564f319d
> AI Builder Extension - App Service support

- cli/azd/internal/cmd/show/show.go
- cli/azd/pkg/output/ux/show.go
Resolves #5093
`azd show <name>`:
> [!NOTE]
> In Compose, secrets for Redis and MongoDB are exported to the project Key Vault, and azd stores them in the App Service app settings as Key Vault references in the form `@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret)`. With these changes, `azd show <name> --show-secrets` displays the reference string but doesn't resolve them to the actual secret value. Created https://github.com/Azure/azure-dev/issues/5174 to track this.
>
> Secrets for Postgres and MySQL are not stored as Key Vault references, so `azd show <name> --show-secrets` displays the actual secret value.
>
> On the other hand, Container Apps has first-class support for secrets, so `azd show <name> --show-secrets` resolves the actual secret value from …
> compose - `azd show` support for App Service

- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/publish.go
- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/release.go
- cli/azd/extensions/microsoft.azd.extensions/internal/cmd/root.go
- cli/azd/extensions/microsoft.azd.extensions/internal/github/github.go
- cli/azd/extensions/microsoft.azd.extensions/internal/models/extension_schema.go
- cli/azd/extensions/microsoft.azd.extensions/internal/user_friendly_error.go
- cli/azd/extensions/microsoft.azd.extensions/main.go
- Fixes issues when specifying `--cwd` flag on commands
- Improved usage of `gh` cli
- Better error messages on `gh` errors
> Developer Extension Refactors usage of `gh` cli and adds better error messages

- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/build.ps1
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/javascript/build.sh
Fixes https://github.com/Azure/azure-dev/issues/5167.
- Added `pkg` package.
@rajeshkamal5050 and @wbreza for notification.
> Extension Templates: add missing Javascript packages to support `azd x build`

- cli/azd/cmd/extensions.go
This change adds support for nested extension namespaces.
`azd` will register the correct hierarchy of extensions regardless of the namespace.
Extension 1 can register namespace `ai.vision`
Extension 1 can be invoked by calling `azd ai vision <command> [options]`
Extension 2 can register namespace `ai.speech`
Extension 2 can be invoked by calling `azd ai speech <command> [options]`
> Extensions: Adds support for nested extension namespaces

- cli/azd/internal/cmd/add/add.go
- cli/azd/internal/cmd/add/add_configure.go
- cli/azd/internal/cmd/add/add_configure_host.go
- cli/azd/internal/cmd/add/add_select.go
- cli/azd/internal/cmd/add/add_select_ai.go
- cli/azd/internal/scaffold/resource_meta.go
Resolves #4877
Resolves #5184
This PR contains some fixes and enhancements in the `azd add` flow:
When adding multiple AI Services/Foundry models, if a service host already 'uses' the AI project, azd will not show that service when prompting for 'uses'.
Previously, the `azd add` preview was not showing the resource type or binding variables.
After the "Retrieving locations..." spinner:
https://github.com/user-attachments/assets/52675ea7-e93d-4373-bd68-67c39647af74
Host types are displayed in a custom sorted order, with **Container App (default)** as the first option.
The text **Azure App Service** is now highlighted in the standard bright blue colour.
> compose - `azd add` fit and finish

- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/build.ps1
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/build.sh
- cli/azd/extensions/microsoft.azd.extensions/internal/resources/languages/python/requirements.txt
Fixes https://github.com/Azure/azure-dev/issues/5168.
- Added Python virtual environment creation and `PyInstaller` dependencies
@rajeshkamal5050 and @wbreza for notification.
> Extension Templates: add missing Python packages to support `azd x build`

- cli/azd/pkg/output/ux/created_repo_value.go
- cli/azd/pkg/pipeline/github_provider.go
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_App_host_-_fed_Cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_branch_name.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_client_cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_fed_Cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles-no_files_-_azdo_selected_-_no_app_host_-_variables_and_secrets.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles_azureDevOpsDirectory-no_files_-_azdo_selected_-_azuredevops_dir_-_client_cred.snap
- cli/azd/pkg/pipeline/testdata/Test_promptForCiFiles_azureDevOpsDirectory-no_files_-_azdo_selected_-_azuredevops_dir_-_fed_Cred.snap
- cli/azd/pkg/tools/github/github.go
- cli/azd/resources/pipeline/.azdo/azure-dev.ymlt
During pipeline config, AZD ask confirmation before overriding variables or secrets.
This change provides a better and easier control for variables/secrets during pipelines config. For example, users can manually override CI secrets/variables from GitHub UI and then ask AZD to ignore setting them again.
> handle existing ci variables and secrets

- cli/azd/pkg/project/scaffold_gen.go
Fix bug where the Bicep for the compose Key Vault isn't being generated if it isn't present in **azure.yaml** but a resource implicitly depends on it.
In this example, since both Postgres and Redis require a Key Vault, the generated Bicep should include a Key Vault resource.
```yaml
name: minimal
metadata:
template: azd-init@0.0.0-dev.0
services:
minimal:
project: .
language: python
resources:
minimal:
type: host.containerapp
uses:
- psql
- redis
port: 80
psql:
type: db.postgres
redis:
type: db.redis
```
This used to work but may have been affected by #4943.
> compose - Fix Bicep generation for implicit key vault resource

- eng/pipelines/templates/jobs/build-azd-extension.yml
- eng/pipelines/templates/jobs/cross-build-azd-extension.yml
- eng/pipelines/templates/stages/build-and-test-azd-extension.yml
- eng/pipelines/templates/stages/release-azd-extension.yml
- eng/scripts/Set-ExtensionVersionVariable.ps1
> [ext builds] Cleanup

- cli/azd/pkg/ioc/container.go
- cli/azd/pkg/ioc/container_test.go
Fixes #5198 
Before upgrading the `golobby/container` package the package was not wrapping errors when there was a container resolution failure.
**Root Cause golobby change:**
https://github.com/golobby/container/compare/v3.3.1...master#diff-14bacfb63a209323729af295c64c9bb978c84e810d18e3e7b7ae66d9b3cd7acaL242
With the recent update the are wrapping all errors and now we need to unwrap the error to determine if the root error was still a container related configuration issue or another error returns by the component initializer/constructor.
We are also able to revert the previous change that was not a full fix for the original issue:
https://github.com/Azure/azure-dev/pull/5065/files#diff-b03e5b88fe3c56354b85e98942a63eff1755fe891f4ccc81ead0088a6f52577eL52
> Unwrap golobby errors and check for container error

- cli/azd/pkg/project/service_target_dotnet_containerapp.go
AZD was trying to login to Azure Container Registry before deploying Aspire services (either a project or a container).
This was a bug because for containers, Aspire supports public images and provides the ACA definition which is not required to push to ACR.
This change moves logging in to ACR only for doing Dotnet publish for Aspire projects.
Fix: https://github.com/dotnet/aspire/issues/8422
> Fix for Aspire projects with containers but not projects

- cli/azd/docs/feature-stages.md
- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Closes #5232
This PR brings over compose resource definitions to the v1.0 azure.yaml schema, and also adds some missing properties present in v1.0 over to the alpha schema.
This PR also updates the `feature-stages.md` to reflect the Beta stage.
> compose beta: update azure.yaml schemas and feature stage doc

- cli/azd/pkg/exec/util_test.go
- cli/azd/pkg/tools/swa/swa.go
This change makes sure that the `latest` tag is used when calling the static-web-apps NPM package when using `az deploy` with a StaticWebApp resource. This ensures that the latest version of the package is always used, which is beneficial because it ensures that the latest features and bug fixes are always included in the deployment process.
> Make sure to always use latest static-web-apps CLI npm package

- cli/azd/extensions/registry.json
This PR modifies the official `registry.json` to release extensions for `azd`
In this release:
The `azd` demo extension that showcases the capabilities and functionality of the `azd` extension framework.
The extensions used to help bootstrap and scaffold `azd` extensions.
> Release initial `azd` extensions

- cli/azd/test/functional/env_test.go
- cli/azd/test/functional/vs_server_test.go
- eng/pipelines/templates/jobs/build-cli.yml
Run VsServer tests in parallel.
Also, 
1. Fix flakiness in Test_CLI_EnvCommandsWorkWhenLoggedOut
2. Fix flakiness when multiple Aspire related tests run in parallel
Addresses #5392
> test: parallelize vs tests, fix flakiness

- .vscode/cspell-github-user-aliases.txt
- cli/azd/.vscode/cspell-azd-dictionary.txt
- cli/azd/.vscode/cspell.yaml
- cli/azd/pkg/project/framework_service_npm.go
- cli/azd/pkg/project/framework_service_python.go
- cli/azd/pkg/project/project_utils.go
- cli/azd/pkg/project/service_target.go
- cli/azd/pkg/project/service_target_appservice.go
- cli/azd/pkg/project/service_target_functionapp.go
- cli/azd/pkg/rzip/rzip.go
- cli/azd/pkg/rzip/rzip_test.go
- cli/azd/test/functional/package_test.go
- go.mod
- go.sum
Support `.webappignore` and `.funcignore` files for zip deploy with behavior described in #4381.
Other notable changes:
1. For function apps, `local.settings.json` is always excluded from the zip package. This makes the behavior consistent with Azure Function Core Tools (`func`).
2. Improve packaging performance slightly for python and npm applications by skipping an extra copy-to-staging step. Notably, this also centralizes the logic of zip deploy packaging for different apps.
3. Add surrounding tests for the behavioral changes.
Addresses #4381, #1039, #4215
> package: support ignore files for zip deploy

- cli/azd/cmd/auth_login.go
- cli/azd/cmd/testdata/TestUsage-azd-auth-login.snap
- cli/azd/pkg/auth/federated_token_client.go
- cli/azd/pkg/auth/federated_token_client_test.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/auth/manager_test.go
Add support for generic OIDC providers, with  `azd auth login --federated-credential-provider oidc`.
Along with the flag passed, a user can set `AZURE_OIDC_TOKEN` to enable OIDC authentication with any CI provider.
In cases where a token exchange is required, `AZURE_OIDC_REQUEST_TOKEN` and `AZURE_OIDC_REQUEST_URL` dan be set.
Addresses #3242, #3304
> auth: add support for generic oidc

- cli/azd/pkg/infra/provisioning/bicep/bicep_provider.go
- cli/azd/pkg/infra/provisioning/bicep/bicep_provider_test.go
- cli/azd/pkg/infra/provisioning/bicep/prompt.go
Light refactoring to replace functions for retrieving module path and bicep module with upfront initialization.
Force a full `bicep build-params` to happen right before deploy. This ends up being the "right behavior" that matches closer to azd's usage of environment variables to be injected right before deployment occurs.
Fixes #4402
> bicep: cleanup + fix bicepparam evaluation

- .github/workflows/cli-ci.yml
- .github/workflows/devops-ext-ci.yml
- .github/workflows/vscode-ci.yml
Currently, if a PR is open and a push happens, the **cli-ci** workflow will start running. If, shortly after a subsequent push on the *same* PR happens, the workflow will start running again without cancelling the previous (now obsolete) run. With these changes, the first run would be cancelled, thus **saving compute resources** (see below for quantity) that can be used to **speed up your overall CI/CD**, without sacrificing functionality, since the second run will contain the changes from the first push as well. 🌱
Here is an example of the behaviour described above: the commit `9b896ab` triggered [this](https://github.com/Azure/azure-dev/actions/runs/13643772836/) workflow run, and shortly after the commit `a28c769`, that happened on top of the first commit, triggered …
> [CI]: Cancel CI runs that become obsolete

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
Fixes #5472
Contributes to #5109
`apiVersion` was added in #4272, for `containerapp` services only.
`resourceGroup` was added in #3744 but only documented in the alpha schema.
> Add `apiVersion` and `resourceGroup`  properties to azure.yaml schema

- context7.json
context7 already has one entry for azd: https://context7.com/azure/azure-dev
This PR updates the configuration for context7 to get only docs folder, readme and contributing. Excluding source code and other files.
The plan is to create a new entry in context7 for azd documentation and samples pointing to the docs repo.
> Adding context7 repository settings

- cli/azd/pkg/project/framework_service_swa.go
- cli/azd/pkg/project/service_target_staticwebapp.go
fix: https://github.com/Azure/azure-dev/issues/5506
This change makes the SWA deployment to validate if users are trying to deploy a service from the root of the project (next to azure.yaml) without using an output folder for the service and fail with a details error and suggestion about it.
Azure SWA has a limitation (Azure/static-web-apps#1672) about deploying applications which source code is the output at the same time. For example, trying to deploy a single HTML file to say hello world.
The returned suggestion helps AI agents to make the required changes to the project to make deployment work.
```
ERROR: error executing step command 'deploy --all': failed deploying service 'name': Application folder path and Application Output folder path cannot be the same
If your service is at the …
```
> Fail fast when deploying SWA from the root with no output folder

- cli/azd/cmd/auth_token.go
- cli/azd/pkg/auth/azd_credential.go
- cli/azd/pkg/auth/errors.go
- cli/azd/pkg/auth/manager.go
- cli/azd/pkg/azapi/azure_deployment_error.go
- cli/azd/pkg/azapi/azure_deployment_error_test.go
- cli/azd/pkg/azapi/deployments.go
- cli/azd/pkg/azapi/stack_deployments.go
- cli/azd/pkg/azapi/standard_deployments.go
Adds support for claims challenges that can occur as part of [Conditional Access Evaluation](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-continuous-access-evaluation).
When a request is rejected by ARM, the following will occur:
1. ARM returns 401 Unauthorized with `claims` populated in `Www-Authenticate` header.
2. [BearerTokenPolicy](https://github.com/Azure/azure-sdk-for-go/blob/4975987a031547cc54fff1a162f55144498bfad4/sdk/azcore/runtime/policy_bearer_token.go#L152) handles parsing of the claims, and will call the credential's `GetToken` implementation with `TokenRequestOptions.Claims` populated.
3. In our credential implementation (azd_credential.go), we now pass the claims through to `azidentity`'s `AcquireTokenSilent` implementation. In almost all …
> auth: handle claims challenges due to Conditional Access Evaluation

- cli/azd/pkg/pipeline/github_provider.go
Fixes issue https://github.com/Azure/azure-dev/issues/5554.
When generating `branchCredentials` name in the `azd pipeline config` command, replace all non-`[A-Za-z0-9-]` characters in the branch name with `-`.
@rajeshkamal5050 and @vhvb1989 for notification.
> Fix: replace invalid branch name characters when generating federated credential names

- cli/azd/test/functional/package_test.go
> Fix `Test_CLI_Package_ZipDeploy_Exclusions` failures on Windows - close zip after opening in `checkFiles`

- cli/azd/cmd/middleware/hooks.go
- cli/azd/pkg/ext/hooks_manager.go
- cli/azd/pkg/output/ux/warning.go
- cli/azd/pkg/output/ux/warning_alt.go
Fixes #5589 
* Update the prefix for `WarningMessage` to be "WARNING: " in all caps, making it consistent with our current design pattern.
* Improve how hook warnings are displayed, with the suggestion text for installing `pwsh` displayed in a neutral colour.
* Restore a few changes from #5585 that were inadvertently reverted.
> Improve warning message formatting

- cli/azd/extensions/registry.json
Closes #5600 
Generated using `microsoft.azd.extensions` from https://github.com/Azure/azure-dev/releases/tag/azd-ext-microsoft-azd-extensions_0.5.0.
Verified `azd x pack` properly generates .tar.gz packages for Linux platforms:
> Update `microsoft.azd.extensions` in registry to 0.5.0

- cli/azd/cmd/extension.go
- cli/azd/cmd/testdata/TestUsage-azd-extension-show.snap
- cli/azd/docs/extension-framework.md
- cli/azd/pkg/extensions/manager.go
- cli/azd/pkg/extensions/manager_test.go
- cli/azd/pkg/extensions/source_manager.go
Fixes #5037
Fixes #5637
This PR includes several improvements to the `azd extension` commands, removing ambiguity and non-determinism especially when there are multiple sources with the same extension ID (common scenario when developing and testing already-published extensions).
* `azd extension list` output is now consistently ordered by source name and ID.
* `azd extension list` now shows the installed extension version (**Installed Version**) instead of a simple boolean (**Installed**). Previously, the wrong version was being shown in some situations and you couldn't tell if the installed version was different from latest available version.
* `azd extension` `show`, `install`, and `upgrade` now return an error if `--source`/`-s` isn't provided and there are multiple sources with the …
> Extension management improvements

- .github/workflows/cli-ci.yml
- .github/workflows/copilot-setup-steps.yml
fix: https://github.com/Azure/azure-dev/issues/5697
> Update Go setup action to version 6 in CI workflows

- ext/vscode/package-lock.json
- ext/vscode/package.json
- ext/vscode/src/services/AzureDevApplicationProvider.ts
- ext/vscode/src/views/workspace/AzureDevCliWorkspaceResourceProvider.ts
Problem: user is currently trapped in repeated error dialogs when a directory containing `azure.yaml` is deleted or renamed.
This fix addresses the problem by:
1. Subscribing for `azure.yaml` configuration directory changes as they occur.
2. Changing refresh button behavior to rediscover all azd applications in current workspace(s). This allows user to perform a manual refresh in case of any missed filesystem updates.
Underneath-the-covers, the AzureDevApplicationProvider is made to be a stateless data provider to support the scenario as described in 2. above.
Fixes: #5690
> vscode: fix handling of azure.yaml directory movements

- cli/azd/docs/guiding-principles.md
Adding a new guiding principles outline for adding azd commands, arguments, flags, etc. This is especially important guidance for contribution and the azd extension framework.
cc: @SophCarp @ccbarragan  - extending from the figma file to a descriptive format
> add guiding principles for extending azd

- cli/azd/cmd/middleware/error.go
- cli/azd/internal/agent/tools/dev/command_executor.go
Enhances the error middleware and MCP command executor to properly handle non-interactive scenarios by preventing AI-powered error handling when user interaction is not possible or desired.
We want to avoid `azd` getting stuck in an agentic error handling loop when it may choose to call another `azd` command from within itself especially during an error handling flow.
- Added CI detection capability to bypass AI error handling in automated environments
- Extended short-circuit conditions to include:
- LLM feature disabled
- `--no-prompt` flag specified
- Running in CI/CD environment
- Prevents AI error handling from attempting user interaction in automated pipelines
- Removed overly restrictive command blocking for `up`, `provision`, `deploy`, `down` commands
- Automatically appends …
> Bypass agentic error handling flow in non-interactive scenarios

- cli/azd/pkg/entraid/entraid.go
- cli/azd/pkg/pipeline/pipeline_manager.go
Adding in an optional parameter for EnsureRoleAssignments so it allows using a custom scope, instead of only assuming subscription scope.
Part of the fix for https://github.com/Azure/azure-dev/issues/5857
> Allow passing in a custom scope when setting role assignments

- schemas/alpha/azure.yaml.json
- schemas/v1.0/azure.yaml.json
To support hosts that support more dynamic languages or hosts that do not require any language such as declarative foundry agents we will turn off strict schema validation.
For example - the upcoming `foundry.hostedagent` can be used without any language when building declarative agents.  Since this service target comes from an extension we also do not have enough metadata to know whether or not language is required.
> Makes language optional in the schema
